### ISSUE TITLE
[tune] Provide an example of 'resume' working

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#10486]
##  Describe your feature request

Right now there are no examples demonstrating the usage of 'resume' and 'run_errored_only'. If we could add a walkthrough/guide (that we also test in CI), that would be very useful.

**Comment by rhamnett** [comment]
@richardliaw To add to this, I am trying to resume a run to perform additional episodes. 

My original tune stopper class is set at 5000. Once the first run is finished, I increase the stop value and resume the tune, the run simply terminates. Could you please advise what I need to do to get it to resume for further episodes?

**Comment by richardliaw** [comment]
@rhamnett Hmm, I think there are a couple workarounds but they aren't first class. Just to help me with context, could you tell me more about your setting (are you using RLlib)? 

Some questions I have:
 * Do you have multiple terminated trials in your experiment, and you want to continue all of them (i.e., `tune.run(resume="all")`)?
 * Do you want the continued run to append to its original logs?

**Comment by rhamnett** [comment]
@richardliaw thanks for the prompt reply. 

I am trying a tune.run(.......,resume=True) not with rllib. In the current run there was just one trial where my stopper stopped things at 5000 iters.

I just want to carry on from where i left off basically to keep finding a better reward. So iter would start going up from 5001 in this example.

Sorry, I am struggling with the terminology a bit as I'm new to Ray

```
Trial name | status | loc | iter | total time (s) | ts | reward
-- | -- | -- | -- | -- | -- | --
APPO_TradingEnv_4e876_00000 | TERMINATED |   | 5000 | 70249.3 | 6623850 | 206200
```

**Comment by richardliaw** [comment]
OK got it. Do your logs (i.e., tensorboard, csv, etc) matter? If not, I think you can easily do something like:

```
tune.run(..., restore=trial_checkpoint_path)
```
Note that `restore` vs `resume`, where `restore` is for a specific checkpoint of a single run, while `resume` is for an entire experiment. 

Checkpoints should be generated if you do something like `tune.run(checkpoint_at_end`. Let me know if that works!

**Comment by rhamnett** [comment]
@richardliaw Ahh I see! Bingo, feel a bit silly now.

Sorry for polluting your thread. Perhaps the docs could hint to this difference a bit more ..or maybe it's just me.

**Comment by rhamnett** [comment]
@richardliaw on resuming, the reward is 'nan' - not what i expected?

**Comment by richardliaw** [comment]
Docs must be improved :) Is it nan? Then perhaps the state isn't being captured somewhere/restored correctly....... cc @sven1977

**Comment by rhamnett** [comment]
Yes nan rewards for future iterations. Am using an APPO run and ray nightly (from today)

**Comment by josephcarmack** [comment]
I am also trying to resume a run. I am using rllib with a custom environment. I did this by copying the rllib train.py script found here:

https://github.com/ray-project/ray/blob/2a86943b13983d677fb2b1b27b25d7096fa5feb3/rllib/train.py

and registered my env in the script so that I can run `python -m train.py --env myCustomEnv`. I then did an experiment with PPO where I grid searched over some of the hyperparameters. I did this with a yaml config file as below:

```yaml
pursuit-ppo-exploration:
    env: pursuit-v1
    run: PPO
    stop:
        timesteps_total: 20000000
    local_dir: data
    checkpoint_freq: 50
    keep_checkpoints_num: 5
    checkpoint_score_attr: episode_reward_mean
    num_samples: 3
    config:
        # environment
        env_config:
            Training: true
        # common params
        framework: torch
        horizon: 500
        num_workers: 5
        num_gpus: 0.2
        num_envs_per_worker: 5
        seed: 1337
        # todo: try out using some of the built-in observation filters
        observation_filter: NoFilter
        # PPO specific params
        use_gae: true
        use_critic: true
        gamma: 0.992
        lambda: 1.0
        kl_coeff: 0.2
        rollout_fragment_length: 200
        train_batch_size: 4000
        sgd_minibatch_size: 512
        shuffle_sequences: true
        num_sgd_iter: 30
        lr: 0.0003
        vf_share_layers: false
        vf_loss_coeff: 1.0
        # todo: explore using entropy regularization to increase exploration
        entropy_coeff: 0.0
        entropy_coeff_schedule: null
        # exploration during training
        explore:
            grid_search: [false, true]
        exploration_config:
            # currently the only built in option for PPO
            type: StochasticSampling
        # todo: understand what below PPO params do
        clip_param: 0.3
        vf_clip_param: 10.0
        grad_clip: 0.5
        kl_target: 0.01
        batch_mode: complete_episodes
```

This results in 6 different trial runs with some checkpoint files saved. What I would like to do is resume training of one of the trial runs from one of the checkpoints with some modified PPO settings, possibly set in a differnt config file? I'm not quite sure how I could do this. I thought maybe the `--resume` feature would allow me to restart the trial from one of the checkpoints and then maybe I could pass in just the config parameters I wanted to override. But I cannot find any examples or documentation on how to use the `--resume` feature.

Any help or direction is much appreciated. I'm running ray 1.01 on a linux gpu server.
