### ISSUE TITLE
How to configure read the docs installation requirements？

### ISSUE THREAD

**Issue by pinggao187** [ray-project/ray#10793]
Your docs website is perfect. I want to refer to your website to configure my project, but I have a problem.

How to configure read the docs to run the file doc/requirements-doc.txt.

command on read the docs：
/home/docs/checkouts/readthedocs.org/user_builds/ray/envs/master/bin/python -m pip install --exists-action=w --no-cache-dir -r doc/requirements-doc.txt

**Comment by richardliaw** [comment]
Thank you for the high praise. 

```
pip install -r doc/requirements-doc.txt
cd doc && make html
```

**Comment by pinggao187** [comment]
Thanks for your response. I may not express my needs clearly.

I see that your website is automatically updated through "read the docs", and the command pip install -r doc/requirements-doc.txt will be automatically executed when building.

I want to add the automatic execution command pip install -r doc/requirements-doc.txt on "read the docs". How to configure it？

read the docs link:
https://readthedocs.org/projects/ray/builds/11883356/

command on read the docs：
/home/docs/checkouts/readthedocs.org/user_builds/ray/envs/master/bin/python -m pip install --exists-action=w --no-cache-dir -r doc/requirements-doc.txt

**Comment by sumanthratna** [comment]
Hi @pinggao187!

I'm guessing the ray team has chosen to [configure this in the RTD admin dashboard](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#using-the-project-admin-dashboard) instead of using a [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file). 

My personal preference is to use a config file; to do this, create a `.readthedocs.yml` file at the root of your repo with the following contents:
```yml
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: doc/conf.py  # or maybe doc/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements-doc.txt
```

e.g., see the [viewmask](https://github.com/sumanthratna/viewmask) [configuration](https://github.com/sumanthratna/viewmask/blob/master/.readthedocs.yml) (disclaimer: I wrote viewmask)
