### ISSUE TITLE
[autoscaler] Unable to launch Kubernetes cluster if I don't have permission to list namespaces

### ISSUE THREAD

**Issue by mkoh-asapp** [ray-project/ray#10928]
### What is the problem?
When trying to create a cluster, Ray is trying to check if the namespace that I provide in my cluster config exists or not. And if it does not exist, it will try to create it.  (https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/kubernetes/config.py#L61)

This causes a problem if I do not have permission to list namespaces or create namespaces on the kube cluster I'm using.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 0.8.7
Python 3.7

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Here is a ray config to reproduce
```
# Created: 2020-09-21T10:39:01-04:00
cluster_name: mkoh-test
min_workers: 1
max_workers: 2
initial_workers: 1
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 60
provider:
  type: kubernetes
  use_internal_ips: true
  namespace: nlp
head_node:
  apiVersion: v1
  kind: Pod
  metadata:
    generateName: ray-head-
    labels:
      component: ray-head
  spec:
    serviceAccountName: autoscaler
    restartPolicy: Never
    volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    containers:
    - name: ray-node
      image:
worker_nodes:
  apiVersion: v1
  kind: Pod
  metadata:
    generateName: ray-worker-
    labels:
      component: ray-worker
  spec:
    serviceAccountName: default
    restartPolicy: Never
    volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    containers:
    - name: ray-node
      imagePullPolicy:
      image:
file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: false
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
- ray stop
- ulimit -n 65536; ray start --head --num-cpus=$MY_CPU_REQUEST --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --webui-host 0.0.0.0
worker_start_ray_commands:
- ray stop
- ulimit -n 65536; ray start --num-cpus=$MY_CPU_REQUEST --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
