### ISSUE TITLE
[autoscaler] Worker node container is not removed after ray down?

### ISSUE THREAD

**Issue by fahadh4ilyas** [ray-project/ray#11098]
## System Information

* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
* **Ray installed from (source or binary)**: source
* **Ray version**: 1.1.0.dev0
* **Python version**: 3.7.7

## Describe the Problem

I've tried using `ray/python/ray/autoscaler/local/example-full.yaml` and filled the docker field so ray was running in container per node. After ray cluster was running successfully, I destroy the cluster using `ray down example-full.yaml`. The container in head node was gone but not in worker nodes. Is that normal? Because after I check inside one of the worker nodes by `docker exec -it ray_docker /bin/bash` and watch `top`, ray worker is still running even though it's in idle phase.

Edit:
I also tried to upload data to every node using `ray rsync-up -A example-full.yaml [source] [dest]` but somehow only head node container that has my file uploaded. Why is that happened?

Another Edit:
I found out that `ray get-worker-ips example-full.yaml` had not result (blank). here is my configuration:

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: pipeline

## NOTE: Typically for local clusters, min_workers == initial_workers == max_workers == len(worker_ips).

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
min_workers: 1
# The initial number of worker nodes to launch in addition to the head node.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
initial_workers: 1

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
max_workers: 1

# Autoscaling parameters.
# Ignore this if min_workers == initial_workers == max_workers.
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
docker:
    image: "rayproject/pipeline:latest" # e.g., rayproject/ray:0.8.7
    container_name: "pipeline_docker" # e.g. ray_docker
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: False
    run_options: []  # Extra options to pass into "docker run"

# Local specific configuration.
provider:
    type: local
    head_ip: 192.168.99.241
    worker_ips: [192.168.99.56]
    # Optional when running automatic cluster management on prem. If you use a coordinator server,
    # then you can launch multiple autoscaling clusters on the same set of machines, and the coordinator
    # will assign individual nodes to clusters as needed.
    # coordinator_address: "127.0.1.1:9123"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: root
    # Optional if an ssh private key is necessary to ssh to the cluster.
    ssh_private_key: ~/.ssh/id_rsa

# Leave this empty.
head_node: {}

# Leave this empty.
worker_nodes: {}

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands:
    - pip install pandas==0.23.4

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
```

But dashboard still show me that worker node with ip `192.168.99.56` is there

**Comment by rkooo567** [comment]
cc @ijrsvt

**Comment by ijrsvt** [comment]
Hey @fahadh4ilyas , I was wondering what the output of `docker container ls -a` is on the worker nodes?

**Comment by fahadh4ilyas** [comment]
> Hey @fahadh4ilyas , I was wondering what the output of `docker container ls -a` is on the worker nodes?

Here is the output
```bash
CONTAINER ID        IMAGE                        COMMAND             CREATED              STATUS              PORTS               NAMES
79d0f5fab23f        rayproject/pipeline:latest   "bash"              About a minute ago   Up About a minute                       pipeline_docker
```
That is before I destroy cluster. After destroying cluster, here is the output
```bash
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
79d0f5fab23f        rayproject/pipeline:latest   "bash"              5 minutes ago       Up 5 minutes                            pipeline_docker
```
Nothing change

**Comment by fahadh4ilyas** [comment]
The cluster actually can still running and using all node. But I can't:
1. Destroy all containers using only `ray down`. I have to `docker stop pipeline_docker` then `docker rm pipeline_docker` manually for every worker nodes.
2. Upload data to all containers using only `ray rsync-up -A`. I have to `docker cp [source] [target]` manually for every worker nodes.

It's fine but is it kinda destroy the purpose of using cluster launcher?

**Comment by ijrsvt** [comment]
Hmm, that should not be happening (the cluster launcher should be handling these cases).
Let me try to reproduce this locally!

**Comment by ijrsvt** [comment]
One thing that is odd is that you are running `docker rm` for the workers. Can you run with high verbosity?
```
ray down -vvvv <name>.yaml
```

**Comment by fahadh4ilyas** [comment]
> One thing that is odd is that you are running `docker rm` for the workers. Can you run with high verbosity?
> 
> ```
> ray down -vvvv <name>.yaml
> ```

here is the result
```
Destroying cluster. Confirm [y/N]: y
Loaded cached provider configuration from /tmp/ray-config-a80fd6fa0eb964463d504f73a07d1b84e6ead9af
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2020-10-01 11:54:51,914	INFO node_provider.py:41 -- ClusterState: Loaded cluster state: ['192.168.99.55', '192.168.99.56', '192.168.99.241']
2020-10-01 11:54:51,915	INFO node_provider.py:41 -- ClusterState: Loaded cluster state: ['192.168.99.55', '192.168.99.56', '192.168.99.241']
Fetched IP: 192.168.99.241
Running `docker exec -it  pipeline_docker /bin/bash -c 'bash --login -c -i '"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'"'"'' `
  Full command is `ssh -tt -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_800099e902/99f6f4be09/%C -o ControlPersist=10s -o ConnectTimeout=120s root@192.168.99.241 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  pipeline_docker /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'"'"'"'"'"'"'"'"''"'"' )'`
Warning: Permanently added '192.168.99.241' (ECDSA) to the list of known hosts.
Stopped all 59 Ray processes.
Shared connection to 192.168.99.241 closed.
2020-10-01 11:54:54,329	INFO node_provider.py:41 -- ClusterState: Loaded cluster state: ['192.168.99.55', '192.168.99.56', '192.168.99.241']
Fetched IP: 192.168.99.241
Running `docker stop pipeline_docker`
  Full command is `ssh -tt -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_800099e902/99f6f4be09/%C -o ControlPersist=10s -o ConnectTimeout=120s root@192.168.99.241 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker stop pipeline_docker)'`
pipeline_docker
Shared connection to 192.168.99.241 closed.
2020-10-01 11:54:55,122	INFO node_provider.py:225 -- NodeProvider: 192.168.99.241: Terminating node
2020-10-01 11:54:55,124	INFO node_provider.py:93 -- ClusterState: Writing cluster state: ['192.168.99.55', '192.168.99.56', '192.168.99.241']
Requested 1 nodes to shut down. [interval=1s]
0 nodes remaining after 5 second(s).
No nodes remaining.
```

**Comment by ijrsvt** [comment]
Ah, what version of ray is installed in the container? 

Also what about 
```
ray down -vvvv  --workers-only <name>.yaml
```

**Comment by fahadh4ilyas** [comment]
> Thanks for the quick response!
> 
> What version of ray is installed in the container?
> Also what about
> 
> ```
> ray down -vvvv  --workers-only <name>.yaml
> ```

here it is.... it seems like it didn't recognize the worker even though the container is running
```
2020-10-01 13:58:33,960	INFO node_provider.py:41 -- ClusterState: Loaded cluster state: ['192.168.99.55', '192.168.99.56', '192.168.99.241']
The head node will not be shut down. (due to --workers-only)
No nodes remaining.
```

**Comment by fahadh4ilyas** [comment]
I check by trying to run it not in docker but at the host, this problem is still appearing. The worker node isn't destroyed and I have to manually `ray stop` it. So, this is not docker problem...

**Comment by ijrsvt** [comment]
Hmm @ericl , do you have any ideas? It seems like workers are not being tagged as such?

**Comment by mlguruz** [comment]
Hi, is there any update on this? 

> @AmeerHajAli

**Comment by mlguruz** [comment]
> @AmeerHajAli

Hi guys, I run into the exact same situation, and I'm using version 2.0.0dev. Can someone help on this please?

**Comment by mlguruz** [comment]
> Hmm @ericl , do you have any ideas? It seems like workers are not being tagged as such?

I've tried all the above suggestions, and I can confirm this issue still exists. 

For example, after I ran `ray down -vvvv --workers-only cluster.yaml`, I didn't see anything happen:

`Checking Local environment settings
Destroying cluster. Confirm [y/N]: y
2022-03-22 14:18:15,825 INFO node_provider.py:43 -- ClusterState: Loaded cluster state: ['192.168.1.153', '192.168.1.155']
The head node will not be shut down. (due to --workers-only)
No nodes remaining.`

However, when I ran `docker ps` on the remote machine, I can still see docker container running:

`CONTAINER ID   IMAGE                       COMMAND   CREATED             STATUS             PORTS     NAMES
01a328f4dff5   rayproject/ray:latest-cpu   "bash"    About an hour ago   Up About an hour             ray_container`

I would really appreciate if you guys could help, as I think it's important for everyone using Ray on docker. 
Thanks!

**Comment by ijrsvt** [comment]
@mlguruz Just to confirm, before running `ray down`, did all the nodes show up when your ran  `ray.nodes()`?

**Comment by mlguruz** [comment]
> @mlguruz Just to confirm, before running `ray down`, did all the nodes show up when your ran `ray.nodes()`?

Yes, but it's complicated... 

If I filter to alive ones by running `list(filter(lambda r: r['Alive'], ray.nodes()))`, I see 
```
[{'NodeID': 'ac2f77598e567ab3f93646d0674f2f8db4d353271d958aeed86214ba',
  'Alive': True,
  'NodeManagerAddress': '192.168.1.153',
  'NodeManagerHostname': 'algoguruz-Oryx-Pro',
  'NodeManagerPort': 3489,
  'ObjectManagerPort': 12233,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store.4',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 6666,
  'alive': True,
  'Resources': {'accelerator_type:GTX': 1.0,
   'CPU': 8.0,
   'memory': 20079827354.0,
   'object_store_memory': 8605640294.0,
   'GPU': 1.0,
   'node:192.168.1.153': 1.0}},
 {'NodeID': 'd40ec517134c94aae37f5ee3280cfc3f6e2206e62d803460e89c438d',
  'Alive': True,
  'NodeManagerAddress': '192.168.1.155',
  'NodeManagerHostname': 'system76-pc',
  'NodeManagerPort': 9651,
  'ObjectManagerPort': 2685,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 60729,
  'alive': True,
  'Resources': {'GPU': 1.0,
   'CPU': 12.0,
   'memory': 40109902235.0,
   'object_store_memory': 20054951116.0,
   'node:192.168.1.155': 1.0,
   'accelerator_type:G': 1.0}}]
```
, which are *exactly* the nodes I have locally. 

However, on the worker node (i.e. ip = 192.168.1.153), I'm seeing ever increasing number of raylets and dead workers. 
So, if I ran `list(filter(lambda r: not r['Alive'], ray.nodes()))`, I see:
```
[{'NodeID': '9a2a6aa7eb3622157b728c511a5d75837b872c218f5f655249f2627e',
  'Alive': False,
  'NodeManagerAddress': '192.168.1.153',
  'NodeManagerHostname': 'algoguruz-Oryx-Pro',
  'NodeManagerPort': 17371,
  'ObjectManagerPort': 14549,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 6666,
  'alive': False,
  'Resources': {}},
 {'NodeID': '285d88846577c49a240a0653f410d7606a78b9c4912b8b6d1640c8d5',
  'Alive': False,
  'NodeManagerAddress': '192.168.1.153',
  'NodeManagerHostname': 'algoguruz-Oryx-Pro',
  'NodeManagerPort': 23927,
  'ObjectManagerPort': 23965,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store.1',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 6666,
  'alive': False,
  'Resources': {}},
 {'NodeID': 'b5084a0b31263b1fd16cdf0b245543567194bf759fb49df2838b7d3f',
  'Alive': False,
  'NodeManagerAddress': '192.168.1.153',
  'NodeManagerHostname': 'algoguruz-Oryx-Pro',
  'NodeManagerPort': 8059,
  'ObjectManagerPort': 29985,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store.3',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 6666,
  'alive': False,
  'Resources': {}},
 {'NodeID': '0b461189494f91ef384344eb8207e0829c45d40f0db305d786ec6647',
  'Alive': False,
  'NodeManagerAddress': '192.168.1.153',
  'NodeManagerHostname': 'algoguruz-Oryx-Pro',
  'NodeManagerPort': 31185,
  'ObjectManagerPort': 17573,
  'ObjectStoreSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/plasma_store.2',
  'RayletSocketName': '/tmp/ray/session_2022-03-22_11-43-21_425970_234/sockets/raylet',
  'MetricsExportPort': 6666,
  'alive': False,
  'Resources': {}}]
```

I don't know if this is another bug or what... and I don't see many reports...

**Comment by ijrsvt** [comment]
@mlguruz Hmm, very strange. Could you also run:
```
import ray.autoscaler.sdk
ray.autoscaler.sdk.get_worker_node_ips(PATH_TO_FILE)
```
^This will get the autoscaler's view of the world.

**Comment by mlguruz** [comment]
This is what I see: 
```
In [14]: import ray.autoscaler.sdk
    ...: ray.autoscaler.sdk.get_worker_node_ips(PATH_TO_FILE)
Out[14]: ['192.168.1.153']
```

**Comment by ijrsvt** [comment]
Hmm, that's weird that it is not trying to run `ray stop` in the container. Could you share your YAML if that is okay?

**Comment by mlguruz** [comment]
> Hmm, that's weird that it is not trying to run `ray stop` in the container. Could you share your YAML if that is okay?

Absolutely. 

```
# A unique identifier for the head node and workers of this cluster.
cluster_name: 'user'

# Running Ray in Docker images is optional (this docker section can be commented out).
# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
docker:
#    image: "rayproject/ray-ml:latest-gpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull
#    image: rayproject/ray:latest-cpu   # use this one if you don't need ML dependencies, it's faster to pull
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: False
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536
        - --shm-size=30GB
#        - --network host

provider:
    type: local
    head_ip: '192.168.1.155'
#    head_ip: localhost
###    head_ip: 'localhost'
####    # You may need to supply a public ip for the head node if you need
####    # to run `ray up` from outside of the Ray cluster's network
####    # (e.g. the cluster is in an AWS VPC and you're starting ray from your laptop)
####    # This is useful when debugging the local node provider with cloud VMs.
####    # external_head_ip: YOUR_HEAD_PUBLIC_IP
    worker_ips: ['192.168.1.153',]
##     Optional when running automatic cluster management on prem. If you use a coordinator server,
##     then you can launch multiple autoscaling clusters on the same set of machines, and the coordinator
##     will assign individual nodes to clusters as needed.
##        coordinator_address: "<host>:<port>"
#    coordinator_address: "192.168.1.155:8888"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: 'user'
    # You can comment out `ssh_private_key` if the following machines don't need a private key for SSH access to the Ray
    # cluster:
    #   (1) The machine on which `ray up` is executed.
    #   (2) The head node of the Ray cluster.
    #
    # The machine that runs ray up executes SSH commands to set up the Ray head node. The Ray head node subsequently
    # executes SSH commands to set up the Ray worker nodes. When you run ray up, ssh credentials sitting on the ray up
    # machine are copied to the head node -- internally, the ssh key is added to the list of file mounts to rsync to head node.
    ssh_private_key: ~/.ssh/id_rsa

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == max_workers == len(worker_ips).
min_workers: 1

#initial_workers: 1

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == max_workers == len(worker_ips).
max_workers: 1
# The default behavior for manually managed clusters is
# min_workers == max_workers == len(worker_ips),
# meaning that Ray is started on all available nodes of the cluster.
# For automatically managed clusters, max_workers is required and min_workers defaults to 0.

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

idle_timeout_minutes: 5

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH. E.g. you could save your conda env to an environment.yaml file, mount
# that directory to all nodes and call `conda -n my_env -f /path1/on/remote/machine/environment.yaml`. In this
# example paths on all nodes must be the same (so that conda can be called always with the same argument)
file_mounts: {
#    "~/.ssh": "~/.ssh/backup_202203",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: [
#    "~/.ssh": "~/.ssh",
]

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands: [
#    'ssh-keygen && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys'
#    'sudo chown ray:users /tmp/cluster-default.state'
]
    # If we have e.g. conda dependencies stored in "/path1/on/local/machine/environment.yaml", we can prepare the
    # work environment on each worker by:
    #   1. making sure each worker has access to this file i.e. see the `file_mounts` section
    #   2. adding a command here that creates a new conda environment on each node or if the environment already exists,
    #     it updates it:
    #      conda env create -q -n my_venv -f /path1/on/local/machine/environment.yaml || conda env update -q -n my_venv -f /path1/on/local/machine/environment.yaml
    #
    # Ray developers:
    # you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # To run the nightly version of ray (as opposed to the latest), either use a rayproject docker image
    # that has the "nightly" (e.g. "rayproject/ray-ml:nightly-gpu") or uncomment the following line:
    # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"

# Custom commands that will be run on the head node after common setup.
head_setup_commands: [
#    'conda activate user_py37'
#    'echo "export AUTOSCALER_HEARTBEAT_TIMEOUT_S=120" >> ~/.bashrc'
#     'ssh-keygen && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys'
#    'sudo chown ray:users /tmp/cluster-default.state'

]

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: [
#    'conda activate user_py37'
#    'echo "export AUTOSCALER_HEARTBEAT_TIMEOUT_S=120" >> ~/.bashrc'
]

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
  # If we have e.g. conda dependencies, we could create on each node a conda environment (see `setup_commands` section).
  # In that case we'd have to activate that env on each node before running `ray`:
  # - conda activate my_venv && ray stop
  # - conda activate my_venv && ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  # If we have e.g. conda dependencies, we could create on each node a conda environment (see `setup_commands` section).
  # In that case we'd have to activate that env on each node before running `ray`:
#    - conda activate user_py37 && ray stop
  # - ray start --address=$RAY_HEAD_IP:6379
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 #--metrics-export-port=6666 --dashboard-agent-grpc-port=7777


#ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_070dd72385/9fe1c64cbc/%C -o ControlPersist=10s -o ConnectTimeout=120s user@192.168.1.153 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_HEAD_IP=192.168.1.155; ray start --address=$RAY_HEAD_IP:6379)'"'"'"'"'"'"'"'"''"'"' )'
```
