### ISSUE TITLE
Sometimes the worker nodes show up with the head node's type

### ISSUE THREAD

**Issue by danwallach** [ray-project/ray#11377]
### What is the problem?

This is Python 3.8.5, with the Ray daily wheel. I've got a fairly straightforward configuration with huge nodes for the workers and a smaller node for the head. If you look at my dashboard, you'll see most of the worker nodes have 64 cores, but `172.31.35.149` has 4 cores, even though it's a worker. 

![Screen Shot 2020-10-13 at 4 39 43 PM](https://user-images.githubusercontent.com/743029/95919169-bd66dd00-0d72-11eb-8da4-91568f8cf2f2.png)

### Reproduction (REQUIRED)

Here are the relevant parts of my YAML:

```
cluster_name: default
min_workers: 12
max_workers: 12
initial_workers: 12
target_utilization_fraction: 0.8
idle_timeout_minutes: 10
provider:
    type: aws
    region: us-east-2
    availability_zone: us-east-2a,us-east-2b,us-east-2c
    cache_stopped_nodes: False # If not present, the default is True.

available_node_types:
    worker_x64:
        node_config:
            InstanceType: c5a.16xlarge
        resources: {"CPU": 64}
        max_workers: 64
    head_x64:
        node_config:
            InstanceType: m5a.xlarge
        resources: {"CPU": 4}
        max_workers: 4

worker_default_node_type: worker_x64
head_node_type: head_x64
```

I've seen this sort of behavior on and off for the past month while playing with Ray.

Possibly related issue: https://github.com/ray-project/ray/issues/10929
