### ISSUE TITLE
[rllib] Multi-agent with different hyperparameters

### ISSUE THREAD

**Issue by m3t4n01a** [ray-project/ray#11376]
I've been trying to get a simple **hierarchical system** working on some very basic problems and I am assuming I can't get it to work because I cannot set different hyperparameters for the two agents.

I would like to **train them in the same time**, this means I'll have to settle for the same set of hyperparameters for both agents in any one trial. Is that correct? If so, how would I go about implementing such a feature, where I can set different hyperparameters for agents? Having fixed hyperparams for one of the agents would also work for me I think, but this is not possible either, or is it?

I'd appreciate any help.

**Comment by sven1977** [comment]
There is a hierarchical_training.py example in the examples folder, where this is done with a single trainer and two policies ("multi-agent" setup). You can then specify config-overrides within the "policies" config key:
```
config:
    multiagent:
        policies:
            pol1: {None, [obsspace], [actionspace], {extra config overrides for pol1}}
            pol2: {None, [obsspace], [actionspace], {extra config overrides for pol2}}
```
