### ISSUE TITLE
[core] Stale file handles in the plasma object store take up disk space

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#11950]
<!--Please include [tune], [rllib], [autoscaler] etc. in the issue title if relevant-->

### What is the problem?

When loading large data sets (200GB) into memory and storing (parts of it) in the object store, Ray starts to occupy disk space for the object store file. This disk space stays occupied when the program exits.


`issue.yaml`
```
cluster_name: stale_ref_issue
min_workers: 0
max_workers: 0
initial_workers: 0
autoscaling_mode: default
docker:
    image: 'anyscale/ray-ml:latest'
    container_name: ray_container
    pull_before_run: false
    run_options:
        - --privileged
        - --shm-size=510000000000
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    # cache_stopped_nodes: false
auth:
    ssh_user: ubuntu
head_node:
    InstanceType: r5.16xlarge
    ImageId: ami-05ac7a76b4c679a79

worker_nodes:
    InstanceType: m5.xlarge
    ImageId: ami-05ac7a76b4c679a79
    InstanceMarketOptions:
        MarketType: spot
file_mounts: {
    "/root/xgboost-benchmark": "/Users/kai/coding/anyscale/projects/xgboost-benchmark",
}
cluster_synced_files:
    - /tmp/ray_tmp_mount/~/xgboost-benchmark
file_mounts_sync_continuously: true
initialization_commands: []
setup_commands: []
head_setup_commands: 
    - apt install -y lsof
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=500000000000 --resources='{\"actor_cpus\": 0}'"
worker_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --resources='{\"actor_cpus\": 4}'"
metadata:
    anyscale:
        working_dir: ~/xgboost-benchmark
```

`issue.py`
```python
import os

if "OMP_NUM_THREADS" in os.environ:
    del os.environ["OMP_NUM_THREADS"]

import numpy as np
import pandas as pd

import ray

ray.init(address="auto")

print("Creating dataframe")
df = pd.DataFrame(np.random.uniform(0., 10., size=(1_000_000_000, 10)))
print(f"Created dataframe with {len(df)} rows.")

print("Storing sharded dataframe in object store ")
for i in range(0, 10):
    part = df.iloc[i*100_000_000:(i+1)*100_000_000]
    ray.put(part)
    print(f"Stored shard {i}")

print("Everything is in the object store now.")

```



Before:
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:         510360        3320      505111           1        1928      504240
Swap:             0           0           0


# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          97G   11G   87G  11% /
tmpfs            64M     0   64M   0% /dev
tmpfs           250G     0  250G   0% /sys/fs/cgroup
shm             475G   12K  475G   1% /dev/shm
/dev/root        97G   11G   87G  11% /root/xgboost-benchmark
```

While creating dataframe: free -m memory increases (up until 80GB)
/dev/shm stays the same

After storing the shards:
```
After storing shards/exiting the program:

              total        used        free      shared  buff/cache   available
Mem:         510360        3334      474509       30518       32516      473679
Swap:             0           0           0



# df -h                                                                                                                                                                                                                        ip-172-31-16-137: Wed Nov 11 11:12:54 2020

Filesystem      Size  Used Avail Use% Mounted on
overlay          97G   11G   87G  11% /
tmpfs            64M     0   64M   0% /dev
tmpfs           250G     0  250G   0% /sys/fs/cgroup
shm             475G   30G  446G   7% /dev/shm
/dev/root        97G   11G   87G  11% /root/xgboost-benchmark
```


There's stale file handles to a plasma object store files after the program exits:

```
osquery> select of.*, p.pid, p.name, p.cmdline from process_open_files of left outer join processes p using (pid) where of.path LIKE ‘%(deleted)’;
pid         fd          path                                        pid         name        cmdline
----------  ----------  ------------------------------------------  ----------  ----------  ----------
10129       8           /var/tmp/etilqs_dcf136ced3bd4c36 (deleted)  10129       osqueryi    osqueryi
157         0           /dev/pts/1 (deleted)                        157         redis-serv  /root/anac
162         0           /dev/pts/1 (deleted)                        162         redis-serv  /root/anac
166         0           /dev/pts/1 (deleted)                        166         gcs_server  /root/anac
167         0           /dev/pts/1 (deleted)                        167         /root/anac  /root/anac
185         0           /dev/pts/1 (deleted)                        185         /root/anac  /root/anac
186         0           /dev/pts/1 (deleted)                        186         plasma_sto  /root/anac
187         0           /dev/pts/1 (deleted)                        187         raylet      /root/anac
187         26          /tmp/plasmafC3mGl (deleted)                 187         raylet      /root/anac
190         0           /dev/pts/1 (deleted)                        190         /root/anac  /root/anac
191         0           /dev/pts/1 (deleted)                        191         /root/anac  /root/anac
239         0           /dev/pts/1 (deleted)                        239         ray:IDLE    ray::IDLE
239         26          /tmp/plasmafC3mGl (deleted)                 239         ray:IDLE    ray::IDLE
240         0           /dev/pts/1 (deleted)                        240         ray:IDLE    ray::IDLE
....
357         26          /tmp/plasmafC3mGl (deleted)                 357         ray:IDLE    ray::IDLE
358         0           /dev/pts/1 (deleted)                        358         ray:IDLE    ray::IDLE
358         26          /tmp/plasmafC3mGl (deleted)                 358         ray:IDLE    ray::IDLE
359         0           /dev/pts/1 (deleted)                        359         ray:IDLE    ray::IDLE
359         26          /tmp/plasmafC3mGl (deleted)                 359         ray:IDLE    ray::IDLE
360         0           /dev/pts/1 (deleted)                        360         ray:IDLE    ray::IDLE
360         26          /tmp/plasmafC3mGl (deleted)                 360         ray:IDLE    ray::IDLE
361         0           /dev/pts/1 (deleted)                        361         ray:IDLE    ray::IDLE
361         26          /tmp/plasmafC3mGl (deleted)                 361         ray:IDLE    ray::IDLE
362         0           /dev/pts/1 (deleted)                        362         ray:IDLE    ray::IDLE
362         26          /tmp/plasmafC3mGl (deleted)                 362         ray:IDLE    ray::IDLE
363         0           /dev/pts/1 (deleted)                        363         ray:IDLE    ray::IDLE
363         26          /tmp/plasmafC3mGl (deleted)                 363         ray:IDLE    ray::IDLE
```


### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
