### ISSUE TITLE
[autoscaler] restarting ray with `ray up` switches object store location from /dev/shm to /tmp

### ISSUE THREAD

**Issue by krfricke** [ray-project/ray#11951]
### What is the problem?

Restarting the ray runtime on a cluster that uses docker with shm moves the plasma object store location to /tmp.

After starting the cluster the first time (scroll to end):
```
# ps aux | grep plasma_directory
root        8435  1.3  0.0 979289612 67788 ?     Sl   11:24   0:03 /root/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-11-11_11-24-02_969644_8401/sockets/raylet --store_socket_name=/tmp/ray/session_2020-11-11_11-24-02_969644_8401/sockets/plasma_store --object_manager_port=8076 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=63984 --node_ip_address=172.31.16.137 --redis_address=172.31.16.137 --redis_port=6379 --num_initial_workers=64 --maximum_startup_concurrency=64 --static_resource_list=node:172.31.16.137,1.0,CPU,64,memory,455,object_store_memory,6580 --config_list=plasma_store_as_thread,True --python_worker_command=/root/anaconda3/bin/python /root/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py --node-ip-address=172.31.16.137 --node-manager-port=63984 --object-store-name=/tmp/ray/session_2020-11-11_11-24-02_969644_8401/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-11-11_11-24-02_969644_8401/sockets/raylet --redis-address=172.31.16.137:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=41883 --redis-password=5241590000000000 --java_worker_command= --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-11-11_11-24-02_969644_8401 --metrics-agent-port=41883 --metrics_export_port=63079 --object_store_memory=500000000000 --plasma_directory=/dev/shm --head_node
```

```
ray up -y issue.yaml
```

After restarting (scroll to end):
```
root       13477  3.1  0.0 491008224 67388 ?     Sl   11:29   0:00 /root/anaconda3/lib/python3.7/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-11-11_11-29-30_982983_13439/sockets/raylet --store_socket_name=/tmp/ray/session_2020-11-11_11-29-30_982983_13439/sockets/plasma_store --object_manager_port=8076 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=53349 --node_ip_address=172.31.16.137 --redis_address=172.31.16.137 --redis_port=6379 --num_initial_workers=64 --maximum_startup_concurrency=64 --static_resource_list=node:172.31.16.137,1.0,CPU,64,memory,455,object_store_memory,6580 --config_list=plasma_store_as_thread,True --python_worker_command=/root/anaconda3/bin/python /root/anaconda3/lib/python3.7/site-packages/ray/workers/default_worker.py --node-ip-address=172.31.16.137 --node-manager-port=53349 --object-store-name=/tmp/ray/session_2020-11-11_11-29-30_982983_13439/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-11-11_11-29-30_982983_13439/sockets/raylet --redis-address=172.31.16.137:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=60879 --redis-password=5241590000000000 --java_worker_command= --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-11-11_11-29-30_982983_13439 --metrics-agent-port=60879 --metrics_export_port=50207 --object_store_memory=500000000000 --plasma_directory=/tmp --head_node
root       14852  0.0  0.0   5192  2412 pts/10   S+   11:29   0:00 grep --color=auto plasma_directory
```

`issue.yaml`
```
cluster_name: stale_ref_issue
min_workers: 0
max_workers: 0
initial_workers: 0
autoscaling_mode: default
docker:
    image: 'anyscale/ray-ml:latest'
    container_name: ray_container
    pull_before_run: false
    run_options:
        - --privileged
        - --shm-size=510000000000
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    # cache_stopped_nodes: false
auth:
    ssh_user: ubuntu
head_node:
    InstanceType: r5.16xlarge
    ImageId: ami-05ac7a76b4c679a79

worker_nodes:
    InstanceType: m5.xlarge
    ImageId: ami-05ac7a76b4c679a79
    InstanceMarketOptions:
        MarketType: spot
file_mounts: {
    "/root/xgboost-benchmark": "/Users/kai/coding/anyscale/projects/xgboost-benchmark",
}
cluster_synced_files:
    - /tmp/ray_tmp_mount/~/xgboost-benchmark
file_mounts_sync_continuously: true
initialization_commands: []
setup_commands: []
head_setup_commands: 
    - apt install -y lsof
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=500000000000 --resources='{\"actor_cpus\": 0}'"
worker_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --resources='{\"actor_cpus\": 4}'"
metadata:
    anyscale:
        working_dir: ~/xgboost-benchmark
```

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
