### ISSUE TITLE
[docker] Default docker AWS example won't rsync across nodes

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#12194]
### What is the problem?

In order to rsync files from one node to another, we rely on boto:

```python
config = Config(retries={"max_attempts": BOTO_MAX_RETRIES})
aws_credentials = aws_credentials or {}
ec2 = boto3.client(
    "ec2", region_name=region, config=config, **aws_credentials)
instance_types = ec2.describe_instance_types()
```

However, this will not work on the default docker image. Thus, when you try to rsync between nodes, you run into:
```
'EC2' has no attribute 'describe_instance_types'.
```

# Repro:

take a Tune script and run it on the cluster:

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: basic

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 1
initial_workers: 1
max_workers: 1
autoscaling_mode: aggressive

target_utilization_fraction: 0.9

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 20

docker:
    image: "rayproject/ray:latest-cpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

head_node:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    # InstanceMarketOptions:
    #     MarketType: spot
           # SpotOptions:
           #     MaxPrice: "9.0"


worker_nodes:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    # # Run workers on spot by default. Comment this out to use on-demand.
    # InstanceMarketOptions:
    #     MarketType: spot
        # SpotOptions:
        #     MaxPrice: "9.0"

file_mounts: {
    /root/tune/: ~/ray/python/ray/tune/,
}
initialization_commands: []
setup_commands:
  - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip install ipdb ray[tune] torch torchvision
  - rm -rf  /root/anaconda3/lib/python3.7/site-packages/ray/tune
  - cp -r /root/tune/  /root/anaconda3/lib/python3.7/site-packages/ray/tune

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# # Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=1000000000

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=1000000000
```
