### ISSUE TITLE
[Autoscaler] [Docker] Cluster shutdown fails with `No such container: ray_container`

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#12326]
I have a AWS cluster using Docker. I try to shut it down with `ray down cluster.yaml` and it fails with this error:
```
Loaded cached provider configuration from /var/folders/qt/f7ftj_xs6fn_swc4vn7kx0y80000gn/T/ray-config-a2a9e60572b77712cee83f75d3fb9a7c71fb2fb4
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Destroying cluster. Confirm [y/N]: y
Fetched IP: 34.219.19.214
Running `docker exec -it  ray_container /bin/bash -c 'bash --login -c -i '"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'"'"'' `
Warning: Permanently added '34.219.19.214' (ECDSA) to the list of known hosts.
Error: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Command failed:

  ssh -tt -i ~/.ssh/amog-anyscale.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_15207363a2/b961348b8b/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@34.219.19.214 bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (ray stop)'"'"'"'"'"'"'"'"''"'"' )'

Exception occurred when stopping the cluster Ray runtime (use -v to dump teardown exceptions).
Ignoring the exception and attempting to shut down the cluster nodes anyway.
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Warning: Permanently added '34.219.19.214' (ECDSA) to the list of known hosts.
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-0dc3d73bfd56fd872
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-06fdae5f11ded53cd
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-0043a53e10d32d032
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-0bdb7ec77187c757e
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-07d8ef27afa026bb3
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-0e4b95f27a5c259a4
Fetched IP: 34.219.19.214
Running `docker stop ray_container`
Error response from daemon: No such container: ray_container
Shared connection to 34.219.19.214 closed.
Docker stop failed on i-033c3290cbd0a2bca
```
The 4 lines from `Fetched IP` to `Docker stop failed` continuously gets repeated.

Here is my YAML file for reference:
```
cluster_name: amog_xgboost_tune
min_workers: 1
max_workers: 200
initial_workers: 1
autoscaling_mode: default
docker:
    image: 'anyscale/ray-ml:latest'
    container_name: ray_container
    pull_before_run: false
    run_options:
        - --privileged
        - --shm-size=510000000000
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    cache_stopped_nodes: false
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/amog-anyscale.pem
head_node:
    # InstanceType: m5.4xlarge
    InstanceType: r5.16xlarge
    ImageId: ami-05ac7a76b4c679a79
    KeyName: amog-anyscale
worker_nodes:
    InstanceType: m5.xlarge
    ImageId: ami-05ac7a76b4c679a79
    KeyName: amog-anyscale
    InstanceMarketOptions:
        MarketType: spot
initialization_commands: []
setup_commands:
    - echo "hello"
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - pip install dask distributed xgboost s3fs
head_setup_commands: 
    - echo "hello"
    - pip install -U git+https://github.com/ray-project/xgboost_ray@master#xgboost_ray
worker_setup_commands:
    - echo "hello"
    - pip install -U git+https://github.com/ray-project/xgboost_ray@master#xgboost_ray
head_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=500000000000 --resources='{\"actor_cpus\": 0}'"
worker_start_ray_commands:
    - ray stop
    - "ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --resources='{\"actor_cpus\": 4}'"
```

Is there anyway I can force shutdown of the cluster?

cc @ijrsvt
