### ISSUE TITLE
[autoscaler] Unable to connect to local cluster.

### ISSUE THREAD

**Issue by akhiarov** [ray-project/ray#12451]
**System information**

-     OS Platform and Distribution: Ubuntu 20.04.1 LTS
-     Ray installed from (source or binary): binary (pip install ray)
-     Ray version: 1.0.1.post1
-     Python version: Python 3.7.7 (installed with conda 4.8.2 in separate environment)
-     Exact command to reproduce: import ray; ray.init(address="auto")

**Describe the problem**

Created cluster with 1 head and 2 workers (see .yaml content below)
Started ray cluster with the command
`ray up ray-cluster.yaml`
It looks like cluster was started, since http://localhost:8265/ shows all workers.
`ray monitor ray-cluster.yaml`
shows correct number of total nodex and, cores(CPU):

> 2020-11-26 19:36:51,615	INFO autoscaler.py:591 -- Cluster status: 2/2 target nodes (0 pending)
>  - MostDelayedHeartbeats: {'192.168.1.72': 0.12203049659729004, '192.168.1.74': 0.12198352813720703, '192.168.1.70': 0.12194204330444336}
>  - NodeIdleSeconds: Min=3018 Mean=3023 Max=3032
>  - NumNodesConnected: 3
>  - NumNodesUsed: 0.0
>  - ResourceUsage: 0.0/14.0 CPU, 0.0 GiB/10.59 GiB memory, 0.0 GiB/3.36 GiB object_store_memory
>  - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0
> 

But the command 
`ray timeline`
Gives the error:

> 2020-11-26 22:41:18,937	INFO scripts.py:1312 -- Connecting to Ray instance at 192.168.1.70:6379.
> 2020-11-26 22:41:18,938	INFO worker.py:651 -- Connecting to existing Ray cluster at address: 192.168.1.70:6379
> F1126 22:41:28.965765 52127 52127 raylet_client.cc:57] Could not connect to socket /tmp/ray/session_2020-11-26_18-46-18_070553_90/sockets/raylet
> *** Check failure stack trace: ***
>     @     0x7f175212587d  google::LogMessage::Fail()
>     @     0x7f1752126cec  google::LogMessage::SendToLog()
>     @     0x7f1752125559  google::LogMessage::Flush()
>     @     0x7f1752125771  google::LogMessage::~LogMessage()
>     @     0x7f17520d8be9  ray::RayLog::~RayLog()
>     @     0x7f1751df402f  ray::raylet::RayletConnection::RayletConnection()
>     @     0x7f1751df5340  ray::raylet::RayletClient::RayletClient()
>     @     0x7f1751d9889b  ray::CoreWorker::CoreWorker()
>     @     0x7f1751d9c454  ray::CoreWorkerProcess::CreateWorker()
>     @     0x7f1751d9d6c2  ray::CoreWorkerProcess::CoreWorkerProcess()
>     @     0x7f1751d9e09b  ray::CoreWorkerProcess::Initialize()
>     @     0x7f1751cce006  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
>     @     0x7f1751ccf7b5  __pyx_tp_new_3ray_7_raylet_CoreWorker()
>     @     0x561718c22c49  _PyObject_FastCallKeywords
>     @     0x561718c879a1  _PyEval_EvalFrameDefault
>     @     0x561718bcbb00  _PyEval_EvalCodeWithName
>     @     0x561718c1b497  _PyFunction_FastCallKeywords
>     @     0x561718c83cba  _PyEval_EvalFrameDefault
>     @     0x561718bcbb00  _PyEval_EvalCodeWithName
>     @     0x561718c1b497  _PyFunction_FastCallKeywords
>     @     0x561718c83cba  _PyEval_EvalFrameDefault
>     @     0x561718bcb2b9  _PyEval_EvalCodeWithName
>     @     0x561718bcc610  _PyFunction_FastCallDict
>     @     0x561718c8451a  _PyEval_EvalFrameDefault
>     @     0x561718bcb2b9  _PyEval_EvalCodeWithName
>     @     0x561718bcc610  _PyFunction_FastCallDict
>     @     0x561718beab93  _PyObject_Call_Prepend
>     @     0x561718bdd95e  PyObject_Call
>     @     0x561718c8451a  _PyEval_EvalFrameDefault
>     @     0x561718c1b20b  _PyFunction_FastCallKeywords
>     @     0x561718c82e70  _PyEval_EvalFrameDefault
>     @     0x561718bcbb00  _PyEval_EvalCodeWithName
> Aborted (core dumped)
> 

When I try to use ray from Python by running 
```
import ray
ray.init(address="auto")
```
I am getting error message too:

> 2020-11-26 21:19:55,158	INFO worker.py:651 -- Connecting to existing Ray cluster at address: 192.168.1.70:6379
> F1126 21:20:05.187245 44658 44658 raylet_client.cc:57] Could not connect to socket /tmp/ray/session_2020-11-26_18-19-15_205352_132/sockets/raylet
> *** Check failure stack trace: ***
>     @     0x7ff0cb04887d  google::LogMessage::Fail()
>     @     0x7ff0cb049cec  google::LogMessage::SendToLog()
>     @     0x7ff0cb048559  google::LogMessage::Flush()
>     @     0x7ff0cb048771  google::LogMessage::~LogMessage()
>     @     0x7ff0caffbbe9  ray::RayLog::~RayLog()
>     @     0x7ff0cad1702f  ray::raylet::RayletConnection::RayletConnection()
>     @     0x7ff0cad18340  ray::raylet::RayletClient::RayletClient()
>     @     0x7ff0cacbb89b  ray::CoreWorker::CoreWorker()
>     @     0x7ff0cacbf454  ray::CoreWorkerProcess::CreateWorker()
>     @     0x7ff0cacc06c2  ray::CoreWorkerProcess::CoreWorkerProcess()
>     @     0x7ff0cacc109b  ray::CoreWorkerProcess::Initialize()
>     @     0x7ff0cabf1006  __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
>     @     0x7ff0cabf27b5  __pyx_tp_new_3ray_7_raylet_CoreWorker()
>     @     0x55e1b400ac49  _PyObject_FastCallKeywords
>     @     0x55e1b406f9a1  _PyEval_EvalFrameDefault
>     @     0x55e1b3fb3b00  _PyEval_EvalCodeWithName
>     @     0x55e1b4003497  _PyFunction_FastCallKeywords
>     @     0x55e1b406bcba  _PyEval_EvalFrameDefault
>     @     0x55e1b3fb3b00  _PyEval_EvalCodeWithName
>     @     0x55e1b4003497  _PyFunction_FastCallKeywords
>     @     0x55e1b406bcba  _PyEval_EvalFrameDefault
>     @     0x55e1b3fb32b9  _PyEval_EvalCodeWithName
>     @     0x55e1b3fb41d4  PyEval_EvalCodeEx
>     @     0x55e1b3fb41fc  PyEval_EvalCode
>     @     0x55e1b40c9f44  run_mod
>     @     0x55e1b40d42b1  PyRun_FileExFlags
>     @     0x55e1b40d44a3  PyRun_SimpleFileExFlags
>     @     0x55e1b40d55d5  pymain_main
>     @     0x55e1b40d56fc  _Py_UnixMain
>     @     0x7ff0cc19f0b3  __libc_start_main
>     @     0x55e1b407a3c0  (unknown)
> Aborted (core dumped)
>

**Comment by akhiarov** [comment]
**ray-cluster.yaml**

```
cluster_name: grid
min_workers: 2
max_workers: 2
#upscaling_speed: 1.0
idle_timeout_minutes: 5
docker:
    image: "rayproject/ray:latest-cpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_container"
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"
provider:
    type: local
    head_ip: grid-0
    worker_ips: [grid-2, grid-4]
auth:
    ssh_user: roustem
    ssh_private_key: ~/.ssh/id_rsa
head_node: {}
worker_nodes: {}
file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: False
rsync_exclude:
    - "**/.git"
    - "**/.git/**"
is searched for
if .gitignore is provided
rsync_filter:
    - ".gitignore"
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379

```
