### ISSUE TITLE
No way to configure own VPC or subnet IDs

### ISSUE THREAD

**Issue by Laksh1997** [ray-project/ray#12530]
Hi. In the configuration file, I try to add custom subnets. However, they do not register. It ends up using completely different subnets.

```yaml
# ~/Desktop/ray_cluster.yaml
cluster_name: default

min_workers: 0
max_workers: 2

docker:
    image: "rayproject/ray:latest-gpu"
    container_name: "ray_container"
    pull_before_run: True
    run_options: []

provider:
    type: aws
    region: eu-west-1
    availability_zone: eu-west-1a,eu-west-1b
    cache_stopped_nodes: False # If not present, the default is True.

auth:
    ssh_user: ubuntu

head_node:
    # VpcId:
    SubnetId: subnet-***********qwe
    # CidrBlock: 10.19.0.0/16
    InstanceType: m5a.large
    ImageId: ami-006ff58f5247c50eb # Deep Learning AMI (Ubuntu) Version 30

    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 100


worker_nodes:
    SubnetId: subnet-***********qwe
    InstanceType: m5a.large
    ImageId: ami-006ff58f5247c50eb # Deep Learning AMI (Ubuntu) Version 30

```

```
ray up -y ~/Desktop/ray_cluster.yaml
```

Then it starts the cluster, using completely different subnets!

```
Cluster: default

Checking AWS environment settings
AWS config
  IAM Profile: ray-autoscaler-v1 [default]
  EC2 Key pair (head & workers): ray-autoscaler_eu-west-1 [default]
  VPC Subnets (head & workers): subnet-******xyz, subnet-*******abc, subnet-*******ghj, subnet-*********jkl [default]
  EC2 Security groups (head & workers): sg-08311cf18ac8ee7fe [default]
  EC2 AMI (head & workers): ami-006ff58f5247c50eb

No head node found. Launching a new cluster. Confirm [y/N]: y [automatic, due to --yes]

Acquiring an up-to-date head node
  Launched 1 nodes [subnet_id=subnet-03522bc8f27f03e72]
    Launched instance i-05b500ebd17f1bfe9 [state=pending, info=pending]
  Launched a new head node
  Fetching the new head node

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/6] Waiting for SSH to become available
    Running `uptime` as a test.
    Waiting for IP
      Not yet available, retrying in 10 seconds
```
