### ISSUE TITLE
[core] Using ray wheels with latest master in a Python soft-link setup breaks

### ISSUE THREAD

**Issue by roireshef** [ray-project/ray#12543]
### What is the problem?
I'm trying to edit ray python code with using latest nightly build and soft-linking to my Ray repo using the script in:
https://docs.ray.io/en/master/development.html#building-ray-python-only

It fails on missing files and constants. The soft-linking script is probably missing some files, but I'm not entirely sure which ones to add and which to not. 

*Ray version and other system information (Python version, TensorFlow version, OS):*
Latest nightly wheel
Latest master branch

### Reproduction (REQUIRED)
1. install latest Ray nightly wheel and run he script in https://docs.ray.io/en/master/development.html#building-ray-python-only
2. Run any Tune experiment

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by simon-mo** [comment]
Thanks for filing this issue. Which commit are you on? This might be related to https://github.com/ray-project/ray/commit/9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd cc @sven1977

**Comment by roireshef** [comment]
> Thanks for filing this issue. Which commit are you on? This might be related to [9021f15](https://github.com/ray-project/ray/commit/9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd) cc @sven1977

@simon-mo I'm at 9021f15b2ac4a72187c7770f6a8f6d3a6f3373bd ("[RLlib] Fix setup-dev.py error when creating a softlink for new_dashboard. (#12442)") but please do note that there are quite a few exceptions thrown asking for different files that aren't mapped with soft links but neither exist in the nightly build.

It might be a good idea to include a test that makes sure this setup isn't broken when PRs are getting approved by your build system.

**Comment by simon-mo** [comment]
@sven1977 can you help?

**Comment by wuisawesome** [comment]
@roireshef do you have a reproduction of this? For reference, this seems to consistently work for me when doing autoscaler development. 

Happy to find some time to sit down with you pair debug if this is still an issue btw. 

For reference, here's a cluster yaml of my typical setup:

```
# Experimental: an example of configuring a mixed-node-type cluster.
cluster_name: alex
min_workers: 0
max_workers: 40

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-1
    availability_zone: us-west-1a

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    cpu_4_ondemand:
        node_config:
            InstanceType: m4.xlarge
        # For AWS instances, autoscaler will automatically add the available
        # CPUs/GPUs/accelerator_type ({"CPU": 4} for m4.xlarge) in "resources".
        resources: {"CPU": 4}
        min_workers: 2
        max_workers: 5
    custom1:
        node_config:
            InstanceType: m4.4xlarge
            InstanceMarketOptions:
                MarketType: spot
        resources: {"Custom1": 1}
        max_workers: 10
    custom2:
        node_config:
            InstanceType: m4.4xlarge
            InstanceMarketOptions:
                MarketType: spot
        resources: {"Custom2": 2}
        max_workers: 4

# Specify the node type of the head node (as configured above).
head_node_type: cpu_4_ondemand

# Specify the default type of the worker node (as configured above).
worker_default_node_type: cpu_4_ondemand

# The default settings for the head node. This will be merged with the per-node
# type configs given above.
head_node:
    ImageId: latest_dlami

# The default settings for worker nodes. This will be merged with the per-node
# type configs given above.
worker_nodes:
    ImageId: latest_dlami

setup_commands:
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-1.1.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
    - git clone --branch master https://github.com/wuisawesome/ray.git || true
    - pushd ray; git reset --hard; popd;
    - ray/python/ray/setup-dev.py -y 
    - rm /home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py
    - ln -s /home/ubuntu/ray/python/ray/monitor.py /home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/monitor.py


# Configure the cluster for very conservative auto-scaling otherwise.
target_utilization_fraction: 1.0
idle_timeout_minutes: 2

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
```
