### ISSUE TITLE
Command runner logs are improperly quoted when logged

### ISSUE THREAD

**Issue by worldveil** [ray-project/ray#12631]
### What is the problem?

Commands in the monitor logs are incorrectly quoted. This makes debugging issues really, really tough since I can't be sure what the actual command run to get the error was. 

In particular, when scaling up a cluster, I ran into this rsync error, for which running the verbatim logged command doesn't result in the same error as the log states. 

```
# cat /tmp/ray/session_latest/logs/monitor.out | grep rsync
2020-12-04 20:43:53,849 VINFO command_runner.py:522 -- Running `rsync --rsh ssh -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_63a9f0ea7b/f786baef9d/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz --exclude **/.git --exclude **/.git/** --filter dir-merge,- .gitignore /tmp/anyscale-0.3.24.tar.gz ubuntu@172.31.26.88:/tmp/ray_tmp_mount/anyscale-dev-prod-aedb54c828929615/tmp/anyscale-0.3.24.tar.gz`
```

You can see around things like `--filter dir-merge,- .gitignore` there should be quotes. The command just fails as written, but that's not how it was run on the cluster.

Versions:

```
# ray --version
ray, version 1.0.1.post1
# python --version
Python 3.7.7
```

### Reproduction (REQUIRED)

YAML to reproduce:

```yaml
min_workers: 2
max_workers: 2

docker:
    image: anyscale/ray-ml:latest-gpu
    container_name: ray_container
    pull_before_run: False

head_node:
    InstanceType: p2.xlarge
    IamInstanceProfile:
        Arn: '<ARN HERE>'
worker_nodes:
    InstanceType: p2.xlarge
    IamInstanceProfile:
        Arn: '<ARN HERE>'

rsync_exclude:
    - "**/.git"
    - "**/.git/**"
rsync_filter:
    - ".gitignore"

setup_commands:
    - >-
      git clone git@bitbucket.org/org/project.git /project || true;

target_utilization_fraction: 0.8

head_start_ray_commands:
    - >-
      ray stop;
      ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml;

worker_start_ray_commands:
    - >-
      ray stop;
      ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076;

provider:
    type: aws
    region: ap-southeast-2
    cache_stopped_nodes: true

auth:
    ssh_user: ubuntu

metadata:
    anyscale:
        working_dir: /project
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
