### ISSUE TITLE
[autoscaler] resource demands are not removed when ray.kill() is called on an actor that did not start yet.

### ISSUE THREAD

**Issue by AmeerHajAli** [ray-project/ray#12698]
The resource demands of an actor killed with ray.kill() are not removed if the actor did not start yet (say waiting for its worker node to launch)
### Reproduction (REQUIRED)
yaml:
```
available_node_types:
    def_head:
        node_config: {}
        resources: {"CPU": 2}
        max_workers: 1
    def_worker:
        node_config: {}
        resources: {"CPU": 2, "GPU": 1,  "WORKER": 1}
        max_workers: 3
```
the code:
```
import os
import ray

ray.init(address="auto")

@ray.remote(num_cpus=0.2, resources={"WORKER": 1.0})
class ActorA:
    def __init__(self):
        pass

a = ActorA.remote()
ray.kill(a) # do not wait until it starts
```
this will print:
`INFO resource_demand_scheduler.py:186 -- Resource demands: [{'WORKER': 1.0, 'CPU': 0.2}]`

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
