### ISSUE TITLE
[7/7] Starting the Ray runtime ISSUES

### ISSUE THREAD

**Issue by Marco-Macedo** [ray-project/ray#13086]
Hello,
After the cluster configuration file(.yaml), we tried to lauch the cluster with the command ray up but he are having problems with the 7 step:

(.YAML FILE)
///////////////////////////////////////////////////////////////////////////////////////////////
```
# A unique identifier for this cluster.
cluster_name: default

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 1 # this means 1  workers

upscaling_speed: 1.0

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
  type: local
  head_ip: 10.2.33.225
  worker_ips: [10.2.33.233]


# How Ray will authenticate with newly launched nodes.
auth:
  ssh_user: faomen
  ssh_private_key: ~/.ssh/id_rsa

file_mounts_sync_continuously: False

initialization_commands: []

setup_commands:
- ll /users/faomen
- ls /users/faomen


head_setup_commands: []

worker_setup_commands:
- ll /users/faomen

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
- ray stop
- ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
- ray stop
- ulimit -n 65536; ray start --address=$10.2.33.225:6379 --object-manager-port=8076
```

And the error output is this:
```
 [7/7] Starting the Ray runtime
Could not terminate `/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --store_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --object_manager_port=0 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=65426 --node_ip_address=10.2.33.225 --redis_address=10.2.33.225 --redis_port=6379 --num_initial_workers=4 --maximum_startup_concurrency=4 --static_resource_list=node:10.2.33.225,1.0,CPU,4,memory,189,object_store_memory,65 --config_list=plasma_store_as_thread,True "--python_worker_command=/usr/bin/python3 /usr/local/lib/python3.8/dist-packages/ray/workers/default_worker.py --node-ip-address=10.2.33.225 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --redis-address=10.2.33.225:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=61543 --redis-password=5241590000000000" --java_worker_command= --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339 --metrics-agent-port=61543 --metrics_export_port=54295 "--agent_command=/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/new_dashboard/agent.py --node-ip-address=10.2.33.225 --redis-address=10.2.33.225:6379 --metrics-export-port=54295 --dashboard-agent-port=61543 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password=5241590000000000" --object_store_memory=4957699276 --plasma_directory=/dev/shm --head_node` due to psutil.AccessDenied (pid=41369, name='raylet')
Could not terminate `/usr/local/lib/python3.8/dist-packages/ray/core/src/plasma/plasma_store_server -s /tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store -m 4957699276 -d /dev/shm -z` due to psutil.AccessDenied (pid=41368, name='plasma_store_server')
Could not terminate `/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/gcs/gcs_server --redis_address=10.2.33.225 --redis_port=6379 --config_list=plasma_store_as_thread,True --gcs_server_port=0 --metrics-agent-port=61543 --node-ip-address=10.2.33.225 --redis_password=5241590000000000` due to psutil.AccessDenied (pid=41354, name='gcs_server')
Could not terminate `/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/monitor.py --logs-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-address=10.2.33.225:6379 --redis-password=5241590000000000` due to psutil.AccessDenied (pid=41355, name='/usr/bin/python')
Could not terminate `/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/log_monitor.py --redis-address=10.2.33.225:6379 --logs-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password 5241590000000000` due to psutil.AccessDenied (pid=41370, name='/usr/bin/python')
Could not terminate `"/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *:6379" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=41342, name='redis-server')
Could not terminate `"/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/thirdparty/redis/src/redis-server *:48772" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" ""` due to psutil.AccessDenied (pid=41349, name='redis-server')
Could not terminate `/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --store_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --object_manager_port=0 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=65426 --node_ip_address=10.2.33.225 --redis_address=10.2.33.225 --redis_port=6379 --num_initial_workers=4 --maximum_startup_concurrency=4 --static_resource_list=node:10.2.33.225,1.0,CPU,4,memory,189,object_store_memory,65 --config_list=plasma_store_as_thread,True "--python_worker_command=/usr/bin/python3 /usr/local/lib/python3.8/dist-packages/ray/workers/default_worker.py --node-ip-address=10.2.33.225 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --redis-address=10.2.33.225:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=61543 --redis-password=5241590000000000" --java_worker_command= --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339 --metrics-agent-port=61543 --metrics_export_port=54295 "--agent_command=/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/new_dashboard/agent.py --node-ip-address=10.2.33.225 --redis-address=10.2.33.225:6379 --metrics-export-port=54295 --dashboard-agent-port=61543 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password=5241590000000000" --object_store_memory=4957699276 --plasma_directory=/dev/shm --head_node` due to psutil.AccessDenied (pid=41369, name='raylet')
Could not terminate `/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/log_monitor.py --redis-address=10.2.33.225:6379 --logs-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password 5241590000000000` due to psutil.AccessDenied (pid=41370, name='/usr/bin/python')
Could not terminate `/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/new_dashboard/dashboard.py --host=localhost --port=8265 --redis-address=10.2.33.225:6379 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password 5241590000000000` due to psutil.AccessDenied (pid=41367, name='/usr/bin/python')
Could not terminate `/usr/local/lib/python3.8/dist-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --store_socket_name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --object_manager_port=0 --min_worker_port=10000 --max_worker_port=10999 --node_manager_port=65426 --node_ip_address=10.2.33.225 --redis_address=10.2.33.225 --redis_port=6379 --num_initial_workers=4 --maximum_startup_concurrency=4 --static_resource_list=node:10.2.33.225,1.0,CPU,4,memory,189,object_store_memory,65 --config_list=plasma_store_as_thread,True "--python_worker_command=/usr/bin/python3 /usr/local/lib/python3.8/dist-packages/ray/workers/default_worker.py --node-ip-address=10.2.33.225 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --redis-address=10.2.33.225:6379 --config-list=plasma_store_as_thread,True --temp-dir=/tmp/ray --metrics-agent-port=61543 --redis-password=5241590000000000" --java_worker_command= --cpp_worker_command= --redis_password=5241590000000000 --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339 --metrics-agent-port=61543 --metrics_export_port=54295 "--agent_command=/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/new_dashboard/agent.py --node-ip-address=10.2.33.225 --redis-address=10.2.33.225:6379 --metrics-export-port=54295 --dashboard-agent-port=61543 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password=5241590000000000" --object_store_memory=4957699276 --plasma_directory=/dev/shm --head_node` due to psutil.AccessDenied (pid=41369, name='raylet')
Could not terminate `/usr/bin/python3 -u /usr/local/lib/python3.8/dist-packages/ray/new_dashboard/agent.py --node-ip-address=10.2.33.225 --redis-address=10.2.33.225:6379 --metrics-export-port=54295 --dashboard-agent-port=61543 --node-manager-port=65426 --object-store-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/plasma_store --raylet-name=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/sockets/raylet --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2020-12-26_10-01-28_619441_41339/logs --redis-password=5241590000000000` due to psutil.AccessDenied (pid=41412, name='/usr/bin/python')
```
