### ISSUE TITLE
dashboard crashes on KeyboardInterrupt with gRPC error "Deadline Exceeded"

### ISSUE THREAD

**Issue by alifaki077** [ray-project/ray#13122]
### What is the problem?

So as the title says, when I press Ctrl + C to stop a running program the dashboard crashes with the following error in dashboard.err

```
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/ray/dashboard/dashboard.py", line 697, in run
    timeout=2)
  File "/root/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1609339839.469843129","description":"Error received from peer ipv4:<HEAD-IP-HERE>:49647","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 0.8.7
Python 3.7.7
The code is running in a local cluster inside docker

### Reproduction (REQUIRED)

```python
# main.py
import ray
import time

ray.init(dashboard_host="0.0.0.0", dashboard_port=8265)

@ray.remote
def f():
    time.sleep(1)
    print("done")

if __name__ == "__main__":
    refs = []
    for i in range(100):
        refs.append(f.remote())
    ray.get(refs)

```

and here's cluster config

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: default

## NOTE: Typically for local clusters, min_workers == initial_workers == max_workers == len(worker_ips).

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
min_workers: 2
# The initial number of worker nodes to launch in addition to the head node.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
initial_workers: 2

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == initial_workers == max_workers == len(worker_ips).
max_workers: 2

# Autoscaling parameters.
# Ignore this if min_workers == initial_workers == max_workers.
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
docker:
    image: "rayproject/ray:0.8.7" # e.g., rayproject/ray:0.8.7
    container_name: "ray_test" # e.g. ray_docker
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: False
    run_options:  # Extra options to pass into "docker run"
      - --shm-size=512m
      - -e PYTHONDONTWRITEBYTECODE=1

# Local specific configuration.
provider:
    type: local
    head_ip: $HEAD_IP
    worker_ips:
        - $WORKER_1_IP
        - $WORKER_2_IP
    # Optional when running automatic cluster management on prem. If you use a coordinator server,
    # then you can launch multiple autoscaling clusters on the same set of machines, and the coordinator
    # will assign individual nodes to clusters as needed.
    #    coordinator_address: "<host>:<port>"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: $USER
    # Optional if an ssh private key is necessary to ssh to the cluster.
    ssh_private_key: ~/.ssh/id_rsa

# Leave this empty.
head_node: {}

# Leave this empty.
worker_nodes: {}

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
     "~/$USER/main.py": "main.py"
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: True

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
# install docker if it's not installed
initialization_commands:
- "docker -v || (apt-get install sudo curl rsync && \
             curl -fsSL https://get.docker.com -o get-docker.sh && \
             sudo sh get-docker.sh && \
             sudo usermod -aG docker $USER && \
             sudo systemctl restart docker -f)"

# List of shell commands to run to set up each nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
