### ISSUE TITLE
[autoscaler] How to start kubernetes autoscaler docker container with non-root user

### ISSUE THREAD

**Issue by monaxu1** [ray-project/ray#13369]
**Description:**
My goal is to start a k8s cluster/node with non-root user, say `jovyan`. I have added a user `jovyan` to  the docker image for kubernetes autoscaler and it works well locally. In addition, I added `- --user=jovyan` to the `run_options` in `autoscaler-k8s.yaml`. However, when I was trying to launch a k8s cluster via `ray attach autoscaler-k8s.yaml`, the user option doesn't seem to work, as I was still under root user.

Any idea of how to solve this issue?

Main part of yaml file has been posted as below,
```
# Kubernetes pod config for the head node pod.
head_node:
    apiVersion: v1
    kind: Pod
    metadata:
        # Automatically generates a name for the pod with this prefix.
        generateName: ray-head-
    spec:
        serviceAccountName: autoscaler

        restartPolicy: Never

        volumes:
         - name: dshm
           emptyDir:
            medium: Memory

        containers:
        - name: ray-node
          imagePullPolicy: Always
          image: autoscaler:test
          command: ["/bin/bash", "-c", "--"]
          args: ["trap : TERM INT; sleep infinity & wait;"]
          ports:
              - containerPort: 6379 # Redis port.
              - containerPort: 6380 # Redis port.
              - containerPort: 6381 # Redis port.
              - containerPort: 12345 # Ray internal communication.
              - containerPort: 12346 # Ray internal communication.

          # This dshm volume allocates shared memory for Ray to use for its plasma
          # object store. 

          volumeMounts:
              - mountPath: /dev/shm
                name: dshm
                
          # For cpu machine
          resources:
              requests:
                  cpu: 1
                  memory: 4Gi
              limits:
                  memory: 15Gi
                  cpu: 4
          env:
              - name: MY_CPU_REQUEST
                valueFrom:
                    resourceFieldRef:
                        resource: requests.cpu
          run_options:
            - --user=jovyan
```
