### ISSUE TITLE
Ray cluster: auth_user permissions

### ISSUE THREAD

**Issue by theoturner** [ray-project/ray#13602]
### What is the problem?

Ray permissions do not match those of the `auth ssh_user` specified. Ray Cluster on Ubuntu (v1.1).

### Reproduction

Create a ray cluster from `.yaml` with:
```yaml
auth:
    ssh_user: ubuntu

...

head_setup_commands:
    - mkdir abc
```
Start cluster:
```
ray up /path/to/your.yaml
```
Result:
```
mkdir: cannot create directory ‘abc’: Permission denied
```

However, logging in as user `ubuntu`: `mkdir abc` works fine.

As I understand this is because ray works in a container with working directory `/`.

So, ideally we'd want to copy `/home/ubuntu` into the container - how do we do that?
