### ISSUE TITLE
[Autoscaler] Resources field should not be required in available node types.

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#13911]
### What is the problem?

The `resources` field should not be required when using available node types. 

For example, in 

```
cluster_name: single-node-benchmarks
min_workers: 0
max_workers: 0

upscaling_speed: 9999999

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a

auth:
    ssh_user: ubuntu

available_node_types:
    head_node:
        node_config:
            InstanceType: m4.16xlarge
            ImageId: ami-098555c9b343eb09c 
        resources:
          node: 1
        max_workers: 999999
    worker_node:
        node_config:
            InstanceType: m4.xlarge
            ImageId: ami-098555c9b343eb09c 

head_node_type: head_node

worker_default_node_type: worker_node
```

the worker node will fail to validate because it doesn't contain `resources: {}`. 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
