### ISSUE TITLE
[autoscaler] Support Memory Aware Scheduling on a multi-node-type cluster.

### ISSUE THREAD

**Issue by birgerbr** [ray-project/ray#14104]
Using [Support Memory Aware Scheduling](https://docs.ray.io/en/master/memory-management.html#memory-aware-scheduling) is very useful, but it's not supported yet together with a multi-node-type cluster as the memory resource in `available_node_types` not supported (https://discuss.ray.io/t/what-is-the-memory-unit-in-available-node-types-resources/857/4).

Btw: Thanks for a great product!

**Comment by rkooo567** [comment]
Thanks @birgerbr for the request! :) 

cc @AmeerHajAli Can we add a priority flag to this request so that we won't lose the track of it?

Also @birgerbr can you elaborate your use cases here? It'll be helpful for us to decide the priority of the task!

**Comment by birgerbr** [comment]
Here is an example of trying to use a memory-aware function on a multi-node-type cluster:

`memory_aware_func.py`:
```py
import ray

ray.init(address="auto")

def f():
    pass

ray.get(ray.remote(memory=200*1024**2)(f).remote())
print("Done")
```

ray cluster config (without any memory resource in `available_node_types`):
```yaml
cluster_name: default
min_workers: 0
max_workers: 5
upscaling_speed: 10.0
idle_timeout_minutes: 5
provider:
    type: kubernetes
    use_internal_ips: true
    namespace: ray
    autoscaler_service_account:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
            name: autoscaler
    autoscaler_role:
        kind: Role
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
            name: autoscaler
        rules:
        - apiGroups: [""]
          resources: ["pods", "pods/status", "pods/exec"]
          verbs: ["get", "watch", "list", "create", "delete", "patch"]
    autoscaler_role_binding:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
            name: autoscaler
        subjects:
        - kind: ServiceAccount
          name: autoscaler
        roleRef:
            kind: Role
            name: autoscaler
            apiGroup: rbac.authorization.k8s.io
    services:
      - apiVersion: v1
        kind: Service
        metadata:
            name: ray-head
        spec:
            selector:
                component: ray-head
            ports:
                - protocol: TCP
                  port: 8000
                  targetPort: 8000
                  name: 8k
                - protocol: TCP
                  port: 6379
                  name: redis-primary
                  targetPort: 6379
                - protocol: TCP
                  port: 6380
                  targetPort: 6380
                  name: redis-shard-0
                - protocol: TCP
                  port: 6381
                  targetPort: 6381
                  name: redis-shard-1
                - protocol: TCP
                  port: 12345
                  targetPort: 12345
                  name: object-manager
                - protocol: TCP
                  port: 12346
                  targetPort: 12346
                  name: node-manager
      - apiVersion: v1
        kind: Service
        metadata:
            name: ray-workers
        spec:
            selector:
                component: ray-worker
            ports:
                - protocol: TCP
                  port: 8000
                  targetPort: 8000

available_node_types:
    head_node:
        node_config:
            metadata:
                generateName: ray-head-
                labels:
                    component: ray-head
                tolerations:
                - key: ray-head
                  operator: Equal
                  value: "true"
                  effect: NoSchedule
        resources: {}
        min_workers: 0
        max_workers: 0
    node_pool_cpu:
        node_config:
            apiVersion: v1
            kind: Pod
            metadata:
                generateName: ray-worker-cpu-
                labels:
                    component: ray-worker
            spec:
                tolerations:
                - key: cloud.google.com/gke-preemptible
                  operator: Equal
                  value: "true"
                  effect: NoSchedule
                - key: imerso-ray-worker
                  operator: Equal
                  value: "true"
                  effect: NoSchedule
                serviceAccountName: default
                restartPolicy: Never
                volumes:
                - name: dshm
                  emptyDir:
                      medium: Memory
                containers:
                - name: ray-node
                  imagePullPolicy: Always
                  image: rayproject/ray:1.1.0
                  command: ["/bin/bash", "-c", "--"]
                  args: ["trap : TERM INT; sleep infinity & wait;"]
                  ports:
                      - containerPort: 12345 # Ray internal communication.
                      - containerPort: 12346 # Ray internal communication.
                  volumeMounts:
                      - mountPath: /dev/shm
                        name: dshm
                  resources:
                      requests:
                          cpu: 7
                          memory: 25Gi
                  env:
                      - name: MY_CPU_REQUEST
                        valueFrom:
                            resourceFieldRef:
                                resource: requests.cpu
        resources: {"CPU": 7}
        min_workers: 0
        max_workers: 3
    node_pool_gpu:
        node_config:
            apiVersion: v1
            kind: Pod
            metadata:
                generateName: ray-worker-gpu-
                labels:
                    component: ray-worker
            spec:
                tolerations:
                - key: cloud.google.com/gke-preemptible
                  operator: Equal
                  value: "true"
                  effect: NoSchedule
                - key: imerso-ray-worker
                  operator: Equal
                  value: "true"
                  effect: NoSchedule

                serviceAccountName: default
                restartPolicy: Never
                volumes:
                - name: dshm
                  emptyDir:
                      medium: Memory
                containers:
                - name: ray-node
                  imagePullPolicy: Always
                  image: rayproject/ray:1.1.0-gpu
                  command: ["/bin/bash", "-c", "--"]
                  args: ["trap : TERM INT; sudo /usr/sbin/ldconfig.real; sleep infinity & wait;"]
                  ports:
                      - containerPort: 12345 # Ray internal communication.
                      - containerPort: 12346 # Ray internal communication.
                  volumeMounts:
                      - mountPath: /dev/shm
                        name: dshm
                  resources:
                      requests:
                          cpu: 7
                          memory: 25Gi
                      limits:
                          nvidia.com/gpu: 1
                  env:
                      - name: MY_CPU_REQUEST
                        valueFrom:
                            resourceFieldRef:
                                resource: requests.cpu
        resources: {"CPU": 7, "GPU": 1, "accelerator_type:T4": 1}
        min_workers: 0
        max_workers: 3

head_node_type: head_node     
worker_default_node_type: node_pool_cpu

head_node:
    apiVersion: v1
    kind: Pod
    spec:
        serviceAccountName: autoscaler
        restartPolicy: Never
        volumes:
        - name: dshm
          emptyDir:
              medium: Memory
        containers:
        - name: ray-node
          imagePullPolicy: Always
          image: rayproject/ray:1.1.0
          command: ["/bin/bash", "-c", "--"]
          args: ["trap : TERM INT; sleep infinity & wait;"]
          ports:
              - containerPort: 6379 # Redis port.
              - containerPort: 6380 # Redis port.
              - containerPort: 6381 # Redis port.
              - containerPort: 12345 # Ray internal communication.
              - containerPort: 12346 # Ray internal communication.
          volumeMounts:
              - mountPath: /dev/shm
                name: dshm
          resources:
              requests:
                  cpu: 500m
                  memory: 5Gi
              limits:
                  memory: 5Gi
          env:
              - name: MY_CPU_REQUEST
                valueFrom:
                    resourceFieldRef:
                        resource: requests.cpu

worker_nodes: {}
file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: False
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --num-cpus=0 --object-store-memory 1073741824 --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=ray-head.ray.svc.cluster.local:6379 --object-store-memory 104857600 --object-manager-port=8076
```

The task is never scheduled:
```console
$ ray submit /tmp/ray.config.yaml /tmp/memory_aware_func.py
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2021-02-16 08:53:30,849 INFO command_runner.py:170 -- NodeUpdater: ray-head-b4j7p: Running kubectl -n ray exec -it ray-head-b4j7p -- bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python ~/memory_aware_func.py)'
2021-02-15 23:53:32,186 INFO worker.py:657 -- Connecting to existing Ray cluster at address: 10.4.0.12:6379
2021-02-15 23:53:32,238 WARNING worker.py:1034 -- The actor or task with ID df5a1a828c9685d3ffffffff01000000 cannot be scheduled right now. It requires {CPU: 1.000000}, {memory: 0.195312 GiB} for placement, however the cluster currently cannot provide the requested resources. The required resources may be added as autoscaling takes place or placement groups are scheduled. Otherwise, consider reducing the resource requirements of the task.
```

No feasible node type was found:
```console
(base) ray@ray-head-b4j7p:/$ tail /tmp/ray/session_latest/logs/monitor.log
2021-02-15 23:56:30,188 INFO resource_demand_scheduler.py:187 -- Unfulfilled demands: [{'CPU': 1.0, 'memory': 4.0}]
2021-02-15 23:56:30,188 INFO resource_demand_scheduler.py:605 -- No feasible node type to add for [{'CPU': 1.0, 'memory': 4.0}]
2021-02-15 23:56:30,205 INFO resource_demand_scheduler.py:209 -- Node requests: {}
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:148 -- Cluster resources: [{'memory': 70.0, 'node:10.4.0.12': 1.0, 'object_store_memory': 14.0}]
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:149 -- Node counts: defaultdict(<class 'int'>, {'head_node': 1})
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:159 -- Placement group demands: []
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:186 -- Resource demands: [{'memory': 4.0, 'CPU': 1.0}]
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:187 -- Unfulfilled demands: [{'memory': 4.0, 'CPU': 1.0}]
2021-02-15 23:56:35,289 INFO resource_demand_scheduler.py:605 -- No feasible node type to add for [{'memory': 4.0, 'CPU': 1.0}]
2021-02-15 23:56:35,303 INFO resource_demand_scheduler.py:209 -- Node requests: {}
```
