### ISSUE TITLE
[Autoscaler] Head node doesn't seem to respect num cpus = 0

### ISSUE THREAD

**Issue by rkooo567** [ray-project/ray#14173]
### What is the problem?

After I start a cluster with a head node num cpus=0, it seems like it doesn't respect that config. Below is my ray status output. I am supposed to have 0 cpu, but it has 32.

```
Fetched IP: 34.222.13.21
Warning: Permanently added '34.222.13.21' (ECDSA) to the list of known hosts.
ray status
ubuntu@ip-172-31-16-156:~$ ray status
======== Autoscaler status: 2021-02-18 01:03:02.892588 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray-legacy-head-node-type
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 0.0/32.0 CPU
 0.00/226.514 GiB memory
 0.00/2.393 GiB object_store_memory

Demands:
 (no resource demands)
```

Here's my autoscaler bootstrap output;
```
{"cluster_name": "Default", "max_workers": 0, "upscaling_speed": 1.0, "docker": {"image": "", "container_name": "", "pull_before_run": true, "run_options": []}, "idle_timeout_minutes": 5, "provider": {"type": "aws", "region": "us-west-2", "availability_zone": "us-west-2a,us-west-2b", "cache_stopped_nodes": true}, "auth": {"ssh_user": "ubuntu", "ssh_private_key": "~/ray_bootstrap_key.pem"}, "head_node": {"InstanceType": "i3.8xlarge", "ImageId": "ami-0a2363a9cff180a64", "BlockDeviceMappings": [{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 1000}}], "IamInstanceProfile": {"Arn": "arn:aws:iam::959243851260:instance-profile/ray-autoscaler-v1"}, "KeyName": "ray-autoscaler_4_us-west-2", "SubnetIds": ["subnet-d9d4ff92", "subnet-a65f56df"], "SecurityGroupIds": ["sg-0e910697b8092382c"]}, "worker_nodes": {"InstanceType": "i3.8xlarge", "ImageId": "ami-0a2363a9cff180a64", "BlockDeviceMappings": [{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 1000}}], "KeyName": "ray-autoscaler_4_us-west-2", "SubnetIds": ["subnet-d9d4ff92", "subnet-a65f56df"], "SecurityGroupIds": ["sg-0e910697b8092382c"]}, "file_mounts": {}, "cluster_synced_files": [], "file_mounts_sync_continuously": false, "rsync_exclude": ["**/.git", "**/.git/**"], "rsync_filter": [".gitignore"], "initialization_commands": [], "setup_commands": ["echo 'export PATH=\"$HOME/anaconda3/envs/tensorflow_p36/bin:$PATH\"' >> ~/.bashrc", "pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl", "sudo bash -c 'rm -rf /etc/security/limits.d; echo \"* soft nofile 65535\" >> /etc/security/limits.conf; echo \"* hard nofile 65535\" >> /etc/security/limits.conf;'", "pip install tqdm", "pip install -U dask", "pip install fastparquet --ignore-installed", "pip install -U numpy==1.19.5 scipy xarray dataclasses zarr", "mkdir -p /tmp/spill"], "head_setup_commands": ["echo 'export PATH=\"$HOME/anaconda3/envs/tensorflow_p36/bin:$PATH\"' >> ~/.bashrc", "pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl", "sudo bash -c 'rm -rf /etc/security/limits.d; echo \"* soft nofile 65535\" >> /etc/security/limits.conf; echo \"* hard nofile 65535\" >> /etc/security/limits.conf;'", "pip install tqdm", "pip install -U dask", "pip install fastparquet --ignore-installed", "pip install -U numpy==1.19.5 scipy xarray dataclasses zarr", "mkdir -p /tmp/spill"], "worker_setup_commands": ["echo 'export PATH=\"$HOME/anaconda3/envs/tensorflow_p36/bin:$PATH\"' >> ~/.bashrc", "pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl", "sudo bash -c 'rm -rf /etc/security/limits.d; echo \"* soft nofile 65535\" >> /etc/security/limits.conf; echo \"* hard nofile 65535\" >> /etc/security/limits.conf;'", "pip install tqdm", "pip install -U dask", "pip install fastparquet --ignore-installed", "pip install -U numpy==1.19.5 scipy xarray dataclasses zarr", "mkdir -p /tmp/spill"], "head_start_ray_commands": ["ray stop", "ray start --num-cpus=0 --head --port=6379 --object-manager-port=8076 --object-store-memory=3758096384 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{\"automatic_object_spilling_enabled\":true,\"max_io_workers\":1,\"object_spilling_config\":\"{\\\"type\\\":\\\"filesystem\\\",\\\"params\\\":{\\\"directory_path\\\":\\\"/tmp/spill\\\"}}\"}'"], "worker_start_ray_commands": ["ray stop", "ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=3758096384"], "available_node_types": {"ray-legacy-head-node-type": {"node_config": {"InstanceType": "i3.8xlarge", "ImageId": "ami-0a2363a9cff180a64", "BlockDeviceMappings": [{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 1000}}], "IamInstanceProfile": {"Arn": "arn:aws:iam::959243851260:instance-profile/ray-autoscaler-v1"}, "KeyName": "ray-autoscaler_4_us-west-2", "SubnetIds": ["subnet-d9d4ff92", "subnet-a65f56df"], "SecurityGroupIds": ["sg-0e910697b8092382c"]}, "resources": {"CPU": 32}, "min_workers": 0, "max_workers": 0}, "ray-legacy-worker-node-type": {"node_config": {"InstanceType": "i3.8xlarge", "ImageId": "ami-0a2363a9cff180a64", "BlockDeviceMappings": [{"DeviceName": "/dev/sda1", "Ebs": {"VolumeSize": 1000}}], "KeyName": "ray-autoscaler_4_us-west-2", "SubnetIds": ["subnet-d9d4ff92", "subnet-a65f56df"], "SecurityGroupIds": ["sg-0e910697b8092382c"]}, "resources": {"CPU": 32}, "min_workers": 0, "max_workers": 0}}, "head_node_type": "ray-legacy-head-node-type", "no_restart": false}
```

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):
My cluster.yaml
```
cluster_name: Default

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 0

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 0

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    image: "" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    # image: rayproject/ray:latest-gpu   # use this one if you don't need ML dependencies, it's faster to pull
    container_name: ""
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

    # Example of running a GPU head with CPU workers
    # head_image: "rayproject/ray-ml:latest-gpu"
    # Allow Ray to automatically detect GPUs

    # worker_image: "rayproject/ray-ml:latest-cpu"
    # worker_run_options: []

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    # Availability zone(s), comma-separated, that nodes may be launched in.
    # Nodes are currently spread between zones by a round-robin approach,
    # however this implementation detail should not be relied upon.
    availability_zone: us-west-2a,us-west-2b
    # Whether to allow node reuse. If set to False, nodes will be terminated
    # instead of stopped.
    cache_stopped_nodes: True # If not present, the default is True.

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below.
#    ssh_private_key: /path/to/your/key.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
head_node:
    InstanceType: i3.8xlarge
    ImageId: ami-0a2363a9cff180a64 # Deep Learning AMI (Ubuntu) Version 30

    # You can provision additional disk space with a conf as follows
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 1000

    # Additional options in the boto docs.

# Provider-specific config for worker nodes, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as SubnetId and KeyName.
# For more documentation on available fields, see:
# http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
worker_nodes:
    InstanceType: i3.8xlarge
    ImageId: ami-0a2363a9cff180a64 # Deep Learning AMI (Ubuntu) Version 30

    # You can provision additional disk space with a conf as follows
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 1000

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up nodes.
setup_commands:
    - echo 'export PATH="$HOME/anaconda3/envs/tensorflow_p36/bin:$PATH"' >> ~/.bashrc
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl
    - sudo bash -c 'rm -rf /etc/security/limits.d; echo "* soft nofile 65535" >> /etc/security/limits.conf; echo "* hard nofile 65535" >> /etc/security/limits.conf;'
    - pip install tqdm
    - pip install -U dask
    - pip install fastparquet --ignore-installed
    - pip install -U numpy==1.19.5 scipy xarray dataclasses zarr
    - mkdir -p /tmp/spill
    # - sudo mkfs -t xfs /dev/nvme1n1
    # - sudo mkdir -p /obj-data
    # - sudo mount /dev/nvme1n1 /obj-data
    # - sudo chown -R ubuntu /obj-data;
    # - mkdir /obj-data/ray_spilled_objects

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --num-cpus=0 --head --port=6379 --object-manager-port=8076 --object-store-memory=3758096384 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":1,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/tmp/spill\"}}"}'

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=3758096384

```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
