### ISSUE TITLE
[Autoscaler] available_node_types is required in local mode?

### ISSUE THREAD

**Issue by chenk008** [ray-project/ray#14188]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

python version: 3.6.5
OS: linux

monitor.err show the log:
`KeyError: 'available_node_types'`

### Reproduction (REQUIRED)

ray up  demo.yaml

demo.yaml:

```
cluster_name: test 

min_workers: 2

max_workers: 5

idle_timeout_minutes: 5

provider:
    type: local
    coordinator_address: "ray-coordinator.ray-operator.svc.staging.alipay.net:8080"

auth:
    ssh_user: admin
    ssh_private_key: ~/.ssh/admin_id_rsa

head_node: {}

worker_nodes: {}

setup_commands:
    - pip uninstall -y ray
    - pip install -U ray

head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml

worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
