### ISSUE TITLE
[k8s] num_CPUs doesn't seem to be working

### ISSUE THREAD

**Issue by mbehrendt** [ray-project/ray#14403]
### What is the problem?
Ray version 1.2, k8s 18.6 and 19.x, Ubuntu 18.04.

### Reproduction (REQUIRED)
this is in the context of https://github.com/ray-project/ray/issues/14400 and https://github.com/ray-project/ray/issues/14400

when i invoke a task many times in parallel, often times there is no provisioning of additional task instances although there is enough free capacity available. This seems to be 

To reproduce, just setup a k8s cluster as described in the issue referenced above. Then run this code on Ray and watch with `kubctl -n ray get pods` how the number of pods behaves. in general, i've seen very inconsistent behavior across multiple runs - in many cases, the number of pods wasn't scaled at all. By watching the output from the monitor cli which is suggested at the end of the cluster provisioning process.

@richardliaw ^^

see this thread for further background information: https://discuss.ray.io/t/min-workers-doesnt-seem-to-be-honored/1002

``` import ray
import time
import datetime
import os
import subprocess


ray.init(address='<point to ray on k8s cluster',  _redis_password='insert your own value')

@ray.remote(num_cpus=1)
def f(i):
    time.sleep(30)
    print("index: "  + str(i))


futures = [f.remote(i) for i in range(200)]

print(ray.get(futures)) # [0, 1, 4, 9]
```

@richardliaw ^^

**Comment by jeremiaswerner** [comment]
I'am seeing a similar issue with Ray on Kubernetes, where the autoscaler is not able to scale up. It seems like it does not find an appropriate worker node type

```
2021-03-04 02:08:20,572	WARNING resource_demand_scheduler.py:643 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}, {'CPU': 2.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
2021-03-04 02:08:21,107	INFO autoscaler.py:300 --
```

The config defines 2 CPU via resource requests and limits as well as in the resources section:
```
available_node_types:
  worker_node:
    # Minimum number of Ray workers of this Pod type.
    min_workers: 2
    # Maximum number of Ray workers of this Pod type. Takes precedence over min_workers.
    max_workers: 10
    # User-specified custom resources for use by Ray. Object with string keys and integer values.
    # (Ray detects CPU and GPU from pod spec resource requests and limits, so no need to fill those here.)
    resources: {"foo": 1, "bar": 2, "CPU": 2}
    node_config:
    ....
              resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 2
              memory: 4Gi
```


Does anyone has any idea?
