### ISSUE TITLE
Run ray via docker-compose

### ISSUE THREAD

**Issue by oleg-savko** [ray-project/ray#14505]
How to run single node ray via docker-compose?

I tried run like this:
```
  ray:
    image: rayproject/ray:1.2.0
    shm_size: '2gb'
    network_mode: 'host'
    ports:
      - 8265:8265
      - 6380:6380
    entrypoint: "ray start --head --port 6380 --dashboard-host 0.0.0.0"
```

But its stop conntainer immediately:

> (base) root@gl-prod-warehouse-sel:~/idf-reporting/mlflow# docker-compose up ray
> Starting mlflow_ray_1 ... done
> Attaching to mlflow_ray_1
> ray_1                 | 2021-03-05 04:18:22,014 INFO services.py:1174 -- View the Ray dashboard at http://xxxxx:8265
> ray_1                 | 2021-03-05 04:18:22,017 WARNING services.py:1628 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 4294967296 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=Xgb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 2gb.
> ray_1                 | 2021-03-05 04:18:21,536 INFO scripts.py:537 -- Local node IP: xxxxx
> ray_1                 | 2021-03-05 04:18:22,033 SUCC scripts.py:565 -- --------------------
> ray_1                 | 2021-03-05 04:18:22,033 SUCC scripts.py:566 -- Ray runtime started.
> ray_1                 | 2021-03-05 04:18:22,034 SUCC scripts.py:567 -- --------------------
> ray_1                 | 2021-03-05 04:18:22,034 INFO scripts.py:569 -- Next steps
> ray_1                 | 2021-03-05 04:18:22,034 INFO scripts.py:571 -- To connect to this Ray runtime from another node, run
> ray_1                 | 2021-03-05 04:18:22,034 INFO scripts.py:577 --   ray start --address='xxxx:6380' --redis-password='5241590000000000'
> ray_1                 | 2021-03-05 04:18:22,034 INFO scripts.py:579 -- Alternatively, use the following Python code:
> ray_1                 | 2021-03-05 04:18:22,034 INFO scripts.py:582 -- import ray
> ray_1                 | 2021-03-05 04:18:22,035 INFO scripts.py:589 -- ray.init(address='auto', _redis_password='5241590000000000')
> ray_1                 | 2021-03-05 04:18:22,035 INFO scripts.py:592 -- If connection fails, check your firewall settings and network configuration.
> ray_1                 | 2021-03-05 04:18:22,035 INFO scripts.py:596 -- To terminate the Ray runtime, run
> ray_1                 | 2021-03-05 04:18:22,035 INFO scripts.py:597 --   ray stop
> mlflow_ray_1 exited with code 0

If I add `--block` option to `entrypoint`:

```
ray:
    image: rayproject/ray:1.2.0
    shm_size: '2gb'
    network_mode: 'host'
    ports:
      - 8265:8265
      - 6380:6380
    entrypoint: "ray start --head --port 6380 --dashboard-host 0.0.0.0 --block"
```

Its not terminated, but also seems not started, in logs I see only (forever):

> (base) root@gl-prod-warehouse-sel:~/idf-reporting/mlflow# docker-compose up ray
> Recreating mlflow_ray_1 ... done
> Attaching to mlflow_ray_1
> ray_1                 | 2021-03-05 04:21:53,219 INFO services.py:1174 -- View the Ray dashboard at http://xxxx:8265
> ray_1                 | 2021-03-05 04:21:53,221 WARNING services.py:1628 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 4294967296 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=Xgb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 2gb.

What I am doing wrong?
