### ISSUE TITLE
[autoscaler] SubnetId, a valid AWS field, is being ignored in cluster yaml

### ISSUE THREAD

**Issue by xcharleslin** [ray-project/ray#14551]
### What is the problem?

[Cluster config docs](https://docs.ray.io/en/master/cluster/config.html#cluster-configuration-node-config-type) say that you can put any valid AWS field in NodeConfig. But, putting `SubnetId` is silently ignored.

This issue has already been raised before; see https://github.com/ray-project/ray/issues/12530 . This new issue is not to find a workaround, but to *fix the documentation/implementation mismatch*.

My suggested fix (only to start discussion, not volunteering :sweat_smile: ) is the following:

1. Move any fields that are Ray-specific concepts out of the NodeConfig dict and into the Provider dict. (This is already true today for most fields; I believe SubnetIds is the sole violation of this.)
2. No hidden behaviour or silent failures in the NodeConfig dict. Either support all the AWS fields, or explicitly raise an error for the ones we don't want the user passing in. 

### Reproduction (REQUIRED)

(From https://github.com/ray-project/ray/issues/12530.)
```yaml
# ~/Desktop/ray_cluster.yaml
cluster_name: default

min_workers: 0
max_workers: 2

docker:
    image: "rayproject/ray:latest-gpu"
    container_name: "ray_container"
    pull_before_run: True
    run_options: []

provider:
    type: aws
    region: eu-west-1
    availability_zone: eu-west-1a,eu-west-1b
    cache_stopped_nodes: False # If not present, the default is True.

auth:
    ssh_user: ubuntu

head_node:
    # VpcId:
    SubnetId: subnet-***********qwe
    # CidrBlock: 10.19.0.0/16
    InstanceType: m5a.large
    ImageId: ami-006ff58f5247c50eb # Deep Learning AMI (Ubuntu) Version 30

    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 100


worker_nodes:
    SubnetId: subnet-***********qwe
    InstanceType: m5a.large
    ImageId: ami-006ff58f5247c50eb # Deep Learning AMI (Ubuntu) Version 30

```

```
ray up -y ~/Desktop/ray_cluster.yaml
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
