### ISSUE TITLE
[kubernetes] Allow exposing custom ports with Kubernetes Operator

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#14699]
The [Ray Kubernetes Operator](https://docs.ray.io/en/releases-1.2.0/cluster/k8s-operator.html) makes it easy to spin up a Ray cluster on Kubernetes, but unlike the cluster config, it doesn't provide a mechanism to expose custom ports.

Using a normal Ray config for Kubernetes, we could do something like this to add port `8000` for Ray Serve:

```
services:
      - apiVersion: v1
        kind: Service
        metadata:
            name: local-cluster-ray-head
        spec:
            selector:
                component: local-cluster-ray-head
            ports:
                - name: client
                  protocol: TCP
                  port: 10001
                  targetPort: 10001
                - name: dashboard
                  protocol: TCP
                  port: 8265
                  targetPort: 8265
                - name: serve
                  protocol: TCP
                  port: 8000
                  targetPort: 8000
```

However, the k8s operator abstracts the service definition, so we cannot add the 8000 port.

Instead, we need to create an entirely different service, which works, but is not ideal:

```
apiVersion: v1
kind: Service
metadata:
  name: local-cluster-ray-head-serve
  labels:
    app: local-cluster-ray-head-serve
  namespace: ray
spec:
  type: ClusterIP
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    component: local-cluster-ray-head
```

cc @richardliaw
