### ISSUE TITLE
[autoscaler] [kubernetes] Calling ray down does not remove Kubernetes services

### ISSUE THREAD

**Issue by tgaddair** [ray-project/ray#14700]
When creating a cluster on Kubernetes, Ray will allocate a service routing traffic to the head node when the user adds this to their cluster config:

```
services:
      - apiVersion: v1
        kind: Service
        metadata:
            name: local-cluster-ray-head
        spec:
            selector:
                component: local-cluster-ray-head
            ports:
                - name: client
                  protocol: TCP
                  port: 10001
                  targetPort: 10001
                - name: dashboard
                  protocol: TCP
                  port: 8265
                  targetPort: 8265
```

However, when calling `ray down cluster.yaml`, this service (unlike the pods) will not be removed. The expected behavior is that all resources created by `ray up` should be properly cleaned up after calling `ray down`.

cc @richardliaw
