### ISSUE TITLE
[rllib]I Cannot reproduce pong_apex example reward curve

### ISSUE THREAD

**Issue by piscesvivian** [ray-project/ray#14888]
### Describe your feature request

For feature requests or questions, post on our Discussion page instead: https://discuss.ray.io/

I run it with command, 
```
rllib train -f pong_apex.yaml
```

yaml config file `pong_apex.yaml` content: 
```
# This reaches ~20 reward in 50 minutes (6M train steps, 2M env steps) on a
# p3.2xlarge AWS instance.
# See https://app.wandb.ai/zplizzi/test/runs/ayuuhixr?workspace=user-zplizzi
# for training curves.
pong-apex:
    env: PongNoFrameskip-v4
    run: A3C
    config:
        # Works for both torch and tf.
        framework: tf
        log_level: DEBUG
        num_workers: 100
        num_envs_per_worker: 2
        num_gpus: 0
        lr: 0.0005
        train_batch_size: 64
        gamma: 0.99
```
The only diffrence is server is no GPUs.

and waiting, waiting

after run about 13 hours, reward is still -16.  not like offical curve pic discribe
I know a few things abount RL, how can I reproduce this exsample
```
Memory usage on this node: 143.7/503.3 GiB
Using FIFO scheduling algorithm.
Resources requested: 101.0/128 CPUs, 0/0 GPUs, 0.0/601.54 GiB heap, 0.0/261.79 GiB objects
Result logdir: /root/ray_results/pong-apex
Number of trials: 1/1 (1 RUNNING)
+------------------------------------+----------+---------------------+--------+------------------+-----------+----------+----------------------+----------------------+--------------------+
| Trial name                         | status   | loc                 |   iter |   total time (s) |        ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |
|------------------------------------+----------+---------------------+--------+------------------+-----------+----------+----------------------+----------------------+--------------------|
| A3C_PongNoFrameskip-v4_d32a9_00000 | RUNNING  | 10.3.163.101:177414 |  12130 |          60499.7 | 190756960 |   -20.26 |                  -18 |                  -21 |            3760.38 |
+------------------------------------+----------+---------------------+--------+------------------+-----------+----------+----------------------+----------------------+--------------------+


Result for A3C_PongNoFrameskip-v4_d32a9_00000:
  agent_timesteps_total: 0
  custom_metrics: {}
  date: 2021-03-24_13-10-02
  done: false
  episode_len_mean: 3750.31
  episode_media: {}
  episode_reward_max: -18.0
  episode_reward_mean: -20.21
  episode_reward_min: -21.0
  episodes_this_iter: 16
  episodes_total: 204519
  experiment_id: cacf359aec124ab9910fcefe1c54964d
  hostname: node101
  info:
    learner:
      cur_lr: 0.0005000000237487257
      grad_gnorm: 1.1505966186523438
      model: {}
      policy_entropy: 35.793338775634766
      policy_loss: 3.801820755004883
      var_gnorm: 71.14576721191406
      vf_explained_var: 0.0
      vf_loss: 0.14569684863090515
    num_steps_sampled: 190788440
    num_steps_trained: 190788440
  iterations_since_restore: 12132
  node_ip: 10.3.163.101
  num_healthy_workers: 100
  off_policy_estimator: {}
  perf:
    cpu_util_percent: 42.17142857142857
    ram_util_percent: 28.599999999999998
  pid: 177414
  policy_reward_max: {}
  policy_reward_mean: {}
  policy_reward_min: {}
  sampler_perf:
    mean_action_processing_ms: 0.13910690431073428
    mean_env_render_ms: 0.0
    mean_env_wait_ms: 3.8398117384236174
    mean_inference_ms: 2.7500159924190375
    mean_raw_obs_processing_ms: 0.8849323901919834
  time_since_restore: 60509.7089509964
  time_this_iter_s: 5.010364532470703
  time_total_s: 60509.7089509964
  timers:
    apply_grad_throughput: 9581.396
    apply_grad_time_ms: 2.087
    grad_wait_time_ms: 1.467
    update_time_ms: 3.299
  timestamp: 1616562602
  timesteps_since_restore: 0
  timesteps_total: 190788440
  training_iteration: 12132
  trial_id: d32a9_00000
```

Offical Curve：
![Offical Curve](https://docs.ray.io/en/master/_images/apex.png)

My Image cannot upload !!

primary version info:
```
ray 2.0.0.dev    # 1.2.0 also test
tensorflow 2.4.1
torch 1.8.0
gym 0.18.0
atari-py 0.2.6
```

Is there any step I did wrong?
