### ISSUE TITLE
[Autoscaler] ray up fails with no error message

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15269]
I'm doing `ray up` on a simple Cluster yaml, but it's failing with a generic `Failed to setup head node` with no additional information. This is on nightly Ray. 

Cluster yaml:
```
cluster_name: amog-gpu
min_workers: 0
max_workers: 0
initial_workers: 0
autoscaling_mode: default
docker:
    image: "anyscale/ray-ml:latest-gpu"
    container_name: "ray_container"
    pull_before_run: True
    run_options: []
target_utilization_fraction: 0.9
idle_timeout_minutes: 10
provider:
    type: aws
    region: us-west-2
    cache_stopped_nodes: False
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/amog-anyscale.pem
head_node:
    InstanceType: g3.8xlarge
    KeyName: amog-anyscale
    BlockDeviceMappings:
        -
            DeviceName: /dev/sda1
            Ebs:
                VolumeSize: 300
worker_nodes:
    InstanceType: p3.8xlarge
    ImageId: latest_dlami
    KeyName: amog-anyscale
    BlockDeviceMappings:
        -
            DeviceName: /dev/sda1
            Ebs:
                VolumeSize: 300
initialization_commands: []
setup_commands:
    - echo "hello"
    - 'ray || pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl' 
head_setup_commands: []
worker_setup_commands: []
```

cc @AmeerHajAli @ijrsvt @DmitriGekhtman
