### ISSUE TITLE
[Autoscaler] KeyName not found

### ISSUE THREAD

**Issue by amogkam** [ray-project/ray#15278]
### What is the problem?
I want to specify a KeyName for my nodes in order to use the provided SSH key. According to the docs, `KeyName` should be specified under `node_config` since its an argument that goes to `boto.create_instances`. My cluster.yaml looks like this:
```
cluster_name: horovod-release-tests

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers defaults to 0.
min_workers: 3
max_workers: 3

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    cache_stopped_nodes: False

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/amog-anyscale.pem

available_node_types:
    gpu_2_32:
        min_workers: 3
        max_workers: 3
        resources: {"CPU": 32, "GPU": 2}
        node_config:
            KeyName: amog-anyscale
            InstanceType: g3.8xlarge
            ImageId: ami-0a2363a9cff180a64
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs: 
                      VolumeSize: 150


head_node_type: gpu_2_32
worker_default_node_type: gpu_2_32

file_mounts: {}

setup_commands: 
    - pip install -U {{env["RAY_WHEEL"]}}
    - pip install 'ray[rllib]'
    - pip install torch torchvision
    - HOROVOD_WITH_GLOO=1 HOROVOD_WITHOUT_MPI=1 HOROVOD_WITHOUT_TENSORFLOW=1 HOROVOD_WITHOUT_MXNET=1 HOROVOD_WITH_PYTORCH=1 pip install -U git+https://github.com/horovod/horovod.git

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - export RAY_BACKEND_LOG_LEVEL=debug
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - export RAY_BACKEND_LOG_LEVEL=debug
```
However, despite `KeyName` being specified under `node_config`, I get this error:
```
Checking AWS environment settings
`KeyName` missing for head node.
```

I can resolve this by adding 
```
head_node:
    KeyName: amog-anyscale

worker_nodes:
    KeyName: amog-anyscale
```
but aren't these fields supposed to be deprecated?

Please let me know if I'm doing something incorrectly.

cc @AmeerHajAli @DmitriGekhtman @ijrsvt
