### ISSUE TITLE
ray up is unable to use anything other than the default VPC

### ISSUE THREAD

**Issue by cmeisinger** [ray-project/ray#16125]
### What is the problem?

Ray Version 1.3.0

When Running 'ray up' I only ever see the default VPC/Subnets listed.   Going through old bugs, I've tried config tuning with SubnetID/SubnetIDs/SubnetIds, I've used lists and strings for the values, etc.  I can never get it to look at anything other than the default VPC.

Depending on the verbiage used, I either see mismatches between the SG and subnet IDs (InvalidParameter) or I see this error message which is frankly confusing and feels broken.
`botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "SubnetID", must be one of: BlockDeviceMappings, ImageId, InstanceType, Ipv6AddressCount, Ipv6Addresses, KernelId, KeyName, MaxCount, MinCount, Monitoring, Placement, RamdiskId, SecurityGroupIds, SecurityGroups, SubnetId, `

### Reproduction (REQUIRED)
Testing config: 

```
cluster_name: chrism-testing-ray
provider:
   type: aws
   region: us-west-2
   availability_zone: us-west-2a,us-west-2b,us-west-2c
auth:
   ssh_user: ubuntu
setup_commands:
  - touch /tmp/some_file.txt

available_node_types:
    ray.head.default:
        min_workers: 1
        max_workers: 0
        resources: {}
        node_config:
            InstanceType: m5.large
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 100
            SubnetIds: [subnet-06d80eab261fee834]
            InstanceMarketOptions:
                MarketType: spot
    ray.worker.default:
        min_workers: 1
        max_workers: 2
        resources: {}
        node_config:
            InstanceType: m5.large
            SubnetIds: ["subnet-06d80eab261fee834", "subnet-013416e97b402b6f0"]
            InstanceMarketOptions:
                MarketType: spot
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
