### ISSUE TITLE
File mounts not syncing with Docker unless it's a folder

### ISSUE THREAD

**Issue by javi-redondo** [ray-project/ray#16262]
### What is the problem?

Python 3.8/Ray 1.3

When I configure `file_mounts` to sync individual files, e.g., a couple of code files, they appear to be updating after I run `ray up` but then the files are not actually updated.

### Reproduction (REQUIRED)

```
cluster_name: my_cluster

max_workers: 10

docker:
    image: "rayproject/ray:latest-cpu"
    container_name: "ray_container"

provider:
    type: aws
    region: us-west-1
    cache_stopped_nodes: False

available_node_types:
    default:
        resources: {}
        node_config:
            InstanceType: m5.large

head_node_type: default

setup_commands: []

file_mounts:
    "~/code.py": "./code.py"
    "~/module.py": "./module.py"
```
