### ISSUE TITLE
Why the self built ray image cannot start the worker nodes

### ISSUE THREAD

**Issue by Simple-meimei** [ray-project/ray#16960]
# I can't get worker nodes when I build my own ray1.0.0 image.
Here are my steps. The official code of ray 1.0.0 is used to build the image.I don't know what's wrong.
## 1.Modify ray/docker/development/dockerfile as follows:
```
FROM rayproject/ray-deps:latest
ADD ray.tar /ray
ADD sources.list /etc/apt/
ADD kubernetes.list /etc/apt/sources.list.d

RUN sudo apt-get update && \
sudo apt-get -y upgrade && \
sudo apt install -y build-essential curl unzip cmake zip gnupg && \
sudo apt-get clean 

#dash->bash
RUN echo "dash dash/sh boolean false" | sudo debconf-set-selections
RUN sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash

RUN sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh
RUN wget https://github.com/bazelbuild/bazel/releases/download/3.2.0/bazel-3.2.0-installer-linux-x86_64.sh && \
sudo chmod +x bazel-3.2.0-installer-linux-x86_64.sh && \
./bazel-3.2.0-installer-linux-x86_64.sh --user
ENV PATH=$PATH:$HOME/bin

RUN echo 'build --remote_cache="https://storage.googleapis.com/ray-bazel-cache"' >> $HOME/.bazelrc 
RUN echo 'build --remote_upload_local_results=false' >> $HOME/.bazelrc 

WORKDIR /ray/ray-1.0.0/
USER root
RUN bazel build //:ray_pkg || bazel build --jobs 1 //:ray_pkg  

WORKDIR /ray/ray-1.0.0/python/
RUN pip install -e . 
WORKDIR /ray/ray-1.0.0
```
## 5.Modify the node image in ray/python/ray/autoscaler/kubernetes/example-full.yaml to the image pushed in step 3.
The content of ray/python/ray/autoscaler/kubernetes/example-full.yaml is as follows：
```
cluster_name: default
min_workers: 2
max_workers: 10
initial_workers: 2
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

provider:
    type: kubernetes
    use_internal_ips: true
    namespace: ray
    autoscaler_service_account:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
            name: autoscaler

    autoscaler_role:
        kind: Role
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
            name: autoscaler
        rules:
        - apiGroups: [""]
          resources: ["pods", "pods/status", "pods/exec"]
          verbs: ["get", "watch", "list", "create", "delete", "patch"]

    autoscaler_role_binding:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
            name: autoscaler
        subjects:
        - kind: ServiceAccount
          name: autoscaler
        roleRef:
            kind: Role
            name: autoscaler
            apiGroup: rbac.authorization.k8s.io

    services:
      - apiVersion: v1
        kind: Service
        metadata:
          
            name: ray-head
        spec:
           
            selector:
                component: ray-head
            ports:
                - protocol: TCP
                  port: 8000
                  targetPort: 8000

      - apiVersion: v1
        kind: Service
        metadata:
            
            name: ray-workers
        spec:
            
            selector:
                component: ray-worker
            ports:
                - protocol: TCP
                  port: 8000
                  targetPort: 8000

head_node:
    apiVersion: v1
    kind: Pod
    metadata:
      
        generateName: ray-head-

        labels:
            component: ray-head
    spec:
        
        serviceAccountName: autoscaler

        restartPolicy: Never

        volumes:
        - name: dshm
          emptyDir:
              medium: Memory

        containers:
        - name: ray-node
          imagePullPolicy: Always
          
          image: limeiya/ray1
         
          command: ["/bin/bash", "-c", "--"]
          args: ["trap : TERM INT; sleep infinity & wait;"]
          ports:
              - containerPort: 6379 # Redis port.
              - containerPort: 6380 # Redis port.
              - containerPort: 6381 # Redis port.
              - containerPort: 12345 # Ray internal communication.
              - containerPort: 12346 # Ray internal communication.

          volumeMounts:
              - mountPath: /dev/shm
                name: dshm
          resources:
              requests:
                  cpu: 1000m
                  memory: 512Mi
              limits:
                 
                  memory: 2Gi
          env:
              
              - name: MY_CPU_REQUEST
                valueFrom:
                    resourceFieldRef:
                        resource: requests.cpu

worker_nodes:
    apiVersion: v1
    kind: Pod
    metadata:
        
        generateName: ray-worker-

        labels:
            component: ray-worker
    spec:
        serviceAccountName: default

        restartPolicy: Never

        volumes:
        - name: dshm
          emptyDir:
              medium: Memory

        containers:
        - name: ray-node
          imagePullPolicy: Always
       
          image: limeiya/ray1
         
          command: ["/bin/bash", "-c", "--"]
          args: ["trap : TERM INT; sleep infinity & wait;"]
          ports:
              - containerPort: 12345 # Ray internal communication.
              - containerPort: 12346 # Ray internal communication.

          volumeMounts:
              - mountPath: /dev/shm
                name: dshm
          resources:
              requests:
                  cpu: 1000m
                  memory: 512Mi
              limits:
                
                  memory: 2Gi
          env:
             
              - name: MY_CPU_REQUEST
                valueFrom:
                    resourceFieldRef:
                        resource: requests.cpu

file_mounts: {
}

cluster_synced_files: []

file_mounts_sync_continuously: False

initialization_commands: []

setup_commands: []

head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --num-cpus=$MY_CPU_REQUEST --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host 0.0.0.0

worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --num-cpus=$MY_CPU_REQUEST --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```
## 6.Execute the `ray up ray/python/ray/autoscaler/kubernetes/example-full.yaml` command on my k8s cluster.
It turns out that there is only one head node, but no worker node.
![image](https://user-images.githubusercontent.com/45993919/124932979-16c81800-e036-11eb-9130-65a596106ca1.png)
**Questions:**
**Why can't I have worker nodes? What's wrong with my way of making a ray image.Thank you very much！**
