### ISSUE TITLE
`Check failed: it != placement_group_leasing_in_progress_.end()` non-deterministically

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17258]
I get this error on 1.4.0. It's non-deterministic.

```
(pid=gcs_server) [2021-07-20 20:14:06,360 C 261 261] gcs_placement_group_scheduler.cc:202:  Check failed: it != placement_group_leasing_in_progress_.end()
(pid=gcs_server) [2021-07-20 20:14:06,360 E 261 261] logging.cc:441: *** Aborted at 1626837246 (unix time) try "date -d @1626837246" if you are using GNU date ***
(pid=gcs_server) [2021-07-20 20:14:06,361 E 261 261] logging.cc:441: PC: @                0x0 (unknown)
(pid=gcs_server) [2021-07-20 20:14:06,361 E 261 261] logging.cc:441: *** SIGABRT (@0x3e800000105) received by PID 261 (TID 0x7fb401550840) from PID 261; stack trace: ***
(pid=gcs_server) [2021-07-20 20:14:06,361 E 261 261] logging.cc:441:     @     0x562e8e57fabf google::(anonymous namespace)::FailureSignalHandler()
(pid=gcs_server) [2021-07-20 20:14:06,361 E 261 261] logging.cc:441:     @     0x7fb401ab23c0 (unknown)
(pid=gcs_server) [2021-07-20 20:14:06,362 E 261 261] logging.cc:441:     @     0x7fb40159b18b gsignal
(pid=gcs_server) [2021-07-20 20:14:06,362 E 261 261] logging.cc:441:     @     0x7fb40157a859 abort
(pid=gcs_server) [2021-07-20 20:14:06,363 E 261 261] logging.cc:441:     @     0x562e8e570ffe ray::SpdLogMessage::Flush()
(pid=gcs_server) [2021-07-20 20:14:06,363 E 261 261] logging.cc:441:     @     0x562e8e5710cd ray::RayLog::~RayLog()
(pid=gcs_server) [2021-07-20 20:14:06,364 E 261 261] logging.cc:441:     @     0x562e8e353ed4 ray::gcs::GcsPlacementGroupScheduler::MarkScheduleCancelled()
(pid=gcs_server) [2021-07-20 20:14:06,364 E 261 261] logging.cc:441:     @     0x562e8e364797 ray::gcs::GcsPlacementGroupManager::RemovePlacementGroup()
(pid=gcs_server) [2021-07-20 20:14:06,364 E 261 261] logging.cc:441:     @     0x562e8e365693 ray::gcs::GcsPlacementGroupManager::HandleRemovePlacementGroup()
(pid=gcs_server) [2021-07-20 20:14:06,365 E 261 261] logging.cc:441:     @     0x562e8e23cd28 _ZNSt17_Function_handlerIFvvEZN3ray3rpc14ServerCallImplINS2_35PlacementGroupInfoGcsServiceHandlerENS2_27RemovePlacementGroupRequestENS2_25RemovePlacementGroupReplyEE13HandleRequestEvEUlvE_E9_M_invokeERKSt9_Any_data
(pid=gcs_server) [2021-07-20 20:14:06,365 E 261 261] logging.cc:441:     @     0x562e8e5344d8 boost::asio::detail::completion_handler<>::do_complete()
(pid=gcs_server) [2021-07-20 20:14:06,366 E 261 261] logging.cc:441:     @     0x562e8e6c27f1 boost::asio::detail::scheduler::do_run_one()
(pid=gcs_server) [2021-07-20 20:14:06,367 E 261 261] logging.cc:441:     @     0x562e8e6c2921 boost::asio::detail::scheduler::run()
(pid=gcs_server) [2021-07-20 20:14:06,368 E 261 261] logging.cc:441:     @     0x562e8e6c49f0 boost::asio::io_context::run()
(pid=gcs_server) [2021-07-20 20:14:06,368 E 261 261] logging.cc:441:     @     0x562e8e2011bc main
(pid=gcs_server) [2021-07-20 20:14:06,368 E 261 261] logging.cc:441:     @     0x7fb40157c0b3 __libc_start_main
(pid=gcs_server) [2021-07-20 20:14:06,369 E 261 261] logging.cc:441:     @     0x562e8e21c307 (unknown)
2021-07-20 20:14:09,591 WARNING worker.py:1114 -- The autoscaler failed with the following error:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 317, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 207, in _run
    self.update_load_metrics()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 170, in update_load_metrics
    request, timeout=4)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1626837249.587267467","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1626837249.587265297","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
```

Yaml:

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: large

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 11
initial_workers: 11
max_workers: 11
# autoscaling_mode: aggressive

# target_utilization_fraction: 0.9

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 15

docker:
    image: "rayproject/ray:1.4.0-cpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    cache_stopped_nodes: False

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

head_node:
    InstanceType: m5.4xlarge
    ImageId: latest_dlami
    # InstanceMarketOptions:
    #     MarketType: spot
           # SpotOptions:
           #     MaxPrice: "9.0"


worker_nodes:
    InstanceType: m5.16xlarge
    ImageId: latest_dlami
    # # Run workers on spot by default. Comment this out to use on-demand.
    # InstanceMarketOptions:
    #     MarketType: spot
        # SpotOptions:
        #     MaxPrice: "9.0"

file_mounts: {
}
initialization_commands: []
setup_commands:
  - pip install -U -q boto3
  # - pip install -U ray==1.4.0 # https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip install -q ipdb ray[rllib] #torch torchvision
  # - rm -rf  /root/anaconda3/lib/python3.7/site-packages/ray/tune
  # - rm -rf  /root/anaconda3/lib/python3.7/site-packages/ray/autoscaler
  # - cp -r /root/tune/  /root/anaconda3/lib/python3.7/site-packages/ray/tune
  # - cp -r /root/autoscaler/  /root/anaconda3/lib/python3.7/site-packages/ray/autoscaler
  # - apt update && apt-get install -y libglib2.0-0 libgl1-mesa-glx
  # - pip install -U tensorflow
  - sudo apt update && sudo apt install -y build-essential
  - pip install statsmodels tqdm convertdate "pystan<3" fbprophet sklearn

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# # Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray stop --force
    -  ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=10000000000

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray stop --force
    -  ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=10000000000
```

Code:
```python
from tqdm import tqdm
import itertools
import json

import ray
from ray.util.queue import Queue, Empty
from ray.util.placement_group import get_current_placement_group

import time

import numpy as np
import os

import time

FINISH = "FINISH"
NODE_BATCH = 50
WORKER_MINI_BATCH = 5
TIMING = 0.5


class Timer:
    def __init__(self, name=""):
        self.name = name

    def __enter__(self):
        self.start = time.time()
        print(f"starting {self.name}...")
        return self

    def __exit__(self, *args):
        self.end = time.time()
        self.interval = self.end - self.start
        print(f"{self.name} took: {self.interval:.2f} s")


def batch(iterable, n=1):
    l = len(iterable)
    for ndx in range(0, l, n):
        yield iterable[ndx:min(ndx + n, l)]


def train(config):
    assert isinstance(config, dict), config
    time.sleep(TIMING)
    result = {"error": np.random.uniform(), "params": config}
    return  result


@ray.remote
class NodeTrialRunner:
    def __init__(self, num_workers: int, fn, queue: Queue, timeout: int = 5, minibatch=WORKER_MINI_BATCH, key=None):
        self.num_workers = num_workers
        self.queue = queue
        self.timeout = timeout
        self.minibatch_len = minibatch

        self._node_ip = ray.util.get_node_ip_address()
        pg = get_current_placement_group()

        self.trial_queue = Queue(
            maxsize=num_workers * 2, actor_options=dict(num_cpus=0, placement_group=pg))

        self.workers = [
            TrialRunner.options(placement_group=pg).remote(fn, self.trial_queue, key=key)
            for _ in range(num_workers)
        ]

    def get_host(self):
        return self._node_ip

    def run(self):
        futures = [w.run.remote() for w in self.workers]
        start = time.perf_counter()
        underutil_counter = 0

        while True:
            try:
                config_batch = self.queue.get_nowait()
                if config_batch == FINISH:
                    print('got finish')
                    break
            except Empty:
                if time.perf_counter() - start > self.timeout:
                    # print(f'node timed out: {time.perf_counter()}, {start}')
                    break
                time.sleep(0.01)
                continue
            for mini in batch(config_batch, n=self.minibatch_len):
                assert len(mini) == self.minibatch_len
                self.trial_queue.put(mini)
            start = time.perf_counter()

        self.trial_queue.put(FINISH)

        results = []
        in_progress = futures
        timeout = 120
        start = time.time()
        while in_progress:
            ready, in_progress = ray.wait(in_progress, timeout=1)
            for fut in ready:
                try:
                    res = ray.get(fut)
                    results.append(res)
                except Exception as e:
                    index = futures.index(fut)
                    print(f"Worker {index} on node {self._node_ip} died: "
                          f"{e}")
                    continue
            cur_time = time.time() - start
        # print("We finished!")
        return reduce_results(*results)


@ray.remote
class TrialRunner:
    def __init__(self, fn, queue: Queue, timeout: int = 5, key=None):
        self.fn = fn
        self.queue = queue
        self.timeout = timeout
        self.key = key

    def run(self):
        results = []
        start = time.perf_counter()
        underutil_counter = 0

        while True:
            try:
                config_batch = self.queue.get_nowait()
                if config_batch == FINISH:
                    break
            except Empty:
                if time.perf_counter() - start > self.timeout:
                    break
                time.sleep(0.01)
                underutil_counter += 1
                continue
            for config in config_batch:
                start = time.perf_counter()
                result = self.fn(config)
                taken = time.perf_counter() - start
                results.append({config[self.key]: result})
            start = time.perf_counter()

        return reduce_results(*results) # [:self.num_returns]  # TODO: fixme


def grid_search(config, resolved=None):
    config = config.copy()
    resolved = resolved or {}

    keys = sorted(config.keys())
    key = keys[0]

    vars = config.pop(key)
    for var in vars:
        this = resolved.copy()
        this[key] = var
        if not config:
            yield this
        else:
            for r in grid_search(config, this):
                yield r


def tune_grid_search(func, cfg, max_cpus):
    num_nodes = len(ray.nodes())
    cpus_per_node = [int(node["Resources"]["CPU"]) for node in ray.nodes() if "CPU" in node["Resources"]]
    from collections import Counter
    counter = Counter(cpus_per_node)
    print(f"Resources: {cpus_per_node}")
    print(f"Node batch size: {NODE_BATCH}")
    print(f"Worker minibatch {WORKER_MINI_BATCH}")

    used_cpus = 0
    pgs = {}
    while used_cpus < max_cpus:
        cpus = cpus_per_node.pop(0)
        pgs[ray.util.placement_group([{"CPU": cpus}])] = cpus
        used_cpus += cpus
    print(f"Created placement groups for {used_cpus}")

    config_queue = Queue(maxsize=100, actor_options=dict(num_cpus=0))

    runners = [
        NodeTrialRunner.options(
            placement_group=pg, placement_group_bundle_index=0).remote(
                num_workers=cpus, fn=func, queue=config_queue, key="target")
        for pg, cpus in pgs.items()
    ]

    new_runners = []
    for runner in runners:
        try:
            ray.get(runner.get_host.remote(), timeout=30)
            new_runners.append(runner)
        except Exception as e:
            print(e)
            continue

    runners = new_runners
    print(f"total length of new runners: {len(new_runners)}")


    futures = [runner.run.remote() for runner in runners]

    grid_list = list(grid_search(cfg))
    with Timer("put"):
        all_batches = list(batch(grid_list, n=NODE_BATCH))
        for config_batch in tqdm(all_batches):
            config_queue.put(config_batch)

    with Timer("consume"):
        left = len(all_batches)
        t = tqdm(total=left)
        while left > 10:
            qsize = config_queue.qsize()
            t.update(n=left - qsize)
            left = qsize
            time.sleep(2)
        t.close()
        if left:
            print("Straggler tokens are left, moving on.")


    results = []
    in_progress = futures
    with Timer("collection"):
        t = tqdm(total=len(in_progress))
        while in_progress:
            ready, in_progress = ray.wait(in_progress, timeout=0.5)
            for fut in ready:
                try:
                    res = ray.get(fut)
                    results.append(res)
                    t.update(n=1)
                except Exception as e:
                    index = futures.index(fut)
                    host = hosts[index]
                    print(f"Node worker {index} on node {host} died: "
                          f"{e}")
                    continue
        t.close()


    [ray.util.remove_placement_group(pg) for pg in pgs]

    return reduce_results(*results)


def reduce_results(*all_results: "Dict[Target, Result]", score="error") -> "Dict[Target, Result]":
    if not all_results:
        return {}
    # print(f"reducing some results: {len(all_results)}")
    best_results = {}
    for result_dict in all_results:
        for target, result in result_dict.items():
            assert "error" in result, result
            assert "params" in result, result
            if target not in best_results:
                best_results[target] = result
            else:
                if best_results[target][score] > result[score]:
                    best_results[target] = result
    return best_results


if __name__ == "__main__":
    ray.init(address="auto")
    config = {
        "target": list(range(5)),
        "p": [1, 2],
        "x": list(range(10)),
        "b": list(range(100)),
    }
    INIT_CPUS = 890

    list_cfgs = 1
    for g in config.values():
        list_cfgs *= len(g)
    print("Model time: ", TIMING)
    print(f"total configs: {list_cfgs}")

    if list_cfgs > 2**32:
        print("WARNING: You're using a huge amount of local memory. This may break ray.")

    start = time.perf_counter()
    all_results = []
    for i in range(20):
        results = tune_grid_search(func=train, cfg=config, max_cpus=INIT_CPUS)
        all_results.append(results)
    taken = time.perf_counter() - start

    best_results = reduce_results(*all_results)

    print("RESULT", best_results)

    test_output_json = os.environ.get("TEST_OUTPUT_JSON",
                                      "/tmp/tune_test.json")
    with open(test_output_json, "wt") as f:
        json.dump(best_results, f)

    print(f"TOOK {taken:.2f} seconds!")
```

cc @rkooo567 @wuisawesome @ericl
