### ISSUE TITLE
Ray [client] [autoscaler] ray.init() SIGARBT from CoreWorker when connecting to existing cluster

### ISSUE THREAD

**Issue by bmframos** [ray-project/ray#17459]
### What is the problem?
I am getting a SIGARBT error when attempting to connect to an existing ray autoscaled cluster on aws. I've tried minimal documentation examples the problem still remains.
The cause seems to be the [CoreWorker instantiation](https://github.com/ray-project/ray/blob/2ae6b944a25dc2d371e0496895e3bdbe29c3d046/python/ray/worker.py#L1355-L1361) in `worker.py`, and it simply terminates with no error whatsoever.

I can run any sample of code if I SSH into the head node cluster or if I use ray submit, but using ray client's ray.init to connect to the existing cluster does not work.

*Ray version and other system information (Python version, TensorFlow version, OS):*
- Ray: 1.4.1
- Python: 3.7.7
- Pytorch: 1.9
- OS: MacOS BigSur

### Reproduction
ray_autoscaler.yaml
```
cluster_name: markerless-navigation-cluster

max_workers: 5

upscaling_speed: 1.0

docker:
    image: "rayproject/ray-ml:latest-gpu"
    container_name: "markerless-navigation"
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

provider:
    type: aws
    region: us-east-1
    availability_zone: us-east-1b, us-east-1c, us-east-1d, us-east-1f, us-east-1a
    cache_stopped_nodes: False # If not present, the default is True.

auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        min_workers: 1
        max_workers: 1
        resources: {} 
        node_config:
            IamInstanceProfile:
              Arn: arn:aws:iam::<account_id>:instance-profile/ray-head-v1
            InstanceType: r5b.xlarge
            ImageId: latest_dlami
    ray.worker.default:
        min_workers: 0
        max_workers: 5
        resources: {}
        node_config:
            IamInstanceProfile:
              Arn: arn:aws:iam::<account_id>:instance-profile/ray-worker-v1
            InstanceType: r5b.xlarge
            ImageId: latest_dlami
            InstanceMarketOptions:
                MarketType: spot
            # Additional options in the boto docs.

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default

cluster_synced_files: []

file_mounts_sync_continuously: True

rsync_exclude:
    - "**/.git"
    - "**/.git/**"

rsync_filter:
    - ".gitignore"

initialization_commands: []

file_mounts: {
}


setup_commands: []

head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

head_node: {}
worker_nodes: {}
```
Tried:
1. ray up ray_autoscaler.yaml
2. ray start --address address --redis-password pass
3. run simple python docs example

Also tried passing the ip and port to ray.init, and using the deprecated ray.client(address).connect(), which results in connection timeout.  Any ideas?

```
@ray.remote
def ray_remote_execution():
    return gethostbyname(gethostname())


def test_ray_remote_execution():
     try:
        ray.init()
    except Exception as e:
         raise ConnectionError(e)
    object_ids = [ray_remote_execution.remote() for _ in range(10)]
    ip_addresses = ray.get(object_ids)
    assert len(ip_addresses) == 10
    assert ip_addresses.pop() == gethostbyname(gethostname())
    ray.shutdown()
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).
- I need to use 1.4.1 because of autoscaler?
