### ISSUE TITLE
[1.5.2] [1.4.1] [tune] [internalerror] The client has been closed.

### ISSUE THREAD

**Issue by dmkulazhenko** [ray-project/ray#17506]
### Important:
This issue was NOT tested on latest Ray==1.5.1.
It's reported only because I have this in trace:
`RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!`
If you don't care about it and I shouldn't post this trace -- fell free to close it.

**UPD:** reproduced on ray==**1.5.1** and ray==**1.5.2**. 

### Env

Ray ver: ray[all]==1.4.1
OS: Amazon Linux 2
Python: 3.8.11 (pyenv-global)

Overall - clean AML2 with some libs such as `zlib / libffi / bzip2 / readline / ...`

### Reproduction

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

------

#### Ray cloud cluster config:

```
cluster_name: RAT-cluster
max_workers: 3
upscaling_speed: 1
idle_timeout_minutes: 1

provider:
    type: aws
    region: eu-west-1
    availability_zone: eu-west-1a
    cache_stopped_nodes: True

available_node_types:
    ray.head.default:
        min_workers: 0
        max_workers: 0
        resources: {"CPU": 0}
        node_config:
            InstanceType: m5.large
            ImageId: "my-ami"
            KeyName: stub
            SecurityGroupIds: ["sg-"]
            SubnetId: "subnet-"
            IamInstanceProfile: {Name: "ray-cluster"}
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 25

    ray.worker.default:
        min_workers: 0
        max_workers: 3
        resources: {}
        node_config:
            InstanceType: c5.2xlarge
            ImageId: "my-ami"
            KeyName: stub
            SecurityGroupIds: ["sg-"]
            SubnetId: "subnet-"
            IamInstanceProfile: {Name: "ray-cluster"}
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 25

head_node_type: ray.head.default

auth:
    ssh_user: ray-master
    ssh_private_key: "/home/stub/.ssh/stub.pem"

file_mounts: {
    /home/ray-master/.ssh: "/home/stub/Projects/project/local/keys"
}

rsync_exclude:
    - "**/.git"
    - "**/.git/**"
rsync_filter:
    - ".gitignore"

initialization_commands: []
setup_commands: [
    "test -e /home/ray-master/project || git clone -b branch --single-branch git@my.git/project",
    "test -e /home/ray-master/project2 || git clone git@my.git/project2",
    "pip install /home/ray-master/project",
    "pip install /home/ray-master/project2"
]
```

Tune-job that I execute is pretty simple:
- `optuna` calibration
- `checkpoint_frequency=1`
- `samples=5`

Really nothing special in calibration job, just a `tune.Experiment` executed via `tune.run()`.
Ray init: `ray.init(address="auto")`.

Trace:
```
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 2.0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (2 RUNNING, 3 TERMINATED)
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc            
|----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_5673671a | RUNNING    | 10.111.0.227:3802 |   
| Tuner_5696156c | RUNNING    |                   |
| Tuner_fb9e2096 | TERMINATED |                   | 
| Tuner_56a9029e | TERMINATED |                   | 
| Tuner_56cb7d2e | TERMINATED |                   | 
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+


2021-08-02 14:29:04,317	ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-08-02 14:29:04,317	ERROR syncer.py:413 -- Trial Tuner_5673671a: Checkpoint sync skipped. This should not happen.
Trial Tuner_5696156c reported f1=0.00 with parameters={...}. This trial completed.
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 1.0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (1 RUNNING, 4 TERMINATED)
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc               |  
|----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_5696156c | RUNNING    | 10.111.0.227:3796 | 
| Tuner_fb9e2096 | TERMINATED |                   |   
| Tuner_5673671a | TERMINATED |                   |  
| Tuner_56a9029e | TERMINATED |                   |    
| Tuner_56cb7d2e | TERMINATED |                   |    
+----------------+------------+-------------------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+


2021-08-02 14:39:36,857	ERROR syncer.py:190 -- Sync execution failed.
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/syncer.py", line 186, in sync_down
    result = self.sync_client.sync_down(self._remote_path,
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 212, in sync_down
    return self._execute(self.sync_down_template, source, target)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 271, in _execute
    stdout=self._get_logfile())
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/sync_client.py", line 201, in _get_logfile
    raise RuntimeError(
RuntimeError: [internalerror] The client has been closed. Please report this stacktrace + your cluster configuration on Github!
2021-08-02 14:39:36,858	ERROR syncer.py:413 -- Trial Tuner_5696156c: Checkpoint sync skipped. This should not happen.
== Status ==
Memory usage on this node: 1.7/7.6 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/15.61 GiB heap, 0.0/6.69 GiB objects
Current best trial: 56cb7d2e with f1=0.3159319785218439 and parameters={...}
Result logdir: /home/ray-master/pipeopt_experiments/test
Number of trials: 5/5 (5 TERMINATED)
+----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+
| Trial name     | status     | loc   |  
|----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------|
| Tuner_fb9e2096 | TERMINATED |       | 
| Tuner_5673671a | TERMINATED |       |   
| Tuner_5696156c | TERMINATED |       |    
| Tuner_56a9029e | TERMINATED |       |       
| Tuner_56cb7d2e | TERMINATED |       |      
+----------------+------------+-------+---------------------------------------------------+------------------------------------------+-----------------------------------------+----------------------------------------------+-----------------------------------+-----------------------------------+--------+------------------+----------+-------------+-----------+

2021-08-02 14:39:36,986	INFO tune.py:549 -- Total run time: 3641.36 seconds (3641.18 seconds for the tuning loop).
```

Also (not during this run, but one time I had this error during same trial run:
```
Failure # 1 (occurred at 2021-07-30_21-45-54)
Traceback (most recent call last):
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 702, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 686, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray-master/.pyenv/versions/3.8.11/lib/python3.8/site-packages/ray/worker.py", line 1483, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
```

Ray job executes like this:
```
$> ray up ray-cluster.yaml
$> ray submit ray-cluster.yaml test.py
```

test.py:
```
from project.api import ExperimentAPI
from project.pipeopt import Driver

CONFIG = {...}


def main():
    # Returns over internal Experiment object
    exp = ExperimentAPI(**CONFIG).instantiate() 
    
    # Driver -- tool, which inits ray
    driver = Driver(ray_init_params={"address": "auto"})
    
    # Transforms exp to Tune.Experiment and executes using Tune.run()
    driver.execute(exp)


if __name__ == "__main__":
    main()

```

Executing `test.py` on local machine (without `address="auto"`) leads to successful calibration.
