### ISSUE TITLE
Empty error at the end of script getting futures from ray server on cluster.

### ISSUE THREAD

**Issue by OrEisenberg** [ray-project/ray#17647]
[autoscaler]

### What is the problem?

- python version: 3.7/3.8 (confirmed that it breaks for both)
- `ray` version:  1.5.1
- local OS: MacOS Big Sur 11.4 (local)
- remote OS: ubuntu focal 20.04 (remote)

### Reproduction
I set up a ray cluster which, upon launch, configures itself to be a server (config file to follow). I then run the following script locally.

```
import ray
import ray.util

REMOTE_CLUSTER_IP = '0.0.0.0'
REMOTE_CLUSTER_PORT = 0

ray.util.connect(f'{REMOTE_CLUSTER_IP}:{REMOTE_CLUSTER_PORT}')

@ray.remote
def hello_world():
    return 'Hello, world!'

result = ray.get([hello_world.remote() for _ in range(5)])
if result == ['Hello, world!' for _ in range(5)]:
    print('Got expected result!')

print('Script exiting...')
```

Here is the perplexing stdout I get (verbatim):
```
>>> python script.py
Got expected result!
Script exiting...
Error in sys.excepthook:

Original exception was:

```

The `config.yaml` file I'm using to spin up my cluster is as follows.

```

cluster_name: cluster

max_workers: 2
upscaling_speed: 1.0

docker:
    image: rayproject/ray:nightly-py37 | rayproject/ray:nightly-py38
    container_name: "ray_container"
    pull_before_run: False # pulled down already in AMI (which is rebuilt every day)
    run_options: []

idle_timeout_minutes: 5

# AWS config
provider:
    type: aws
    region: <AWS_REGION>
    cache_stopped_nodes: False

auth:
    ssh_user: ubuntu
    ssh_private_key: <PRIVATE_KEY>

available_node_types:
    ray.head.custom:
        min_workers: 0
        max_workers: 0
        resources: {}
        node_config:
            SubnetId: <SUBNET_ID>
            ImageId: <AMI>
            SecurityGroupIds: <SECURITY_GROUP_IDS>
            InstanceType: <INSTANCE_TYPE>
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 100
    ray.worker.custom:
        min_workers: 0
        max_workers: 2
        resources: {}
        node_config:
            SubnetId: <SUBNET_ID>
            ImageId: <AMI>
            SecurityGroupIds: <SECURITY_GROUP_IDS>
            InstanceType: <INSTANCE_TYPE>
            InstanceMarketOptions:
                MarketType: spot

head_node_type: ray.head.custom

file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: False

rsync_exclude:
    - "**/.git"
    - "**/.git/**"

rsync_filter:
    - ".gitignore"


# forward external dashboard port to internal dashboard port so that dashboard is accessible from external port
initialization_commands: ['sudo iptables -t nat -A PREROUTING -p tcp --dport <DASHBOARD_EXTERNAL_PORT> -j REDIRECT --to-port <DASHBOARD_PORT>']
setup_commands: []
head_setup_commands: []
worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --dashboard-host "<DASHBOARD_IP>" --dashboard-port <DASHBOARD_PORT> --head --port=<PORT> --object-manager-port=<OBJECT_MANAGER_PORT> --autoscaling-config=~/ray_bootstrap_config.yaml
    - nohup python -m ray.util.client.server --host "<HOST_IP>" --port <HOST_PORT> &
# Start the worker node.
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:<PORT> --object-manager-port=<OBJECT_MANAGER_PORT>

head_node: {}
worker_nodes: {}
```

It seem like the shutdown/cleanup process is erroring out in some mysterious way (however, even if I manually shut down before the script exits, I still get the same error, so I have no idea what's actually happening). I think that this is all the information needed to replicate the bug, but please do let me know if there's anything I'm forgetting or if I can elaborate in any way. I also welcome any and all comments about how I'm doing stuff!
