### ISSUE TITLE
[tune] Distributed checkpoints don't get deleted

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#17940]
### What is the problem?

The standard rsync mechanism does not delete checkpoints upon `keep_checkpoints_num` garbage collection.

Here's a script to reproduce this:

```python
#!/usr/bin/env python

import argparse
import json
import os

import numpy as np

import ray
from ray import tune
from ray.tune.schedulers import HyperBandScheduler


def train(config, checkpoint_dir=None):
    step = 0
    if checkpoint_dir:
        with open(os.path.join(checkpoint_dir, "checkpoint")) as f:
            step = json.loads(f.read())["timestep"]

    for timestep in range(step, 10):
        v = np.tanh(float(timestep) / config.get("width", 1))
        v *= config.get("height", 1)

        # Checkpoint the state of the training every 3 steps
        # Note that this is only required for certain schedulers
        # if timestep % 3 == 0:
        with tune.checkpoint_dir(step=timestep) as checkpoint_dir:
            path = os.path.join(checkpoint_dir, "checkpoint")
            with open(path, "w") as f:
                f.write(json.dumps({"timestep": timestep}))

        # Here we use `episode_reward_mean`, but you can also report other
        # objectives such as loss or accuracy.
        tune.report(episode_reward_mean=v)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()
    if args.server_address is not None:
        ray.init(args.server_address)
    else:
        ray.init(num_cpus=4 if args.smoke_test else None)

    # Hyperband early stopping, configured with `episode_reward_mean` as the
    # objective and `training_iteration` as the time unit,
    # which is automatically filled by Tune.
    # hyperband = HyperBandScheduler(max_t=200)

    analysis = tune.run(
        train,
        name="hyperband_test",
        num_samples=20,
        metric="episode_reward_mean",
        mode="max",
        stop={"training_iteration": 10 if args.smoke_test else 99999},
        config={"height": tune.uniform(0, 100)},
        keep_checkpoints_num=1,
        local_dir="./tmp-results",
        # scheduler=hyperband,
        fail_fast=True)
    print("Best hyperparameters found were: ", analysis.best_config)
```

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: basic

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 2
initial_workers: 2
max_workers: 2
autoscaling_mode: aggressive

target_utilization_fraction: 0.9

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 20

docker:
    image: "rayproject/ray:nightly-cpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
#    run_options: []  # Extra options to pass into "docker run"

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    # cache_stopped_nodes: False

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
head_node:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    # InstanceMarketOptions:
    #     MarketType: spot
           # SpotOptions:
           #     MaxPrice: "9.0"


worker_nodes:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    # # Run workers on spot by default. Comment this out to use on-demand.
    # InstanceMarketOptions:
    #     MarketType: spot
        # SpotOptions:
        #     MaxPrice: "9.0"

file_mounts: {
}

initialization_commands: []
setup_commands:
  - pip install -U boto3
  - pip install ipdb ray[rllib] #torch torchvision
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# # Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --object-store-memory=1000000000

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=1000000000

```

Here's the output:

```
'/home/ray/tmp-results/hyperband_test/train_97422_00008_8_height=24.046_2021-08-18_17-44-22':
checkpoint_000009  events.out.tfevents.1629333862.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00009_9_height=39.926_2021-08-18_17-44-22':
checkpoint_000009  events.out.tfevents.1629333862.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00010_10_height=2.9272_2021-08-18_17-44-22':
checkpoint_000009  events.out.tfevents.1629333862.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00011_11_height=53.061_2021-08-18_17-44-22':
checkpoint_000009  events.out.tfevents.1629333862.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00012_12_height=11.617_2021-08-18_17-44-22':
checkpoint_000009  events.out.tfevents.1629333934.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00013_13_height=27.268_2021-08-18_17-45-34':
checkpoint_000009  events.out.tfevents.1629333939.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00014_14_height=12.423_2021-08-18_17-45-39':
checkpoint_000000  checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  events.out.tfevents.1629333947.ip-172-31-22-248  params.pkl    result.json
checkpoint_000001  checkpoint_000003  checkpoint_000005  checkpoint_000007  checkpoint_000009  params.json                                      progress.csv

'/home/ray/tmp-results/hyperband_test/train_97422_00015_15_height=63.531_2021-08-18_17-45-47':
checkpoint_000000  checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  events.out.tfevents.1629333948.ip-172-31-22-248  params.pkl    result.json
checkpoint_000001  checkpoint_000003  checkpoint_000005  checkpoint_000007  checkpoint_000009  params.json                                      progress.csv

'/home/ray/tmp-results/hyperband_test/train_97422_00016_16_height=60.827_2021-08-18_17-45-48':
checkpoint_000000  checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  events.out.tfevents.1629333949.ip-172-31-22-248  params.pkl    result.json
checkpoint_000001  checkpoint_000003  checkpoint_000005  checkpoint_000007  checkpoint_000009  params.json                                      progress.csv

'/home/ray/tmp-results/hyperband_test/train_97422_00017_17_height=78.073_2021-08-18_17-45-49':
checkpoint_000009  events.out.tfevents.1629333953.ip-172-31-22-248  params.json  params.pkl  progress.csv  result.json

'/home/ray/tmp-results/hyperband_test/train_97422_00018_18_height=59.584_2021-08-18_17-45-53':
checkpoint_000000  checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  events.out.tfevents.1629333960.ip-172-31-22-248  params.pkl    result.json
checkpoint_000001  checkpoint_000003  checkpoint_000005  checkpoint_000007  checkpoint_000009  params.json                                      progress.csv

'/home/ray/tmp-results/hyperband_test/train_97422_00019_19_height=17.832_2021-08-18_17-46-00':
checkpoint_000000  checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  events.out.tfevents.1629333962.ip-172-31-22-248  params.pkl    result.json
checkpoint_000001  checkpoint_000003  checkpoint_000005  checkpoint_000007  checkpoint_000009  params.json
```

Note that some of the checkpoints should not exist (there should only be checkpoint_000009)

cc @amholler
