### ISSUE TITLE
[datasets] Segfault sometimes when using windowed data shuffling/ingest

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#18101]
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* master

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

Here is the stack trace:

```
(pid=14053, ip=172.31.63.35) *** SIGSEGV received at time=1629779882 on cpu 40 ***
(pid=14053, ip=172.31.63.35) PC: @     0x7f8a60f35d10  (unknown)  ray::core::CoreWorkerDirectTaskReceiver::HandleTask()::{lambda()#1}::operator()()
(pid=14053, ip=172.31.63.35)     @     0x7f8a62b8f980  758251280  (unknown)
(pid=14053, ip=172.31.63.35)     @     0x7f8a60f3648a         80  std::_Function_handler<>::_M_invoke()
(pid=14053, ip=172.31.63.35)     @     0x7f8a60eb7b35        448  ray::core::NormalSchedulingQueue::ScheduleRequests()
(pid=14053, ip=172.31.63.35)     @     0x7f8a612755e6        112  boost::asio::detail::completion_handler<>::do_complete()
(pid=14053, ip=172.31.63.35)     @     0x7f8a61377e58        112  boost::asio::detail::scheduler::do_run_one()
(pid=14053, ip=172.31.63.35)     @     0x7f8a61378a11        160  boost::asio::detail::scheduler::run()
(pid=14053, ip=172.31.63.35)     @     0x7f8a6137a560         64  boost::asio::io_context::run()
(pid=14053, ip=172.31.63.35)     @     0x7f8a60f22405        144  ray::core::CoreWorkerProcess::RunTaskExecutionLoop()
(pid=14053, ip=172.31.63.35)     @     0x7f8a60dad3d7         32  __pyx_pw_3ray_7_raylet_10CoreWorker_9run_task_loop()
(pid=14053, ip=172.31.63.35)     @     0x5576d487ab71  (unknown)  _PyMethodDef_RawFastCallKeywords
(pid=14053, ip=172.31.63.35)     @     0x7f8a60dad3c0  (unknown)  (unknown)
```

Workload script:

```python
import time
import numpy as np
import torch
import ray
import argparse
import os
from ray.data.dataset_pipeline import DatasetPipeline

DUMMY_ROW = {'key': 0, 'embeddings_name0': 1527, 'embeddings_name1': 175, 'embeddings_name2': 8, 'embeddings_name3': 5, 'embeddings_name4': 5, 'embeddings_name5': 687, 'embeddings_name6': 165, 'embeddings_name7': 10, 'embeddings_name8': 137, 'embeddings_name9': 597, 'embeddings_name10': 1574, 'embeddings_name11': 78522, 'embeddings_name12': 283941, 'embeddings_name13': 3171, 'embeddings_name14': 39560, 'embeddings_name15': 718571, 'embeddings_name16': 73699, 'one_hot0': 1, 'one_hot1': 30, 'labels': 0.3801173847541949, '__index_level_0__': 0}


def create_parser():
    parser = argparse.ArgumentParser(description="Eric Example")
    parser.add_argument("--address")
    parser.add_argument("--num-rows", type=int, default=1 * (10**9))
    parser.add_argument("--num-files", type=int, default=200)
    parser.add_argument("--read-cache", action="store_true", default=False)
    parser.add_argument("--data-dir", type=str, default="s3://shuffling-data-loader-benchmarks/data/")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=250000,
        metavar="N",
        help="input batch size for training (default: 64)")
    parser.add_argument("--num-workers", type=int, default=4)
    return parser


# def run_shuffle(args, data_dir):
#     ds = ray.data.read_parquet(data_dir)
#     res = ds.random_shuffle().take(10)
#     print(res)
def create_shuffled_dataset(args, data_dir):
    if data_dir:
        ds = ray.data.read_parquet(data_dir)
    else:
        ds = ray.data.range(args.num_rows).map(lambda i: DUMMY_ROW)
    pipeline = ds.repeat().random_shuffle()
    splits = pipeline.split(args.num_workers, equal=True)
    return splits


def create_windowed_dataset(args, data_dir, windows=10, epochs=2):
    if data_dir:
        ds = ray.data.read_parquet(data_dir)
    else:
        ds = ray.data.range(args.num_rows).map(lambda i: DUMMY_ROW)

    splits = ds.split(windows)

    def loop_over(datasets):
        return [(lambda ds=ds: ds) for i in range(epochs) for ds in datasets]


    pipe = DatasetPipeline.from_iterable(loop_over(splits))
    return pipe.split(args.num_workers, equal=True)

def run_consume(args, data_dir=None):
    splits = create_windowed_dataset(args, data_dir)

    @ray.remote(num_gpus=1)
    def consume(split, rank=None, batch_size=None):
        for i, x in enumerate(split.iter_rows()):
            time.sleep(1)
            if i % 10 == 0:
                print(i)
        return

    tasks = [
        consume.remote(split, rank=idx, batch_size=args.batch_size)
        for idx, split in enumerate(splits)
    ]
    ray.get(tasks)


if __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()
    print("Connecting to Ray cluster...")
    ray.init(address=args.address)

    # data_dir = None
    data_dir = os.path.join(args.data_dir, f"r{args.num_rows:_}-f{args.num_files}/")
    run_consume(args, data_dir=data_dir)
    # run_shuffle(args)
```

Will reproduce on Anyscale cluster, but on OSS here are the specs:
```
Cluster config:

Head node type
g3.8xlarge

Worker node 1
g3.8xlarge (min: 3, max: 3)

Worker node 2
m5.16xlarge (min: 4, max: 4)
```

TO run:

```
python script.py --address=auto --num-workers=4
```

**Comment by richardliaw** [comment]
I unfortunately cannot do this on an anyscale cluster, but here is my cluster yaml:

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: shuffling-data-loader-horovod

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 1
initial_workers: 1
max_workers: 10

# target_utilization_fraction: 0.9

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 20
docker:
    image: horovod/horovod-ray:sha-3278964 # 7/20
    container_name: ray_docker

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    # region: us-east-2
    # availability_zone: us-east-2a
    cache_stopped_nodes: False # If not present, the default is True.

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

head_node_type: head

available_node_types:
    head:
        node_config:
            InstanceType: g3.4xlarge
            ImageId: latest_dlami
            # Set primary volume to 25 GiB
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 300

    gpu_nodes:
        min_workers: 3
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 3
        node_config:
            InstanceType: g3.4xlarge
            ImageId: latest_dlami
            IamInstanceProfile:
                Arn: arn:aws:iam::959243851260:instance-profile/ray-autoscaler-v1
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 300

    memory_nodes:
        min_workers: 4
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 4
        node_config:
            InstanceType: m5.16xlarge
            ImageId: latest_dlami
            IamInstanceProfile:
                Arn: arn:aws:iam::959243851260:instance-profile/ray-autoscaler-v1
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 300
    # Run workers on spot by default. Comment this out to use on-demand.
    # InstanceMarketOptions:
    #     MarketType: spot
        # SpotOptions:
        #     MaxPrice: "9.0"

file_mounts: {
}

setup_commands:
    - pip install -q boto3 tqdm torch torchvision  pyarrow fsspec s3fs==2021.08.0
    - pip uninstall ray -y && pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
   
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# # Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop --force
    - rm -rf /tmp/ray/
    -  ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml 

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop --force
    - rm -rf /tmp/ray/
    - RAY_BACKEND_LOG_LEVEL=debug ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```
