### ISSUE TITLE
SSH Error Ray Up on Azure

### ISSUE THREAD

**Issue by MarvinSt** [ray-project/ray#18197]
Hi all,

I am trying to setup a cluster on Azure using Ray and am looking for some help. I followed the steps in the documentation and the infrastructure is being created on Azure, but when calling `ray up -y config.yaml --no-config-cache` it throws the following error:
```
2021-08-29 22:17:11,678 INFO config.py:57 -- Creating/Updating Resource Group: ray-cluster
Updating cluster configuration and running full setup.
Cluster Ray runtime will be restarted. Confirm [y/N]: y [automatic, due to --yes]

<1/1> Setting up head node
  Prepared bootstrap config
  New status: waiting-for-ssh
  [1/7] Waiting for SSH to become available
    Running `uptime` as a test.
    Fetched IP: ...
getsockname failed: Bad file descriptor
channel_send_open: channel 0: unexpected internal error
    SSH still not available (SSH command failed.)
```

- I have created the ssh keys using `ssh-keygen -t rsa -b 4096` in the default location 
(Windows PC: `C:\Users\{user}\.ssh\id_rsa`). 

- I can also successfully connect to the VM via SSH using the command line  
`ssh -i C:\Users\{user}\.ssh\id_rsa ubuntu@{ip}`

This is my config.yaml, but I also tried a few others, with the same results.
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# The maximum number of workers nodes to launch in addition to the head
# node. min_workers default to 0.
max_workers: 1

# Cloud-provider specific configuration.
provider:
    type: azure
    location: germanywestcentral
    resource_group: ray-cluster

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    # you must specify paths to matching private and public key pair files
    # use `ssh-keygen -t rsa -b 4096` to generate a new ssh key pair
    ssh_private_key: ~/.ssh/id_rsa
    # changes to this should match what is specified in file_mounts
    ssh_public_key: ~/.ssh/id_rsa.pub

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray.head.default:
        max_workers: 0
        # The resources provided by this node type.
        resources: {"CPU": 2}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                vmSize: Standard_D2s_v3
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-1804
                imageSku: 1804-gen2
                imageVersion: 21.07.12

    ray.worker.default:
        min_workers: 0
        # The resources provided by this node type.
        resources: {"CPU": 2}
        # Provider-specific config, e.g. instance type.
        node_config:
            azure_arm_parameters:
                vmSize: Standard_D2s_v3
                imagePublisher: microsoft-dsvm
                imageOffer: ubuntu-1804
                imageSku: 1804-gen2
                imageVersion: 21.07.12
                # optionally set priority to use Spot instances
                priority: Spot
```

Hopefully, there is a simple solution and I am missing a crucial step. I tried it on Google Cloud as well and had a similar issue.

Thanks for your support!
