### ISSUE TITLE
[Bug] [autoscaler] Ray tune torch.DistributedTrainableCreator duplicated trials across workers when using GPU

### ISSUE THREAD

**Issue by bmframos** [ray-project/ray#18844]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune, Ray Clusters

### What happened + What you expected to happen

Using the ray autoscaler with the AWS provider and ray tune, when launching a distributed tune experiment via the ray client `ray exec docker/ray_autoscaler.yaml 'python train_function.py'`, the trials are duplicated instead of parallelized, if using GPU.

For the given reproduction script, the result is that 2 workers will work simultaneously (2 different nodes on the cluster), but will repeat the exact same trial, therefore printing the same random number. The expected behaviour would be that this 2 workers ran on parallel, without duplicating the trial.

This seems to happen only when using GPU, when running with CPU we get the expected behaviour, E.g. by omitting resources from `DistributedTrainableCreator(tune.with_parameters(trainable_func, input_arguments=cfg))`, there are no duplicated trials, but everything executes on CPU.

### Reproduction script

`ray_autoscaler.yaml`
```
cluster_name: test-cluster
upscaling_speed: 1.0
max_workers: 10
docker:
    image: "private_repo/image"
    container_name: "image-name"
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"
idle_timeout_minutes: 5
provider:
    type: aws
    region: us-east-1
    cache_stopped_nodes: True # If not present, the default is True.
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/private-key.pem
available_node_types:
    ray.head.default:
        min_workers: 0
        max_workers: 1
        resources: {} # Automatically detected based on instance type
        node_config:
            KeyName: ray-autoscaler_us-east-1
            IamInstanceProfile:
              Arn: arn:aws:iam::ID:instance-profile/ray-head-v1
            InstanceType: t3.large
            ImageId: latest_dlami
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 1000
    ray.worker.default:
        min_workers: 1
        max_workers: 10
        resources: {}
        node_config:
            KeyName: ray-autoscaler_us-east-1
            IamInstanceProfile:
              Arn: arn:aws:iam::ID:instance-profile/ray-worker-v1
            InstanceType: p2.xlarge
            ImageId: latest_dlami
head_node_type: ray.head.default
cluster_synced_files: []
file_mounts_sync_continuously: True
rsync_exclude:
    - "**/.git"
    - "**/.git/**"
rsync_filter:
    - ".gitignore"
initialization_commands:
    - docker rm -f $(docker ps -aq) >/dev/null 2>&1 || true
file_mounts: {}
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
head_node: {}
worker_nodes: {}
```
`train_function.py`
```
def trainable_func(
    config: dict = None,
    checkpoint_dir: Path = None,
    input_arguments: DictConfig = None,
): 
    # Do random work
    print(random.randint(0,100))
    tune.report(optimization_metric="mean")

ray.init(address="auto")
trainable_cls = DistributedTrainableCreator(
    tune.with_parameters(trainable_func, input_arguments=cfg),
    num_gpus_per_worker=1,
    num_cpus_per_worker=0,
    num_workers=2
)
analysis = tune.run(
                    trainable_cls,
                    metric="mean",
                    mode="min",
                    num_samples=10,
                    config={'param': tune.choice("True", "False"), 'optimization_metric': 'mean'}
                    search_alg=HyperOptSearch(max_concurrent=10),
                    queue_trials=True
                )
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
