### ISSUE TITLE
[runtime env] [Bug] Specifying pip "requirements.txt" per-task doesn't work on remote cluster

### ISSUE THREAD

**Issue by architkulkarni** [ray-project/ray#18976]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Specifying pip requirements per-task in a local `requirements.txt` file doesn't work when using a remote cluster. It tries to parse the `requirements.txt` file on the cluster side, but the file doesn't exist there.  This bug is present in 1.7.0rc0 and 1.6.0, and possibly earlier versions.

### Reproduction script

 Create a folder with a `requirements.txt` file containing the single line `pip-install-test` and navigate to that folder.

Start a remote cluster with `ray up -y config.yaml`.  I used the Cluster launcher with the following config.yaml:
```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal-170rc0-archit

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2

setup_commands:
    - pip uninstall -y ray && pip install -U "ray[default]==1.7.0rc0"
```

Then run the following repro script:
```python
import ray
ray.init("ray://54.70.131.201:10001")

@ray.remote 
def test_import(): 
    import pip_install_test
    return True            

assert ray.get( 
    test_import.options(runtime_env={"pip": "requirements.txt"}).remote()
) 
```

We get the following error:
```python-traceback
~/anaconda3/envs/17rc0-2/lib/python3.7/site-packages/ray/util/client/worker.py in _call_schedule_for_task(self, task)
    468         if not ticket.valid:
    469             try:
--> 470                 raise cloudpickle.loads(ticket.error)
    471             except (pickle.UnpicklingError, TypeError):
    472                 logger.exception("Failed to deserialize {}".format(

ValueError: requirements.txt is not a valid file
```
### Anything else

This occurs whether you use `requirements.txt`, `./requirements.txt`, or the full absolute path.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
