### ISSUE TITLE
[Bug] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.

### ISSUE THREAD

**Issue by kssanthosh** [ray-project/ray#19071]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Ray operator starting with error

`Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts.`

I can see all permissions are fine.

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-operator-serviceaccount
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ray-operator-clusterrole
rules:
- apiGroups: ["", "cluster.ray.io"]
  resources: ["rayclusters", "rayclusters/finalizers", "rayclusters/status", "pods", "pods/exec", "services"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: ray-operator-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: ray-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io

```

### Reproduction script

Deploy it with helm3 and try to spin up ray work some time work only start after restarting ray operator

### Anything else

Ray work is starting after restarting Ray operator it is not able to trace the changes. I'm using ray work on the same namespace it should work without issue not sure what is happening.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
