### ISSUE TITLE
[Tune] Tune checkpointing is not respecting `keep_checkpoints_num = 1`

### ISSUE THREAD

**Issue by xwjiang2010** [ray-project/ray#19173]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Tune

### What happened + What you expected to happen

For trials that run on worker node, only see 010 checkpoint (expected).
For trials that run on head node, see 002, 004, 006, 008, 010. (not expected).

```
(base) ray@ip-172-31-21-41:~/tmp-results/hyperband_test$ ls *
 basic-variant-state-2021-10-06_17-19-20.json   experiment_state-2021-10-06_17-19-20.json

'Trainer_379de_00000_0_height=2.1031_2021-10-06_17-19-21':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565961.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00001_1_height=36.753_2021-10-06_17-19-21':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565961.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00002_2_height=98.672_2021-10-06_17-19-21':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565961.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00003_3_height=75.506_2021-10-06_17-19-21':
checkpoint_000010  events.out.tfevents.1633565961.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00004_4_height=13.267_2021-10-06_17-19-22':
checkpoint_000010  events.out.tfevents.1633565962.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00005_5_height=19.019_2021-10-06_17-19-22':
checkpoint_000010  events.out.tfevents.1633565962.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00006_6_height=40.094_2021-10-06_17-19-22':
checkpoint_000010  events.out.tfevents.1633565962.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00007_7_height=75.179_2021-10-06_17-19-22':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565964.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00008_8_height=12.398_2021-10-06_17-19-24':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565981.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00009_9_height=91.955_2021-10-06_17-19-41':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565982.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00010_10_height=63.605_2021-10-06_17-19-42':
checkpoint_000010  events.out.tfevents.1633565987.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00011_11_height=54.955_2021-10-06_17-19-47':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565989.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00012_12_height=5.2352_2021-10-06_17-19-49':
checkpoint_000010  events.out.tfevents.1633565994.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00013_13_height=53.071_2021-10-06_17-19-54':
checkpoint_000010  events.out.tfevents.1633565995.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00014_14_height=3.4175_2021-10-06_17-19-55':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565997.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00015_15_height=58.024_2021-10-06_17-19-57':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633565998.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00016_16_height=31.041_2021-10-06_17-19-58':
checkpoint_000010  events.out.tfevents.1633566003.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00017_17_height=22.414_2021-10-06_17-20-03':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633566013.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00018_18_height=14.677_2021-10-06_17-20-13':
checkpoint_000002  checkpoint_000004  checkpoint_000006  checkpoint_000008  checkpoint_000010  events.out.tfevents.1633566014.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json

'Trainer_379de_00019_19_height=7.5963_2021-10-06_17-20-14':
checkpoint_000010  events.out.tfevents.1633566014.ip-172-31-21-41  params.json  params.pkl  progress.csv  result.json
```

### Reproduction script

cluster.yaml
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: basic

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 1
initial_workers: 1
max_workers: 1
autoscaling_mode: aggressive

target_utilization_fraction: 0.9

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 20

docker:
    image: "rayproject/ray:nightly-cpu" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    # image: "rayproject/ray:1.5.0-cpu"
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
#    run_options: []  # Extra options to pass into "docker run"

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a
    # cache_stopped_nodes: False

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
    ssh_private_key: ~/Documents/aws_secrets/xwjiang-test.pem
head_node:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    KeyName: xwjiang-test
    # InstanceMarketOptions:
    #     MarketType: spot
           # SpotOptions:
           #     MaxPrice: "9.0"


worker_nodes:
    InstanceType: m5.xlarge
    ImageId: latest_dlami
    KeyName: xwjiang-test
    # # Run workers on spot by default. Comment this out to use on-demand.
    # InstanceMarketOptions:
    #     MarketType: spot
        # SpotOptions:
        #     MaxPrice: "9.0"
    IamInstanceProfile:
        Arn: arn:aws:iam::959243851260:instance-profile/ray-autoscaler-v1

file_mounts: {
    # /home/ray/anaconda3/lib/python3.7/site-packages/ray/tune: /Users/xwjiang/ray/python/ray/tune,
}

initialization_commands: []
setup_commands:
  # - apt-get update
  # - apt-get -q -yy install curl
  # - pip install pytest
  - pip install ipdb
  # - pip uninstall -y numpy ray || true
  # - sudo rm -rf /home/ray/anaconda3/lib/python3.7/site-packages/numpy
  # - pip install xgboost_ray[default]
  # - pip install petastorm
  # - pip install tblib
  # - pip install torch
  # - pip install torchvision
  # - pip3 install numpy || true
  # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip install ray[tune]
  # - pip install -U "xgboost_ray[default]" petastorm  # Install latest releases
  # - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
  # - sudo mkdir -p /data || true
  # - sudo chown ray:1000 /data || true
  # - rm -rf data/classification.parquet || true
  # - curl -o create_test_data.py https://raw.githubusercontent.com/ray-project/ray/releases/1.3.0/release/xgboost_tests/create_test_data.py
  # - python ./create_test_data.py data/classification.parquet --seed 1234 --num-rows 1000000 --num-cols 40 --num-partitions 100 --num-classes 2
  # - pip install -U boto3
  # - pip install ipdb # ray[rllib] #torch torchvision
  # - pip install awscli
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []
```

script
```
#!/usr/bin/env python

import argparse
import json
import os

import numpy as np

import ray
from ray import tune
from ray.tune.schedulers import HyperBandScheduler
from ray.tune.trainable import Trainable


# def train(config, checkpoint_dir=None):
#     step = 0
#     if checkpoint_dir:
#         with open(os.path.join(checkpoint_dir, "checkpoint")) as f:
#             step = json.loads(f.read())["timestep"]

#     for timestep in range(step, 10):
#         v = np.tanh(float(timestep) / config.get("width", 1))
#         v *= config.get("height", 1)

#         # Checkpoint the state of the training every 3 steps
#         # Note that this is only required for certain schedulers
#         # if timestep % 3 == 0:
#         with tune.checkpoint_dir(step=timestep) as checkpoint_dir:
#             path = os.path.join(checkpoint_dir, "checkpoint")
#             with open(path, "w") as f:
#                 f.write(json.dumps({"timestep": timestep}))

#         # Here we use `episode_reward_mean`, but you can also report other
#         # objectives such as loss or accuracy.
#         tune.report(episode_reward_mean=v)


class Trainer(Trainable):
    def setup(self, config):
        """config is dict type config defined for tune.run api"""
        self.v = np.tanh(float(self.iteration) / config.get("width", 1))
        self.config = config
        print("calling setup")

    def step(self):
        print("training for one epoch")
        self.v *= self.config.get("height", 1)
        return {
            "episode_reward_mean": self.v,
        }

    def save_checkpoint(self, checkpoint_dir):
        """ray tune requires to save model within checkpoint_dir"""
        checkpoint_path = os.path.join(checkpoint_dir,
                                       "checkpoint-{}".format(self.iteration))
        with open(checkpoint_path, "w") as f:
            f.write(json.dumps({"timestep": self.iteration}))
        print("i just saved stuff here! {}".format(checkpoint_path))
        return checkpoint_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--smoke-test", action="store_true", help="Finish quickly for testing")
    parser.add_argument(
        "--server-address",
        type=str,
        default=None,
        required=False,
        help="The address of server to connect to if using "
        "Ray Client.")
    args, _ = parser.parse_known_args()
    ray.init(address="auto")

    # Hyperband early stopping, configured with `episode_reward_mean` as the
    # objective and `training_iteration` as the time unit,
    # which is automatically filled by Tune.
    # hyperband = HyperBandScheduler(max_t=200)

    analysis = tune.run(
        Trainer,
        sync_config=tune.SyncConfig(
            sync_to_driver=True,
        ),
        stop={"training_iteration": 10},
        name="hyperband_test",
        checkpoint_freq=2,
        checkpoint_at_end=True,
        num_samples=20,
        metric="episode_reward_mean",
        mode="max",
        config={"height": tune.uniform(0, 100)},
        keep_checkpoints_num=1,
        local_dir="./tmp-results",
        # scheduler=hyperband,
        fail_fast=True)
    print("Best hyperparameters found were: ", analysis.best_config)

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
