### ISSUE TITLE
[Bug] Autoscaling with TPU VMs doesn't seem to work.

### ISSUE THREAD

**Issue by dirkweissenborn** [ray-project/ray#19461]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I can launch a program with ray on TPU VMs (yay!), however, the autoscaler doesn't seem to work. If I launch the script with min_workers=1 the program starts as exoected, however, if I try to start it with min_workers=0 and max_workers=1 it doesn't. The resource demand keeps pending. Is that expected behavior?

My problem with this is that TPU nodes shouldn't be idling when the job is done.

### Versions / Dependencies

ray 1.7
python 3.8

### Reproduction script

Works:
```
max_workers: 8

available_node_types:
  ...
    tpu:
        min_workers: 1
        resources: {"TPU": 1}  # use TPU custom resource in your code
        node_config:
            acceleratorType: v3-8
            runtimeVersion: v2-alpha
        
```

Doesn't work:
```
max_workers: 8

available_node_types:
  ...
    tpu:
        min_workers: 0
        max_workers: 1
        resources: {"TPU": 1}  # use TPU custom resource in your code
        node_config:
            acceleratorType: v3-8
            runtimeVersion: v2-alpha
        
```

Removing min_worker all together doesn't work either:

```
max_workers: 8

available_node_types:
  ...
    tpu:
        resources: {"TPU": 1}  # use TPU custom resource in your code
        node_config:
            acceleratorType: v3-8
            runtimeVersion: v2-alpha
        
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
