### ISSUE TITLE
[Bug] ray exec --tmux --stop doesn't work.

### ISSUE THREAD

**Issue by dirkweissenborn** [ray-project/ray#19504]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

I am trying to run a job on a cluster using the `--tmux` flag so I can savely shutdown my machine. At the same time I would like the cluster to shutdown after the command is finished. However, this doesn't seem to work:

```
Error: Command failed:

[...] bash --login -c -i 'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (tmux new -d bash -c '"'"'python -c '"'"'"'"'"'"'"'"'import time; time.sleep(60)'"'"'"'"'"'"'"'"'; ray stop; ray teardown ~/ray_bootstrap_config.yaml --yes --workers-only; exec bash'"'"'; sudo shutdown -h now)'
```

### Versions / Dependencies

ray 1.7
python3.8

### Reproduction script

`ray exec test.yaml --start --stop --tmux "python -c 'import time; time.sleep(60)'" `

test.yaml:
```
# Ray cluster config: https://docs.ray.io/en/latest/cluster/config.html#cluster-config

# A unique identifier for the head node and workers of this cluster.
cluster_name: test-cluster

# The maximum number of worker nodes to launch in addition to the head
# node.
max_workers: 7

available_node_types:
    ray_head_default:
        resources: {"CPU": 2}
        node_config:
            machineType: n1-standard-2
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 50
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cpu

provider:
    type: gcp
    region: us-central1
    availability_zone: us-central1-a
    project_id: ********** # replace with your GCP project id

head_node_type: ray_head_default
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
