### ISSUE TITLE
[Bug] autoscaler doesn't shutdown workers after calling request_resources

### ISSUE THREAD

**Issue by mattearllongshot** [ray-project/ray#19785]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

*What happens*: After calling `request_resources` an appropriate number of worker nodes are spun up (expected), however, they never scale down, even if they are unused. 

I observe the following in monitor.log even after reaching 3k CPU:
```
Demands:
 {'CPU': 1}: 3000+ from request_resources()
```

*Expectation*:  Unused workers are shut down.

The old behaviour (ray 1.0.0 and possibly later) used to clear the resource request when the running resources exceeded the request amount, so that the request only lasts until the cluster has scaled up.

### Versions / Dependencies

`ray==1.6.0`

### Reproduction script

Boot a cluster, call `request_resources(n)` where n is greater than the head node resources, wait for the workers to boot, observe that the workers are never shutdown, even after the idle timeout elapses.

### Anything else

I believe this functionality was removed as part of this PR: https://github.com/ray-project/ray/pull/11802/files#diff-32ec34dc41fb43d2614e8bc5a857aac8f9bdca6a985df52fc7f207d62e5cb162L161-L163  (search for `if len(nodes) >= target_workers` in autoscaler.py)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by markgoodhead** [comment]
We are considering making a PR to address this - @DmitriGekhtman @richardliaw any advice on this / would this be accepted into the main repo?

**Comment by DmitriGekhtman** [comment]
This is the expected behavior of the API.

https://docs.ray.io/en/latest/cluster/sdk.html

"This request is persistent until another call to request_resources() is made to override."

I agree that's confusing -- I will update the docs to make this more prominent and explain the implication for downscaling.

**Comment by markgoodhead** [comment]
OK - is there a standard way to recreate the old behaviour? i.e. if I request 3k cores, then immediately request 0k cores, will that still bring up 3k cores? Ideally we want a way to guarantee 3k cores are created, but once that's done we want the autoscaler to take over for downscaling purposes as our job(s) finish.

**Comment by DmitriGekhtman** [comment]
Depending on your workload, you may also be able to achieve the desired effect by setting `upscaling_speed` in the autoscaling config to a very high number -- this will prevent the autoscaler from rate limiting node launch triggered by task and actor resource demands.

Using placement groups in place of autoscaler.sdk.request_resources is also an option. (You'd delete the placement group after the relevant tasks and actors for your workload are scheduled.)

**Comment by markgoodhead** [comment]
OK, is there a programmatic way to wait for the scale up? We're running a batch job which happens automatically so no one is there to manually monitor the scaling up. 

Ideally there'd be some way to tell that the appropriate amount of resource was being started (although not necessarily ready yet - often clusters start in a staggered way and we'd like our job to start running on them as soon as the first one comes up for efficiency reasons) so we can do some workaround like:

`request_resources(num_cpus=3000) 
block_until_resources_started(num_cpus=3000)
request_resources(num_cpus=0)
our_ray_job()`

Would you also consider us adding the old behaviour as a toggleable flag to the request_resources() function?

**Comment by DmitriGekhtman** [comment]
> is there a programmatic way to wait for the scale up

Check out https://docs.ray.io/en/latest/advanced.html#resource-information

> Would you also consider us adding the old behaviour as a toggleable flag to the request_resources() function?

Great idea!

**Comment by DmitriGekhtman** [comment]
cc @edoakes -- I think this discussion touches the concept of "jobs"

**Comment by DmitriGekhtman** [comment]
Can you say more about your use-case?
Would it make sense to have application-level logic that detects when the job is done and then signals that scale-down is allowed?

**Comment by markgoodhead** [comment]
Sure @DmitriGekhtman - essentially we have a batch job of N sub-jobs where each sub-job uses one CPU resource (where N is of the order of a few thousand) and each sub-job takes between 5 and 30 mins. 

Once we start the Ray head node, we want to immediately scale up to a cluster of N cpus and start our batch job at essentially the same time we call request_resources. That way, as the worker nodes come online they are immediately allocated as many sub-jobs as they can take. As the sub-jobs take different lengths to run, often some worker nodes finish all their tasks first and are sat there idle. At that point, we want the normal autoscaler to take over and turn those workers off to save on cost, otherwise towards the end of the job we end up with a large cluster (thousands of cpus) with only a handful of worker nodes active running the very longest sub-jobs.

This is where the old request_resources behaviour was perfect because you could just run a script like
`request_resources(cpus=N)
big_batch_job(sub_jobs=N) 
shutdown()`

And know it'd be essentially as efficient as possible with regards to worker node utilisation (workers are immediately saturated on startup, and scale down once there are no more tasks which can run on it).

FYI we have started work on the feature we discussed (a flag to control the behaviour) and hope to have a draft PR to share soon.

Out of curiosity, what is the use case for the new behaviour? When do users want to keep the resources up even if they aren't being utilised? I ask because we were wondering what behaviour to make as the 'default' - the pre-1.6.0 behaviour or the post. Of course our use case feels very common/normal to us but I assume there's other ones I'm missing!

**Comment by DmitriGekhtman** [comment]
Would each sub-job trigger autoscaling on its own?

If so, then to guarantee un-throttled upscaling, you could set upscaling_speed=99999 in the autoscaling config.

**Comment by markgoodhead** [comment]
>Would each sub-job trigger autoscaling on its own?
What do you mean by this? We are relying entirely on request_resources() for the scaling up, and just need the autoscaler for scaling down

>If so, then to guarantee un-throttled upscaling, you could set upscaling_speed=99999 in the autoscaling config.
We'll give this a go - am I right in thinking with the new autoscaling logic that if the scheduler has 3k tasks outstanding then 3k cores will be provisioned immediately?

**Comment by DmitriGekhtman** [comment]
That's correct -- if a very large upscaling speed is set, cores should be provisioned about as quickly as if request resources were used.

@wuisawesome would you say that's accurate?

**Comment by markgoodhead** [comment]
What are the reasons (if any) why having `upscaling_speed=99999` as the default for our clusters might be a bad idea? Perhaps if there's 3k tasks but they each take 1 millisecond to finish? I'm wondering if we should just use this as our base cluster setting as I think every ray task we ever run is significant enough that we may as well always start extra worker resource to work on it if it isn't already available.

**Comment by wuisawesome** [comment]
Seems like we're all converging on using upscaling speed (which I'm supportive of). Yeah, the bad case for `upscaling_speed=inf` is if task time << node startup time. Of course, note that if you increase this number, you'll want to set your max_workers appropriately.

**Comment by SlowShip** [comment]
I've just ran a few tests with `upscaling_speed: 99999`, it's a bit too conservative for our use case.

Requesting 10,000 tasks each taking up 1 CPU (using `@ray.remote(num_cpus=1)`)

```yaml
max_workers: 64
min_workers: 0
upscaling_speed: 99999
```
Head node has `resources: {"CPU": 8}` and workers have `resources: {"CPU": 47}`

`ray submit` output
```
...
(scheduler +4s) Adding 5 nodes of type ray.worker.default.
(scheduler +1m15s) Resized to 102 CPUs.
(scheduler +1m20s) Resized to 243 CPUs.
(scheduler +1m26s) Adding 1 nodes of type ray.worker.default.
(scheduler +2m4s) Adding 21 nodes of type ray.worker.default.
(scheduler +2m40s) Resized to 290 CPUs.
(scheduler +3m15s) Resized to 384 CPUs.
(scheduler +3m20s) Resized to 995 CPUs.
(scheduler +3m26s) Resized to 1277 CPUs.
(scheduler +3m38s) Adding 22 nodes of type ray.worker.default.
(scheduler +4m51s) Resized to 1606 CPUs.
(scheduler +4m57s) Resized to 2264 CPUs.
(scheduler +5m3s) Resized to 2311 CPUs.
(scheduler +5m9s) Adding 15 nodes of type ray.worker.default.
...
```
You can see it takes 5 minutes to try and scale to the max workers, even though the number of resources we're using exceeds that. We really want it to instantly scale to have enough cpus for all our tasks (or max_workers if thats lower), then to scale down gracefully as our tasks finish.

**Comment by SlowShip** [comment]
More context:

Ray version: 1.9.2

Running 
```
ray up -y cluster.yaml
ray submit cluster.yaml test.py
```


```yaml
---
# cluster.yaml
auth:
  ssh_private_key: ~/.ssh/our_key
  ssh_user: user
available_node_types:
  ray.head.default:
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize: 30
          VolumeType: gp2
      IamInstanceProfile:
        Arn: XXXXXXXXXX
      ImageId: XXXXXXXXXX
      InstanceType: m5.2xlarge
      KeyName: worker
      SecurityGroupIds:
      - XXXXXXXXXX
      SubnetIds:
      - XXXXXXXXXX
    resources: {"CPU": 8}
  ray.worker.default:
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize: 30
          VolumeType: gp2
      IamInstanceProfile:
        Arn: XXXXXXXXXX
      ImageId: XXXXXXXXXX
      InstanceMarketOptions:
        MarketType: spot
      InstanceType: c5a.12xlarge
      KeyName: worker
      SecurityGroupIds:
      - XXXXXXXXXX
      SubnetIds:
      - XXXXXXXXXX
    resources: {"CPU": 47}
cluster_name: some-cluster
head_node_type: ray.head.default
idle_timeout_minutes: 1
max_workers: 64
min_workers: 0
provider:
  availability_zone: eu-west-1c
  cache_stopped_nodes: false
  region: eu-west-1
  type: aws
  use_internal_ips: true
setup_commands:
- python3 -m pip uninstall ray
- python3 -m pip install ray[default]
upscaling_speed: 99999
```

```python
# test.py
from collections import Counter
import ray
import socket
import time

ray.init(address='auto')

@ray.remote(num_cpus=1)
def f():
    time.sleep(120)
    return socket.gethostbyname(socket.gethostname())

object_ids = [f.remote() for _ in range(10000)]
ip_addresses = ray.get(object_ids)
print(Counter(ip_addresses))
```
