### ISSUE TITLE
[Bug] Ray autoscaler doesn't respect namespace for TPU VMs.

### ISSUE THREAD

**Issue by dirkweissenborn** [ray-project/ray#20286]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Cluster names are not respected when launching 2 different clusters. The workers of the first cluster just get a deletion command once the new cluster starts.

### Versions / Dependencies

ray 1.8.0

### Reproduction script

```
ray up -n cluster1 tpu.yaml

ray up -n cluster2 tpu.yaml

ray monitor -n cluster2 tpu.yaml

```

This leads to the following output for cluster2 monitor:

```
2021-11-12 16:44:21,863	INFO autoscaler.py:942 -- Creating new (spawn_updater) updater thread for node projects/inceptive-compute/locations/us-central1-b/nodes/ray-cluster1-worker-97af1f23-tpu.
...
2021-11-12 16:44:27,175	INFO updater.py:296 -- New status: waiting-for-ssh
2021-11-12 16:44:27,185	INFO updater.py:241 -- [1/7] Waiting for SSH to become available
2021-11-12 16:44:27,185	INFO updater.py:244 -- Running `uptime` as a test.
2021-11-12 16:44:27,339	INFO command_runner.py:357 -- Fetched IP: 10.128.0.91
2021-11-12 16:44:27,339	INFO log_timer.py:27 -- NodeUpdater: projects/***/locations/us-central1-b/nodes/ray-cluster1-worker-97af1f23-tpu: Got IP  [LogTimer=0ms]
```

Why is cluster 2 using the worker of cluster 1 here?! These commands actually lead to the VM shutting down, and both clusters failing. This makes it impossible to use TPU VMs with more than 1 cluster right now.

**tpu.yaml**

```
# This config is an example TPU config allowing you to run
# https://github.com/Yard1/swarm-jax on GCP TPUs
# Replace provider.project_id with your GCP project id
# After the nodes are up, run:
#   ray attach tpu.yaml swarm_tpu_jax.py swarm-jax/data/enwik8 [NUM_TPUS] [EPOCHS]

# A unique identifier for the head node and workers of this cluster.
cluster_name: tputest

# The maximum number of worker nodes to launch in addition to the head
# node.
max_workers: 1

available_node_types:
    ray_head_default:
        resources: {"CPU": 2}
        node_config:
            machineType: n1-standard-1
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 50
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cpu
    ray_tpu:
        min_workers: 1
        resources: {"TPU": 1}  # use TPU custom resource in your code
        node_config:
            # Only v2-8 and v3-8 accelerator types are currently supported.
            # Support for TPU pods will be added in the future.
            acceleratorType: v2-8
            runtimeVersion: v2-alpha
            schedulingConfig:
                # Set to false to use non-preemptible TPUs
                preemptible: true

provider:
    type: gcp
    region: us-central1
    availability_zone: us-central1-b
    project_id: ***  # replace with your GCP project id

setup_commands:
  - python -m pip install ray

# Specify the node type of the head node (as configured above).
# TPUs cannot be head nodes (will raise an exception).
head_node_type: ray_head_default

# Compute instances have python 3.7, but TPUs have 3.8 - need to update
# Install Jax and other dependencies on the Compute head node
head_setup_commands: []

# Install Jax and other dependencies on TPU
worker_setup_commands: []

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
