### ISSUE TITLE
[Bug] [Ray Autoscaler] [Core] Ray Worker Node Relaunching during 'ray up'

### ISSUE THREAD

**Issue by michaelzhiluo** [ray-project/ray#20402]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

Ray Autoscaler will relaunch the worker even if the head and worker node are both healthy and their file systems are identical.
This can be replicated by running `ray up` on most Autoscaler configuration files over and over again.

@concretevitamin @ericl 

### Versions / Dependencies

Most recent version of Ray and Ray Autoscaler.

### Reproduction script

Autoscaler Config provided below.  Run `ray up -y config/aws-distributed.yml --no-config-cache` one time and wait (important!) until the worker is fully setup via `ray status`. Rinse and repeat on the same configuration file. Eventually, on one of the runs, the Autoscaler will relaunch the worker node.
```
auth:
  ssh_user: ubuntu
available_node_types:
  ray.head.default:
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 500
      ImageId: ami-04b343a85ab150b2d
      InstanceType: p3.2xlarge
    resources: {}
  ray.worker.default:
    max_workers: 1
    min_workers: 1
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 500
      ImageId: ami-04b343a85ab150b2d
      InstanceType: p3.2xlarge
    resources: {}
cluster_name: temp-aws
docker:
  container_name: ''
  image: ''
  pull_before_run: true
  run_options:
  - --ulimit nofile=65536:65536
  - -p 8008:8008
file_mounts: {}
head_node_type: ray.head.default
head_start_ray_commands:
- ray stop
- ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml
idle_timeout_minutes: 5
initialization_commands: []
max_workers: 1
provider:
  cache_stopped_nodes: true
  region: us-east-2
  type: aws
rsync_exclude:
- '**/.git'
- '**/.git/**'
rsync_filter:
- .gitignore
setup_commands:
- pip3 install ray
- mkdir -p /tmp/workdir && cd /tmp/workdir && pip3 install --upgrade pip && pip3
  install ray[default]
upscaling_speed: 1.0
worker_start_ray_commands:
- ray stop
- ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
