### ISSUE TITLE
[Bug] Tuple Action Space in Behavior Cloning  

### ISSUE THREAD

**Issue by RodgerLuo** [ray-project/ray#20589]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### What happened + What you expected to happen

I’m using this [saving experience example](https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/examples/saving_experiences.py) to collect a dataset for Behavior Cloning (BC) algorithm. The action space of my environment is tuple. After feeding the saved experience into BC, I got the following error:

```
ValueError: The two structures don't have the same nested structure.
 
First structure: type=ndarray str=[[0 1]
[1 0]
[1 0]
[0 0]
[0 1]
[0 0]
[1 0]
[0 1]
[1 0]
[0 0]]
 
Second structure: type=tuple str=(Discrete(2), Discrete(2))
```
This error was trigged by `normalize_action()` at `ray/rllib/utils/spaces/space_utils.py`. 

### Versions / Dependencies

Ray 1.8.0
Python 3.6
MacOS Big Sur

### Reproduction script

An easy way to reproduce the error is to change the CartPole environment into a tuple action space. Specifically, the following steps will reproduce the error mentioned above:

1. Use the following action space
```
        self.action_space = spaces.Tuple((
            spaces.Discrete(2),
            spaces.Discrete(2)
        ))
```
to replace the original action space `self.action_space = spaces.Discrete(2)`

2. Use [saving experience example](https://github.com/ray-project/ray/blob/releases/1.8.0/rllib/examples/saving_experiences.py) to collect a small dataset

3. Use the following config for training:
```
bc-cartpole:
    env: CartPole-TupleAction
    run: BC
    local_dir: "~/workspace/temp"  # directory to store checkpoints
    checkpoint_at_end: False
    stop:
        timesteps_total: 10000
    config:
        # Works for both torch and tf.
        framework: torch
        num_workers: 0
        # actions_in_input_normalized: True
        input: "/home/ubuntu/ray_playground/tuple_action_bc/demo_data"
```

### Anything else

This error happens every time when training with BC on tuple action space environments. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
