### ISSUE TITLE
[RLlib] Moving all Envs to have the c'tor signature

### ISSUE THREAD

**Issue by avnishn** [ray-project/ray#21611]
@sven1977: Should we start making all our example envs' (MultiAgentEnv or others) with the c'tor signature?

e.g. 

```
class env:
    def __init__(self, env_ctx: EnvContext):
        super().__init__()
```

Envs defined like this can more easily be configured in a user's config:

```
config:
    env: HierarchicalWindyMazeEnv  # <- just the class suffices here, no tune.register_env needed!
    env_config:
        # <- c'tor args that go into `env_ctx`
```
