### ISSUE TITLE
DDPG vs DDPG2 Implementations

### ISSUE THREAD

**Issue by andrewztan** [ray-project/ray#2181]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.3
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.4
- **Python version**: 3.6
- **Exact command to reproduce**:

## Comparing two different implementations of DDPG in ray/rllib:
* Impl 1 (open source implementation): https://github.com/ray-project/ray/tree/master/python/ray/rllib/ddpg
* Impl 2 (student implementation): https://github.com/ray-project/ray/tree/master/python/ray/rllib/ddpg2

## Differences in implementation and hyperparameters:      
https://docs.google.com/document/d/18yHw_J3y9SbtdCzLXz5miKm7UD1hZ57y1YEOd-VNN2U/edit?usp=sharing

#### DDPG with smoothing
![pendulum_ddpg-ddpg2_100iter](https://user-images.githubusercontent.com/7733195/41019356-1c27f7d6-6913-11e8-9911-db154494b3f7.png)

#### No smoothing
![pendulum_ddpg-ddpg2_no-smoothing](https://user-images.githubusercontent.com/7733195/41060384-62f3c3ea-6984-11e8-9ec4-2ef0c38053aa.png)

### MountainCarContinuous-v0
![mountaincarcontinuous_ddpg-ddpg2](https://user-images.githubusercontent.com/7733195/40966958-b9ccde1e-6866-11e8-92cd-7250fa4011f3.png)

![mountaincarcontinuous_ddpg-ddpg2_50iter](https://user-images.githubusercontent.com/7733195/41019392-3d427ef0-6913-11e8-9446-bbf43bac1e30.png)

### HalfCheetah-v2
![cheetah_ddpg-ddpg2](https://user-images.githubusercontent.com/7733195/41084414-f9c197d4-69e8-11e8-89f0-9732be67dc91.png)

#### Takeaway: Both implementations are sound, but DDPG offers many more hyperparameters to toggle. DDPG worked for HalfCheetah, but DDPG2 did not.
The hyperparameters used to reproduce the above results are available as .yaml files.

### Comparing hyperparameters used between DDPG and DDPG2 for Pendulum-v0:
```yaml
pendulum-ddpg:
    env: Pendulum-v0
    run: DDPG
    stop:
        episode_reward_mean: -160
        time_total_s: 1200 # 20 minutes
    config:
        # Same parameter, same default values
        actor_lr: 0.0001
        critic_lr: 0.001
        gamma: 0.99
        env_config: {}
        noise_scale: 0.1
        exploration_theta: 0.15
        exploration_sigma: 0.2

        # Same parameter, different values (set to default values of DDPG2)
        num_workers: 1
        timesteps_per_iteration: 600
        tau: 0.001
        buffer_size: 10000
        learning_starts: 500
        clip_rewards: False
        prioritized_replay: False
        train_batch_size: 64

        # Different parameters (different values)
        # === Exploration ===
        schedule_max_timesteps: 100000
        exploration_fraction: 0.1
        exploration_final_eps: 0.02
        target_network_update_freq: 0
        # === Optimization ===
        sample_batch_size: 1
        use_huber: False
        huber_threshold: 1.0
        l2_reg: 0 # original: 1e-6
        random_starts: False # original: True
        num_gpus_per_worker: 0
        optimizer_class: "LocalSyncReplayOptimizer"
        optimizer_config: {}
        per_worker_exploration: False
        worker_side_prioritization: False
        # === Tensorflow ===
        tf_session_args: {
            "device_count": {
                "CPU": 2
            },
            "log_device_placement": False,
            "allow_soft_placement": True,
            "gpu_options": {
                "allow_growth": True
            },
            "inter_op_parallelism_threads": 1,
            "intra_op_parallelism_threads": 1,
        }
        # === Model ===
        actor_hiddens: [64, 64]
        critic_hiddens: [64, 64]
        n_step: 1
        model: {}
        # === Replay Buffer ===
        smoothing_num_episodes: 1
        prioritized_replay_alpha: 0.6
        prioritized_replay_beta: 0.4
        prioritized_replay_eps: 0.000001
```

```yaml
pendulum-ddpg2:
    env: Pendulum-v0
    run: DDPG2
    stop:
        episode_reward_mean: -160
        time_total_s: 1200 # 20 minutes
    config:
        # Same parameter, same default values
        actor_lr: 0.0001
        critic_lr: 0.001
        gamma: 0.99
        env_config: {}
        noise_parameters: {
            "mu": 0,
            "sigma": 0.2,
            "theta": 0.15,
        }

        # Same parameter, different values (set to default values of DDPG2)
        num_workers: 1
        train_steps: 600
        tau: 0.001
        optimizer: {
            "buffer_size": 10000,
            "learning_starts": 500,
            "clip_rewards": False,
            "prioritized_replay": False,
            "train_batch_size": 64,
        }

        # Different parameters (different values)
        horizon: 500
        noise_add: True
        noise_epsilon: 0.0002
        num_local_steps: 1
```    
  
  

### Comparing hyperparameters used between DDPG and DDPG2 for MountainCarContinuous-v0:
```yaml
mountaincarcontinuous-ddpg:
    env: MountainCarContinuous-v0
    run: DDPG
    stop:
        episode_reward_mean: 90
        # time_total_s: 1200 # 20 minutes
    config:
        # Same parameter, same default values
        actor_lr: 0.0001
        critic_lr: 0.001
        gamma: 0.99
        env_config: {}
        noise_scale: 0.75 # original: 0.1
        exploration_theta: 0.15
        exploration_sigma: 0.2

        # Same parameter, different values (set to default values of DDPG2)
        num_workers: 1
        timesteps_per_iteration: 600
        tau: 0.01 # original: 0.001
        buffer_size: 50000
        learning_starts: 1000
        clip_rewards: False
        prioritized_replay: False
        train_batch_size: 64

        # Different parameters (different values)
        # === Exploration ===
        schedule_max_timesteps: 100000
        exploration_fraction: 0.4 # original: 0.1
        exploration_final_eps: 0.02
        target_network_update_freq: 0
        # === Optimization ===
        sample_batch_size: 1
        use_huber: False
        huber_threshold: 1.0
        l2_reg: 0 # original: 1e-6
        random_starts: False # original: True
        num_gpus_per_worker: 0
        optimizer_class: "LocalSyncReplayOptimizer"
        optimizer_config: {}
        per_worker_exploration: False
        worker_side_prioritization: False
        # === Tensorflow ===
        tf_session_args: {
            "device_count": {
                "CPU": 2
            },
            "log_device_placement": False,
            "allow_soft_placement": True,
            "gpu_options": {
                "allow_growth": True
            },
            "inter_op_parallelism_threads": 1,
            "intra_op_parallelism_threads": 1,
        }
        # === Model ===
        actor_hiddens: [32, 64] # original: [64, 64]
        critic_hiddens: [64, 64]
        n_step: 3 # original: 1
        model: {}
        # === Replay Buffer ===
        smoothing_num_episodes: 1
        prioritized_replay_alpha: 0.6
        prioritized_replay_beta: 0.4
        prioritized_replay_eps: 0.000001
```

```yaml
mountaincarcontinuous-ddpg2:
    env: MountainCarContinuous-v0
    run: DDPG2
    stop:
        episode_reward_mean: 90
        # time_total_s: 1200 # 20 minutes
    config:
        # Same parameter, same default values
        actor_lr: 0.0001
        critic_lr: 0.001
        gamma: 0.99
        env_config: {}
        noise_parameters: {
            "mu": 0,
            "sigma": 0.2,
            "theta": 0.15,
        }

        # Same parameter, different values (set to default values of DDPG2)
        num_workers: 1
        train_steps: 600
        tau: 0.01 # original: 0.001
        optimizer: {
            "buffer_size": 50000,
            "learning_starts": 1000,
            "clip_rewards": False,
            "prioritized_replay": False,
            "train_batch_size": 64,
        }

        # Different parameters (different values)
        horizon: 500
        noise_add: True
        noise_epsilon: 0.0002
        num_local_steps: 1
```
