### ISSUE TITLE
[helm] [k8s] Expose Volumes and VolumesMounts to Helm values.yml

### ISSUE THREAD

**Issue by vicyap** [ray-project/ray#21872]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/ray/issues) and found no similar feature requirement.

### Description

I would like to be able to add volumes and volumeMounts to pods launched by the Ray Cluster. For example, these lines (https://github.com/ray-project/ray/blob/ray-1.9.2/deploy/charts/ray/templates/raycluster.yaml#L62-L64) should be configurable from the helm chart values.yml.

This ticket is related to this slack thread: https://ray-distributed.slack.com/archives/CPE2K3UD8/p1642793234013300

Example config with no added volumes
```yaml
podTypes:
    workerType:
        CPU: 1
        memory: 512Mi

        volumes: []
        volumeMounts: []
```

Example config with a persistent claim
```yaml
podTypes:
    workerType:
        CPU: 1
        memory: 512Mi

        volumes:
          - name: nfs
            persistentVolumeClaim:
              claimName: nfs-claim
        volumeMounts:
          - name: nfs
            mountPath: "/nfs"
```
volumes would use https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/#Volume for schema.
volumeMounts would use https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1 for schema.

### Use case

My goal is to use Ray to process multiple files that are hosted over NFS. The worker pods need to be able to access those files.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
