### ISSUE TITLE
[Bug] Hard-coded timeout for get()

### ISSUE THREAD

**Issue by takeshi-yoshimura** [ray-project/ray#21883]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I am testing ray around plasma allocating host memory of 10^3, 10^4,... 10^9 bytes, and the test was stuck on 10^9 (1 GB) with repeated retry messages.

```
2022-01-24 19:04:09,640 DEBUG worker.py:364 -- Internal retry for get [ClientObjectRef(00310a0f0a45af5cffffffffffffffffffffffff0100000002000000)]
```

raylet.out:
```
...
[2022-01-24 17:54:45,890 I 223 223] store_runner.cc:30: Allowing the Plasma store to use up to 4.7744GB of memory.
...
[2022-01-24 18:03:50,253 I 223 223] object_buffer_pool.cc:146: Not enough memory to create requested object 00310a0f0a45af5cffffffffffffffffffffffff0100000002000000, aborting
```

The raylet repeatedly attempts to create objects but it kept failing. The object store had 4GB but it says the memory space is not enough for 1GB memory allocation. Increasing/decreasing the size of object store memory didn't resolve this (the same messages are shown and spill didn't work).

~I also investigated this issue further and found that the above error happened only when I set `@ray.remote(num_gpus=1)` although I didn't touch GPU memory.~ (See my comment below)

I think this is very strange behavior and so I report this here. To be honest, I am new to ray, but do I miss something?

### Versions / Dependencies

OpenShift 4.8 (Red Hat Enterprise Linux release 8.4 (Ootpa)) with CUDA 11.4 and driver 470.82.01.
Tested images: rayproject/ray:1.7.0-py37, rayproject/ray:latest-py37 (1.9.2), rayproject/ray:nightly-py37-cu111 (2.0.0.dev0 on Jan 25).
Each cluster node has 112 CPU cores (Intel(R) Xeon(R) Gold 6258R), 1TiB memory, 4 Tesla V100-PCIE-16GB.
Huge pages are disabled.

My YAML file is like the following (I believe I do nothing special).
```
apiVersion: cluster.ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster-gpu
  namespace: ray-operator-system
spec:
  # The maximum number of workers nodes to launch in addition to the head node.
  maxWorkers: 1
  upscalingSpeed: 0
  idleTimeoutMinutes: 99999
  headPodType: head-node
  podTypes:
  - name: head-node
    # Minimum number of Ray workers of this Pod type.
    minWorkers: 0
    # Maximum number of Ray workers of this Pod type. Takes precedence over minWorkers.
    maxWorkers: 0
    rayResources: {"GPU": 0}
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        # Automatically generates a name for the pod with this prefix.
        generateName: head-
      spec:
        restartPolicy: Never
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        containers:
        - name: ray-node
          imagePullPolicy: Always
          image: rayproject/ray:1.7.0-py37
          command: ["/bin/bash", "-c", "--"]
          args: ['trap : TERM INT; sleep infinity & wait;']
          ports:
          - containerPort: 6379  # Redis port
          - containerPort: 10001  # Used by Ray Client
          - containerPort: 8265  # Used by Ray Dashboard

          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          resources:
            requests:
              cpu: "1"
              memory: "16G"
              nvidia.com/gpu: "0"
            limits:
              cpu: "1"
              memory: "16G"
              nvidia.com/gpu: "0"
  - name: worker-node
    minWorkers: 1
    maxWorkers: 1
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        generateName: worker-
      spec:
        restartPolicy: Never
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        containers:
        - name: ray-node
          imagePullPolicy: Always
          image: rayproject/ray:1.7.0-py37
          command: ["/bin/bash", "-c", "--"]
          args: ["trap : TERM INT; sleep infinity & wait;"]
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          resources:
            requests:
              cpu: "8"
              memory: "16G"
              nvidia.com/gpu: "1"
            limits:
              cpu: "8"
              memory: "16G"
              nvidia.com/gpu: "1"
  headStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --head --no-monitor --dashboard-host 0.0.0.0
  workerStartRayCommands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379

```

### Reproduction script

```
#!/usr/bin/env python
import time, ray
@ray.remote(num_gpus=1)
def gimme_object(size):
  return ray.put(bytearray(10**size))
ray.init("ray://localhost:10001", logging_level="DEBUG")
for size in range(3,10):
  time_start = time.time()
  task = gimme_object.remote(size)
  objref = ray.get(task)
  time_pull = time.time()-time_start
  print(f"took {time_pull:.3f}s for remote to put data with size={10**size} into plasma")
  time_start = time.time()
  obj = ray.get(objref)
  time_pull = time.time()-time_start
  print(f"took {time_pull:.3f}s to pull object from plasma with size={len(obj)} bytes")
  time.sleep(1)
```

### Anything else

Logs: [logs.tar.gz](https://github.com/ray-project/ray/files/7938321/logs.tar.gz)

ray memory (Note: 10.130.4.94 is the head node's IP):
```
======== Object references status: 2022-01-24 18:56:45.340288 ========
Grouping by node address...        Sorting by object size...        Display allentries per group...


--- Summary for node address: 10.130.4.94 ---
Mem Used by Objects  Local References  Pinned        Pending Tasks  Captured in Objects  Actor Handles
1000000969.0 B       4, (1000000969.0 B)  0, (0.0 B)    0, (0.0 B)     0, (0.0 B)           0, (0.0 B)   

--- Object references for node address: 10.130.4.94 ---
IP Address       PID    Type    Call Site               Size    Reference Type      Object Ref                                              
10.130.4.94      615    Driver  disabled                86.0 B  LOCAL_REFERENCE     00ffffffffffffffffffffffffffffffffffffff0100000001000000

10.130.4.94      615    Driver  disabled                264.0 B  LOCAL_REFERENCE     16310a0f0a45af5cffffffffffffffffffffffff0100000001000000

10.130.4.94      615    Driver  disabled                600.0 B  LOCAL_REFERENCE     00ffffffffffffffffffffffffffffffffffffff0100000002000000

10.130.4.94      615    Driver  <unknown>               1000000019.0 B  LOCAL_REFERENCE     00310a0f0a45af5cffffffffffffffffffffffff0100000002000000

To record callsite information for each ObjectRef created, set env variable RAY_record_ref_creation_sites=1

--- Aggregate object store stats across all nodes ---
Plasma memory usage 953 MiB, 3 objects, 10.47% full, 10.47% needed
Objects consumed by Ray tasks: 0 MiB.
```

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!
