### ISSUE TITLE
[Bug] raylet SIGSEGV

### ISSUE THREAD

**Issue by newmanwang** [ray-project/ray#22377]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

raylet at worker node crashed with SIGSEGV signal

```
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317: *** SIGSEGV received at time=1644724000 on cpu 5 *** 
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317: PC: @     0x5581e30bd2e6  (unknown)  google::protobuf::MessageLite::ParseFromZeroCopyStream()
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x7fcb2713d980       1504  (unknown)
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x5581e29943e1        256  grpc::GenericDeserialize<>()
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x5581e299f383         96  grpc::ServerInterface::PayloadAsyncRequest<>::FinalizeResult()
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x5581e2ce716a         64  grpc::CompletionQueue::AsyncNextInternal()
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x5581e2bc03c4        160  ray::rpc::GrpcServer::PollEventsFromCompletionQueue()
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @     0x5581e311d060  (unknown)  execute_native_thread_routine 
[2022-02-13 11:46:40,549 E 149 189] logging.cc:317:     @ ... and at least 3 more frames
```

### Versions / Dependencies

ray 1.10.0

### Reproduction script

Have no idea how to reproduce

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rkooo567** [comment]
Hmm this seems like it is coming from gRPC. Do you have any special setup in your cluster?

**Comment by newmanwang** [comment]
I follow the "Local On Premise Cluster (List of nodes)" setup procedure, nothing special, most of the time it works just fine.

ray 1.10.0 in image xxxx.com/xxx/ray:1.10.0

here is the ray.yaml
```
cluster_name: default

docker:
    image: "xxxx.com/xxx/ray:1.10.0" # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    container_name: "ray_container"
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536
        - --shm-size=5gb
        # ray的ssh远程执行命令不能容忍warning，ray的docker image的Locale和节点上的不一样，导致ssh远程执行命令报locale不一致。这里让head node docker的locale使用普通节点常用
的en_US.utf-8
        - --env=LC_ALL=en_US.UTF-8
        - --env=LANG=en_US.UTF-8
        - --env=TZ=Asia/Shanghai
        - -v /home/ray/work:/tmp
        - -v /home/ray/logs:/logs
        - -v /mnt/ray_train:/data
        - -v /mnt/ray_train/train/envs:/home/ray/anaconda3/envs


provider:
    type: local
    head_ip: 192.168.10.128
   
    worker_ips: [192.168.10.191, 192.168.10.202, 192.168.11.20, 192.168.11.21, 192.168.11.22, 192.168.11.23, 192.168.11.24, 192.168.11.25, 192.168.11.26, 192.168.11.27]
  

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: root
    # You can comment out `ssh_private_key` if the following machines don't need a private key for SSH access to the Ray
    # cluster:
    #   (1) The machine on which `ray up` is executed.
    #   (2) The head node of the Ray cluster.
    #
    # The machine that runs ray up executes SSH commands to set up the Ray head node. The Ray head node subsequently
    # executes SSH commands to set up the Ray worker nodes. When you run ray up, ssh credentials sitting on the ray up
    # machine are copied to the head node -- internally, the ssh key is added to the list of file mounts to rsync to head node.
    ssh_private_key: ~/.ssh/id_rsa

min_workers: 10

max_workers: 10

upscaling_speed: 1.0

idle_timeout_minutes: 0.5


file_mounts: {
}

cluster_synced_files: []


file_mounts_sync_continuously: False

rsync_exclude:
    - "**/.git"
    - "**/.git/**"


rsync_filter:
    - ".gitignore"


initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands: []
    # If we have e.g. conda dependencies stored in "/path1/on/local/machine/environment.yaml", we can prepare the
    # work environment on each worker by:
    #   1. making sure each worker has access to this file i.e. see the `file_mounts` section
    #   2. adding a command here that creates a new conda environment on each node or if the environment already exists,
    #     it updates it:
    #      conda env create -q -n my_venv -f /path1/on/local/machine/environment.yaml || conda env update -q -n my_venv -f /path1/on/local/machine/environment.yaml
    #
    # Ray developers:
    # you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # To run the nightly version of ray (as opposed to the latest), either use a rayproject docker image
    # that has the "nightly" (e.g. "rayproject/ray-ml:nightly-gpu") or uncomment the following line:
    # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
  # If we have e.g. conda dependencies, we could create on each node a conda environment (see `setup_commands` section).
  # In that case we'd have to activate that env on each node before running `ray`:
  # - conda activate my_venv && ray stop
  # - conda activate my_venv && ulimit -c unlimited && ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
    - conda activate ray && ray stop
  #  - conda activate ray && ulimit -c unlimited && RAY_BACKEND_LOG_LEVEL=debug ray start --verbose --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml  --dashboard-host 0.0.0.0 --num-cpus 0 --include-dashboard true --object-store-memory=4294967296
    - conda activate ray && ulimit -c unlimited && ray start --verbose --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml  --dashboard-host 0.0.0.0 --num-cpus 0 --include-dashboard true --object-store-memory=4294967296

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  # If we have e.g. conda dependencies, we could create on each node a conda environment (see `setup_commands` section).
  # In that case we'd have to activate that env on each node before running `ray`:
  # - conda activate my_venv && ray stop
  # - ray start --address=$RAY_HEAD_IP:6379
    - conda activate ray && ray stop
  #  - conda activate ray && RAY_BACKEND_LOG_LEVEL=debug ray start --address=$RAY_HEAD_IP:6379 --object-store-memory=4294967296
    - conda activate ray && ray start --address=$RAY_HEAD_IP:6379 --object-store-memory=4294967296
```
