### ISSUE TITLE
Only show defaults in serve info (?)

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#23020]
This is really verbose, should we only include things that we set to non-defaults?
```
(base) C02X23BRJHD3:serve eoakes$ serve info
deployments:
- autoscaling_config: null
  graceful_shutdown_timeout_s: 20.0
  graceful_shutdown_wait_loop_s: 2.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  import_path: my_file.Echo
  init_args:
  - eoakes
  init_kwargs: {}
  max_concurrent_queries: 100
  name: echo
  num_replicas: 1
  ray_actor_options:
    accelerator_type: null
    memory: 0.0
    num_cpus: 1.0
    num_gpus: 0.0
    object_store_memory: 0.0
    resources: {}
    runtime_env: {}
  route_prefix: /
  user_config: null
```
