### ISSUE TITLE
[autoscaler][Bug] You can connect to cluster even if head setup fails

### ISSUE THREAD

**Issue by bveeramani** [ray-project/ray#23154]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### Issue Severity

Low: It annoys or frustrates me for a moment.

### What happened + What you expected to happen

I launched a cluster and the setup commands failed. I expected to be unable to connect to the head node, but I could.

### Versions / Dependencies

**Python**: 3.8.12
**OS**: macOS
**Ray**: 1.10

### Reproduction script

Create a cluster configuration `config.yaml`.
```
cluster_name: my-cluster

provider:
    type: aws
    region: us-west-2

auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/id

available_node_types:
    ray.head.default:
        node_config:
            KeyName: my-key-pair
            InstanceType: p3.8xlarge
            ImageId: latest_dlami
    ray.worker.default:
        node_config:
            KeyName: my-key-pair
            InstanceType: p3.8xlarge
            ImageId: latest_dlami

head_node_type: ray.head.default

setup_commands:
    - fail
```

Launch the cluster.
```
ray up config.yaml
```

Setup commands will fail.
```
...
  [6/7] Running setup commands
    (0/3) fail

Command 'fail' not found, did you mean:

  command 'tail' from deb coreutils
  command 'mail' from deb mailutils
  command 'qail' from deb qmail
  command 'fal' from deb dnet-progs
  command 'fai' from deb fai-client
  command 'sail' from deb bsdgames

Try: sudo apt install <deb name>

Shared connection to 34.222.95.50 closed.
  New status: update-failed
  !!!
  SSH command failed.
  !!!
  
  Failed to setup head node.
```

You should be able to still connect to the cluster.
```
ray attach config.yaml
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
