### ISSUE TITLE
[autoscaler] GCP worker nodes get prematurely terminated as idle

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#2340]
### System information
- OS Platform and Distribution: Linux Ubuntu 16.04
- Ray installed from (source or binary): source
- Ray version: 0.4.0 (@[6bf48f47bcf91610db42b350e8149c85e01afb0d](https://github.com/ray-project/ray/tree/6bf48f47bcf91610db42b350e8149c85e01afb0d))
- Python version: Python 3.6.5
- Exact command to reproduce:

### Describe the problem
I'm running an experiment script using GCP autoscaler. All the worker nodes (but not the head node) running the trials are shut down as idle after about the `idle_timeout_minutes` (as specified in the autoscaler config) minutes, even though they should continue running the trials.

I haven't yet tried reproducing this on AWS, so it's possible that this is just GCP problem or it could happen on AWS as well.

I'm happy to submit a PR to fix the issue if someone could point me to a right direction with this. The logs indicate that the nodes are terminated because they are idle, meaning that the `last_used[node_ip] < horizon` [here](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/autoscaler.py#L370). Does anyone have an idea why the `last_used` doesn't get correctly updated?

### Source code / logs

Here are few consecutive status logs from the ray process:

All runners still running:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 204 s, 10 ts, -2.06 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 221 s, 11 ts, -5.56 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 120 s, 5 ts, -5.07 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 119 s, 5 ts, -15.9 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 119 s, 6 ts, 7.13 acc
 ```

`runner_3`s last report:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 222 s, 11 ts, 7.74 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 221 s, 11 ts, -5.56 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 120 s, 5 ts, -5.07 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 135 s, 7 ts, -9.27 acc
```

`runner_2`s last report:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 222 s, 11 ts, 7.74 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 239 s, 12 ts, 0.317 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 139 s, 6 ts, -1.34 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 135 s, 7 ts, -9.27 acc
```

```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 257 s, 13 ts, 5.64 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 239 s, 12 ts, 0.317 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 139 s, 6 ts, -1.34 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 151 s, 8 ts, -3.18 acc
```

`runner_4`s last report:
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 257 s, 13 ts, 5.64 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 274 s, 14 ts, -2.64 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 139 s, 6 ts, -1.34 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 151 s, 8 ts, -3.18 acc
```

`runner_0` and `runner_1` keep running normally (on the head node):
```
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/48 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 275 s, 14 ts, 0.906 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 292 s, 15 ts, 6.85 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 139 s, 6 ts, -1.34 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 151 s, 8 ts, -3.18 acc

...

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 40/16 CPUs, 0/0 GPUs
Result logdir: /home/ubuntu/ray_results/swimmer-rllab/default/20180702-ray-idle-test-1
RUNNING trials:
 - mujoco-runner_0_seed=1:	RUNNING [pid=3034], 559 s, 30 ts, 2.15 acc
 - mujoco-runner_1_seed=2:	RUNNING [pid=3045], 573 s, 31 ts, 14.8 acc
 - mujoco-runner_2_seed=3:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2787], 139 s, 6 ts, -1.34 acc
 - mujoco-runner_3_seed=4:	RUNNING [ray-sac-mujoco-worker-86c72356 pid=2777], 138 s, 6 ts, 6.71 acc
 - mujoco-runner_4_seed=5:	RUNNING [ray-sac-mujoco-worker-6b57b3f7 pid=2727], 151 s, 8 ts, -3.18 acc
```

And the logs from the autoscaler clearly state that they were terminated due to idleness:
```

==> /tmp/raylogs/monitor-2018-07-03_03-21-21-07915.out <==
StandardAutoscaler [2018-07-03 03:29:19.812311]: 3/2 target nodes
 - NodeIdleSeconds: Min=0 Mean=34 Max=61
 - NumNodesConnected: 4
 - NumNodesUsed: 1.0
 - ResourceUsage: 16.0/64.0 CPU, 0.0/0.0 GPU
StandardAutoscaler: Terminating idle node: ray-sac-mujoco-worker-6b57b3f7

==> /tmp/raylogs/monitor-2018-07-03_03-21-21-07915.err <==
INFO:googleapiclient.discovery:URL being requested: DELETE https://www.googleapis.com/compute/v1/projects/sac-ray-test/zones/us-west1-a/instances/ray-sac-mujoco-worker-6b57b3f7?alt=json

...

==> /tmp/raylogs/monitor-2018-07-03_03-21-21-07915.out <==
Done.
StandardAutoscaler: Terminating idle node: ray-sac-mujoco-worker-86c72356

==> /tmp/raylogs/monitor-2018-07-03_03-21-21-07915.err <==
INFO:googleapiclient.discovery:URL being requested: DELETE https://www.googleapis.com/compute/v1/projects/sac-ray-test/zones/us-west1-a/instances/ray-sac-mujoco-worker-86c72356?alt=json
```

**Comment by hartikainen** [comment]
Looking at this a bit more closely, I think it's possible that the processes die in the workers, and that's why they are considered idle. I don't have timestamps for those logs so it's hard to say if they stop reporting because the nose is terminated, or vice versa. If this is the case, I'm still not sure why the status logs wouldn't change from `RUNNING` to something else, and why would all the workers behave differently from the head.

I'll post another set of logs that include timestamps tomorrow.

**Comment by hartikainen** [comment]
Just ran the following example, and the same thing keeps happening:
```python
import ray
from ray import tune


def my_func(config, reporter):  # add the reporter parameter
    import time, numpy as np
    i = 0
    while True:
        reporter(timesteps_total=i, mean_accuracy=i ** config['alpha'])
        i += config['beta']
        time.sleep(0.01)


tune.register_trainable('my_func', my_func)
ray.init(redis_address=ray.services.get_node_ip_address() + ':6379')
# ray.init()


tune.run_experiments({
    'my_experiment': {
        'run': 'my_func',
        'trial_resources': {'cpu':8},
        'stop': { 'mean_accuracy': 100 },
        'config': {
            'alpha': tune.grid_search([0.0, 0.2, 0.4, 0.6, 0.8, 1.0]),
            'beta': tune.grid_search([2]),
        },
        'local_dir': '~/ray_results',
    }
})
```

Here's my autoscaler config:
```yaml
cluster_name: sac-mujoco

min_workers: 0
max_workers: 100

docker:
    image: ""
    container_name: "" # e.g. ray_docker
    # container_name: "sac-ray-mujoco"

target_utilization_fraction: 0.9

idle_timeout_minutes: 1

provider:
    type: gcp
    region: us-west1
    availability_zone: us-west1-a
    project_id: <project_id>

auth:
    ssh_user: ubuntu

head_node:
    machineType: n1-standard-16
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          sourceImage: projects/<project_id>/global/images/<project_id>-v5 # Based on Ubuntu 16.04 LTS

worker_nodes:
    machineType: n1-standard-16 # n1-highcpu-16
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          # See https://cloud.google.com/compute/docs/images for more images
          sourceImage: projects/<project_id>/global/images/<project_id>-v5 # Based on Ubuntu 16.04 LTS
    scheduling:
      - preemptible: true

file_mounts: {
    "/tmp/current_branch_sha": "<repo>/.git/refs/heads/feature/<current_branch>",
    "~/rllab/vendor/mujoco/mjkey.txt": "<repo>/.mujoco/mjkey.txt",
}

setup_commands: []
head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - >-
        ray start
        --head
        --redis-port=6379
        --object-manager-port=8076
        --autoscaling-config=~/ray_bootstrap_config.yaml

worker_start_ray_commands:
    - ray stop
    - >-
        ray start
        --redis-address=$RAY_HEAD_IP:6379
        --object-manager-port=8076
```
