### ISSUE TITLE
[Doc] Issue on page /cluster/config.html - Node Docker field description is wrong.

### ISSUE THREAD

**Issue by ecm200** [ray-project/ray#23560]
Under the `node_types` definition of the yaml configuration, the `Node Docker` fields are given as follow:

```yaml
image: str
pull_before_run: bool
worker_run_options:
    - str
disable_automatic_runtime_detection: bool
disable_shm_size_detection: bool
```

However, when executing a YAML configuration with a docker specification like above, it reports a configuration error:

``` shell
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('image' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['available_node_types']['patternProperties']['.*']['properties']['docker']:
    {'additionalProperties': False,
     'description': 'Configuration of Worker nodes.',
     'properties': {'pull_before_run': {'description': 'run `docker pull` '
                                                       'first',
                                        'type': 'boolean'},
                    'worker_image': {'description': 'analogous to '
                                                    'head_image',
                                     'type': 'string'},
                    'worker_run_options': {'description': 'analogous to '
                                                          'head_run_options, '
                                                          'merged with the '
                                                          'global docker '
                                                          'run_options.',
                                           'type': 'array'}},
     'type': 'object'}

On instance['available_node_types']['ray.worker.default_bayes']['docker']:
    {'image': 'rayclusternodes.azurecr.io/smartreturntoolsbayes-ray-2.0.0dev-cpu:0.1.5',
     'pull_before_run': False,
     'worker_run_options': ['--ulimit nofile=65536:65536', '--privileged']}
```

It would appear the that the `Node Docker` configuration expects `worker_image` instead of `image` as specified in the docs.
The configuration API should read:

```yaml
worker_image: str
pull_before_run: bool
worker_run_options:
    - str
disable_automatic_runtime_detection: bool
disable_shm_size_detection: bool
```
