### ISSUE TITLE
RLLib Trainer recovery loses the cached counter

### ISSUE THREAD

**Issue by RuofanKong** [ray-project/ray#23652]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

RLlib

### Issue Severity

Medium: It contributes to significant difficulty to complete my task but I work arounds and get it resolved.

### What happened + What you expected to happen

I notice that when RLLib trainer hits a sporadic failure and tries the recovery by calling `try_recover_from_step_attempt()`, all previous cached counters, such as `timesteps_total`, `num_agent_steps_sampled`, `num_agent_steps_trained`, `num_steps_sampled` and `num_steps_trained` are lost. By digging into the code, it looks that it's because trainer resets the execution plan here (https://github.com/ray-project/ray/blob/ray-1.11.0/rllib/agents/trainer.py#L2442), which loses all cached data. The issue would impact the users who would like to track the correct data after trainer recovery.

### Versions / Dependencies

OS: MacOS Montery 12.2.1
Python: 3.8.3
Ray Version: 1.11.0
Installation: From binary.

### Reproduction script

The issue could be reproduced by running the following code `try_repro.py`:

```
mport ray
import ray.rllib.agents.ppo as ppo
from ray.tune.logger import pretty_print


def train_cartpole() -> None:
    ray.init()
    config = ppo.DEFAULT_CONFIG
    config["num_gpus"] = 0
    config["num_workers"] = 3
    config["ignore_worker_failures"] = True
    trainer = ppo.PPOTrainer(config=config, env="CartPole-v0")

    for _ in range(2):
        # For the first iteration of training, it's okay. But in the second iteration,
        # since trainer raises the RayError and it does the recovery by calling 
        # `try_recover_from_step_attempt()`, training afterwards loses all cached counter:
        # `timesteps_total`, `num_agent_steps_sampled`, `num_agent_steps_trained`, 
        # `num_steps_sampled` and `num_steps_trained`
        result = trainer.step()
        print(pretty_print(result))


train_cartpole()
```
To repro the issue, you'd also need to mock the trainer raising RayError. Specifically in trainer.py:
```
# In trainer initializer, add this flag:
class Trainer:
    def __init__(...):
        # The flag to control if it raises the RayError or not.
        self._should_raise_ray_error: Optional[bool] = None
        ...
    @ExperimentalAPI
    def step_attempt(self) -> ResultDict:
        # At the beginning of the call, add this,
        if self._should_raise_ray_error:
            from ray.exceptions import RayError
            # Once raised up once, stop raise the error any more.
            self._should_raise_ray_error = False
            raise RayError("Help me try recovery!")
        ...
```
By running `try_repro.py`, you'd expect to see that at iteration 1, all counters are correct as below, as it's happy train path:
```
...
sampler_perf:
  mean_action_processing_ms: 0.05362194621578165
  mean_env_render_ms: 0.0
  mean_env_wait_ms: 0.045704921720390465
  mean_inference_ms: 0.5179739454281688
  mean_raw_obs_processing_ms: 0.08118072511787268
timers:
  learn_throughput: 2330.911
  learn_time_ms: 3431.276
  load_throughput: 32505856.0
  load_time_ms: 0.246
  sample_throughput: 4179.34
  sample_time_ms: 1913.699
  update_time_ms: 2.731
timesteps_this_iter: 7998
timesteps_total: 7998
```
while in the iteration 2, since the trainer does the recovery, all previous cached counter are lost and reset:
```
  ...
  num_agent_steps_sampled: 7998
  num_agent_steps_trained: 7998
  num_steps_sampled: 7998
  num_steps_trained: 7998
  num_steps_trained_this_iter: 7998
  sampler_perf:
  mean_action_processing_ms: 0.05387757716861405
  mean_env_render_ms: 0.0
  mean_env_wait_ms: 0.04589715019704485
  mean_inference_ms: 0.5143007286731307
  mean_raw_obs_processing_ms: 0.0766880699825194
timers:
  learn_throughput: 2530.925
  learn_time_ms: 3160.11
  load_throughput: 35237440.538
  load_time_ms: 0.227
  sample_throughput: 4302.116
  sample_time_ms: 1859.085
  update_time_ms: 1.885
timesteps_this_iter: 7998
timesteps_total: 7998
```
Specifically, `timesteps_total`, `num_agent_steps_sampled`, `num_agent_steps_trained`, `num_steps_sampled` and `num_steps_trained` all should be 7998 * 2, however it only counts the second iteration.

### Anything else

None.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
