### ISSUE TITLE
[Autoscaler][Docs] Request resource from a specific worker group

### ISSUE THREAD

**Issue by daikeshi** [ray-project/ray#23937]
### Description

Hey, I'm running Ray cluster on Kubernetes with multiple worker groups that are associated with different node instance types. We have autoscaler enabled on our cluster, but we don't have a way to control which worker group to use when we request the resource. It would be nice if we can request resource from a specific pre-defined worker group. 

### Use case

When I request resource, I can specify the worker group, so I can better manage my cluster resources

1. request resource from cpu only worker pool
`ray.autoscaler.sdk.request_resources(num_cpus=20, worker_group="cpu_only_workers)` 

2. request resource from specific gpu worker pool
`ray.autoscaler.sdk.request_resources(num_cpu=16, num_gpu=4, worker_group="a100x4_workers)`

**Comment by richardliaw** [comment]
@wuisawesome who is the right person to address/answer this?

**Comment by wuisawesome** [comment]
@daikeshi hey, what do you mean by "worker group" here? The first thing that comes to mind, is can you do via custom resources. In your 2 examples, it would be

```
ray.autoscaler.sdk.request_resources([{"CPU": 1, "_cpu_worker_group": "0.001"}]*16)
ray.autoscaler.sdk.request_resources([{"GPU": 1, "CPU": 4 "_gpu_worker_group": "0.001"}]*4)
```

then, in your autoscaler yaml, you would have 

```
available_node_types:
  from_cpu_group:
    resources: {"_cpu_worker_group": 1}
    node_config:
        nodeSelector: # however you actually specify that this pod should be launched in a specific worker group
```
