### ISSUE TITLE
[Core] [GCP] Unable to connect to Ray Dashboard running on head node

### ISSUE THREAD

**Issue by melonipoika** [ray-project/ray#24073]
### What happened + What you expected to happen

After launching a Ray cluster with `--include-dashboard=true` in the `head_start_ray_command`, I can see from the logs that the dashboard is started, but I am not able to connect to it:

```
 [7/7] Starting the Ray runtime
Did not find any active Ray processes.
Shared connection to 34.132.189.101 closed.
Local node IP: 10.128.0.11
2022-04-21 03:58:21,746	INFO services.py:1414 -- View the Ray dashboard at http://127.0.0.1:8265

--------------------
Ray runtime started.
--------------------
```

nmap putput:

```
$ nmap -sV --reason -Pn  -p 8265 146.148.48.251                                                                                                                                                          (rllib) 
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-19 16:19 EEST
Nmap scan report for 251.48.148.146.bc.googleusercontent.com (146.148.48.251)
Host is up, received user-set.
PORT     STATE    SERVICE REASON      VERSION
8065/tcp filtered unknown no-response
```

I have created a firewall rule to open port 8265 and added the firewall tag to the head node config:

```
ray_head_default:
        node_config:
            machineType: n1-highcpu-32
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 500
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/<my-project>/global/images/common-cpu-ray-ml-head-v20220331
            tags:
              items:
                - ray-dashboard
```

### Versions / Dependencies

Ray 1.11.0
Python 3.8.13
Debian GNU/Linux 10 (buster)

### Reproduction script

Cluster config:

Cluster config:

```
# A unique identifier for the head node and workers of this cluster.
cluster_name: gpu-docker-mixed

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 36

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 8.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    image: "us-central1-docker.pkg.dev/<gcp-project-id>/ray-ml/ray-ml:e82623d"
    container_name: "ray_nvidia_docker" # e.g. ray_docker

    # # Example of running a GPU head with CPU workers
    # head_image: "rayproject/ray-ml:latest-gpu"

    run_options: ["-v /dev/shm:/dev/shm"]
    # worker_image: "rayproject/ray-ml:latest"

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 30

# Cloud-provider specific configuration.
provider:
    availability_zone: us-central1-b
    project_id: <gcp-project-id>
    type: gcp
    region: us-central1

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below. This requires that you have added the key into the
# project wide meta-data.
#    ssh_private_key: /path/to/your/key.pem

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray_head_default:
        # The resources provided by this node type.
        resources: {"CPU": 32}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: n1-highcpu-32
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 500
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/<gcp-project-id>/global/images/common-cpu-ray-ml-head-v20220331
            tags:
              items:
                - ray-dashboard

                  
    ray_learner_gpu:
        # The minimum number of nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 1
        # The maximum number of workers nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 1
        # The resources provided by this node type.
        resources: {"CPU": 48, "GPU": 4}
        
        #worker_setup_commands:
        #    - sudo mount -o remount,size=909G /dev/shm
        #docker:
        #    worker_run_options: ["--shm-size 900g"]
          
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: a2-highgpu-4g
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 500
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/<gcp-project-id>/global/images/common-cu113-ray-ml-worker-v20220331
            # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
            guestAccelerators:
              - acceleratorType: nvidia-tesla-a100
                acceleratorCount: 4
            metadata:
              items:
                - key: install-nvidia-driver
                  value: "True"
            # Run workers on preemtible instance by default.
            # Comment this out to use on-demand.
            scheduling:
              - preemptible: true
              - onHostMaintenance: TERMINATE
            # Un-Comment this to launch workers with the Service Account of the Head Node
            serviceAccounts:
              - email: ray-autoscaler-sa-v1@<gcp-project-id>.iam.gserviceaccount.com
                scopes:
                  - https://www.googleapis.com/auth/cloud-platform

    ray_worker_gpu:
        # The minimum number of nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 1
        # The maximum number of workers nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 5
        # The resources provided by this node type.
        resources: {"CPU": 8, "GPU": 2}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert    

        node_config:
            machineType: n1-highmem-8
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 500
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/<gcp-project-id>/global/images/common-cu110-ray-ml-worker-v20220331
            # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
            guestAccelerators:
              - acceleratorType: nvidia-tesla-t4
                acceleratorCount: 2
            metadata:
              items:
                - key: install-nvidia-driver
                  value: "True"
            # Run workers on preemtible instance by default.
            # Comment this out to use on-demand.
            scheduling:
              - preemptible: true
              - onHostMaintenance: TERMINATE
            # Un-Comment this to launch workers with the Service Account of the Head Node
            serviceAccounts:
              - email: ray-autoscaler-sa-v1@<gcp-project-id>.iam.gserviceaccount.com
                scopes:
                  - https://www.googleapis.com/auth/cloud-platform

# Specify the node type of the head node (as configured above).
head_node_type: ray_head_default

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands:
    - gcloud auth configure-docker us-central1-docker.pkg.dev -q
    - sudo mount -o remount,size=$(($(grep MemTotal /proc/meminfo | tr -dc '0-9') * 830 / 1073741824))G /dev/shm
    - bash -c $'ps -e | grep apt | awk \'{print $1}\' | xargs tail -f --pid || true' # Wait for auto upgrade that might run in the background.

# List of shell commands to run to set up nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    # Wait until nvidia drivers are installed
    - >-
      timeout 300 bash -c "
          command -v nvidia-smi && nvidia-smi
          until [ \$? -eq 0 ]; do
              command -v nvidia-smi && nvidia-smi
          done"
    - df -h
#    - pip install torch==1.10.2+cu111 -f https://download.pytorch.org/whl/cu111/torch_stable.html

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --head
      --port=6379
      --object-manager-port=8076
      --autoscaling-config=~/ray_bootstrap_config.yaml
      --include-dashboard=true
      --dashboard-port=8265

# Command to start ray on worker nodes. You don't need to change this.

worker_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --address=$RAY_HEAD_IP:6379
      --object-manager-port=8076
      --object-store-memory $(($(grep MemTotal /proc/meminfo | tr -dc '0-9') * 819))
head_node: {}
worker_nodes: {}
```
