### ISSUE TITLE
[Autoscaler/Gloo] 

### ISSUE THREAD

**Issue by delkov** [ray-project/ray#24305]
### What happened + What you expected to happen

I have 2 ubuntu 18.04 & 20.04 machine with 1 GPU each;
Ray status says: 
```
Healthy:
 2 local.cluster.node
Usage:
 0.0/32.0 CPU
 0.0/2.0 GPU

```

but if I make num_workers > 20 (exceed head node cpu amount), I've got:
```
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [127.0.0.1]:14221: Connection refused
```

My port are opened! (I checked via nc).
```
#0 machine(head: ) getent hosts `hostname`
127.0.0.1       PC103686
#1 machine  getent hosts `hostname`
fe80::dfe2:2fe8:9344:552a PC834
```
Please help!

### Versions / Dependencies

Ray 1.12

### Reproduction script

I've used exmple-minimal-manual.yaml to create cluster:
```
cluster_name: minimal-manual

provider:
    type: local
    head_ip: 10.0.84.63
    worker_ips: [10.0.84.80]

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: delkov

```

```
def train_fashion_mnist(num_workers=2, use_gpu=False):
    trainer = Trainer(backend="torch", num_workers=num_workers, use_gpu=use_gpu)
    trainer.start()
    result = trainer.run(
        train_func=train_func,
        config={"lr": 1e-3, "batch_size": 64, "epochs": 4},
        callbacks=[JsonLoggerCallback()],
    )
    trainer.shutdown()
    print(f"Loss results: {result}")
```

### Issue Severity

High: It blocks me from completing my task.
