### ISSUE TITLE
[rllib] Relevant parameters for reproducing Ape-X results

### ISSUE THREAD

**Issue by michaelschaarschmidt** [ray-project/ray#2466]
Hi,

I am looking to reproduce the APE-X pong results (fig 5b) from the paper, and was just wondering if  there were were any parameters beyond num workers and replay workers I should take care of when scaling up 16 - 256 workers, e.g. target network sync frequency or anything else.

I was also wondering if there was any specific network architecture used for these experiments, or if there was anything else I should modify for max performance.

Otherwise I would just use all default settings in the optimized pong-apex configuration and go through the worker counts.

Any input appreciated!

**Comment by richardliaw** [comment]
I think these are the parameters used - https://github.com/ray-project/ray/blob/master/python/ray/rllib/tuned_examples/pong-apex.yaml

**Comment by ericl** [comment]
Those parameters in the YAML reproduce the learning curve (as seen on the docs, but not in the paper).

For that particular figure, you should use the Pong-v0 env (or any other Pong that has internal frameskip -- I think that's slightly faster than the gym frameskip wrapper in Python), and you'll also need to modify AsyncSamplesOptimizer to disable throttling of the sampling based on learner updates. The simplest way to do that is to probably comment out the "replay processing" and "update priorities" block. That way, you're measuring just throughput of collecting samples and putting them into the replay buffer shards.

Other params to play with are SAMPLE_QUEUE_DEPTH (if you find workers aren't maxing out their CPU) and num_replay_shards (if you find that replay shards have saturated their CPU or you don't get linear scaling).

**Comment by michaelschaarschmidt** [comment]
Hey, many thanks for this response, just one more thing:

" Our implementation scales nearly linearly up to 160k environment frames per second with 256 workers (Figure 5(b)), and the optimizer can compute gradients for ∼8.5k 80×80×4 observations/s on a V100 GPU."

So does the optimizer throughput here not relate to 256 workers then if the worker throughput was tested without learning?

I was going to measure the combined throughput (as this seems  the practically interesting metric), but will see if I break it down then.

**Comment by ericl** [comment]
Yeah, in the original version of the paper we just had the 160k frames/s measurement; later on we added the learner throughput once that was working. I agree the text description is inconsistent now, we should probably update it to show combined numbers instead.

I would expect a slight performance penalty from enabling the learner too, since the replay shards now need to not only receive data from the sampling tasks, but also decompress data for the learner.

**Comment by michaelschaarschmidt** [comment]
Ok great, thank you very much, I will just see if it makes a meaningful difference.

**Comment by ericl** [comment]
Here's a sample from running the 32-worker example on current master:
```
    sample_throughput: 2122.191
    train_throughput: 7198.869
```

This seemed a bit low, so I looked at https://github.com/ray-project/ray/issues/2439 again and there is indeed a bug in sample accounting (ugh). We under-count by 2x.

So taking that into account, and assuming linear scaling still holds, we have sample_throughput * (256 / 32) * frameskip * undercount_factor = 2122*(256/32)*4*2 = 135k, which is within 80% of 160k. The 20% is probably from the replay tasks, or perhaps other changes since april.

**Comment by michaelschaarschmidt** [comment]
Ah, that explains some things, thank you for looking into it further!

**Comment by ericl** [comment]
I was testing a large-scale Ray cluster on master and had some time to try running Ape-X some more. Here are the results:

```
pong-apex:
    env: PongNoFrameskip-v4
    run: APEX
    config:
        target_network_update_freq: 50000
        timesteps_per_iteration: 500000  # avoid iters getting too short at high scale
        num_workers: 256
        num_envs_per_worker: 4
        sample_batch_size: 198  # 198 + (n_step-1) = 200
        lr: .0001
        gamma: 0.99
----

256 (8 m4.16xl workers, 1 p3.16xl head)
[this is also w/num_replay_buffer_shards=8; train_throughput suffers slightly
with 4 presumably since the replay buffers are saturated by the incoming samples]
    sample_throughput: 31668.639
    train_throughput: 6912.247

    sample_throughput: 32726.576
    train_throughput: 7048.373

    sample_throughput: 32244.161
    train_throughput: 7297.561

    sample_throughput: 32109.764
    train_throughput: 7358.858

    sample_throughput: 32002.949
    train_throughput: 7244.361

128 (4 m4.16xl workers, 1 p3.16xl head)

    sample_throughput: 19047.655
    train_throughput: 7795.961

    sample_throughput: 18922.615
    train_throughput: 7834.001

    sample_throughput: 18851.6
    train_throughput: 7827.309

    sample_throughput: 18710.961
    train_throughput: 7624.907

    sample_throughput: 18792.313
    train_throughput: 7925.505

64 (4 m4.16xl workers, 1 p3.16xl head)
    sample_throughput: 9223.982
    train_throughput: 7324.971

    sample_throughput: 9215.993
    train_throughput: 7091.788
```

So the peak seems to be ~128k env frames/s on 256 workers, which seems reasonable with the learner thread enabled.
