### ISSUE TITLE
[ray-lightning]  Failed to import CuPy

### ISSUE THREAD

**Issue by melonipoika** [ray-project/ray#25582]
### What happened + What you expected to happen

When importing CuPy from a training script on a Ray cluster with trainer.fit(), an error occurs:

```
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================
```

I attached to the worker VM using the command: `ssh -tt -o IdentitiesOnly=yes -i /home/jose/.ssh/ray-autoscaler_gcp_us-central1_just-tpus_ubuntu_0.pem ubuntu@<IP-address> docker exec -it ray_nvidia_docker /bin/bash`

Two things that look strange:

```
(base) ray@ray-gpu-docker-t4-jose-worker-9262da6c-compute:~$ echo $LD_LIBRARY_PATH
/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

But /usr/local/nvidia directory doesn’t exist:

```
(base) ray@ray-gpu-docker-t4-jose-worker-9262da6c-compute:~$ cd /usr/local/nvidia
bash: cd: /usr/local/nvidia: No such file or directory
```

libcuda.so.1 in in a path that is not in LD_LIBRARY_PATH:

```
(base) ray@ray-gpu-docker-t4-jose-worker-9262da6c-compute:/usr$ find . -name libcuda.so.1
./lib/x86_64-linux-gnu/libcuda.so.1
./local/cuda-11.2/compat/libcuda.so.1
```

This is the output of `ldconfig` on the worker node:

```
(base) ray@ray-gpu-docker-t4-jose-worker-058b40d4-compute:/usr/local/nvidia/lib$ sudo ldconfig --verbose | grep cuda
/sbin/ldconfig.real: Can't stat /usr/local/cuda-11/targets/x86_64-linux/lib: No such file or directory
/sbin/ldconfig.real: Path /usr/local/nvidia/lib' given more than once /sbin/ldconfig.real: Can't stat /usr/local/nvidia/lib64: No such file or directory /sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory /sbin/ldconfig.real: Path /lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path `/usr/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.27.so is the dynamic linker, ignoring
/usr/local/cuda/targets/x86_64-linux/lib:
libcudart.so.11.0 -> libcudart.so.11.2.152
libicudata.so.60 -> libicudata.so.60.2
libcuda.so.1 -> libcuda.so.470.57.02
```

I have tried to create a symlink to the actual path where libcuda.so.1 is in the worker node, but same result:

```
worker_setup_commands:
    # Wait until nvidia drivers are installed
    - >-
      timeout 300 bash -c "
          command -v nvidia-smi && nvidia-smi
          until [ \$? -eq 0 ]; do
              command -v nvidia-smi && nvidia-smi
          done"
    - sudo mkdir -p /usr/local/nvidia
    - sudo ln -s /usr/lib/x86_64-linux-gnu /usr/local/nvidia/lib
```

Full traceback:

```
Put failed:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/home/ray/anaconda3/lib/python3.7/site-packages/cupy/__init__.py in <module>

/home/ray/anaconda3/lib/python3.7/site-packages/cupy/_core/__init__.py in <module>

ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_10531/2953277746.py in <module>
----> 1 trainer.fit(model, datamodule=data)

/opt/conda/envs/correction/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader, ckpt_path)
    739             train_dataloaders = train_dataloader
    740         self._call_and_handle_interrupt(
--> 741             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    742         )
    743 

/opt/conda/envs/correction/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    683         """
    684         try:
--> 685             return trainer_fn(*args, **kwargs)
    686         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    687         except KeyboardInterrupt as exception:

/opt/conda/envs/correction/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    775         # TODO: ckpt_path only in v1.7
    776         ckpt_path = ckpt_path or self.resume_from_checkpoint
--> 777         self._run(model, ckpt_path=ckpt_path)
    778 
    779         assert self.state.stopped

/opt/conda/envs/correction/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1197 
   1198         # dispatch `start_training` or `start_evaluating` or `start_predicting`
-> 1199         self._dispatch()
   1200 
   1201         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

/opt/conda/envs/correction/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in _dispatch(self)
   1277             self.training_type_plugin.start_predicting(self)
   1278         else:
-> 1279             self.training_type_plugin.start_training(self)
   1280 
   1281     def run_stage(self):

/opt/conda/envs/correction/lib/python3.7/site-packages/ray_lightning/ray_ddp.py in start_training(self, trainer)
    253 
    254     def start_training(self, trainer):
--> 255         results = self.execution_loop(tune_enabled=True)
    256         # reset optimizers, since main process is never used for training and
    257         # thus does not have a valid optim state.

/opt/conda/envs/correction/lib/python3.7/site-packages/ray_lightning/ray_ddp.py in execution_loop(self, tune_enabled)
    316 
    317         model = self._model
--> 318         model_ref = ray.put(model)
    319         # Don't pickle the model when training remotely.
    320         self._model = None

/opt/conda/envs/correction/lib/python3.7/site-packages/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    102             # we only convert init function if RAY_CLIENT_MODE=1
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
--> 104                 return getattr(ray, func.__name__)(*args, **kwargs)
    105         return func(*args, **kwargs)
    106 

/opt/conda/envs/correction/lib/python3.7/site-packages/ray/util/client/api.py in put(self, *args, **kwargs)
     50             kwargs: opaque keyword arguments
     51         """
---> 52         return self.worker.put(*args, **kwargs)
     53 
     54     def wait(self, *args, **kwargs):

/opt/conda/envs/correction/lib/python3.7/site-packages/ray/util/client/worker.py in put(self, val, client_ref_id)
    396                 "call 'put' on it (or return it).")
    397         data = dumps_from_client(val, self._client_id)
--> 398         return self._put_pickled(data, client_ref_id)
    399 
    400     def _put_pickled(self, data, client_ref_id: bytes):

/opt/conda/envs/correction/lib/python3.7/site-packages/ray/util/client/worker.py in _put_pickled(self, data, client_ref_id)
    405         if not resp.valid:
    406             try:
--> 407                 raise cloudpickle.loads(resp.error)
    408             except (pickle.UnpicklingError, TypeError):
    409                 logger.exception("Failed to deserialize {}".format(resp.error))

/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/server.py in _put_object()

/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/server/server_pickler.py in loads_from_client()

/home/ray/anaconda3/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle.py in subimport()

/tmp/ray/session_2022-06-08_02-26-36_183967_418/runtime_resources/py_modules_files/_ray_pkg_db4f5dd51909eaa8/source/metrics/__init__.py in <module>

/tmp/ray/session_2022-06-08_02-26-36_183967_418/runtime_resources/py_modules_files/_ray_pkg_db4f5dd51909eaa8/source/metrics/surface_dice.py in <module>

/home/ray/anaconda3/lib/python3.7/site-packages/cupy/__init__.py in <module>

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================
```

Tagging @DmitriGekhtman @pouyajafarian @oskaradermecker

### Versions / Dependencies

Ray 1.11.1
Custom Docker image based on rayproject/ray-ml:1.11.1-gpu
cupy-cuda110==10.2.0

### Reproduction script

I can't share my notebook, we would need to create a simpler one where we can easily reproduce this and share...

### Issue Severity

High: It blocks me from completing my task.

**Comment by DmitriGekhtman** [comment]
Thank you for posting. 

- Not sure if the @ mentions went through.
- The issue comment looks like it has some formatting bugs -- would you mind editing that for readability.
- If there's a way to get a simple repro script, that would be much appreciated.

**Comment by melonipoika** [comment]
Fixed the typo on the description that caused the formatting issue.

We are running ray-lightning in our notebook in client mode. Interestingly, if we do `ray submit` to the same cluster, we can import CuPy successfully.

@oskaradermecker, could you please provide a way to reproduce this issue?

**Comment by melonipoika** [comment]
@richardliaw yes, it does. We are testing on worker nodes with 1x T4 GPU.

This is the worker node config:

```
 ray_worker_gpu:
        # The minimum number of nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of workers nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 64
        # The resources provided by this node type.
        resources: {"CPU": 4, "GPU": 1}
        # Provider-specific config for the head node, e.g. instance type. By default
        # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
        # For more documentation on available fields, see:
        # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
        node_config:
            machineType: n1-standard-4
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 500
                  # See https://cloud.google.com/compute/docs/images for more images
                  sourceImage: projects/just-tpus/global/images/common-cu113-ray-ml-worker-v20220511
                  # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
            guestAccelerators:
              - acceleratorType: nvidia-tesla-t4
                acceleratorCount: 1
            metadata:
              items:
                - key: install-nvidia-driver
                  value: "True"
            # Run workers on preemtible instance by default.
            # Comment this out to use on-demand.
            scheduling:
            #  - preemptible: true
              - onHostMaintenance: TERMINATE
            # Un-Comment this to launch workers with the Service Account of the Head Node
            serviceAccounts:
              - email: ray-autoscaler-sa-v1@<project-id>.iam.gserviceaccount.com
                scopes:
                  - https://www.googleapis.com/auth/cloud-platform
```
