### ISSUE TITLE
[serve] Second deployment with route_prefix is silently ignored

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#26208]
app.yaml:
```
# This file was generated using the `serve build` command on Ray v3.0.0.dev0.

import_path: tmp:app

deployments:

- name: Model
  num_replicas: 1
  route_prefix: null
  max_concurrent_queries: 100
  user_config: {"arg": "unhealthy"}
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Model_1
  num_replicas: 1
  route_prefix: /
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Driver
  num_replicas: 1
  route_prefix: /
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null
```

Status:
```
(ray) eoakes@Edwards-MacBook-Pro-2 ray % serve status
app_status:
  status: RUNNING
  message: ''
  deployment_timestamp: 1656538394.1232471
deployment_statuses:
- name: Model
  status: HEALTHY
  message: ''
- name: Model_1
  status: HEALTHY
  message: ''
- name: Driver
  status: HEALTHY
  message: ''
```
