### ISSUE TITLE
[serve] Bad error message for extraneous deployment in config

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#26206]
I added a `DNE` deployment that doesn't actually exist in the code:
```
# This file was generated using the `serve build` command on Ray v3.0.0.dev0.

import_path: tmp:app

deployments:

- name: Model
  num_replicas: 1
  route_prefix: null
  max_concurrent_queries: 100
  user_config: {"arg": "unhealthy"}
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Model_1
  num_replicas: 1
  route_prefix: null
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Driver
  num_replicas: 1
  route_prefix: /
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: DNE
  num_replicas: 1
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null
```

```
app_status:
  status: DEPLOY_FAILED
  message: "Deployment failed:\nTraceback (most recent call last):\n  File \"/Users/eoakes/code/ray/python/ray/serve/controller.py\"\
    , line 520, in get_serve_status\n    await finished[0]\nray.exceptions.RayTaskError(KeyError):\
    \ \e[36mray::run_graph()\e[39m (pid=40707, ip=127.0.0.1)\n  File \"/Users/eoakes/code/ray/python/ray/serve/controller.py\"\
    , line 585, in run_graph\n    app.deployments[name].set_options(**options)\nKeyError:\
    \ 'DNE'\n"
```
