### ISSUE TITLE
[serve] Replica failing health check doesn't cause REST API to return unhealthy

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#26204]
`tmp.py`:
```python
from ray import serve

from fastapi import FastAPI


@serve.deployment
class Model:
    def __init__(self, arg):
        self._arg = arg

    def check_health(self):
        print(self._arg)
        if self._arg == "unhealthy":
            raise Exception("hihihi")

    def reconfigure(self, c):
        self._arg = c["arg"]

    def __call__(self, *args):
        return self._arg


app = FastAPI()


@serve.deployment
@serve.ingress(app)
class Driver:
    def __init__(self, models):
        self._models = models

    @app.get("/{model}")
    async def hi(self, model: str):
        return await self._models[model].remote()


app = Driver.bind({"a": Model.bind("a"), "b": Model.bind("b")})
```

`app.yaml`:
```
# This file was generated using the `serve build` command on Ray v3.0.0.dev0.

import_path: tmp:app

runtime_env: {}

deployments:

- name: Model
  num_replicas: 1
  route_prefix: null
  max_concurrent_queries: 100
  user_config: {"arg": "unhealthy"}
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Model_1
  num_replicas: 1
  route_prefix: null
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null

- name: Driver
  num_replicas: 1
  route_prefix: /
  max_concurrent_queries: 100
  user_config: null
  autoscaling_config: null
  graceful_shutdown_wait_loop_s: 2.0
  graceful_shutdown_timeout_s: 20.0
  health_check_period_s: 10.0
  health_check_timeout_s: 30.0
  ray_actor_options: null
```

Status (despite controller logs saying it's being marked unhealthy):
```
app_status:
  status: RUNNING
  message: ''
  deployment_timestamp: 1656537678.8220658
deployment_statuses:
- name: Model
  status: HEALTHY
  message: ''
- name: Model_1
  status: HEALTHY
  message: ''
- name: Driver
  status: HEALTHY
  message: ''
```
