### ISSUE TITLE
[serve] Weird quote escaping in "waiting to be placed" error in `serve status`

### ISSUE THREAD

**Issue by edoakes** [ray-project/ray#26210]
```
app_status:
  status: DEPLOYING
  message: ''
  deployment_timestamp: 1656538595.892479
deployment_statuses:
- name: Model
  status: HEALTHY
  message: ''
- name: Model_1
  status: UPDATING
  message: 'Deployment ''Model_1'' has 1 replicas that have taken more than 30s to
    be scheduled. This may be caused by waiting for the cluster to auto-scale, or
    waiting for a runtime environment to install. Resources required for each replica:
    {''CPU'': 1, ''GPU'': 1.0}, resources available: {''CPU'': 7.0}.'
- name: Driver
  status: HEALTHY
  message: ''
```
