### ISSUE TITLE
Autoscaler runs silently when the header failed to create new workers on GCP

### ISSUE THREAD

**Issue by matthew-z** [ray-project/ray#2660]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.5
- **Python version**: 3.6
- **Exact command to reproduce**: add some incorrect fields to the config of "worker_nodes"
 
### Describe the problem
If the config of `worker_nodes` is incorrect, the autoscaler (provider: GCP) will not log any error. Instead, the monitor of autoscaler only shows "pending", which makes debug difficult. 

```
==> /tmp/raylogs/monitor-2018-08-15_19-03-58-04897.out <==
StandardAutoscaler [2018-08-15 19:14:10.263689]: 0/2 target nodes (2 pending)
 - NodeIdleSeconds: Min=607 Mean=607 Max=607
 - NumNodesConnected: 1
 - NumNodesUsed: 0.0
 - ResourceUsage: 0.0/2.0 CPU, 0.0/0.0 GPU
 ```

In my case, I set incorrect GPU type and forgot `onHostMaintenance: "TERMINATE"`  on GPU worker config.

BTW, the monitor continues show this even I corrected this problem. 
```
==> /tmp/raylogs/monitor-2018-08-15_19-32-24-06050.err <==
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/compute/v1/projects/learn-173309/zones/asia-east1-a/instances?filter=%28%28labels.ray-node-type+%3D+worker%29%29+AND+%28%28status+%3D+PROVISIONING%29+OR+%28status+%3D+RUNNING%29+OR+%28status+%3D+STAGING%29%29+AND+%28labels.ray-cluster-name+%3D+default%29&alt=json
```

### Source code / logs
 ```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: default

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 2

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 2

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    image: "" # e.g., tensorflow/tensorflow:1.5.0-py3
    container_name: "" # e.g. ray_docker


# The autoscaler will scale up the cluster to this target fraction of resource
# usage. For example, if a cluster of 10 nodes is 100% busy and
# target_utilization is 0.8, it would resize the cluster to 13. This fraction
# can be decreased to increase the aggressiveness of upscaling.
# This value must be less than 1.0 for scaling to happen.
target_utilization_fraction: 0.8

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: asia-east1
    availability_zone: asia-east1-a
    project_id: $my_project # Globally unique project id

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: $USER

# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below. This requires that you have added the key into the
# project wide meta-data.
#    ssh_private_key: /path/to/your/key.pem

# Provider-specific config for the head node, e.g. instance type. By default
# Ray will auto-configure unspecified fields such as subnets and ssh-keys.
# For more documentation on available fields, see:
# https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
head_node:
    machineType: n1-standard-2
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          # See https://cloud.google.com/compute/docs/images for more images
          sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts  # Ubuntu
    
    # Additional options can be found in in the compute docs at
    # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

worker_nodes:
    machineType: n1-standard-2
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          # See https://cloud.google.com/compute/docs/images for more images
          sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts  # Ubuntu

    guestAccelerators:
      - acceleratorType: nvidia-tesla-k80
        acceleratorCount: 1
    # Run workers on preemtible instance by default.
    # Comment this out to use on-demand.
    scheduling:
      - preemptible: true

    # Additional options can be found in in the compute docs at
    # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# List of shell commands to run to set up nodes.
setup_commands:
    # Consider uncommenting these if you also want to run apt-get commands during setup
    # - sudo pkill -9 apt-get || true
    # - sudo pkill -9 dpkg || true
    # - sudo dpkg --configure -a

    # Install basics.
    - sudo apt-get update
    - >-
      sudo apt-get install -y
      # cmake
      pkg-config
      build-essential
      autoconf
      curl
      libtool
      unzip
      flex
      bison
      # python
    # Install Anaconda.
    - >-
      wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O ~/anaconda3.sh
      || true
    - bash ~/anaconda3.sh -b -p ~/anaconda3 || true
    - rm ~/anaconda3.sh
    - echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc

    # Build Ray.
    # Note: if you're developing Ray, you probably want to create a boot-disk
    # that has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    - echo 'export PATH="$HOME/anaconda3/envs/tensorflow_p36/bin:$PATH"' >> ~/.bashrc
    - >-
      pip install
      google-api-python-client==1.6.7
      cython==0.27.3
      ray
    # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.0-cp27-cp27mu-manylinux1_x86_64.whl
    # - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.5.0-cp35-cp35m-manylinux1_x86_64.whl
    # - pip install ray
    # - >-
    #   cd ~
    #   && git clone https://github.com/ray-project/ray || true
    # - >-
    #   cd ~/ray/python
    #   && pip install -e . --verbose
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --head
      --redis-port=6379
      --object-manager-port=8076
      --autoscaling-config=~/ray_bootstrap_config.yaml
# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - >-
      ulimit -n 65536;
      ray start
      --redis-address=$RAY_HEAD_IP:6379
      --object-manager-port=8076

```
