### ISSUE TITLE
[autoscaler/core][logging] Make autoscaler event error color red

### ISSUE THREAD

**Issue by wuisawesome** [ray-project/ray#26992]
### What happened + What you expected to happen

The current default autoscaler error message color is painfully difficult to read on the default background.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/3980609/180896595-f63c60ea-d867-477b-a76a-c972e3897da3.png">

### Versions / Dependencies

Master

### Reproduction script

Launch a 4 CPU head node with available 8 CPU worker node, then trigger autoscaling.

```
available_node_types:
  head_node:
    resources: { "CPU" : 4}
  worker_node:
    resources: {"CPU": 8}
    min_workers: 0
    max_workers: 1
```

```
ray.init()
@ray.remote(num_cpus=8)
def foo():
   pass

ray.get(foo.remote())
```
