### ISSUE TITLE
Failure in rollout.py when using use_lstm: True

### ISSUE THREAD

**Issue by valldabo2** [ray-project/ray#2704]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16:04
- **Ray installed from (source or binary)**: python 3.6 wheel from ray installation instructions
- **Ray version**: 0.5.0
- **Python version**: 3.6.6
- **Exact command to reproduce**: rollout.py 

### Describe the problem

When setting use_lstm: True and training a model with train.py the rollout.py crashes with an assertionerror.

So, I run the following yaml with train.py -f <filename>.yaml
```yaml
cartpole-ppo:
    env: CartPole-v0
    run: PPO
    stop:
        episode_reward_mean: 200
        time_total_s: 180
    config:
        num_workers: 3
        num_sgd_iter: 8
        sgd_batchsize: 256
        model:
          use_lstm: True
    checkpoint_freq: 1
```
And then rollout using rollout.py checkpoint --run PPO --steps 1000 and get the following error message.

### Source code / logs

Traceback (most recent call last):
  File "rollout.py", line 177, in <module>
    run(args, parser)
  File "rollout.py", line 157, in run
    action = agent.compute_action(state)
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 242, in compute_action
    policy_id=policy_id)
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 323, in for_policy
    return func(self.policy_map[policy_id])
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 241, in <lambda>
    filtered_obs, state, is_training=False)[0],
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/evaluation/policy_graph.py", line 87, in compute_single_action
    [obs], [[s] for s in state], is_training, episodes=[episode])
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 129, in compute_actions
    is_training)
  File "/home/olle/miniconda3/envs/orderbookmdp/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 111, in build_compute_actions
    (self._state_inputs, state_batches)
AssertionError: ([<tf.Tensor 'default/c:0' shape=(?, 256) dtype=float32>, <tf.Tensor 'default/h:0' shape=(?, 256) dtype=float32>], [])
