### ISSUE TITLE
Periodically hang for a long time

### ISSUE THREAD

**Issue by joneswong** [ray-project/ray#2800]
### System information
- 32 cpu cores, 2 gpu
- **CentOS7**
- **source**
- **0.5.0**
- **py3.6**
- configuration:

```
prosthetics-apex-ddpg:
    env: ooxx
    run: APEX_DDPG
    stop:
        episode_reward_mean: 500
    checkpoint_freq: 20
    local_dir: /gruntdata/app_data/jones.wz/rl/nips2018/
    config:
        # problem setting
        clip_rewards: False
        horizon: 75

        # Misc
        timesteps_per_iteration: 2000
        num_workers: 20
        gpu: True
        min_iter_time_s: 30

        # Exploration
        schedule_max_timesteps: 1000000
        exploration_fraction: 0.1
        exploration_final_eps: 0.01
        noise_scale: 0.1
        per_worker_exploration: True
        worker_side_prioritization: False

        # Model
        actor_hiddens: [256, 128]
        actor_hidden_activation: selu
        critic_hiddens: [256, 128]
        critic_hidden_activation: selu

        # Optimization
        n_step: 3
        target_network_update_freq: 20000
        tau: 1.0
        use_huber: False
        grad_norm_clipping: 40.0
        train_batch_size: 256
        sample_batch_size: 32
        max_weight_sync_delay: 100
        learning_starts: 20000

        # Replay buffer
        buffer_size: 200000
```

### Describe the problem

I am using APEX_DDPG for an continuous control problem. The environment is widely used and wrapped by myself.
The experiment works well sometime, but will periodically hang for a while in some cases. It won't crash but there are not always tens of python process as what when it normally runs, e.g.,
![image](https://user-images.githubusercontent.com/6416895/44942676-20db5e00-adea-11e8-81f5-e0f79d4e5ac7.png)
![image](https://user-images.githubusercontent.com/6416895/44942686-36e91e80-adea-11e8-9043-12c3d2444d65.png)

Could you give me some suggestions to see what happened in those cases?
