### ISSUE TITLE
Ray 2.0 Migration Guide

### ISSUE THREAD

**Issue by matthewdeng** [ray-project/ray#28223]
Hi all!

There are many API changes that took place for Ray 2.0. Below is an aggregated list of different migration guides for each Ray component. If you have any questions feel free to comment on this issue.

## Core APIs
Ray Core - [Ray Core 2.0 Changes](https://docs.google.com/document/d/1dAutLMyOyUT7c2a7KQ9o1Xp3XddgxWTHQxPoEgRrRDY/edit#)

## Library APIs
Ray RLlib - [Ray RLlib 2.0 Changes](https://docs.google.com/document/d/1a3UEHEz6_Jth9O_2GR9Qp9c9IFyD5dObHCNSBsRgPGU/edit#)
Ray Tune - [Ray Tune 2.0 Changes](https://docs.google.com/document/d/1o-J5UAeH4M5gGN9BwdrCt1q-nLe58mp94xsmTaW0Flc/edit#)
Ray Train - [Ray Train 2.0 Changes](https://docs.google.com/document/d/1kLA4n18CbvIo3i2JQNeh2E48sMbFWAeopYwnuyoFGS8/edit#heading=h.34ky30tn5mz3)
Ray Serve - [Ray Serve 2.0 Migration Guide](https://docs.google.com/document/d/13-S2K8XFEOfugJlO4N3D-PThEG01x-nYJEVwk22aFok/edit#heading=h.1shr20op7nls)
XGBoost Integrations -[Ray XGBoost Integrations 2.0 Changes](https://docs.google.com/document/d/1_SmhazM77knwWforaEYA-pAWMbik-NXqpYv910FyB-4/edit#heading=h.99d4v3mkys91)
Misc Util - [Ray Util 2.0 Changes](https://docs.google.com/document/d/1Xgx9hiNEii7oxcTV-ZcWFjrnojnYm-Y3sd19QN59orQ/edit#)

## Cluster APIs
Ray Autoscaler - [Ray Autoscaler 2.0 Changes](https://docs.google.com/document/d/1es-vs8h8mFPGPA9yIyWW4HaFU9HqTM07hV4e2s45zPo/edit#heading=h.z38gfxud3hix)
KubeRay - [KubeRay 0.3.0 Migration Guide](https://docs.google.com/document/d/11up7sEbCUgMvZv_tGFrULsw8GPQtRMNybqNILSbhaDI/edit#heading=h.4znzhpjhbs90)

Hope this helps!

**Comment by mbcastledine** [comment]
I have followed this migration guide, however I am having trouble restricting tasks from running on my head node.
```
head_node_type: head

available_node_types:
  head:
    resources: {}
    max_workers: 0
    node_config:
     ...
```
Have I misread the migration guide?

**Comment by mbcastledine** [comment]
@matthewdeng Appreciate the quick response. I have updated my configuration as you suggested, however I still find when I submit jobs I am ending up with tasks running on my head node.

See below for my current node configuration:
head_node_type: head

```
available_node_types:
  head:
    resources: {"CPU": 0}
    max_workers: 0
    node_config:
      InstanceType: r5.xlarge
      ImageId: ami-01dc883c13e87eeda
      SubnetIds:
        - subnet-0eeade3572d9f62b1 # PrivateSubnetA
        - subnet-0888a1c0b7babd768 # PrivateSubnetB
        - subnet-08f52a701bc6650a9 # PrivateSubnetC
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 200

  worker:
    min_workers: 0
    resources: {}
    node_config:
      InstanceType: c5.4xlarge
      ImageId: ami-01dc883c13e87eeda
      SubnetIds:
        - subnet-0eeade3572d9f62b1 # PrivateSubnetA
        - subnet-0888a1c0b7babd768 # PrivateSubnetB
        - subnet-08f52a701bc6650a9 # PrivateSubnetC
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50

```
