### ISSUE TITLE
[Cluster] agent.py using 100% of a CPU core

### ISSUE THREAD

**Issue by jmakov** [ray-project/ray#28538]
### What happened + What you expected to happen

Deployed on a local cluster, `agent.py` is using on every node a CPU core almost all the time (2s 100% usage, 2s pause).

### Versions / Dependencies

name: puma-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.14=ha878542_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py38h578d9bd_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgomp=12.1.0=h8d9b700_16
  - libnsl=2.0.0=h7f98852_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.12=h166bdaf_3
  - nb_conda_kernels=2.3.1=py38h578d9bd_1
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - openssl=3.0.5=h166bdaf_2
  - pip=22.2.2=pyhd8ed1ab_0
  - python=3.8.13=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pyzmq=23.2.1=py38hfc09fa9_0
  - readline=8.1.2=h0f457ee_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.3=h4ff8645_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.2=py38h0a891b7_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - pip:
    - aiohttp==3.8.1
    - aiohttp-retry==2.8.3
    - aiosignal==1.2.0
    - amqp==5.1.1
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.1
    - aplus==0.11.0
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astropy==5.1
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - asyncssh==2.12.0
    - atpublic==3.1.1
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - bcrypt==4.0.0
    - beautifulsoup4==4.11.1
    - billiard==3.6.4.0
    - blake3==0.3.1
    - bleach==5.0.1
    - blessed==1.19.1
    - bokeh==2.4.3
    - bqplot==0.12.36
    - branca==0.5.0
    - cachetools==5.2.0
    - celery==5.2.7
    - certifi==2022.9.14
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.0.4
    - click-didyoumean==0.3.0
    - click-plugins==1.1.1
    - click-repl==0.2.0
    - clickhouse-cityhash==1.0.2.3
    - clickhouse-driver==0.2.4
    - cloudpickle==2.2.0
    - colorama==0.4.5
    - colorcet==3.0.0
    - commonmark==0.9.1
    - configobj==5.0.6
    - cramjam==2.5.0
    - cryptography==38.0.1
    - cycler==0.11.0
    - dask==2022.6.1
    - datashader==0.14.2
    - datashape==0.5.2
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dictdiffer==0.9.0
    - diskcache==5.4.0
    - distlib==0.3.6
    - distributed==2022.6.1
    - distro==1.7.0
    - dpath==2.0.6
    - dpcpp-cpp-rt==2022.1.0
    - dulwich==0.20.46
    - dvc==2.25.0
    - dvc-data==0.7.1
    - dvc-http==2.19.1
    - dvc-objects==0.2.2
    - dvc-render==0.0.10
    - dvc-ssh==2.19.0
    - dvc-task==0.1.2
    - dvclive==0.10.0
    - executing==1.0.0
    - fastapi==0.84.0
    - fastjsonschema==2.16.1
    - fastparquet==0.8.3
    - filelock==3.8.0
    - flatten-dict==0.4.2
    - flufl-lock==7.1.1
    - fonttools==4.37.1
    - frozendict==2.3.4
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - funcy==1.17
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-api-core==2.10.1
    - google-auth==2.11.0
    - googleapis-common-protos==1.56.4
    - gpustat==1.0.0
    - grandalf==0.6
    - grpcio==1.43.0
    - h11==0.13.0
    - h5py==3.7.0
    - heapdict==1.0.1
    - holoviews==1.15.0
    - httptools==0.5.0
    - hvplot==0.8.1
    - hydra-core==1.2.0
    - idna==3.4
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - intel-cmplr-lib-rt==2022.1.0
    - intel-cmplr-lic-rt==2022.1.0
    - intel-opencl-rt==2022.1.0
    - intel-openmp==2022.1.0
    - ipydatawidgets==4.3.2
    - ipykernel==6.15.3
    - ipyleaflet==0.17.1
    - ipympl==0.9.2
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - ipyvolume==0.5.2
    - ipyvue==1.7.0
    - ipyvuetify==1.8.4
    - ipywebrtc==0.6.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - json5==0.9.10
    - jsonschema==4.16.0
    - jupyter-contrib-core==0.4.0
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.5.0
    - jupyter-server==1.18.1
    - jupyter-server-mathjax==0.2.6
    - jupyterlab==3.4.7
    - jupyterlab-execute-time==2.1.0
    - jupyterlab-git==0.39.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.1
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - kombu==5.2.4
    - lckr-jupyterlab-variableinspector==3.0.9
    - llvmlite==0.39.1
    - locket==1.0.0
    - lxml==4.9.1
    - lz4==4.0.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mkl==2022.1.0
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - msgpack==1.0.4
    - multidict==6.0.2
    - multipledispatch==0.6.0
    - nanotime==0.5.2
    - nbclassic==0.4.3
    - nbclient==0.6.8
    - nbconvert==7.0.0
    - nbdime==3.1.1
    - nbformat==5.5.0
    - networkx==2.8.6
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - numba==0.56.2
    - numpy==1.22.4
    - nvidia-ml-py==11.495.46
    - omegaconf==2.2.3
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - packaging==21.3
    - pandas==1.4.4
    - pandocfilters==1.5.0
    - panel==0.13.1
    - param==1.12.2
    - parso==0.8.3
    - partd==1.3.0
    - pathspec==0.9.0
    - patsy==0.5.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - progressbar2==4.0.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.31
    - protobuf==3.20.2
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-spy==0.3.14
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyct==0.4.8
    - pydantic==1.10.2
    - pydot==1.4.2
    - pyerfa==2.0.0.1
    - pygit2==1.10.1
    - pygments==2.13.0
    - pygtrie==2.5.0
    - pykalman==0.9.5
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dotenv==0.21.0
    - python-utils==3.3.3
    - pythreejs==2.4.1
    - pytz==2022.2.1
    - pytz-deprecation-shim==0.1.0.post0
    - pyviz-comms==2.2.1
    - pyyaml==6.0
    - ray==2.0.0
    - requests==2.28.1
    - rich==12.5.1
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scipy==1.9.1
    - scmrepo==0.1.1
    - send2trash==1.8.0
    - setuptools==59.8.0
    - shortuuid==1.0.9
    - shtab==1.5.5
    - smart-open==6.2.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.2.post1
    - sshfs==2022.6.0
    - stack-data==0.5.0
    - starlette==0.19.1
    - statsmodels==0.13.2
    - ta-lib-binary==0.4.21
    - tabulate==0.8.10
    - tbb==2021.6.0
    - tblib==1.7.0
    - terminado==0.15.0
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tomlkit==0.11.4
    - toolz==0.12.0
    - tqdm==4.64.1
    - traittypes==0.2.1
    - typing-extensions==4.3.0
    - tzdata==2022.2
    - tzlocal==4.2
    - urllib3==1.26.12
    - uvicorn==0.18.3
    - uvloop==0.17.0
    - vaex==4.12.0
    - vaex-astro==0.9.1
    - vaex-core==4.12.0
    - vaex-hdf5==0.12.3
    - vaex-jupyter==0.8.0
    - vaex-ml==0.18.0
    - vaex-server==0.8.1
    - vaex-viz==0.5.3
    - vine==5.0.0
    - virtualenv==20.16.5
    - voluptuous==0.13.1
    - watchfiles==0.17.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - websockets==10.3
    - widgetsnbextension==4.0.3
    - xarray==2022.6.0
    - xeus-python==0.14.3
    - xeus-python-shell==0.5.0
    - xyzservices==2022.6.0
    - yarl==1.8.1
    - zc-lockfile==2.0
    - zict==2.2.0
    - zipp==3.8.1
    - zstandard==0.18.0
    - zstd==1.5.2.6

### Reproduction script

ray up cluster.yaml -no-config-cache -y

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by scottsun94** [comment]
CC: @rkooo567

**Comment by rkooo567** [comment]
Can you provide a repro script?

**Comment by jmakov** [comment]
I start the cluster with `ray up cluster.yaml` without doing anything else.

**Comment by tomsunelite** [comment]
I got the same issue on ray head node(other worker nodes seems ok), and only start ray with command(ray 2.0.0):
```code
ray start --head --disable-usage-stats
```code

![image](https://user-images.githubusercontent.com/4536375/197930090-11cf807c-7977-423c-a19d-79431d7489ab.png)

**Comment by rkooo567** [comment]
Do you guys mind running `py-spy flamegraph --pid <pid>` and share the output? Currently have no bandwidth to reproducing the issue.

**Comment by rkooo567** [comment]
I couldn't reproduce the issue from the master. Please give me more detail for the reproduction. E.g.,

- what's the cluster.yaml? Can you share it?
- Do you run any workload? If so, can you share it? 
- Also can you try running the py-spy and share the flamegraph with me?

**Comment by jmakov** [comment]
No workload. Will try to run py-spy when I get to the cluster.

cluster.yaml:
```yaml
cluster_name: default
provider:
  type: local
  head_ip: 192.168.0.101
  worker_ips:
    - 192.168.0.110
    - 192.168.0.106
    - 192.168.0.107
    - 192.168.0.108
auth:
  ssh_user: toaster
upscaling_speed: 1.0
idle_timeout_minutes: 5

# needed so we can run `setup commands`
file_mounts: {
      "/mnt/workspace/ray/mount_driver_node": "~/workspace/repos/puma-lab",
}
cluster_synced_files: []
file_mounts_sync_continuously: False
rsync_exclude:
  - "**/.git"
  - "**/.git/**"
rsync_filter:
  - ".gitignore"
initialization_commands: []
setup_commands:
  # If env already there, the command fails, we can update packages
  #- mamba env create -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml || mamba env update -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml
  # Since updating packages is error-prone operation, we just create a new env when packages change
  - mamba env create -q -n puma-lab -f /mnt/workspace/ray/mount_driver_node/env.yaml || true
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
  - conda activate puma-lab && ray stop
  - conda activate puma-lab && ulimit -c unlimited && ray start --head --disable-usage-stats --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml --system-config='{"automatic_object_spilling_enabled":true,"max_io_workers":8,"min_spilling_size":104857600,"object_spilling_config":"{\"type\":\"filesystem\",\"params\":{\"directory_path\":\"/mnt/workspace/ray/object_spilling\"}}"}'
worker_start_ray_commands:
  - conda activate puma-lab && ray stop
  - conda activate puma-lab && ulimit -c unlimited && ray start --address=$RAY_HEAD_IP:6379 --disable-usage-stats
```
