### ISSUE TITLE
[Serve] `serve build` option to output Kubernetes config format

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#28831]
### Description

`serve build` should have an option to output the config file in Kubernetes format.

### Use case

`serve build` outputs [a Serve config file](https://docs.ray.io/en/releases-2.0.0/serve/production-guide/config.html) that can be deployed to a Ray cluster with `serve run` and `serve deploy`:

```yaml
import_path: ...

runtime_env: ...

deployments:

    - name: ...
      num_replicas: ...
      ...

    - name:
      ...

    ...
```

Kuberay `RayServices` use this config when deploying Serve. However, the KubeRay config uses camel case ([see example](https://github.com/ray-project/kuberay/blob/2793b2c3ec3f002c7c3399e0a7101fc3f5cbfc65/ray-operator/config/samples/ray_v1alpha1_rayservice.yaml#L12-L43)) for the deployment options, so this config can't be directly copy-pasted.

Adding a Kubernetes output option would let users copy-paste the config directly.
