### ISSUE TITLE
[Kubernetes] Struggling to set up an internal Redis with a custom K8s setup.

### ISSUE THREAD

**Issue by DmitriGekhtman** [ray-project/ray#28878]
### What happened + What you expected to happen

We're having some trouble setting up an external Redis with a static, non-operator-managed, K8s-Deployment-based Ray cluster setup.
The [config file in this draft PR](https://github.com/ray-project/ray/pull/28877/files) is my attempt to get it working.

That file is my attempt to combine the existing static Ray cluster setup [here](https://github.com/ray-project/ray/blob/fa3200f33bb038a539313130c4f1e37e3d03807b/doc/kubernetes/ray-cluster.yaml) with the example Redis setup [here](https://github.com/ray-project/kuberay/blob/1694b9e2fba06f4d2378ea70c3fda679ee67b61d/ray-operator/config/samples/ray-cluster.external-redis.yaml).
See another user's attempt here: https://github.com/ray-project/ray/pull/28687

The problem we are both running into is that, while the Ray cluster runs successfully, it seems the external Redis is not in use; querying the external Redis shows no keys.

Setting up an external Redis using the [KubeRay docs](https://ray-project.github.io/kuberay/guidance/gcs-ft/) does work.
But I cannot for the life of me figure out the key operational difference between that working setup and my attempt at a static setup.

Related: https://github.com/ray-project/ray/issues/24985

### Versions / Dependencies

Ray master.

### Reproduction script

```shell
# Apply the configuration here: 
# https://raw.githubusercontent.com/ray-project/ray/88a916f515483379b7fd9bc809007d9092566072/doc/kubernetes/ray-cluster-external-redis.yaml
kubectl apply -f raycluster-external-redis.yaml
# Wait for the cluster to start...
# Exec into the Redis pod
kubectl -n ray exec -it kubectl exec -it redis-5bb67bfb86-7pv55 -- redis-cli
# Give it the password
AUTH 5241590000000000
# Get all the keys
KEYS *
# Output indicates no Keys!
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by simon-mo** [comment]
The environment variable seems not to be properly passed into the container 
```
(base) ray@ray-head-5b95d5f758-5nlc2:/tmp/ray/session_latest/logs$ printenv | sort | grep RAY_REDIS_ADDRESS
```

**Comment by simon-mo** [comment]
The reason is the duplicated `env` key
```
      containers:
        - name: ray-head
          image: rayproject/ray:latest
          env:
            # RAY_REDIS_ADDRESS can force ray to use external redis
            - name: RAY_REDIS_ADDRESS
              value: redis:6379
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "ray start --head --port=6379 --num-cpus=$MY_CPU_REQUEST --dashboard-host=0.0.0.0 --block"
...
          env:
            # This is used in the ray start command so that Ray can spawn the
            # correct number of processes. Omitting this may lead to degraded
            # performance.
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
```
