### ISSUE TITLE
[Core]  Ray Autoscaler does not restart a worker node on setup failure

### ISSUE THREAD

**Issue by mzakharocsc** [ray-project/ray#29127]
### What happened + What you expected to happen

In a ray aws cluster, dynamically added worker nodes that sometimes fail to execute statements listed inside `setup_commands` configuration block will not recover. Command execution failure is reported on the monitor console, but the failed node will continue to show up as `uninitialized` pending status indefinitely.  
Expected behaviour is to restart/retry setting up the worker after the failure has occurred/some timeout. 

Example of command failure:
```
2022-10-06 11:40:16,543	ERR updater.py:158 -- New status:update-failed
2022-10-06 11:40:16,544	ERR updater.py:160 -- !!!
2022-10-06 11:40:16,544	VERR updater.py:168 -- {'message': 'SSH command failed.'}
2022-10-06 11:40:16,544	ERR updater.py:170 -- SSH command failed.
2022-10-06 11:40:16,544	ERR updater.py:172 -- !!!
```

Example of monitor status after node setup failure has occured:
```
======== Autoscaler status: 2022-10-06 11:58:17.648737 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray.head.default
Pending:
<IP>: ray.worker.default, uninitialized
Recent failures:
 (no failures)
```

### Versions / Dependencies

Ray 2.0.0
Python 3.8.0

### Reproduction script

```
cluster_name: default
max_workers: 8
upscaling_speed: 1.0

docker:
    image: rayproject/ray:latest-cpu   # use this one if you don't need ML dependencies, it's faster to pull
    container_name: "ray_container"
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536
   
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-east-1
    availability_zone: us-east-1a
    cache_stopped_nodes: True # If not present, the default is True.
    use_internal_ips: true

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: m5.large
            ImageId: ami-x 

    ray.worker.default:
        min_workers: 0
        max_workers: 8
        # resources: {"CPU": 1, "GPU": 1, "custom": 5}
        resources: {}
        node_config:
            InstanceType: m5.large
            ImageId: ami-x
 
head_node_type: ray.head.default


# List of shell commands to run to set up nodes.
setup_commands:
    - SOME_SOMETIMES_FAILING_COMMAND

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    -  ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```
### Issue Severity

Low: It annoys or frustrates me.
