### ISSUE TITLE
[Core] Workers die randomly and crash all pipeline

### ISSUE THREAD

**Issue by Tehada** [ray-project/ray#29461]
### What happened + What you expected to happen

Hello, ray team! Thank you for a great library!

Our company uses ray to launch daily data pipelines and they started to fail ~1 month ago. The error, which crashes pipeline looks like this:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/hpa_makers/backends/ray.py", line 147, in <module>
    fire.Fire()
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/my-app/backends/ray.py", line 141, in main
    ray.get(tasks)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.WorkerCrashedError: The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
root@ray-cluster-minimal-head-ad37d561-compute:/app#
```

We run cluster on gcp with spot vms, but we were doing so for around 6 months and it worked fine until recently. To run ray jobs I use sth like `ray exec "python -m run_jobs"`.

So basically, I started this pipeline on around 20 workers (n2d-highmem-64 in google cloud, it is 512GiB RAM spot vm) and after around 10 minutes it crashed with error "The worker died unexpectedly". Also before crashing I saw several times messages of this type:

```
2022-10-17 12:23:49,079 WARNING worker.py:1829 -- The node with node id: a5f8c09ad9446209fd4b33cdb4d5c9b27209e45c3c1d0d9c24f21baf and address: 10.132.0.6 and node name: 10.132.0.6 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a       (1) raylet crashes unexpectedly (OOM, preempted node, etc.)
        (2) raylet has lagging heartbeats due to slow network or busy workload.
```
But they don't crush the pipeline, unlike another error.

What I tried to fix the problem:
1. made some research on closed issues and on discuss.ray.io -- wasn't able to find useful info how to fix my issue.
2. upgraded ray from 1.9.0 to 2.0.0

I would appreciate any help, regarding this issue. Ideally I would like to fix it, but learning how to silently ignore this problem to avoid crash of pipeline also seems like a way to go (don't know how to do it though).

### Versions / Dependencies

ray 2.0.0

### Reproduction script

 I managed to reproduce this problem on tasks, which were doing only sleep for some time like this:

```python
@ray.remote()
def run_job():
        t = random.random() * 60 * 10
        time.sleep(t)

def main():
    def get_tasks():
        n_tasks = 10
        tasks = []

        memory = get_required_memory()
        for _ in range(n_tasks):
            tasks += [run_job.options(num_cpus=1, memory=memory).remote()]

        return tasks

    tasks = get_tasks()
    ray.get(tasks)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by Tehada** [comment]
> hey @Tehada have you get a chance to check if the worker (spot instance) is actually dead?

No, it is up after the exception, I can even ssh into it.

**Comment by rkooo567** [comment]
Have you tracked the memory usage of the cluster? I recommend you to set up prometheus after upgrading to ray 2.0. https://docs.ray.io/en/master/ray-observability/ray-metrics.html. Many times this sort of issue happens due to OOM (like your workers use too much memory and OS kills them randomly)

**Comment by Tehada** [comment]
> Have you tracked the memory usage of the cluster? I recommend you to set up prometheus after upgrading to ray 2.0 (Ray 2.0 will also give you a better error in this case). https://docs.ray.io/en/master/ray-observability/ray-metrics.html. Many times this sort of issue happens due to OOM (like your workers use too much memory and OS kills them randomly)

Yeah, I see your point, but I specificially used dummy task which was doing only time.sleep to check for OOM. It appeares that even doing only time.sleep leads to the problem, described above.

**Comment by Tehada** [comment]
Also, got some more deails on problem: when pipeline crashes, spot vm's with workers actually stay forever, unless I will stop them manually from google cloud website. On stuck vm's I see that docker container of ray is not up (output of `docker ps` is empty), hence, the reason that ray's head node couldn't communicate with it. This could be somehow related to the another issue: when executing `ray up` for the first time, after command is finished, the container inside head node is also not up for some reason, but after executing `ray up` again the container is there and I can do `ray attach`, `ray exec` (without second `ray up` I see error "No such container: my_container", if I will try to attach).

Overall problem with pipeline seems to be related to container exiting for some reason. And it is definitely not due to OOM, bcoz time.sleep shouldn't cause it. Not sure about high CPU usage or network load, but they also seem unlikely due to time.sleep being too light on these resources.

**Comment by stephanie-wang** [comment]
Thanks for the info! I think you are definitely right that there is some issue with starting Ray. That would explain this message:

```bash
2022-10-17 12:23:49,079 WARNING worker.py:1829 -- The node with node id: a5f8c09ad9446209fd4b33cdb4d5c9b27209e45c3c1d0d9c24f21baf and address: 10.132.0.6 and node name: 10.132.0.6 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a       (1) raylet crashes unexpectedly (OOM, preempted node, etc.)
        (2) raylet has lagging heartbeats due to slow network or busy workload.
```

Can you try running `ray cluster-dump <config.yaml>` to collect a dump of all the logs? If the machines are still up, I think this will include logs from the dead raylets and we can see if there's any info about why they've died. Another thing to try (if it's possible) is to run without docker and check if the same issue occurs. You should be able to do this by passing an empty docker image in the cluster config and installing ray during setup instead.

**Comment by Tehada** [comment]
Also, here is minimal example to reproduce the problem.

minimal-example.yaml:

```yaml
cluster_name: cluster-minimal

provider:
  type: gcp
  region: europe-west1
  availability_zone: europe-west1-c
  project_id: ----

docker:
  image: "rayproject/ray:2.0.0-py310"
  container_name: "my-container"
  pull_before_run: True

head_setup_commands: []
setup_commands: []

available_node_types:
    head:
        resources: {"CPU": 0}
        node_config:
            machineType: e2-standard-8
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 50
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cpu
    worker:
        resources: {"CPU": 62, "memory": 539018395648}
        node_config:
            machineType: n2d-highmem-64
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 700
                  sourceImage: projects/deeplearning-platform-release/global/images/family/common-cpu
            scheduling:
              - preemptible: true
            serviceAccounts:
            - email: ----
              scopes:
              - https://www.googleapis.com/auth/cloud-platform

head_node_type: head

max_workers: 5
idle_timeout_minutes: 4
upscaling_speed: 1.0

file_mounts: {
  "/home/ray/script": "script",
}
```

file ray_testik.py in script directory:
```python
import ray
import random
import time


@ray.remote
def run_job():
    tt = random.random() * 60 * 10
    print(f"Sleeping {tt} seconds in shit_mode...")
    time.sleep(tt)


def main():
    def get_tasks():
        n_tasks = 10
        tasks = []

        for _ in range(n_tasks):
            memory = random.random() * 50 * 1024 * 1024 * 1024
            print(f"Requesting memory: {int(memory / 1024 / 1024)} MiB")
            tasks += [run_job.options(num_cpus=1, memory=memory).remote()]

        return tasks

    tasks = get_tasks()
    print(f"Starting {len(tasks)} tasks...")
    ray.get(tasks)


if __name__ == "__main__":
    main()
```

command to execute the pipeline:
```
ray exec --tmux minimal-example.yaml 'python script/ray_testik.py'
```
