### ISSUE TITLE
Undesired memory growing when using convolutional neural network

### ISSUE THREAD

**Issue by Yak46** [ray-project/ray#29699]
Hello,

I'm trying to run a custom gym environment using a convolutional neural network and a PPO trainer. When I run the trainer using ray.tune, the RAM memory usage grows up to low memory message appears.

In my gym environment, the observation a 256 x 256 x 3 RGB image, the environment fps (frame per second) is 100, and the integration time step is 0.01 s. The maximum episode length is 3072 time steps.
The observation is provided as is done in the "car_racing" gym env using the following command:

`obs = np.transpose(np.array(pygame.surfarray.pixels3d(self.surf)), axes=(1, 0, 2))`

Is this problem related to a poor hardware characteristics of my PC (not enough memory) or it is actually due to an incorrect setting of the PPO parameters config?

 **My system:**

CPU: Intel Core i7-5960X (8 core/16 thread)
RAM: 64 GB
OS: Windows 10
RAY: 2.0.0

**PPO config parameters:**

```
config:
  num_workers: 15
  num_envs_per_worker: 6
  num_gpus: 0
  num_cpus_per_worker: 1
  num_gpus_per_worker: 0
  num_cpus_for_driver: 1
  remote_worker_envs: false
  rollout_fragment_length: 3072
  batch_mode: truncate_episodes
  train_batch_size: 202752
  model:
    dim: 256
    conv_filters: [[16, [11, 11], 6], [32, [7, 7], 4], [64, [5, 5], 3], [128,[3,3],2]]
    conv_activation: tanh
    post_fcnet_hiddens: [64, 32]
    post_fcnet_activation: tanh
    vf_share_layers: true
    free_log_std: true
  gamma: 0.99
  log_level: INFO
  framework: tf
  explore: true
  ignore_worker_failures: true
  use_critic: true
  use_gae: true
  lambda: 0.99
  kl_coeff: 0.0
  sgd_minibatch_size: 61440
  shuffle_sequences: true
  evaluation_interval: 1
  evaluation_duration: 12
  evaluation_duration_unit: episodes
  evaluation_config: {explore: false}
  evaluation_num_workers: 0
  num_sgd_iter: 10
  lr: 0.001
  vf_loss_coeff: 0.5
  clip_param: 0.3
  vf_clip_param: 30000
  lr_schedule:
  - [0, 0.001]
  - [368640000, 1.0e-08]
```

I am aware that the question is not so technical but rather qualitative, but I do not have much experience on this type of problem.

Thank you in advance.
