### ISSUE TITLE
[Rllib] Evaluation duration will be multiplied by num_envs_per_worker when duration unit is "timesteps"

### ISSUE THREAD

**Issue by spacegoing** [ray-project/ray#29946]
### What happened + What you expected to happen

When I set `evaluation_duration` when  `evaluation_duration_unit = "timesteps"`
<img width="681" alt="Screen Shot 2022-11-03 at 00 37 31" src="https://user-images.githubusercontent.com/5180020/199548456-97c29a70-e24e-40b3-aab7-0c74aaa99e64.png">

The evaluation_worker's `rollout_fragment _length` will be `num_envs_per_worker` x `evaluation_duration`
<img width="780" alt="Screen Shot 2022-11-03 at 00 39 39" src="https://user-images.githubusercontent.com/5180020/199548980-e84985b8-b904-45eb-9814-3e3469124e18.png">

Because of this line:
<img width="942" alt="Screen Shot 2022-11-03 at 00 43 47" src="https://user-images.githubusercontent.com/5180020/199549943-b5e30649-94f4-4cca-857e-eb76ef58dce4.png">

### Versions / Dependencies

Ray 2.0

### Reproduction script

I will post my yaml file here. This should be easily run by a ppo object:

```yaml
rllib:
  debugging:
    seed:
    log_level: WARNING
  exploration:
    explore: true
  framework:
    framework: torch
  training:
    gamma: 0.99
  rollouts:
    num_rollout_workers: 1
    num_envs_per_worker: 4
    ignore_worker_failures: true
    observation_filter: MeanStdFilter
  resources:
    # local worker uses for training & inference
    num_gpus: 0
  environment:
    env: 
    clip_rewards: false
    env_config:
  evaluation:
    # This level used for evaluation specific configs
    # evaluation_interval: Optional[int], training iteration
    evaluation_interval: 1
    evaluation_config:
      # This level for overwrite training configs, merging of
      # train and env config dicts is handled in Algorithm.setup()
      explore: false
```
