### ISSUE TITLE
Cluster[<Ray component: Core|RLlib|etc...>] 

### ISSUE THREAD

**Issue by jungwoowoo** [ray-project/ray#30200]
### What happened + What you expected to happen

some workloads were not distributed on cluster.

logs :
(f pid=18152) mean ?  0.4999771519540568
(f pid=18183) mean ?  0.4999771519540568
(f pid=18121) mean ?  0.4999771519540568
(f pid=18152) mean ?  0.4999771519540568
(f pid=18096) mean ?  0.4999771519540568
(f pid=18154) mean ?  0.4999771519540568
(f pid=18157) mean ?  0.4999771519540568
(f pid=18156) mean ?  0.4999771519540568
Traceback (most recent call last):
  File "ray_sample7.py", line 28, in <module>
    results_from_ray = ray.get(object_ids)
  File "/home/medirita/anaconda2/envs/py36/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/medirita/anaconda2/envs/py36/lib/python3.6/site-packages/ray/_private/worker.py", line 2275, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::f() (pid=1008834, ip=192.168.0.50)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.OwnerDiedError: Failed to retrieve object 00ffffffffffffffffffffffffffffffffffffff3202000001000000. To see information about where this ObjectRef was created in Python, set the environment variable RAY_record_ref_creation_sites=1 during `ray start` and `ray.init()`.

The object's owner has exited. This is the Python worker that first created the ObjectRef via `.remote()` or `ray.put()`. Check cluster logs (`/tmp/ray/session_latest/logs/*32020000ffffffffffffffffffffffffffffffffffffffffffffffff*` at IP address 192.168.0.48) for more information about the Python worker failure.
(f pid=18183) mean ?  0.4999771519540568
(f pid=18183) mean ?  0.4999771519540568

### Versions / Dependencies

ray, version 2.0.0

### Reproduction script

1. sample code

```
import numpy as np
from collections import namedtuple
import ray
ray.init(
    address='auto',
    _node_ip_address="192.168.0.48"
)

callback_entry = namedtuple("callback_entry", ['index', 'value'])
result_list = []
def gathering_results_callback(entry):
    result_list[entry.index] = entry.value

@ray.remote
def f(G,temp_index):
    #G = np.random.randint(2, size=(N,N))
    temp = np.mean(G)
    print('mean ? ' , temp)
    return callback_entry(index = temp_index , value = temp)

result_list = np.zeros(400)

values = np.random.randint(2, size=(4848,4848))
ray_param1 = ray.put(values) 

object_ids = [f.remote(ray_param1 , temp_index) for temp_index in range(400)]

results_from_ray = ray.get(object_ids)

for entry in results_from_ray:
    gathering_results_callback(entry)

ray.shutdown()
```

2. cluster yaml :
```
# A unique identifier for the head node and workers of this cluster.
cluster_name: ray_cluster_local

provider:
    type: local
    head_ip: 192.168.0.48
    worker_ips: ['192.168.0.50']

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: cluser_user

min_workers: 1

max_workers: 1

upscaling_speed: 1.0

idle_timeout_minutes: 1

file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []
# List of shell commands to run to set up each nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []
# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - conda activate py36 && ray stop
    - conda activate py36 && ulimit -c unlimited && RAY_REDIS_ADDRESS=192.168.0.48:6000 RAY_scheduler_spread_threshold=0.0 ray start --port=6666 --head --resources '{"node0":2}' --node-ip-address="192.168.0.48" --include-dashboard=true --dashboard-host 192.168.0.48 --dashboard-port 8888 --num-cpus=28 --num-gpus=4 --memory=$((125*$((2**30)))) --redis-password=123456 --autoscaling-config=~/ray_bootstrap_config.yaml
# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - conda activate py36 && ray stop
    - conda activate py36 && RAY_scheduler_spread_threshold=0.0 ray start --memory=$((40*$((2**30)))) --address=192.168.0.48:6666 --node-manager-port 40405 --object-manager-port 42015
```

### Issue Severity

High: It blocks me from completing my task.
