### ISSUE TITLE
Ape-X not reaching expected throughput

### ISSUE THREAD

**Issue by nilsjohanbjorck** [ray-project/ray#3177]
Dear ray-team,

I wanted to try the Ape-X algorithm and thought I'd start by trying to replicate the throughput given in https://github.com/ray-project/ray/issues/2466. I'm using the parameters given there except using only 32 workers and two m4.16xlarge and one p3.2xlarge. I was expecting roughly half of the throughput of the 64 worker example, but instead I get

sample_throughput: 1206.411
train_throughput: 4065.036

any ideas what might be wrong? The ec2 instances are in a placement group. Thanks!!

**Comment by ericl** [comment]
Hm, can you post the config and debug statistics? (In particular, the learner queue size?)

It's possible this is a regression.

**Comment by ericl** [comment]
Here's what I get for a p3.16xl single node on master right now (only using 1 GPU, and all 32 physical CPUs):
```
    sample_throughput: 5133.768
    train_throughput: 4081.346
```

```
pong-apex:
    env: PongNoFrameskip-v4
    run: APEX
    config:
        target_network_update_freq: 50000
        num_workers: 32
        lr: .0001
        gamma: 0.99
        num_envs_per_worker: 8
        sample_batch_size: 20
```

Can you try a larger head node? Also, make sure you have the 'lz4' package installed.
