### ISSUE TITLE
[Ray Core][Security] Add allowed class list config item to avoid deserializing insecure bytes.

### ISSUE THREAD

**Issue by jovany-wang** [ray-project/ray#32159]
### Description

Ray uses cloudpickle as the main serializer/deserializer, which is too dynamic, as a result that it's easy to be attacked.

I'm purposing adding a configuration item `allowed_class_list_for_deserialization`, to limit that only the allowed classes can be deserialized, to avoid the dynamic code attacking.

Some light background articles:
https://morioh.com/p/557f5c408f5e
https://medium.com/@abhishek.dev.kumar.94/sour-pickle-insecure-deserialization-with-python-pickle-module-efa812c0d565

### Use case

The configuration could be a `.yml` file like:
```yml
"allowed_list": {
  "numpy.core.numeric": ["*"], # All classes in package  `numpy.core.numeric` are allowed.
   "numpy": ["dtype"], # Only `numpy.dtype` class is allowed.
}
```
