### ISSUE TITLE
[Core] [AWS Autoscaler] Unable to connect to GCS 

### ISSUE THREAD

**Issue by mlguruz** [ray-project/ray#32227]
### What happened + What you expected to happen

I start to get errors once my aws ec2 cluster reaches a reasonable size (>72 worker instances)
```
==> /tmp/ray/session_latest/logs/monitor.out <==
2023-02-06 01:49:58,281 WARNING utils.py:1414 -- Unable to connect to GCS at 10.28.49.244:6379. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
Shared connection to 10.28.49.244 closed.
```
I understand the head will need good networking/RAM configuration to handle GCS workload, so below is my config for the cluster:
```
    cpu_head:
        resources: {"CPU": 0, "GPU": 0, "memory": 0}        # not for allocating jobs
        node_config:
            InstanceType: r5dn.4xlarge 
```

and my worker config:
```
    cpu_worker:
        resources: {"CPU": 5, "GPU": 0, "memory": 34359738368}      # advertise as having 5 cpus only
        node_config:
            InstanceType: t3.2xlarge                
```

IMO, the head is big enough, and the cluster is not big either.

Could this be a bug? 

### Versions / Dependencies

ray == 2.2.0
python = 3.8.10

### Reproduction script

Use above nodes config.

### Issue Severity

High: It blocks me from completing my task.
