### ISSUE TITLE
AWS AutoScaler Type Error user_tag_spec["ResourceType"] == "instance"

### ISSUE THREAD

**Issue by jwaller59** [ray-project/ray#32266]
### What happened + What you expected to happen

When executing commands on a Ray Cluster on AWS - the log prints out (scheduler +11m36s) Failed to launch 1 node(s) of type ray.worker.default.

The Yaml file loaded is from the full_example.yaml file within the following location: https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/aws

Deep Diving logs returns this error message:

`TypeError: string indices must be integers
1973    if user_tag_spec["ResourceType"] == "instance":
1972  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 346, in _merge_tag_specs
1971    AWSNodeProvider._merge_tag_specs(tag_specs, user_tag_specs)
1970  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 396, in _create_node
1969    created_nodes_dict = self._create_node(node_config, tags, count)
1968  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/aws/node_provider.py", line 320, in create_node
1967    return self.create_node(node_config, tags, count)
1966  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/node_provider.py", line 151, in create_node_with_resources
1965    node_config, node_tags, count, resources
1964  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/node_launcher.py", line 103, in _launch_node
19632023-02-07 02:56:08,729	INFO node_launcher.py:164 -- NodeLauncher0: Traceback (most recent call last):
19622023-02-07 02:56:08,729	INFO node_launcher.py:164 -- NodeLauncher0: Failed to launch {} node(s) of type ray.worker.default.
19612023-02-07 02:56:08,691	INFO node_launcher.py:164 -- NodeLauncher0: Got 1 nodes to launch.
19602023-02-07 02:56:08,690	INFO monitor.py:384 -- :event_summary:Failed to launch 1 node(s) of type ray.worker.default.
19592023-02-07 02:56:08,690	INFO autoscaler.py:1341 -- StandardAutoscaler: Queue 1 new nodes for launch`

Here is the Cluster Yaml file

```

cluster_name: gain-ray

max_workers: 3

upscaling_speed: 1.0

docker:
  image: "rayproject/ray:latest-cpu " # You can change this to latest-cpu if you don't need GPU support and want a faster startup
  container_name: "ray_container"
  pull_before_run: True

idle_timeout_minutes: 5


provider:
  type: aws
  region: us-west-2
  availability_zone: us-west-2a,us-west-2b
  security_group:
    GroupName: 'Ray-Group'
  cache_stopped_nodes: True # If not present, the default is True.


auth:
  ssh_user: ubuntu

available_node_types:
  ray.head.default:
    resources: {}
    node_config:
      InstanceType: m4.16xlarge
  
      ImageId: ami-0387d929287ab193e
      # You can provision additional disk space with a conf as follows
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 140
  
  ray.worker.default:
    min_workers: 1
    max_workers: 5
    resources: {}
    node_config:
      InstanceType: m5.2xlarge
      ImageId: ami-0387d929287ab193e
      TagSpecifications:
        -ResourceType: "instance"
        Tags:
          - Key: Platform
            Value: "ray"



head_node_type: ray.head.default


cluster_synced_files: []


file_mounts_sync_continuously: False

rsync_exclude:
  - "**/.git"
  - "**/.git/**"


rsync_filter:
  - ".gitignore"


initialization_commands: []


setup_commands:
     - pip install modin
     - pip install ray==2.1.0
     - pip install pyarrow
     - pip install -U fsspec
     - pip install s3fs


head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
  - ray stop
  - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml

worker_start_ray_commands:
  - ray stop
  - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076

```

### Versions / Dependencies

Python 3.7.0
Ray 2.1.0

### Reproduction script

Please provide a script that can be run to reproduce the issue. The script should have no external library dependencies (i.e., use fake or mock data / environments):

### Issue Severity

None

### Issue Severity

None
