### ISSUE TITLE
[Serve] Applications are not deleted if removed from config file

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#32664]
### What happened + What you expected to happen

Applications that are not listed in the config file applied to a cluster are not deleted from the cluster. They should be deleted since the config file represents the goal state of the cluster.

### Versions / Dependencies

master

### Reproduction script

Apply config 1:
```
host: 127.0.0.1
port: 8000

applications:
  - name: "app1"
    route_prefix: "/app1"
    import_path: script.app
  - name: "app2"
    route_prefix: "/app2"
    import_path: script.app
```

Apply config 2:
```
host: 127.0.0.1
port: 8000

applications:
  - name: "app3"
    route_prefix: "/app3"
    import_path: script.app
```

`ray summary actors` will show actors from app1 and app2 still alive.

### Issue Severity

None
