### ISSUE TITLE
[Serve] Deploying a new app while old app is being deleted doesn't work with route_prefix conflicts 

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#33097]
### What happened + What you expected to happen

Deploying a new application that has a duplicate `route_prefix` with an existing application is not allowed. However, if the application it conflicts with is in the process of being deleted, we should not block the new application from being deployed.

This is especially important for deploying config files, since old applications will be in the state `ApplicationStatus.DELETING`, but not yet fully deleted, when the new applications get deployed. This issue will block the new applications from deploying if there are overlapping route prefixes.

### Versions / Dependencies

ray 2.3.0

### Reproduction script

Deploy the following config to `PUT /api/serve/applications/`:
```
applications:
  - name: app1
    route_prefix: /app1
    import_path: any.application
```
Redeploy the following tweaked config:
```
applications:
  - name: app2
    route_prefix: /app1
    import_path: any.application
```
This should teardown the old application and deploy the new application, but instead since `app` is in the process of deleting when `app2` is being deployed, `app2` gets blocked from deploying.

### Issue Severity

None
