### ISSUE TITLE
[State api] Better order of info in the output of ray get actor

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33549]
### What happened + What you expected to happen

Here are my thoughts:
- `state` is definitely important and shouldn't be placed at the bottom. It probably should sit after the `class_name` and can be used together with `death_cause`.
- `Name` probably should be put before `class_name`
- `ray_namespace`seems to be the least important one and should be placed at the bottom?

```
(base) ray@ip-10-0-25-201:~/default$ ray get actors 179c6aa242029f05580ff12105000000
---
actor_id: 179c6aa242029f05580ff12105000000
class_name: ImplicitFunc
death_cause: null
is_detached: false
job_id: '05000000'
name: ''
node_id: ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8
pid: 106264
placement_group_id: 2c7b6116182f06a2e8d941ee0ec405000000
ray_namespace: 73d71afc-0d06-4ad8-9782-8d7eeaa083c1
required_resources:
    CPU_group_0_2c7b6116182f06a2e8d941ee0ec405000000: 1.0
    CPU_group_2c7b6116182f06a2e8d941ee0ec405000000: 1.0
serialized_runtime_env: '{"_ray_commit":"aa02993127d448c7f6a68f7c1d7c941df227e008","env_vars":{"PL_DISABLE_FORK":"1"},"pip":{"packages":["emoji"],"pip_check":false},"working_dir":"gcs://_ray_pkg_87f4c9cda16346337136b10fcbc28854.zip"}'
state: ALIVE
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None
