### ISSUE TITLE
[State api] Better order of info in the output of ray get placement-groups

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33557]
### What happened + What you expected to happen

How about putting `placement_group_id` at the top and `name` and `state` as the second and third?

```
(base) ray@ip-10-0-25-201:~/default$ ray get placement-groups 2827ae222ba3c74668dac816fa7c07000000
---
bundles:
-   bundle_id:
        bundle_index: 0
        placement_group_id: 2827ae222ba3c74668dac816fa7c07000000
    node_id: ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8
    unit_resources:
        CPU: 1.0
creator_job_id: '07000000'
is_detached: false
name: ''
placement_group_id: 2827ae222ba3c74668dac816fa7c07000000
state: REMOVED
stats:
    creation_request_received_ns: '1679436058346398950'
    end_to_end_creation_latency_us: '884'
    highest_retry_delay_ms: 0.0
    scheduling_attempt: 1
    scheduling_latency_us: '865'
    scheduling_started_time_ns: '1679436058346417221'
    scheduling_state: REMOVED
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None
