### ISSUE TITLE
[State api] Better order of info in the output of ray get nodes

### ISSUE THREAD

**Issue by scottsun94** [ray-project/ray#33553]
### What happened + What you expected to happen

Here are my thoughts:
- `end_time_ms` should be placed after `start_time_ms`
- `state` should be placed maybe after `node_ip`
- what is `node_name`?
- what does `node:10.0.25.201: 1.0` mean under `resources_total`?

```
(base) ray@ip-10-0-25-201:~/default$ ray get nodes ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8
---
end_time_ms: 0
node_id: ecbe11d355cc23416ac42f530b854b6ab19671dafda928c281d29fd8
node_ip: 10.0.25.201
node_name: 10.0.25.201
resources_total:
    CPU: 8.0
    memory: 19538300928.0
    node:10.0.25.201: 1.0
    object_store_memory: 9769150464.0
start_time_ms: 1679424616474
state: ALIVE
```

### Versions / Dependencies

nightly

### Reproduction script

n/a

### Issue Severity

None
