### ISSUE TITLE
[serve] Confusing errors when a multi-app config fails to parse correctly

### ISSUE THREAD

**Issue by zcin** [ray-project/ray#33577]
### What happened + What you expected to happen

Currently if the user tries to do `serve deploy config.yaml` and config.yaml fails to parse as `ServeApplicationSchema` *and* `ServeDeploySchema`, then the parsing error from `ServeApplicationSchema` will be shown, to align with the “single-app behavior by default” pattern. However if you change the multi-app config slightly (e.g. have conflicting route prefixes) and it causes errors, you’ll get errors that don’t make sense to you because they are errors from trying to parse as a completely different config format.

### Versions / Dependencies

master: a5e488f76cfc296097383f76a9537d3a30838010

### Reproduction script

Trying to deploy:
```
applications:
  - name: "app1"
    route_prefix: "/app1"
    import_path: demo.app

  - name: "app2"
    route_prefix: "/app1"
    import_path: demo.app
```

Gives error:
```
pydantic.error_wrappers.ValidationError: 4 validation errors for ServeApplicationSchema
import_path
  field required (type=value_error.missing)
applications
  extra fields not permitted (type=value_error.extra)
http_options
  extra fields not permitted (type=value_error.extra)
proxy_location
  extra fields not permitted (type=value_error.extra)
```

### Issue Severity

None
