### ISSUE TITLE
[aws][autoscaler] Allow duplicate entries in NetworkInterfaces

### ISSUE THREAD

**Issue by gilvikra** [ray-project/ray#33586]
### What happened + What you expected to happen

If multiple network interfaces with same subnet id are specified in a node config, I get this error:
Not all subnet IDs found: {}"

Example node config:

```
    node_config:
      InstanceType: trn1.32xlarge
      ImageId: ami-042b39567497b9285
      UserData: "\n#!/bin/bash\nyum install -y htop\nyum install -y amazon-cloudwatch-agent\n/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start  -m ec2 -c default\n"
      IamInstanceProfile:
        Arn: arn:aws:iam::146036223160:instance-profile/ray-autoscaler-v1
      EbsOptimized: True
      Placement:
        GroupName: A9VSPhoton1
      NetworkInterfaces:
        - AssociatePublicIpAddress: False
          DeleteOnTermination: True
          InterfaceType: efa
          SubnetId: subnet-094edaca2285f2d5f
          Groups: [sg-0b7b434da6b0c24c2]
          DeviceIndex: 0
          NetworkCardIndex: 0
        - AssociatePublicIpAddress: False
          DeleteOnTermination: True
          InterfaceType: efa
          SubnetId: subnet-094edaca2285f2d5f
          Groups: [sg-0b7b434da6b0c24c2]
          DeviceIndex: 1
          NetworkCardIndex: 1
```

The piece of code causing trouble : 
ray/python/ray/autoscaler/_private/aws/config.py

```
@lru_cache()
def _get_subnets_or_die(ec2, subnet_ids: Tuple[str]):
    subnets = list(
        ec2.subnets.filter(Filters=[{"Name": "subnet-id", "Values": list(subnet_ids)}])
    )

    # TODO: better error message
    cli_logger.doassert(
        len(subnets) == len(subnet_ids), "Not all subnet IDs found: {}", subnet_ids
    )
    assert len(subnets) == len(subnet_ids), "Subnet ID not found: {}".format(subnet_ids)
    return subnets
```

I think we should convert the list to a set instead for checking on lengths. 

### Versions / Dependencies

ray 2.3.0

### Reproduction script

relevant aws yaml config snippet is already provided

### Issue Severity

High: It blocks me from completing my task.
