### ISSUE TITLE
[Core][Autoscaler][GCP] cache_stopped_node is ignored in GCP provider

### ISSUE THREAD

**Issue by Telemaco019** [ray-project/ray#33671]
### What happened + What you expected to happen

I configuring a Ray cluster on Google Cloud Platform and, in the `cluster.yaml` file I have specified `cache_stopped_nodes: True`. I was expecting the Ray autoscaler to stop/deallocate idle worker nodes, but instead, it deletes the compute instances when scaling down. 

It seems like the field `cache_stopped_nodes` is ignored for GCP provider. I have checked the source code and the [`terminate_node()`](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/_private/gcp/node_provider.py#L183) method of the `GCPNodeProvider` always performs a delete on the Compute Instances, without checking the value of `cache_stopped_nodes`. Is this the intended behaviour? Am I missing something? 

Thank you for the amazing work!

### Versions / Dependencies

I have tested this with Ray 2.3.0 and Ray nightly build (23/03/2023). 

### Reproduction script

This is the provider section of my `cluster.yaml` configuration file:

```yaml
provider:
    type: gcp
    region: us-central1
    availability_zone: us-central1-c
    project_id: <redacted>
    cache_stopped_nodes: True
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
