### ISSUE TITLE
[Clusters] - Cannot switch off rsync during Cluster Launch with `ray up`

### ISSUE THREAD

**Issue by RishabhMalviya** [ray-project/ray#34390]
### What happened + What you expected to happen

I’m trying to launch a single-node ray cluster using ray up.

I have two nodes. One is the node I run ray up from, and the other is to be the head node of the ray cluster. I’ve confirmed that the first node can SSH into the second one.

I’m using exactly the same config.yaml as the one found here - [https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml](https://github.com/ray-project/ray/blob/master/python/ray/autoscaler/local/example-full.yaml). When I run `ray up config.yaml`, I get the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'rsync'
```

I don’t really need the rsync stuff since all the nodes I’m working have a shared NAS mounted on to them. So, I commented out the following fields:
1. `file_mounts`
2. `file_mounts_sync_continuously`
3. `rsync_filter`
4. `cluster_synced_files`

and ran `ray up config.yaml` again, but get the same error.

So, here’s my question - how can I switch off file syncing when running the Cluster Launcher? Or is there an easy way to make my error go away?

### Versions / Dependencies

I'm using Ray 2.3.1 with Python 3.8.9

### Reproduction script

This is the Ray Cluster Launch config that I used (with all the file syncing stuff removed):
```
cluster_name: default

provider:
    type: local
    head_ip: YOUR_HEAD_NODE_HOSTNAME
    worker_ips: []

auth:
    ssh_user: root

min_workers: 0

max_workers: 0

upscaling_speed: 1.0

idle_timeout_minutes: 5

initialization_commands: []

setup_commands: []

head_setup_commands: []

worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --port=6379

worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
```

### Issue Severity

High: It blocks me from completing my task.
