### ISSUE TITLE
[KubeRay] Raylet missing on Ray worker group 

### ISSUE THREAD

**Issue by shinysingh** [ray-project/ray#35022]
### What happened + What you expected to happen

I created a worker pool in my ray cluster, where I run a python script that starts remote tasks. However I’m having trouble submitting any ray tasks there due to the following error. The raylet doesn’t seem to exist. Any idea why this could be?
```
"This node has an IP address of 10.17.4.16, and Ray expects this IP address to be either the GCS address or one of the Raylet addresses. Connected to GCS at ray-autoscaler-head-svc.ray.svc.cluster.local and found raylets at 10.17.1.30, 10.17.7.7, 10.17.0.3 but none of these match this node's IP 10.17.4.16. Are any of these actually a different IP address for the same node?You might need to provide --node-ip-address to specify the IP address that the head should use when sending to this node.
```
My yaml looks like this:
```
  - replicas: 1
    minReplicas: 1
    maxReplicas: 1
    groupName: job-scheduler-group
    rayStartParams:
      block: 'true'
      num-cpus: '0'
      num-gpus: '0'
    #pod template
    template:
      spec:
        initContainers:
        # the env var $RAY_IP is set by the operator if missing, with the value of the head service name
        - name: init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for K8s Service $RAY_IP; sleep 2; done"]
 ```

### Versions / Dependencies

Ray version = 2.3.0
Python version = 3.8

### Reproduction script

I'm running a custom Python script as part of the starting command of the ray node

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
