### ISSUE TITLE
[Core] The job temination is not consistent when the worker gets deleted

### ISSUE THREAD

**Issue by YQ-Wang** [ray-project/ray#35047]
### What happened + What you expected to happen

We deploy Ray head using rayproject/ray-ml:2.4.0-cpu and 1 Ray worker using rayproject/ray-ml:2.4.0-gpu. We submit a Ray job, then delete the Ray worker unforcefully.

## What happened:
![Screenshot 2023-05-04 at 10 08 21](https://user-images.githubusercontent.com/20148872/236276309-1d794288-d394-407d-8923-84412d2bf984.png)
The first job can be terminated as expected, while the second cannot.

## What you expected to happen:
Both jobs get terminated.

### Versions / Dependencies

rayproject/ray-ml:2.4.0-cpu
python 3.7

### Reproduction script

The following steps can be done in a local kind cluster.

Step 1: create ray.yml
```
# ray.yml
# Ray head node service, allowing worker pods to discover the head node to perform the bidirectional communication.
# More contexts can be found at [the Ports configurations doc](https://docs.ray.io/en/latest/ray-core/configure.html#ports-configurations).
apiVersion: v1
kind: Service
metadata:
  name: service-ray-head
  labels:
    app: ray-head
spec:
  clusterIP: None
  ports:
  - name: client
    protocol: TCP
    port: 10001
    targetPort: 10001
  - name: dashboard
    protocol: TCP
    port: 8265
    targetPort: 8265
  - name: gcs-server
    protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: ray-head
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ray-head
  labels:
    app: ray-head
spec:
  # Do not change this - Ray currently only supports one head node per cluster.
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      # If the head node goes down, the entire cluster (including all worker
      # nodes) will go down as well. If you want Kubernetes to bring up a new
      # head node in this case, set this to "Always," else set it to "Never."
      restartPolicy: Always
      terminationGracePeriodSeconds: 60

      # This volume allocates shared memory for Ray to use for its plasma
      # object store. If you do not provide this, Ray will fall back to
      # /tmp which cause slowdowns if it's not a shared memory volume.
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: ray-head
          image: rayproject/ray-ml:2.4.0-cpu
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "--" ]
          args:
            - "ray start --head --port=6379 --num-cpus=$MY_CPU_REQUEST --dashboard-host=127.0.0.1 --object-manager-port=8076 --node-manager-port=8077 --dashboard-agent-grpc-port=8078 --dashboard-agent-listen-port=52365 --block"
          ports:
            - containerPort: 6379 # GCS server
            - containerPort: 10001 # Used by Ray Client
            - containerPort: 8265 # Used by Ray Dashboard
          # This volume allocates shared memory for Ray to use for its plasma
          # object store. If you do not provide this, Ray will fall back to
          # /tmp which cause slowdowns if it's not a shared memory volume.
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          env:
            - name: RAY_BACKEND_LOG_LEVEL
              value: warning
            # This is used in the ray start command so that Ray can spawn the
            # correct number of processes. Omitting this may lead to degraded
            # performance.
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
          resources:
            limits:
              cpu: "2"
              memory: "3G"
            requests:
              # For production use-cases, we recommend specifying integer CPU reqests and limits.
              # We also recommend setting requests equal to limits for both CPU and memory.
              # For this example, we use a 500m CPU request to accomodate resource-constrained local
              # Kubernetes testing environments such as KinD and minikube.
              cpu: "2"
              # The rest state memory usage of the Ray head node is around 1Gb. We do not
              # recommend allocating less than 2Gb memory for the Ray head pod.
              # For production use-cases, we recommend allocating at least 8Gb memory for each Ray container.
              memory: "3G"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ray-worker
  labels:
    app: ray-worker
spec:
  # Change this to scale the number of worker nodes started in the Ray cluster.
  replicas: 1
  selector:
    matchLabels:
      app: ray-worker
  template:
    metadata:
      labels:
        app: ray-worker
    spec:
      restartPolicy: Always
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: ray-worker
        image: rayproject/ray-ml:2.4.0-cpu
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c", "--"]
        args:
          - "ray start --num-cpus=$MY_CPU_REQUEST --address=service-ray-head:6379 --object-manager-port=8076 --node-manager-port=8077 --dashboard-agent-grpc-port=8078 --dashboard-agent-listen-port=52365 --block"
        ports:
          - containerPort: 6379 # GCS server
        # This volume allocates shared memory for Ray to use for its plasma
        # object store. If you do not provide this, Ray will fall back to
        # /tmp which cause slowdowns if it's not a shared memory volume.
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: RAY_BACKEND_LOG_LEVEL
            value: warning
          # This is used in the ray start command so that Ray can spawn the
          # correct number of processes. Omitting this may lead to degraded
          # performance.
          - name: MY_CPU_REQUEST
            valueFrom:
              resourceFieldRef:
                resource: requests.cpu
          # The resource requests and limits in this config are too small for production!
          # It is better to use a few large Ray pods than many small ones.
          # For production, it is ideal to size each Ray pod to take up the
          # entire Kubernetes node on which it is scheduled.
        resources:
          limits:
            cpu: "1"
            memory: "1G"
            # For production use-cases, we recommend specifying integer CPU reqests and limits.
            # We also recommend setting requests equal to limits for both CPU and memory.
            # For this example, we use a 500m CPU request to accomodate resource-constrained local
            # Kubernetes testing environments such as KinD and minikube.
          requests:
            cpu: "500m"
            memory: "1G"
```

Step 2: `kubectl apply -f <path to ray.yml>`
Step 3: `kubectl port-forward <head-pod-id> 8265:8265` and open the dashboard
Step 4: run a sample ray job with the script, you can see a job in the dashboard

```
import ray
import time
import logging

@ray.remote(num_cpus=1, max_calls=1, max_retries=0)
def hello_world():
    time.sleep(600)
    logging.info("hello world")
    return "hello world!!!"

if __name__ == '__main__':
    ray.init()

    print("start main function")
    try:
        print(ray.get(hello_world.options(num_cpus=1).remote()))
    except ray.exceptions.RayError as e:
        print("catch exception")
        print(str(e))
```

Step 5: `kubectl delete pod <worker-pod-id> --grace-period=0 --force=true`

After Step 5, we can sometimes see the job cannot be terminated and sometimes it does get terminated. So the behavior is not consistent.

### Issue Severity

High: It blocks me from completing my task.
