### ISSUE TITLE
Ray: Data - Cannot read json its written to s3

### ISSUE THREAD

**Issue by jbpdl22** [ray-project/ray#35501]
### What happened + What you expected to happen

Using ray to write_json to s3 then read back with read_json from s3.  Both interactive on a remote cluster.  Read fails with: "RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'."

One time, I also say the below message from jupyter but this isn't happening consistently:
[2023-05-18 09:38:09,458 C 2677 4344670] core_worker.cc:993:  Check failed: status.ok() An application is trying to access a Ray object whose owner is unknown(00ffffffffffffffffffffffffffffffffffffff0500000006000000). Please make sure that all Ray objects you are trying to access are part of the current Ray session. Note that object IDs generated randomly (ObjectID.from_random()) or out-of-band (ObjectID.from_binary(...)) cannot be passed as a task argument because Ray does not know which task created them. If this was not how your object ID was generated, please file an issue at https://github.com/ray-project/ray/issues/
*** StackTrace Information ***
0   _raylet.so                          0x0000000115f94f50 _ZN3raylsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_10StackTraceE + 84 ray::operator<<()
1   _raylet.so                          0x0000000115fbf014 _ZN3ray13SpdLogMessage5FlushEv + 220 ray::SpdLogMessage::Flush()
2   _raylet.so                          0x0000000115fbee7c _ZN3ray13SpdLogMe[I 2023-05-18 09:38:11.820 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports

### Versions / Dependencies

Ray 2.4 - Python 3.9.16

### Reproduction script

import ray

ray_init = ray.init(
    "ray://<cluster_ip>:10001",
    namespace="foo"
)

ds = ray.data.from_items(
    [{"foo":"bar"}]
)

ds.write_json("s3://<my_bucket>/ray_bugs/some_json")

ds = ray.data.read_json("s3://<my_bucket>/ray_bugs/some_json")
ds.show()

Result: "RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'."

Running locally works fine.

### Issue Severity

None

**Comment by amogkam** [comment]
How are you starting the remote cluster? 

cc @cadedaniel

**Comment by jbpdl22** [comment]
`ray up -y config.yaml --disable-usage-stats`

(My config is below.  Slightly redacted)

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: aws-example-minimal

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    use_internal_ips: true
    cache_stopped_nodes: false

available_node_types:
  ray.head.default:
    node_config:
      InstanceType: m5.large
      SubnetIds: [subnet-foo]
  worker:
    min_workers: 2
    max_workers: 2
    node_config:
      InstanceType: m5.large
      SubnetIds: [subnet-foo]
      IamInstanceProfile:
        Arn: 'arn:aws:iam::<myaccount>:instance-profile/ray-autoscaler-v1'

head_node_type: ray.head.default

file_mounts: {
    "/tmp/current_branch_sha": "/Users/someone/Projects/project/.git/refs/heads/hackathon_ray",
}

setup_commands:
    - test -e project || git clone git@github.com:company/project.git
    - cd project && git fetch && git checkout `cat /tmp/current_branch_sha`
    - wget -q https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O ~/miniconda.sh
    - /bin/bash ~/miniconda.sh -b -p "$HOME"/anaconda
    - export PATH=$HOME/anaconda/bin:$PATH
    - conda create -y -n project --copy -y -q python=3.9 ipykernel cython ipython_genutils
    - conda activate project && echo 'conda activate project' >> ~/.bashrc
    - python3 --version
    - pip3 install 'poetry==1.3.1'
    - poetry --version
    - poetry -C project export -E ml -E spark --without-hashes -f constraints.txt -o /home/ubuntu/constraints.txt
    - pip3 install /home/ubuntu/project[ml,spark] -c /home/ubuntu/constraints.txt
```
