### ISSUE TITLE
[Autoscaler] autoscaler on kuberay deletes pod with workloads 

### ISSUE THREAD

**Issue by saswatac** [ray-project/ray#35560]
### What happened + What you expected to happen

I have deployed an autoscaling cluster using kuberay. It looks like in our cluster sometimes there are failures in connecting to the k8 API server. When that happens, the autoscaler deletes pods.

Autoscaler logs

```


2023-05-16 21:36:59.623 | ======== Autoscaler status: 2023-05-16 16:06:59.622550 ======== |  
-- | -- | --
  |   | 2023-05-16 21:36:59.623 | Node status |  
  |   | 2023-05-16 21:36:59.623 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:36:59.623 | Healthy: |  
  |   | 2023-05-16 21:36:59.623 | 1 head-group |  
  |   | 2023-05-16 21:36:59.623 | 2 default-worker |  
  |   | 2023-05-16 21:36:59.623 | Pending: |  
  |   | 2023-05-16 21:36:59.623 | (no pending nodes) |  
  |   | 2023-05-16 21:36:59.623 | Recent failures: |  
  |   | 2023-05-16 21:36:59.623 | (no failures) |  
  |   | 2023-05-16 21:36:59.623 |   |  
  |   | 2023-05-16 21:36:59.623 | Resources |  
  |   | 2023-05-16 21:36:59.623 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:36:59.623 | Usage: |  
  |   | 2023-05-16 21:36:59.623 | 6.0/8.0 CPU |  
  |   | 2023-05-16 21:36:59.623 | 0.00/88.000 GiB memory |  
  |   | 2023-05-16 21:36:59.623 | 0.01/26.245 GiB object_store_memory |  
  |   | 2023-05-16 21:36:59.623 |   |  
  |   | 2023-05-16 21:36:59.623 | Demands: |  
  |   | 2023-05-16 21:36:59.623 | (no resource demands) |  
  |   | 2023-05-16 21:42:40.886 | 2023-05-16 16:12:40,886	ERROR autoscaler.py:1067 -- StandardAutoscaler: Error parsing config. |  
  |   | 2023-05-16 21:42:40.887 | Traceback (most recent call last): |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen |  
  |   | 2023-05-16 21:42:40.887 | httplib_response = self._make_request( |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request |  
  |   | 2023-05-16 21:42:40.887 | six.raise_from(e, None) |  
  |   | 2023-05-16 21:42:40.887 | File "<string>", line 3, in raise_from |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request |  
  |   | 2023-05-16 21:42:40.887 | httplib_response = conn.getresponse() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse |  
  |   | 2023-05-16 21:42:40.887 | response.begin() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 316, in begin |  
  |   | 2023-05-16 21:42:40.887 | version, status, reason = self._read_status() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 285, in _read_status |  
  |   | 2023-05-16 21:42:40.887 | raise RemoteDisconnected("Remote end closed connection without" |  
  |   | 2023-05-16 21:42:40.887 | http.client.RemoteDisconnected: Remote end closed connection without response |  
  |   | 2023-05-16 21:42:40.887 |   |  
  |   | 2023-05-16 21:42:40.887 | During handling of the above exception, another exception occurred: |  
  |   | 2023-05-16 21:42:40.887 |   |  
  |   | 2023-05-16 21:42:40.887 | Traceback (most recent call last): |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 489, in send |  
  |   | 2023-05-16 21:42:40.887 | resp = conn.urlopen( |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen |  
  |   | 2023-05-16 21:42:40.887 | retries = retries.increment( |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment |  
  |   | 2023-05-16 21:42:40.887 | raise six.reraise(type(error), error, _stacktrace) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 734, in reraise |  
  |   | 2023-05-16 21:42:40.887 | raise value.with_traceback(tb) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen |  
  |   | 2023-05-16 21:42:40.887 | httplib_response = self._make_request( |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 445, in _make_request |  
  |   | 2023-05-16 21:42:40.887 | six.raise_from(e, None) |  
  |   | 2023-05-16 21:42:40.887 | File "<string>", line 3, in raise_from |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 440, in _make_request |  
  |   | 2023-05-16 21:42:40.887 | httplib_response = conn.getresponse() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse |  
  |   | 2023-05-16 21:42:40.887 | response.begin() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 316, in begin |  
  |   | 2023-05-16 21:42:40.887 | version, status, reason = self._read_status() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/lib/python3.8/http/client.py", line 285, in _read_status |  
  |   | 2023-05-16 21:42:40.887 | raise RemoteDisconnected("Remote end closed connection without" |  
  |   | 2023-05-16 21:42:40.887 | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) |  
  |   | 2023-05-16 21:42:40.887 |   |  
  |   | 2023-05-16 21:42:40.887 | During handling of the above exception, another exception occurred: |  
  |   | 2023-05-16 21:42:40.887 |   |  
  |   | 2023-05-16 21:42:40.887 | Traceback (most recent call last): |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/autoscaler.py", line 982, in reset |  
  |   | 2023-05-16 21:42:40.887 | new_config = self.config_reader() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/kuberay/autoscaling_config.py", line 59, in __call__ |  
  |   | 2023-05-16 21:42:40.887 | ray_cr = self._fetch_ray_cr_from_k8s_with_retries() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/kuberay/autoscaling_config.py", line 71, in _fetch_ray_cr_from_k8s_with_retries |  
  |   | 2023-05-16 21:42:40.887 | return self._fetch_ray_cr_from_k8s() |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/ray/autoscaler/_private/kuberay/autoscaling_config.py", line 85, in _fetch_ray_cr_from_k8s |  
  |   | 2023-05-16 21:42:40.887 | result = requests.get( |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 73, in get |  
  |   | 2023-05-16 21:42:40.887 | return request("get", url, params=params, **kwargs) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request |  
  |   | 2023-05-16 21:42:40.887 | return session.request(method=method, url=url, **kwargs) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 587, in request |  
  |   | 2023-05-16 21:42:40.887 | resp = self.send(prep, **send_kwargs) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 701, in send |  
  |   | 2023-05-16 21:42:40.887 | r = adapter.send(request, **kwargs) |  
  |   | 2023-05-16 21:42:40.887 | File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 547, in send |  
  |   | 2023-05-16 21:42:40.887 | raise ConnectionError(err, request=request) |  
  |   | 2023-05-16 21:42:40.887 | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) |  
  |   | 2023-05-16 21:42:41.393 | 2023-05-16 16:12:41,392	INFO autoscaler.py:386 -- |  
  |   | 2023-05-16 21:42:41.393 | ======== Autoscaler status: 2023-05-16 16:12:41.392720 ======== |  
  |   | 2023-05-16 21:42:41.393 | Node status |  
  |   | 2023-05-16 21:42:41.393 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:41.393 | Healthy: |  
  |   | 2023-05-16 21:42:41.393 | 1 head-group |  
  |   | 2023-05-16 21:42:41.393 | 2 default-worker |  
  |   | 2023-05-16 21:42:41.393 | Pending: |  
  |   | 2023-05-16 21:42:41.393 | (no pending nodes) |  
  |   | 2023-05-16 21:42:41.393 | Recent failures: |  
  |   | 2023-05-16 21:42:41.393 | (no failures) |  
  |   | 2023-05-16 21:42:41.393 |   |  
  |   | 2023-05-16 21:42:41.393 | Resources |  
  |   | 2023-05-16 21:42:41.393 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:41.393 | Usage: |  
  |   | 2023-05-16 21:42:41.393 | 6.0/8.0 CPU |  
  |   | 2023-05-16 21:42:41.393 | 0.00/88.000 GiB memory |  
  |   | 2023-05-16 21:42:41.393 | 0.01/26.245 GiB object_store_memory |  
  |   | 2023-05-16 21:42:41.393 |   |  
  |   | 2023-05-16 21:42:41.393 | Demands: |  
  |   | 2023-05-16 21:42:41.393 | (no resource demands) |  
  |   | 2023-05-16 21:42:41.858 | 2023-05-16 16:12:41,858	INFO autoscaler.py:544 -- StandardAutoscaler: Terminating the node with id staging-worker-default-worker-jqgfm and ip 10.244.44.7. (idle) |  
  |   | 2023-05-16 21:42:41.891 | 2023-05-16 16:12:41,891	INFO autoscaler.py:498 -- Node last used: Tue May 16 16:07:06 2023. |  
  |   | 2023-05-16 21:42:41.942 | 2023-05-16 16:12:41,941	INFO autoscaler.py:632 -- Draining 1 raylet(s). |  
  |   | 2023-05-16 21:42:42.753 | 2023-05-16 16:12:42,753	INFO monitor.py:367 -- :event_summary:Removing 1 nodes of type default-worker (idle). |  
  |   | 2023-05-16 21:42:48.005 | 2023-05-16 16:12:48,004	INFO load_metrics.py:160 -- LoadMetrics: Removed ip: 10.244.44.7. |  
  |   | 2023-05-16 21:42:48.005 | 2023-05-16 16:12:48,005	INFO load_metrics.py:163 -- LoadMetrics: Removed 1 stale ip mappings: {'10.244.44.7'} not in {'10.244.40.90', '10.244.3.16'} |  
  |   | 2023-05-16 21:42:48.174 | 2023-05-16 16:12:48,174	INFO autoscaler.py:386 -- |  
  |   | 2023-05-16 21:42:48.174 | ======== Autoscaler status: 2023-05-16 16:12:48.174108 ======== |  
  |   | 2023-05-16 21:42:48.174 | Node status |  
  |   | 2023-05-16 21:42:48.174 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:48.174 | Healthy: |  
  |   | 2023-05-16 21:42:48.174 | 1 head-group |  
  |   | 2023-05-16 21:42:48.174 | 1 default-worker |  
  |   | 2023-05-16 21:42:48.174 | Pending: |  
  |   | 2023-05-16 21:42:48.174 | (no pending nodes) |  
  |   | 2023-05-16 21:42:48.174 | Recent failures: |  
  |   | 2023-05-16 21:42:48.174 | (no failures) |  
  |   | 2023-05-16 21:42:48.174 |   |  
  |   | 2023-05-16 21:42:48.174 | Resources |  
  |   | 2023-05-16 21:42:48.174 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:48.174 | Usage: |  
  |   | 2023-05-16 21:42:48.174 | 4.0/4.0 CPU |  
  |   | 2023-05-16 21:42:48.174 | 0.00/48.000 GiB memory |  
  |   | 2023-05-16 21:42:48.174 | 0.00/14.271 GiB object_store_memory |  
  |   | 2023-05-16 21:42:48.174 |   |  
  |   | 2023-05-16 21:42:48.174 | Demands: |  
  |   | 2023-05-16 21:42:48.174 | {'CPU': 1.0}: 2+ pending tasks/actors |  
  |   | 2023-05-16 21:42:48.835 | 2023-05-16 16:12:48,835	INFO autoscaler.py:1324 -- StandardAutoscaler: Queue 1 new nodes for launch |  
  |   | 2023-05-16 21:42:48.835 | 2023-05-16 16:12:48,835	INFO node_launcher.py:131 -- BaseNodeLauncher: Got 1 nodes to launch. |  
  |   | 2023-05-16 21:42:48.835 | 2023-05-16 16:12:48,835	INFO node_launcher.py:131 -- BaseNodeLauncher: Launching 1 nodes, type default-worker. |  
  |   | 2023-05-16 21:42:49.175 | 2023-05-16 16:12:49,175	INFO monitor.py:367 -- :event_summary:Adding 1 nodes of type default-worker. |  
  |   | 2023-05-16 21:42:54.760 | 2023-05-16 16:12:54,760	INFO autoscaler.py:386 -- |  
  |   | 2023-05-16 21:42:54.760 | ======== Autoscaler status: 2023-05-16 16:12:54.759925 ======== |  
  |   | 2023-05-16 21:42:54.760 | Node status |  
  |   | 2023-05-16 21:42:54.760 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:54.760 | Healthy: |  
  |   | 2023-05-16 21:42:54.760 | 1 head-group |  
  |   | 2023-05-16 21:42:54.760 | 1 default-worker |  
  |   | 2023-05-16 21:42:54.760 | Pending: |  
  |   | 2023-05-16 21:42:54.760 | IP not yet assigned: default-worker, pending |  
  |   | 2023-05-16 21:42:54.760 | Recent failures: |  
  |   | 2023-05-16 21:42:54.760 | (no failures) |  
  |   | 2023-05-16 21:42:54.760 |   |  
  |   | 2023-05-16 21:42:54.760 | Resources |  
  |   | 2023-05-16 21:42:54.760 | --------------------------------------------------------------- |  
  |   | 2023-05-16 21:42:54.760 | Usage: |  
  |   | 2023-05-16 21:42:54.760 | 4.0/4.0 CPU |  
  |   | 2023-05-16 21:42:54.760 | 0.00/48.000 GiB memory |  
  |   | 2023-05-16 21:42:54.760 | 0.00/14.271 GiB object_store_memory |  
  |   | 2023-05-16 21:42:54.760 |   |  
  |   | 2023-05-16 21:42:54.760 | Demands: |  
  |   | 2023-05-16 21:42:54.760 | {'CPU': 1.0}: 2+ pending tasks/actors

```

* 2023-05-16 21:36:59.623 , the status is healthy, and there are two workers.
* 2023-05-16 21:42:40.886, exception occurs.
* 2023-05-16 21:42:41.393 starts back up, reports correct status
*  2023-05-16 21:42:41.858 decides to terminate a worker, thinking it is idle
* 2023-05-16 21:42:48.174 identifies pending , and starts a new node.

This issue, together with https://github.com/ray-project/ray/issues/33799 means our deployed API is unstable - as soon as this issue happens, the deployment starts failing.

### Versions / Dependencies

2.0.0

### Reproduction script

n/a

### Issue Severity

High: It blocks me from completing my task.

**Comment by saswatac** [comment]
perhaps the retry condition https://github.com/ray-project/ray/blob/ray-2.4.0/python/ray/autoscaler/_private/kuberay/autoscaling_config.py#L72 should be more broad?

**Comment by kevin85421** [comment]
cc @scv119 would you mind triaging this issue?

**Comment by DmitriGekhtman** [comment]
@saswatac would you mind share the configs you're using to launch the cluster?

With that information, it might be possible to reproduce the issue by injecting a failure.

**Comment by saswatac** [comment]
@DmitriGekhtman here is the raycluster spec. Note I have modified it a bit from what I exactly used, as it was customized having some credentials and sidecars containers. But it should show the ray specific settings.

```
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: prod-3-8-0-dev0
  namespace: ws-nc-internal
spec:
  autoscalerOptions:
    idleTimeoutSeconds: 60
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    upscalingMode: Default
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      block: "true"
      dashboard-host: 0.0.0.0
      metrics-export-port: "8080"
      num-cpus: "0"
    serviceType: ClusterIP
    template:
      spec:
        containers:
        - env:
          - name: RAY_RUNTIME_ENV_TEMPORARY_REFERENCE_EXPIRATION_S
            value: "3600"
          - name: KUBERNETES_NAMESPACE
            value: ws-nc-internal
          - name: RAY_USAGE_STATS_ENABLED
            value: "0"
          image: neuralconcept.azurecr.io/ncs-workspace-full:nightly
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs
            protocol: TCP
          - containerPort: 10001
            name: client
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 8000
            name: serve
            protocol: TCP
          - containerPort: 6999
            name: redis
            protocol: TCP
          - containerPort: 8080
            name: metrics
            protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 4Gi
            requests:
              cpu: 1
              memory: 4Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-logs
  rayVersion: 2.0.0
  workerGroupSpecs:
  - groupName: default-worker
    maxReplicas: 2
    minReplicas: 1
    rayStartParams:
      block: "true"
      metrics-export-port: "8080"
    replicas: 1
    template:
      spec:
        containers:
        - env:
          - name: RAY_RUNTIME_ENV_TEMPORARY_REFERENCE_EXPIRATION_S
            value: "3600"
          - name: TF_FORCE_GPU_ALLOW_GROWTH
            value: "true"
          image: neuralconcept.azurecr.io/ncs-workspace:nightly
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-node
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          resources:
            limits:
              cpu: 4
              memory: 4Gi
            requests:
              cpu: 4
              memory: 4Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: ray-logs
          - mountPath: /cache
            name: local-ssd
        imagePullSecrets:
        - name: user-repo-secret
        - name: ncs-repo-secret
        initContainers:
        - command:
          - sh
          - -c
          - until nc -zv $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local
            6379; do echo waiting for myservice; sleep 2; done
          image: neuralconcept.azurecr.io/ncs-workspace:nightly
          name: init-myservice
        nodeSelector: {}
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
        serviceAccountName: user-workspace-sa
        tolerations:
        - effect: NoSchedule
          key: nc-workspace
          operator: Equal
          value: "true"
        volumes:
        - emptyDir: {}
          name: data-volume
        - hostPath:
            path: /mnt/raid-disks/disk0
          name: local-ssd
        - emptyDir: {}
          name: ray-logs
status:
  availableWorkerReplicas: 2
  desiredWorkerReplicas: 1
  endpoints:
    client: "10001"
    dashboard: "8265"
    gcs: "6379"
    metrics: "8080"
    redis: "6999"
    serve: "8000"
  lastUpdateTime: "2023-05-26T00:16:56Z"
  maxWorkerReplicas: 2
  minWorkerReplicas: 1
  state: ready
```
