### ISSUE TITLE
[Serve] [Dashboard] Serve error contains `colorama` characters

### ISSUE THREAD

**Issue by shrekris-anyscale** [ray-project/ray#35678]
### What happened + What you expected to happen

Serve errors on the dashboard sometimes contain `colorama` characters throughout the text. See reproduction script.

I expect these characters to be removed when the error is displayed on the dashboard.

### Versions / Dependencies

Ray on the latest master.

### Reproduction script

* Serve config

```yaml
import_path: "fruit:deployment_graph2"  # Fake import path
runtime_env:
  working_dir: "https://github.com/ray-project/test_dag/archive/81c1912273e512a3756e359e08900f0e5b2e1811.zip"
```

* `serve status` output (contains no `colorama` characters)

```console
name: default
app_status:
  status: DEPLOY_FAILED
  message: |-
    Deploying app 'default' failed:
    ray::deploy_serve_application() (pid=17820, ip=10.103.209.171)
      File "/Users/shrekris/Desktop/ray/python/ray/serve/controller.py", line 839, in deploy_serve_application
        app = call_app_builder_with_args_if_necessary(import_attr(import_path), args)
    AttributeError: module 'fruit' has no attribute 'deployment_graph2'
  deployment_timestamp: 1684873608.110614
deployment_statuses: []
```

* Ray dashboard (contains `colorama` characters)

<img width="1414" alt="Screen Shot 2023-05-23 at 1 28 33 PM" src="https://github.com/ray-project/ray/assets/92341594/3b4b2d4e-80a7-4f5d-95fc-760581ffb4b4">

### Issue Severity

Low: It annoys or frustrates me.
