### ISSUE TITLE
Issue with <Ray component: Monitoring and Debugging>: setting metrics-export-port will randomly lose data

### ISSUE THREAD

**Issue by benerain** [ray-project/ray#36059]
### What happened + What you expected to happen

if i start ray using the command `ray start --head --metrics-export-port=8080 ` , and use the `prometheus.yml` like this
```
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ray'
    static_configs: 
      - targets: ['localhost:8080']

```
to start prometheus,  only less than 500 out of 500 submitted tasks' metric are recorded in Prometheus. However, if i start ray using the command `ray start --head` and deploy Prometheus using the following configuration: 

```
scrape_configs:
 - job_name: 'ray'
   file_sd_configs: - files:
      -'/tmp/ray/prom_metrics_service_di scovery.json'
```

all the metrics are properly recorded. Therefore,  I suspect there may be a bug with `metrics-export-port` option 

### Versions / Dependencies

ray, version 2.3.0
Python 3.9.15
macOs 12.6.4 M1 chip

### Reproduction script

Note: Metric loss is less likely to occur when starting a new Ray instance. However, as the Ray instance continues to run and more tasks are submitted, metric loss may become more apparent. 

Here is the script I use to submit test tasks.

Note: Metric loss is less likely to occur when starting a new Ray instance. However, as the Ray instance continues to run and more tasks are submitted, metric loss may become more apparent. Usually, on my computer, after submitting the following script 2-3 times I'll encounter issues with the loss metrics. (To differentiate between each submitted task, please modify the name in the _users list)

```py
import ray
import numpy as np

ray.init()

@ray.remote
def my_task(user, runid):
    x = np.random.randn(1000, 1000)
    for i in range(10):
        x = np.dot(x, x)
    print(f"Task for User {user}, RunID {runid} is running.")
    return f"Task for User {user}, RunID {runid} is done."

_users = ['liyujia_0604_4', 'liyujia_0604_5','liyujia_0604_6']
tasks_per_user = 500
object_refs = []

for user in _users:
    for j in range(tasks_per_user):
        object_refs.append(my_task.options(name=f"{user}_runid{j}").remote(user, j))

results = ray.get(object_refs)

for result in results:
    print(result)
```
I submitted 500 tasks, but I can only query 353 of them in Prometheus: 
<img width="961" alt="截屏2023-06-04 14 25 39" src="https://github.com/ray-project/ray/assets/21291632/f283edce-830a-41ad-ac28-c3b8b1eafcf1">

 deploying Prometheus using json configuration will not result in missing metrics on my computer

### Issue Severity

None
