### ISSUE TITLE
[core] worker-specific idleTimeoutSeconds

### ISSUE THREAD

**Issue by ProjitB** [ray-project/ray#36888]
### Description

`idleTimeoutSeconds` is an autoscaler option right now. Ex.
```
    autoscalerOptions:
      upscalingMode: Default
      # idleTimeoutSeconds is the number of seconds to wait before scaling down a worker pod which is not using Ray resources.
      idleTimeoutSeconds: 86400 
```

It would nice if this were configurable per worker type. 

### Use case

Workers are in general useful to keep around to increase total capacity of ray object store memory.
Some workers run gpu loads and are more expensive to keep around, while cpu machines are not as expensive. Being able to rapidly gc gpu nodes while keeping around cpu nodes would be great
