### ISSUE TITLE
How to change the exploration rate while using tune.

### ISSUE THREAD

**Issue by mynkpl1998** [ray-project/ray#3696]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Ray installed from (source or binary)**: Binary
- **Ray version**: 0.6.1
- **Python version**: 3.6.7

### Describe the problem
I am using DQN to train an agent, After some iteration, I want to set the exploration rate to some desired value. The way I do it without tune is, restore the most recent check pointed model and the following one line of code allow me to set desired epsilon (exploration rate) values.
```

trainer = DQNAgent(env="tsim-v0", config={
        "multiagent": {
        "num_atoms": 51,
    })

trainer.restore("checkpoint_10700/checkpoint-10700")
trainer.optimizer.foreach_evaluator(lambda ev: ev.for_policy(lambda pi:pi.set_epsilon(0.0), policy_id="age_policy"))
```

But as suggested in the documentation, we should run experiments using tune. Hence, I am not sure how can I do the same thing when using tune. 

### Source code / logs

Training Code using tune.
```

def policy_mapper(agent_id):

    if agent_id == "age":
        return "age_policy"
    else:
        return "plan_policy"


if __name__ == "__main__":

    ray.init()

    with open("dqn_train_tune.yaml", "r") as handle:
    	exp_config = yaml.load(handle)


    env_creator_name = "tsim-v0"
    register_env(env_creator_name, lambda config: tsim())
    tmp_env = tsim()

    age_obs_space = tmp_env.age_obs_space
    plan_obs_space = tmp_env.plan_obs_space
    age_act_space = tmp_env.age_act_space
    plan_act_space = tmp_env.plan_act_space

    
    def gen_policy(agent):

        config = {
            "gamma": 0.99
        }

        if agent == "age":
            obs = age_obs_space
            acts = age_act_space
        else:
            obs = plan_obs_space
            acts = plan_act_space

        return (DQNPolicyGraph, obs, acts, {})

    policy_graphs = {
        "age_policy": gen_policy("age"),
        "plan_policy": gen_policy("plan")
    }

    exp_config['apex-age-comm']["config"]["multiagent"]["policy_graphs"] = policy_graphs
    exp_config['apex-age-comm']["config"]["multiagent"]["policy_mapping_fn"] = tune.function(policy_mapper)

    run_experiments(exp_config)
```
   
Config File
```

dqn-age-comm:
  run: DQN
  env: tsim-v0
  checkpoint_freq: 100
  #restore: /home/sumantra/ray_results/apex-age-comm/DQN_tsim-v0_0_2019-01-04_17-51-41tej38kza/checkpoint_4700/checkpoint-4700
  config:
    n_step: 3
    horizon: 1000
    num_gpus: 1
    num_workers: 4
    target_network_update_freq: 50000    
    train_batch_size: 64
    schedule_max_timesteps: 3000000
    exploration_fraction: 0.1
    exploration_final_eps: 0.01
    learning_starts: 50000
    buffer_size: 1000000
    num_atoms: 51
    multiagent:
      policy_graphs: None
      policy_mapping_fn: None
    gamma: 0.99

```
