### ISSUE TITLE
[Serve] Serving the model throws ValueError: unknown enum label "DEPLOYMENT_STATUS_DeploymentStatus.UPDATING"

### ISSUE THREAD

**Issue by xeniyandkn** [ray-project/ray#37933]
### What happened + What you expected to happen

After starting Ray service and serving the model, I keep getting the following error.
`ValueError: unknown enum label "DEPLOYMENT_STATUS_DeploymentStatus.UPDATING"`

<img width="957" alt="Screenshot 2023-07-31 at 11 55 09 AM" src="https://github.com/ray-project/ray/assets/93728505/da5d2fed-e3f3-4c1a-840f-34d594a4f285">

I am trying to serve `"tiiuae/falcon-40b"` model.

### Versions / Dependencies

Ray, version 2.5.1
Python 3.10.11
Mac OS Ventura 13.2.1

### Reproduction script

The following is the code that I run using `serve deploy config.yaml`

```
# This file was generated using the `serve build` command on Ray v2.5.1.
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: serve_model
  route_prefix: /serve
  import_path: serve_model:serve_model_app
  runtime_env: {}
  deployments:
  - name: ModelServer
    num_replicas: 1
    health_check_timeout_s: 300
    ray_actor_options:
      num_cpus: 8
      num_gpus: 1
```

### Issue Severity

High: It blocks me from completing my task.
