### ISSUE TITLE
[Serve] Serving a model and getting Deployment has 1 replicas that have taken more than 30s to initialize. This may be caused by a slow __init__ or reconfigure method. 

### ISSUE THREAD

**Issue by xeniyandkn** [ray-project/ray#37950]
### What happened + What you expected to happen

I am trying to serve a heavier model , falcon 7b or 40b, but I keep getting this timeout issue: `Deployment serve_model_ModelServer has 1 replicas that have taken more than 30s to initialize. This may be caused by a slow __init__ or reconfigure method.`. Is something wrong with my yaml config set up? Is this the best way to allocate the resources for a heavier model?

`config.yaml`

```

proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: serve_model
  route_prefix: /serve
  import_path: serve_model:serve_model_app
  runtime_env: {}
  deployments:
  - name: ModelServer
    num_replicas: 1
    health_check_timeout_s: 30
    ray_actor_options:
      num_cpus: 0.2
```

### Versions / Dependencies

Python 3.11
Ray 2.6.1

### Reproduction script

the following is the code of the model __init__ method:

```import ray
import torch
import logging

from starlette.requests import Request
from transformers import BartTokenizer, BartForConditionalGeneration

LOGGER = logging.getLogger(__name__)

def get_torch_device():
    if torch.cuda.is_available():
        return torch.device("cuda")
    elif torch.backends.mps.is_available():
        return torch.device("mps")
    else:
        return torch.device("cpu")


@ray.serve.deployment
class ModelServer:
    def __init__(self, model_id: str):
        # Load model
        device = get_torch_device()
        self.model_id = model_id
        self.model = BartForConditionalGeneration.from_pretrained(model_id).to(device)
        self.tokenizer = BartTokenizer.from_pretrained(model_id)


    def generate_text(self, input_text):
        # Tokenize the input text
        input_tokens = self.tokenizer(input_text, return_tensors='pt')

        # Move the input tokens to the same device as the model
        input_tokens = input_tokens.to(self.model.device)

        # Generate text using the fine-tuned model
        output_tokens = self.model.generate(**input_tokens, max_new_tokens=200)

        # Decode the generated tokens to text
        output_text = self.tokenizer.decode(output_tokens[0], skip_special_tokens=True)
        return output_text

    async def __call__(self, http_request: Request) -> str:
        data = await http_request.json()
        output = self.generate_text(data["inputs"])
        LOGGER.warning(f"Output: {output}")
        return output
```

### Issue Severity

High: It blocks me from completing my task.
