### ISSUE TITLE
[Serve] What is the model API URL after it's been served 

### ISSUE THREAD

**Issue by xeniyandkn** [ray-project/ray#38016]
### What happened + What you expected to happen

I am trying to find the API URL of the model that I am serving using Ray. 
<img width="1716" alt="Screenshot 2023-08-02 at 1 57 58 PM" src="https://github.com/ray-project/ray/assets/93728505/ef7ba875-4a20-439c-9335-b2e46d273ef6">

The model looks good and the status is healthy. Here's the config of my yaml file:
```
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: serve_falcon_model
  route_prefix: /serve_falcon
  import_path: serve_falcon_model:serve_falcon_model_app
  runtime_env: {}
  deployments:
  - name: ModelServer
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0.2
      # num_gpus: 0
```

### Versions / Dependencies

Ray 2.6.1
Python 3.11.4
MacOS Ventura 13.2.1

### Reproduction script

According to this config, I see that the model is served and healthy on `0.0.0.0:8000/serve_falcon` but when I run a simple script question, the output never resolves:
```
    prompt = "How do I cook fried rice?"
    sample_input = {"prompt": prompt, "stream": True}
    output = requests.post("http://0.0.0.0:8000/serve_falcon", json=sample_input)
    for line in output.iter_lines():
        print(line.decode("utf-8"))
```

### Issue Severity

High: It blocks me from completing my task.
