### ISSUE TITLE
[Serve] fail to detect changes in code and re-deploy 

### ISSUE THREAD

**Issue by JalinWang** [ray-project/ray#38714]
### What happened + What you expected to happen

After making changes to the code, running `serve deploy` won't re-deploy it.
I'm sure the submission is successful because the first line is updated while the second line remains, i.e., the deployment is updated but the actor is not updated.
![image](https://github.com/ray-project/ray/assets/20621784/aaea4ab6-ca0b-4f3b-bc70-3706a41838d7)

### Versions / Dependencies

ray=2.6.1

### Reproduction script

hello.py
```
from ray import serve
from ray.serve.drivers import DAGDriver
from ray.serve.deployment_graph import InputNode


@serve.deployment
def hello(name: str):
    return f"hello world!" # change here

with InputNode() as name:
    greeter = hello.bind(name)

app = DAGDriver.options(route_prefix="/hello").bind(greeter)
```
config.yaml
```

# This file was generated using the `serve build` command on Ray v2.6.2.

# export RAY_AGENT_ADDRESS='http://10.198.8.148:52365'
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8003

applications:
- name: Hello
  route_prefix: /hello
  import_path: hello:app
  runtime_env: {}
  deployments:
  - name: hello
    ray_actor_options:
      num_cpus: 0.0
  - name: DAGDriver
    ray_actor_options:
      num_cpus: 0.0
```
then `serve deploy config.yaml`
After changing `hello.py`, re-deploy. Check the output, it remains the same.
![image](https://github.com/ray-project/ray/assets/20621784/90d793d8-93b1-4019-b220-ee2657ead816)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
