### ISSUE TITLE
[autoscaler] Autoscaler hangs forever on non-zero exit code command

### ISSUE THREAD

**Issue by richardliaw** [ray-project/ray#3957]
### Describe the problem
Autoscaler hangs when any `ssh_cmd` has a non-zero exit code.

### Source code / logs

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 0
max_workers: 0

provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2b

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

head_node:
    InstanceType: m4.10xlarge
    ImageId: ami-3b6bce43  # Amazon Deep Learning AMI (Ubuntu)

setup_commands:
    - error me
```

cc @ericl @ls-daniel
