### ISSUE TITLE
Custom provider keys in the configuration YAML?

### ISSUE THREAD

**Issue by zbarry** [ray-project/ray#4071]
Wondering if it would be possible in the case where you are building your own `NodeProvider` to add custom keys/values for its configuration. Given that it appears the only way to pass options to your `NodeProvider` subclass is via the constructor `(provider_config, cluster_name)`, it would be nice to be able to provide custom configuration options.

Currently there is a check for the `provider` key looking like:

```yaml
    # Cloud-provider specific configuration.
    "provider": (
        {
            "type": (str, REQUIRED),  # e.g. aws
            "region": (str, OPTIONAL),  # e.g. us-east-1
            "availability_zone": (str, OPTIONAL),  # e.g. us-east-1a
            "module": (str,
                       OPTIONAL),  # module, if using external node provider
            "project_id": (None, OPTIONAL),  # gcp project id, if using gcp
            "head_ip": (str, OPTIONAL),  # local cluster head node
            "worker_ips": (list, OPTIONAL),  # local cluster worker nodes
            "use_internal_ips": (bool, OPTIONAL),  # don't require public ips
        },
        REQUIRED),
```

If there could be an additional `extra`, `custom`, `config`, whatever optional key in that dictionary that is passed through without Ray interpretation of it, that would be pretty helpful for the various types of situations you might finding yourself coding up `NodeProvider`s for.
