### ISSUE TITLE
[Serve] Custom Scaling

### ISSUE THREAD

**Issue by GeneDer** [ray-project/ray#41135]
This RFC outlines a proposal to add support for custom scaling. This will provide a new way for users to proactively scaling deployment replicas freely based on any metrics and provide better quality of service.

## Problem
The current autoscaling in Serve only look at request queue size for each deployment and scale based off the traffic reactively. Users have needs for a more proactively way to scale the deployments and on metrics other than the request queue size. Few example usecases including but not limited to:
- Scheduled burst requests coming in at a specific time of day. Serve should be able to scale replicas proactively before the burst to handle the requests
- Users who uses third party autoscaler (e.g. [keda](https://keda.sh/)) or metrics stored outside of Ray (e.g. CloudWatch, Data Dog...etc) wants a way to integrate with Serve and scale accordingly before the traffic is hit
- QoS for example X clients sharing one replica and need to scale proactively based on outside metrics to ensure the quality of service will be met

## Proposal
Users will specify the serve.yaml like below
```
# serve.yaml
applications:
  - name: default
    import_path: resnet:app
    deployments:
    - name: Model
      max_concurrent_queries: 5
      autoscaling_config:
        target_num_ongoing_requests_per_replica: 1
        min_replicas: 0
        initial_replicas: 0
        max_replicas: 200
        custom_scaling: autoscaling_helpers:resnet_app  <-- New config to determine the scale for this deployment
```

And they can define the `custom_scaling` function like any of the ones below. The function will be called from inside of controller's event loop and scale the deployment based on the return value from those functions
```
# autoscaling_helpers.py
def resnet_app(context: AutoscalingContext) -> int: 
    # scale the number of replicas to have a constant 10 requests per replica + 10 replicas to standby
    return context.request_queue_size * 10 + 10


def burst_request_scaling(context: AutoscalingContext) -> int:
    # scale based on time of day
    current_hour = datetime.datetime.utcnow().hour
    if 14 <= current_hour < 16:
        return 100

    return 5 


def thrid_party_integration(context: AutoscalingContext) -> int:
    # query outside metrics and acting on it
    custom_metrics = CloudWatch.Client.get_metric_data("my_metrics...")  # getting metrics from outside Ray
    return custom_metrics.metrics1 * 2 + custom_metrics.metrics2 + 3
```

### Changes
- Add an optional config `custom_scaling` to the deployment's `autoscaling_config`. This will work similar to `import_path` where it's a string pointed to a callable import path and gets imported at the time of deployment. 
  - If this config is specified, then the request queue size autoscale will not be taking affect as the two can have conflicts.  
- Add a new `AutoscalingStateManager` and refactor the current autoscaling logics into this class. 
- Add a new `AutoscalingContext` which provides some default metrics tracked in Ray such as request queue size, number of current replicas, gpu utilization, cpu utilization...etc. This should also offer an interface to query any metrics from Prometheus
- Modify the update logics in the deployment state to call on the new `custom_scaling` function if the config is specified.
  - The call would need to be running on a separate thread and have some kind of timeout and loggings to it doesn't block the main event loop
