### ISSUE TITLE
[Core] "The actor died unexpectedly before finishing this task." in docker

### ISSUE THREAD

**Issue by lsc64** [ray-project/ray#41729]
### What happened + What you expected to happen

Submitted jobs can't be executed.

```
(base) root@c910d7fb7266:/git/# ray job submit -- python /git/hello.py                                  ot found (required by /home/ray/anaconda3/lib/pyth
Job submission server address: http://ray-head-1:8265
                                                                                                                                                                               on3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
-------------------------------------------------------
Job 'raysubmit_zZmX9Y6X5KXKiwqB' submitted successfully
-------------------------------------------------------

Next steps
  Query the logs of the job:
    ray job logs raysubmit_zZmX9Y6X5KXKiwqB
  Query the status of the job:
    ray job status raysubmit_zZmX9Y6X5KXKiwqB
  Request the job to be stopped:
    ray job stop raysubmit_zZmX9Y6X5KXKiwqB

Tailing logs until the job exits (disable with --no-wait):

---------------------------------------                                                                                      ot found (required by /home/ray/anaconda3/lib/pyth
Job 'raysubmit_zZmX9Y6X5KXKiwqB' failed                                                                                                                                        on3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
---------------------------------------

Status message: Unexpected error occurred: The actor died unexpectedly before finishing this task.       
```

### Versions / Dependencies

Docker image `rayproject/ray-ml:latest-py39-gpu` with digest `b7ee55f813ea`

```
(base) ray@37c6aff73763:~$ cat pip-freeze.txt

flax==0.7.2
flit_core @ file:///opt/conda/conda-bld/flit-core_1644941570762/work/source/flit_core
fonttools==4.43.1
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.5.0
future==0.18.3
gast==0.4.0
gcs-oauth2-boto-plugin==3.0
gin-config==0.5.0
gitdb==4.0.10
GitPython==3.1.38
glfw==2.6.2
google-api-core==2.12.0
google-api-python-client==1.7.8
google-apitools==0.5.32
google-auth==2.23.3
google-auth-httplib2==0.1.1
google-auth-oauthlib==0.4.6
google-oauth==1.0.1
google-pasta==0.2.0
google-reauth==0.1.1
googleapis-common-protos==1.61.0
gpustat==1.1.1
GPy==1.10.0
gpytorch==1.10
grapheme==0.6.0
graphviz==0.20.1
greenlet==3.0.0
grpcio==1.59.0
gsutil==5.26
gunicorn==20.1.0
gym==0.26.2
gym-notices==0.0.8
gymnasium==0.28.1
h11==0.12.0
h5py==3.7.0
HEBO @ git+https://github.com/huawei-noah/HEBO@9a2a674c22518eed35a8b98e5134576741a95410#subdirectory=HEBO
higher==0.2.1
hjson==3.1.0
hpbandster==0.7.4
httplib2==0.20.4
httptools==0.6.1
huggingface-hub==0.18.0
humanfriendly==10.0
hyperopt==0.2.7
idna @ file:///croot/idna_1666125576474/work
imageio==2.31.1
imageio-ffmpeg==0.4.5
importlib-metadata==4.10.0
importlib-resources==5.13.0
iniconfig==2.0.0
ipykernel==6.25.2
ipython==8.12.3
ipython-genutils==0.2.0
ipywidgets==7.8.1
isodate==0.6.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycosat @ file:///croot/pycosat_1696536503704/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==1.10.12
pyDeprecate==0.3.2
pygame==2.1.2
pyglet==1.5.15
Pygments==2.13.0
PyJWT==2.8.0
pymars==0.10.0
pymoo==0.6.0.1
pymunk==6.2.1
PyNaCl==1.5.0
PyOpenGL==3.1.7
pyOpenSSL==22.1.0
pyparsing==3.1.1
pypng==0.20220715.0
pyproject_hooks==1.0.0
pyro-api==0.1.2
pyro-ppl==1.8.6
Pyro4==4.82
pyrsistent==0.19.3
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
pyspark==3.4.1
pytest==7.0.1
pytest-remotedata==0.3.2
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
pytorch-lightning==1.6.5
pytz==2022.7.1
pyu2f==0.1.5
PyWavelets==1.4.1
PyYAML==6.0.1
pyzmq==24.0.1
querystring-parser==1.2.4
ray @ file:///home/ray/ray-2.8.0-cp39-cp39-manylinux2014_x86_64.whl#sha256=f0abd5c3d2b7585c5b42545d9746dffee0851289f8c677cf792ed6d8699f633d
ray-cpp==2.8.0
raydp==1.7.0b20231017.dev0
recsim==0.2.4
redis==3.5.3
referencing==0.30.2
regex==2023.10.3
requests @ file:///croot/requests_1690400202158/work
requests-oauthlib==1.3.1
requests-toolbelt==1.0.0
responses==0.13.4
RestrictedPython==6.2
retry-decorator==1.1.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==12.6.0
rpds-py==0.10.6
rsa==4.7.2
ruamel.yaml @ file:///croot/ruamel.yaml_1666304550667/work
ruamel.yaml.cl
timm==0.9.2
tinycss2==1.2.1
tinyscaler==1.2.6
tokenizers==0.12.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.0.1+cu118
torch-cluster==1.6.1+pt20cu118
torch-geometric==2.3.1
torch-scatter==2.1.1+pt20cu118
torch-sparse==0.6.17+pt20cu118
torch-spline-conv==1.2.2+pt20cu118
torchdata==0.6.1
torchmetrics==0.10.3
torchtext==0.15.2+cpu
torchvision==0.15.2+cu118
tornado==6.1
tqdm==4.64.1
traitlets==5.11.2
transformers==4.19.1
triton==2.0.0
tune-sklearn @ git+https://github.com/ray-project/tune-sklearn@f309725f8bd382beed9cdf2720159c65a6422b38
typeguard==2.13.3
typer==0.9.0
types-python-dateutil==2.8.19.14
typing_extensions==4.5.0
tzdata==2023.3
uri-template==1.3.0
uritemplate==3.0.1
urllib3 @ file:///croot/urllib3_1698257533958/work
uvicorn==0.22.0
uvloop==0.18.0
virtualenv==20.21.0
wandb==0.13.4
watchfiles==0.19.0
wcwidth==0.2.8
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.4
websockets==11.0.3
Werkzeug==2.1.2
widgetsnbextension==3.6.6
wrapt==1.15.0
wurlitzer==3.0.3
xgboost==1.7.6
xgboost-ray==0.1.18
xmltodict==0.13.0
xxhash==3.4.1
y-py==0.6.2
yarl==1.9.2
ypy-websocket==0.8.4
zict==3.0.0
zipp==3.17.0
zoopt==0.4.1
zstandard @ file:///croot/zstandard_1677013143055/work
```

### Reproduction script

Create a cluster using the following `compose.yml`

```yaml
version: '3'
networks:
  monitoring:
  ray:
    external: true
volumes:
  tmp:
services:
  head:
    image: rayproject/ray-ml:latest-py39-gpu
    volumes:
      - $HOME/git/:/git/
    entrypoint: "/bin/bash -c"
    command:
      [
        "ray start --head --dashboard-host=0.0.0.0 --num-gpus=0 --block --resources='{\"head_node\": 1}'"
      ]
    ports:
      - '6379:6379'
      - '6380:6380'
      - '8265:8265'
    networks:
      - monitoring
      - ray
    restart: unless-stopped

  client-7:
    image: rayproject/ray-ml:latest-py39-gpu
    volumes:
      - $HOME/git/:/git/
    entrypoint: "/bin/bash -c"
    command: [ "ray start --address=head:6379 --num-gpus=1 --block" ]
    networks:
      - monitoring
    environment:
      - RAY_ADDRESS=head:6379 # Set the Ray head node address
    depends_on:
      - head

```

Create `$HOME/git/hello.py`
```python
print("Hello, World!")
```

Submit the job
```bash
ray job submit -- python /git/hello.py
```

### Issue Severity

High: It blocks me from completing my task.
