### ISSUE TITLE
Ray: Core & Serve - use cached nodes.

### ISSUE THREAD

**Issue by JettScythe** [ray-project/ray#42335]
### What happened + What you expected to happen

When using cache_stopped_nodes: true & preemptible instances on GCP, I would like to re-use stopped nodes if needed. 
What currently happens:
worker nodes are stopped daily and new worker nodes are spun up. For every day I have my ray cluster on gcp, I will have a new stopped worker node. 

I would much prefer ray bring up a cached node. Assuming no upwards autoscaling, this would result in say using only 2 worker nodes. 

### Versions / Dependencies

ray 2.8.0
python 3.10
debian 11

### Reproduction script

```
# A unique identifier for the head node and workers of this cluster.
cluster_name: prod-cluster-cx-ml

# Cloud-provider specific configuration.
provider:
  type: gcp
  region: us-central1
  availability_zone: us-central1-a
  project_id: 
  cache_stopped_nodes: true
  # use_internal_ips: true

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 2.0
max_workers: 25

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker: { }

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# How Ray will authenticate with newly launched nodes.
auth:
  ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below. This requires that you have added the key into the
# project wide meta-data.
#    ssh_private_key: /path/to/your/key.pem

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
  ray_head_default:
    # The resources provided by this node type.
    resources: { "CPU": 0 }  # https://docs.ray.io/en/latest/cluster/vms/user-guides/large-cluster-best-practices.html#configuring-the-head-node
    # Provider-specific config for the head node, e.g. instance type. By default
    # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
    # For more documentation on available fields, see:
    # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
    node_config:
      tags: { items: [ "dev" ] }
      machineType: e2-standard-2
      network_interfaces:
        access_configs:
          nic_type: GVNIC
          network_tier: PREMIUM
      disks:
        - boot: true
          autoDelete: true
          type: PERSISTENT
          initializeParams:
            diskSizeGb: 50
            # See https://cloud.google.com/compute/docs/images for more images
            sourceImage: projects/ml-images/global/images/c0-deeplearning-common-cu121-v20230925-debian-11-py310
  
  ray_worker_small_t4:
    # The resources provided by this node type.
    resources: { "CPU": 2, "GPU": 1 }
    # Provider-specific config for the head node, e.g. instance type. By default
    # Ray will auto-configure unspecified fields such as subnets and ssh-keys.
    # For more documentation on available fields, see:
    # https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert
    node_config:
      tags: { items: [ "dev" ] }
      machineType: n1-standard-2
      network_interfaces:
        access_configs:
          nic_type: GVNIC
          network_tier: PREMIUM
      disks:
        - boot: true
          autoDelete: true
          type: PERSISTENT
          initializeParams:
            diskSizeGb: 50
            # See https://cloud.google.com/compute/docs/images for more images
            sourceImage: projects/ml-images/global/images/c0-deeplearning-common-cu121-v20230925-debian-11-py310
      # Make sure to set scheduling->onHostMaintenance to TERMINATE when GPUs are present
      guestAccelerators:
        - acceleratorType: nvidia-tesla-t4
          acceleratorCount: 1
      metadata:
        items:
          - key: install-nvidia-driver
            value: "True"
      scheduling:
        - preemptible: true
        - onHostMaintenance: TERMINATE
      serviceAccounts:
        - email: 
          scopes:
            - https://www.googleapis.com/auth/cloud-platform
            
            
       # TODO: Change this to pull from git? Push from git to cloud with CI/CD?
file_mounts: {
  ray_deployments: 
}


# All the 'conda activate' are necessary to ensure we are in the python 3.10 conda env.
setup_commands:
  - echo "(conda activate || true)" >> ~/.bashrc
  - mkdir models
  - gcsfuse -o ro llm-quantized-gguf models/
  - pip install ray==2.8.0


# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
  - "__pycache__/*"
```

### Issue Severity

Low: It annoys or frustrates me.
