### ISSUE TITLE
How to enable login and logout button in Ray Dashboard 

### ISSUE THREAD

**Issue by tppalani** [ray-project/ray#42606]
### Description

Hi All,

We have deployed ray cluster in our EKS multi tenant cluster. Our use case is we will create multiple namespaces to application team to utilize the respective namespaces inside the EKS cluster, which means only respective team peopel can we their own namespaces when the connected to the cluster.

Now the thing we have exposed ray dashboard using nginx ingress controller and we have able to access our dashboard, but who ever access ray dashboard URL https://ray-dashboard.com there is not login and logout mechanism, and anyone can see the  already submitted jobs and other cluster configuration as well.

How we are going to mange this, do we have documentation, Ray dashboard will support Okta enablement? can you please some help me on this.

**Comment by tppalani** [comment]
Hi @antoniomdk 

Actually we have configured Tekton, Argocd as okta login method or oauth2proxy. But when we have seen ray board i don't see any login button by default, do you have any document for setup ? 
![image](https://github.com/ray-project/ray/assets/6921037/155919ff-5444-478b-beb8-9aa871f188e4)

**Comment by tppalani** [comment]
Hi @antoniomdk 

I have configured Ray cluster using Kind in my local system. using port forwarding i can able to access ray dashboard https://docs.ray.io/en/latest/cluster/kubernetes/getting-started/raycluster-quick-start.html#kuberay-operator-deploy


Here the steps which i followed auth2-proxy

Using github oauth client id and secret has been created.

```
 ./helm.exe upgrade --install --wait --create-namespace --namespace tools oauth2-proxy oauth2-proxy/oauth2-proxy --version 6.19.1 --values - <<EOF
config:
  clientID: $CLIENT_ID
  clientSecret: $CLIENT_SECRET

extraArgs:
  provider: github
  whitelist-domain: .127.0.0.1.nip.io
  cookie-domain: .127.0.0.1.nip.io
  redirect-url: http://auth.127.0.0.1.nip.io/oauth2/callback
  cookie-secure: 'false'

ingress:
  enabled: true
  path: /
  hosts:
    - auth.127.0.0.1.nip.io
EOF
```
Then i have created ingress
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-dashboard
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.tools.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: http://auth.127.0.0.1.nip.io/oauth2/sign_in?rd=http://\$host\$request_uri
spec:
  rules:
    - host: ray-dashboard.127.0.0.1.nip.io
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: raycluster-kuberay-head-svc
                port:
                  number: 8265
```

Post that when i'm trying to access host name i'm getting initial response with oauth-2proxy, when i'm clicking sign in with github then i'm getting error 404 page not found like

http://localhost/oauth2?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=omjkXEKHspvtYDNnU9WLzKFUobObftoc5f-e_Ne-VDk%3A%2F

http://ray-dashboard.127.0.0.1.nip.io

![image](https://github.com/ray-project/ray/assets/6921037/a60e27b6-95bb-473e-86cf-c00bb8093f55)
