### ISSUE TITLE
[GCS SERVER] memory leak gcs server

### ISSUE THREAD

**Issue by leosantosbh** [ray-project/ray#43253]
### What happened + What you expected to happen

I have a basic adding code... where one of the variables is a reference and another I send in the function, when calling the task everything works normally, but over time the gcs_server component appears to have a high memory consumption, I have prints 20 minutes of execution and 12 hours.

20 minutes

![image](https://github.com/ray-project/ray/assets/34506721/a7d1d970-1e16-432f-93d5-d27f26ad6caf)

after 12 hours:

![image](https://github.com/ray-project/ray/assets/34506721/f0a07525-6085-437c-9dd7-1d24044fcdc4)

When consumption becomes very high, it is no longer possible to create tasks and after a period of time the cluster restarts, the task error messages are (after 1 day):

![image](https://github.com/ray-project/ray/assets/34506721/28601fb6-2db6-48ed-be56-a9cf60321dd8)

I notice that when I use refs and ray.get() a lot it starts to accumulate this higher memory

### Versions / Dependencies

Ray: 2.9.2
Python: 3.10.10

### Reproduction script

To reproduce the error I am using ray docker image with docker compose below:

```
version: "3"

services:  
  ray-head:
    image: rayproject/ray:2.9.2-py310
    ports:
      - "6379:6379"
      - "8265:8265"
      - "10001:10001"
    env_file:
      - .env
    command: 
      - bash 
      - -c
      - |
        ray start --head --dashboard-port=8265 --port=6379 --dashboard-host=0.0.0.0 --redis-password=yourpassword --block
    shm_size: 1g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks:
      - ray_net

  ray-worker:
    iamge: rayproject/ray:2.9.2-py310
    depends_on: 
      - ray-head
    env_file:
      - .env
    command: 
      - bash 
      - -c
      - |
        ray start --address=ray-head:6379 --redis-password=yourpassword --num-cpus=1 --block
    shm_size: 1g
    deploy:
      mode: replicated
      replicas: '1'
      resources:
        limits:
          cpus: '1'
          memory: '2g'
    networks: 
      - ray_net
  
networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16
```

and using the following code to test, to observe the high consumption of the ray I enter the head container and give a "top" command

code:

```
import ray
ray.init(address='ray://localhost:10001')

@ray.remote(num_cpus=1)
def f_sum(a, b):
    return a + b

a = [i for i in range(100000)]
a_ref = ray.put(a)
b = [i for i in range(100000)]

for i in range(1000):
    futures = []
    for j in range(15):
        futures.append(f_sum.remote(a_ref, b))
    
    ray.wait(futures)
    results = ray.get(futures)
    print(results[0][:10])
    del futures
    del results[0:]
```

### Issue Severity

High: It blocks me from completing my task.
