### ISSUE TITLE
[RayJob] Ray cluster launched by KubeRay doesn't respect resource `rayStartParams` field in yaml file

### ISSUE THREAD

**Issue by viirya** [ray-project/ray#43261]
### What happened + What you expected to happen

I use RayJob to submit a text ml job. I follow the doc https://docs.ray.io/en/latest/ray-core/scheduling/resources.html to specify cluster resource like cpu in yaml file, but KubeRay seems not respect `rayStartParams` field in yaml file:


```
│ 2024-02-19 11:36:15,637    INFO worker.py:1540 -- Connecting to existing Ray cluster at address: 240.56.106.17:6379...                                                                                                              │
│ 2024-02-19 11:36:15,642    INFO worker.py:1715 -- Connected to Ray cluster. View the dashboard at 240.56.106.17:8265                                                                                                                │
│ {'CPU': 42.0,                                                                                                                                                                                                                       │
│  'memory': 420000000000.0,                                                                                                                                                                                                          │
│  'node:240.56.103.254': 1.0,                                                                                                                                                                                                        │
│  'node:240.56.105.101': 1.0,                                                                                                                                                                                                        │
│  'node:240.56.106.17': 1.0,                                                                                                                                                                                                         │
│  'node:240.56.116.89': 1.0,                                                                                                                                                                                                         │
│  'node:240.56.118.218': 1.0,                                                                                                                                                                                                        │
│  'node:240.56.122.174': 1.0,                                                                                                                                                                                                        │
│  'node:240.56.122.187': 1.0,                                                                                                                                                                                                        │
│  'node:__internal_head__': 1.0,                                                                                                                                                                                                     │
│  'object_store_memory': 125712615013.0}                                                                                                                                                                                            
```

I also tried to add resource parameter to `ray.init()` in the script, but it complains that connecting to existing cluster cannot specify resource there.

Because the cluster resource doesn't satisfy the requirement in the script, Ray cannot schedule training tasks at all:

```
│   File "/home/ray/anaconda3/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 160, in _create_c10d_store                                                                                                           │
│     return TCPStore(                                                                                                                                                                                                                │
│ RuntimeError: Connection reset by peer                                                                                                                                                                                              
```

### Versions / Dependencies

Base image: ray:2.9.0-py39
Python 3.9
ray 2.9.0
kuberay/operator:1.1.12

### Reproduction script

The yaml file snippet looks like:

```
  rayClusterSpec:
    rayVersion: '2.9.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: "6"
        num-gpus: "0"
   ...
    workerGroupSpecs:
      - replicas: 6
        minReplicas: 6
        maxReplicas: 6
        rayStartParams:
          num-cpus: "6"
          num-gpus: "0"
```


This is the definition of container resources in the yaml file:
```
                resources:
                  limits:
                    cpu: "6"
                    memory: "60G"
                  requests:
                    cpu: "6"
                    memory: "60G"
```

### Issue Severity

High: It blocks me from completing my task.
