### ISSUE TITLE
[Serve] NVIDIA Driver was not detected when running application in container 

### ISSUE THREAD

**Issue by heiruwu** [ray-project/ray#44024]
### What happened + What you expected to happen

I was following the doc [here](https://docs.ray.io/en/latest/serve/advanced-guides/multi-app-container.html) and have the following setup
1. using a custom dockerfile based on `rayproject/ray:2.9.3-py311-cu121`, and install podman and nvidia container toolkit in it, like this
```
RUN apt-get update
RUN apt-get install curl -y
RUN curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
    && curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
RUN bash -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4D64390375060AA4
RUN apt-get update
RUN apt-get install -y podman nvidia-container-toolkit
```
2. using `rayproject/ray:2.9.3-py311-cu121` also for my application image, while installing some extra python packages in it
3. I can successfully serve the application, but within the podman container, nvidia driver is not detected

I can confirm in ray head container, driver and cuda are both accessible and working properly

I also tried using the nvidia runtime hook by adding the following into the dockerfile
```
RUN sed -i 's/^#no-cgroups = false/no-cgroups = true/;' /etc/nvidia-container-runtime/config.toml

WORKDIR /usr/share/containers/oci/hooks.d
RUN echo -e "{\n \
  \"version\": \"1.0.0\",\n \
  \"hook\": {\n \
    \"path\": \"/usr/bin/nvidia-container-toolkit\",\n \
    \"args\": [\"nvidia-container-toolkit\", \"prestart\"],\n \
    \"env\": [\n \
      \"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"\n \
    ]\n \
  },\n \
  \"when\": {\n \
    \"always\": true,\n \
    \"commands\": [\".*\"]\n \
  },\n \
  \"stages\": [\"prestart\"]\n \
}" > oci-nvidia-hook.json
RUN echo -e "hooks_dir = ["/usr/share/containers/oci/hooks.d", "/etc/containers/oci/hooks.d"]\nlabel = false" > /home/ray/.config/containers/libpod.conf
```
but it will throw this error
```
Error: OCI runtime error: error executing hook `/usr/bin/nvidia-container-toolkit` (exit code: 1)
```

#### Host:
os="Ubuntu 22.04.4 LTS"
nvidia-driver="550.54.14"
cuda="12.4"
nvidia-ctk="1.14.6"

#### ray-head:
rayproject/ray:2.9.3-py311-cu121

#### application:
rayproject/ray:2.9.3-py311-cu121

### Reproduction script

run ray with docker-compose
```
ray_server:
    container_name: ray
    image: my-custom-ray-image
    # for dind podman
    privileged: true
    restart: unless-stopped
    environment:
      - RAY_ADDRESS=0.0.0.0:6379
    entrypoint: ["/bin/bash", "-c"]
    command: |
      'ray start --head --node-ip-address=0.0.0.0 --dashboard-host=0.0.0.0 &&
      serve start --http-host=0.0.0.0 &&
      tail -f /dev/null'
    volumes:
      - /var/lib/containers:/var/lib/containers
    healthcheck:
      test: ["CMD", "ray", "status"]
      start_period: 20s
      start_interval: 1s
      interval: 1s
      timeout: 5s
      retries: 10
    shm_size: 4gb
    ports:
      - 8265:8265
```
enter ray
```
docker exec -it ray /bin/bash
```
test nvidia-smi
```
podman run -it --rm -v /tmp/ray:/tmp/ray --cgroup-manager=cgroupfs --network=host --pid=host --ipc=host --userns=keep-id ubuntu nvidia-smi
```
will get
```
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob bccd10f490ab done
Copying config ca2b0f2696 done
Writing manifest to image destination
Storing signatures
Error: executable file `nvidia-smi` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

### Issue Severity

High: It blocks me from completing my task.
