### ISSUE TITLE
Ray Serve: Custom Docker image not working

### ISSUE THREAD

**Issue by ghpu** [ray-project/ray#44349]
### What happened + What you expected to happen

I followed tutorial : https://docs.ray.io/en/latest/serve/production-guide/docker.html

with custom image built from base image rayproject/ray:latest-py310-cpu (image
sha256:a91f0cdcacb2300a3a6744d5aa99b03fb3633776323a3564cba23fc997792ef6)
```
(ServeController pid=36782) WARNING 2024-03-28 22:54:26,064 controller 36782 application_state.py:731 - Deploying app 'fake' failed with exception:
(ServeController pid=36782) Traceback (most recent call last):
(ServeController pid=36782)   File "/home/ghpu/miniconda3/lib/python3.10/site-packages/ray/serve/_private/application_state.py", line 983, in build_serve_application
(ServeController pid=36782)   File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/utils.py", line 1191, in import_attr
(ServeController pid=36782)     module = importlib.import_module(module_name)
(ServeController pid=36782)   File "/home/ray/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
(ServeController pid=36782)     return _bootstrap._gcd_import(name[level:], package, level)
(ServeController pid=36782)   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
(ServeController pid=36782)   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
(ServeController pid=36782)   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
(ServeController pid=36782) ModuleNotFoundError: No module named 'fake'
```

Looks very similar to issue https://github.com/ray-project/ray/issues/43889 , but when running a podman worker.

### Versions / Dependencies

ray: 2.10
python: 3.10.13

### Reproduction script

Dockerfile: 
```
FROM rayproject/ray:latest-py310-cpu
RUN pip install Faker==18.13.0
WORKDIR /serve_app
COPY fake.py /serve_app/fake.py
```
config.yaml:
```
applications:

 - name: fake
   route_prefix: /

   import_path: fake:app

   runtime_env:
     container:
       image: localhost/faker:latest
       worker_path: /home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/workers/default_worker.py
```

### Issue Severity

High: It blocks me from completing my task.
