### ISSUE TITLE
[Core] runtime_env: can't update  an application installed from gitlab

### ISSUE THREAD

**Issue by EtsuNDmA** [ray-project/ray#44423]
### What happened + What you expected to happen

We are deploing development version of an app using RayService. A config looks like

```
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-test
spec:
  serveConfigV2: |
    applications:
      - name: test-app
        import_path: "dag.dag"
        route_prefix: /hello
        runtime_env:
          working_dir: "https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.12"
        deployments:
          - name: Hello
            num_replicas: 1
            ray_actor_options:
              num_cpus: 0.1
  rayClusterConfig:
    rayVersion: "2.9.3"
 ...
```

First time after `kubectl apply -f config.yaml ` an application is deployed successfully. But when we try to update the version `working_dir: "...?sha=0.0.13"` and apply config again, the application is not updated.

In the `runtime_env_setup-01000000.log` we found

```
/tmp/ray/session_2024-03-28_01-10-56_576336_8/logs$ cat runtime_env_setup-01000000.log
2024-03-28 01:13:14,715	INFO uri_cache.py:84 -- Added URI https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.12 with size 211560
2024-03-28 01:15:39,782	INFO uri_cache.py:84 -- Added URI https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.13 with size 211560
2024-03-28 01:15:43,429	INFO plugin.py:257 -- Runtime env working_dir https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.13 is already installed and will be reused. Search all runtime_env_setup-*.log to find the corresponding setup log.
2024-03-28 01:15:43,429	INFO uri_cache.py:71 -- Marked URI https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.13 used.
```

Than we found that `.../session_2024-03-28_01-10-56_576336_8/runtime_resources/working_dir_files/https_my_private_gitlab_com_api_v4_projects_247_repository_archive/dag.py` is at version 0.0.12 and there is no git tag in that path

The problem is that the [parse_uri](https://github.com/ray-project/ray/blob/fb89bf83385f66988e9df73364f7eeb277cfbebf/python/ray/_private/runtime_env/packaging.py#L208) function cuts off query string from the URI. This is not an issue forGitHub because GitHub's URI for archive downloading contains the git tag in the URL path ([github doc](https://docs.github.com/en/repositories/working-with-files/using-files/downloading-source-code-archives#source-code-archive-urls)). But other systems can have a git tag in other parts of the URI. For example, GitLab's URI looks like `https://my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.12` ([gitlab doc](https://docs.gitlab.com/ee/api/repositories.html#get-file-archive
)), where the git tag passed through a query string.

There is a workaround for this issue, just add the git tag to the userinfo part of the URI — `https://0.0.12@my-private-gitlab.com/api/v4/projects/247/repository/archive.zip?sha=0.0.12`

### Versions / Dependencies

ray==2.9.3

### Reproduction script

Create config.yaml

```yaml
applications:
  - name: hello-app
    import_path: "main.dag"
    route_prefix: /hello
    runtime_env:
      working_dir: "https://gitlab.com/api/v4/projects/56440482/repository/archive.zip?sha=0.0.3"
    deployments:
      - name: Hello
        num_replicas: 1
        num_cpus: 0.1
```

Start serving

```bash
serve run config.yaml
```

Check that server responds

```bash
$ curl -X POST http://localhost:8000/hello -d '{"name":"guido"}' 
Hello, guido! (version 0.0.3)
```

In config.yaml replace 0.0.3 with 0.0.4 and deploy

```bash
serve deploy config.yaml
```

Check that server responds, but version was not changed

```bash
$ curl -X POST http://localhost:8000/hello -d '{"name":"guido"}' 
Hello, guido! (version 0.0.3)
```

In config.yaml replace working_dir with "https://0.0.4@gitlab.com/api/v4/projects/56440482/repository/archive.zip?sha=0.0.4" and deploy again

```bash
serve deploy config.yaml
```

Check that server responds and version was changed

```bash
$ curl -X POST http://localhost:8000/hello -d '{"name":"guido"}' 
Hello, guido! (version 0.0.4)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
