### ISSUE TITLE
Running Multiple Applications in Different Containers stuck in status=DEPLOYING

### ISSUE THREAD

**Issue by supraja-968** [ray-project/ray#44708]
### What happened + What you expected to happen

Hi, We have multiple machine learning models that have different CUDA version base images and different dependencies. We've been running into issues because of this and haven't been able to run all these logic together as one model and are blocked because of it. We came across Ray as a solution to this with the possibility of separating these models into different applications and running them in different containers. I'm trying to get a POC with ray, so we can implement this concept within our application but so far, I haven't been able to get it to work. 
I followed this documentation to [Run Multiple Applications in Different Containers](https://docs.ray.io/en/latest/serve/advanced-guides/multi-app-container.html) with the resnet and whisper example. The serve status command returns the below message, with the status stuck in 'DEPLOYING':
```bash
proxies:
  4407b7b9997bdb057edda63415e1a36681493df2ed2af80f31ac8ed9: HEALTHY
applications:
  whisper:
    status: DEPLOYING
    message: ''
    last_deployed_time_s: 1712937778.7738054
    deployments: {}
  resnet:
    status: DEPLOYING
    message: ''
    last_deployed_time_s: 1712937778.7738054
    deployments: {}
target_capacity: null
```

I don't see any active containers to inspect docker logs as well. While looking into the documentation, I also noticed the RUN command in resnet.Dockerfile is missing pip install. So I changed
```RUN torch==2.0.1 torchvision==0.15.2```
to
```RUN pip install torch==2.0.1 torchvision==0.15.2```

Still status is stuck at the moment. 

As a different approach, I followed this documentation - [Deploy Multiple Applications](https://docs.ray.io/en/latest/serve/multi-app.html), which works fine locally, able to get a working example:
```bash
proxies:
  1002520fe2570ed18b8716a56288242c5a7748d169daf3800f5b0e64: HEALTHY
applications:
  app1:
    status: RUNNING
    message: ''
    last_deployed_time_s: 1712938569.102233
    deployments:
      downloader:
        status: HEALTHY
        status_trigger: CONFIG_UPDATE_COMPLETED
        replica_states:
          RUNNING: 1
        message: ''
      ImageClassifier:
        status: HEALTHY
        status_trigger: CONFIG_UPDATE_COMPLETED
        replica_states:
          RUNNING: 1
        message: ''
  app2:
    status: RUNNING
    message: ''
    last_deployed_time_s: 1712938569.102233
    deployments:
      Translator:
        status: HEALTHY
        status_trigger: CONFIG_UPDATE_COMPLETED
        replica_states:
          RUNNING: 1
        message: ''
target_capacity: null
```
 but when I create 2 separate Dockerfiles for image_classifier and text_translator, and update the config.yaml file from
```yaml
runtime_env: {}
```
to
```yaml
runtime_env:
      container:
        image: docker.io/supraja968/image-classifier:latest
        worker_path: /home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
```

and move towards the first example of running multiple applications in different containers, it gets stuck again at status=DEPLOYING.

### Versions / Dependencies

Python 3.10.12
Ray 2.10.0
OS Linux 6.5.0-26-generic 26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Reproduction script

https://docs.ray.io/en/latest/serve/multi-app.html
https://docs.ray.io/en/latest/serve/advanced-guides/multi-app-container.html

### Issue Severity

High: It blocks me from completing my task.

**Comment by zcin** [comment]
Hi @supraja-968 if you are using Python 3.10, then you likely need to change the `worker_path` to `/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/workers/default_worker.py`. The docs [here](https://docs.ray.io/en/latest/serve/advanced-guides/multi-app-container.html#worker-path-field) describe in more detail how to determine the correct `worker_path` to set. Let me know if this solves your issue. It's understandably a bit confusing, so it is one of our goals to automatically infer the worker path in the future, but for now you have to manually determine the correct worker path and set it correctly.

**Comment by SamuelBroughton** [comment]
Hi @supraja-968 @zcin @anyscalesam was there a solution for this?

I was trying my own solution but also had status stuck in deploying. So I thought I would reproduce the docs but have the same issue.

* I just built and deployed the resnet.Dockerfile for simplicity on Ubuntu 22.04 using podman as instructed.
* after building the image I ran it interactively and found it was running with python 3.8.18 and ray 2.10.0, So I built my host environment to match this with conda 
* I then started the ray with `ray start --head` and tried to deploy the following serve.yaml file with `serve deploy serve.yaml`

```yaml
proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

grpc_options:
  port: 9000
  grpc_servicer_functions: []

logging_config:
  encoding: TEXT
  log_level: INFO
  logs_dir: null
  enable_access_log: true

applications:
  - name: resnet
    import_path: resnet50_example:app
    route_prefix: /resnet
    runtime_env:
      container:
        image: "name/resnet:latest"
        worker_path: /home/ray/anaconda3/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
```

In my serve dashboard resnet is just forever stuck on DEPLOYING:

```
proxies:
  bd9ab2a8439c95564a5a32d36e1d6a22e18d961bafe30724773f1a78: HEALTHY
applications:
  resnet:
    status: DEPLOYING
    message: ''
    last_deployed_time_s: 1726930330.0024555
    deployments: {}
target_capacity: null
```

Any ideas?
