### ISSUE TITLE
Serialization Issue

### ISSUE THREAD

**Issue by Timothy102** [ray-project/ray#45074]
### What happened + What you expected to happen

Hey, there. I'm running a rather simple Python script on Ray cluster on AWS. I have 3 classes, 6 or 7 functions, and cannot get past serialization errors by Ray. That's annoying. 

I would have expected to run this smoothly.

### Versions / Dependencies

Python 3.9.6, Mac OS Sonoma 14.4, ray==2.12.0, standard other libraries.

### Reproduction script

ray up cluster.yaml && ray submit cluster.yaml main.py

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: ray-yt-cluster

# Cloud-provider specific configuration.
provider:
    type: aws
    region: eu-central-1

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 3

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: m5.large
    ray.worker.default:
        min_workers: 3
        max_workers: 4
        resources: {}
        node_config:
            InstanceType: m5.large
        initialization_commands:
            - pip install yt-dlp

```

### Issue Severity

High: It blocks me from completing my task.
