### ISSUE TITLE
[Clusters]  dashboard is empty with AWS Cluster

### ISSUE THREAD

**Issue by Jendker** [ray-project/ray#46731]
### What happened + What you expected to happen

Accessing the ray dashboard of the AWS cluster does not work. I am getting an empty page similarly to https://github.com/ray-project/ray/issues/39564
If I am trying to submit the job using the forwarded port I am getting: `Request failed with status code 500: No available agent to submit job, please try again later..`
None of these issues happen when starting the dashboard using a GCP cluster.

### Versions / Dependencies

Ray version: 2.32.0
Python: 3.10.14
OS: MacOS 14.5

### Reproduction script

1. Copy one of the AWS configs such as https://github.com/ray-project/ray/blob/eb4287097e7c124b7f6d443bf360decb76343543/python/ray/autoscaler/aws/example-minimal.yaml
2. Launch the AWS cluster: `ray up -y example-minimal.yaml`
3. Run `ray dashboard`
4. Open the browser on "localhost:8265"
5. The interface appears for a split second and then disappears
6. Jobs cannot be started. `RAY_ADDRESS='http://127.0.0.1:8265' ray job submit --working-dir . -- python example.py` results in `Request failed with status code 500: No available agent to submit job, please try again later..`

### Issue Severity

High: It blocks me from completing my task.

**Comment by avriiil** [comment]
I'm running into this too. 
Unclear yet if this is related but I can't seem to submit jobs to this cluster either.

**Comment by avriiil** [comment]
I'm running into this too. 

I'm working with:
Ray 2.35.0
macOS 14.3.1
Python 3.11.0

@Jendker did you ever find a workaround?

**Comment by Jendker** [comment]
Yes, I did. Looks like the exemplary config files are outdated.

In the yaml file I had to add this:
```
setup_commands:
    - sudo apt-get update
    - sudo NEEDRESTART_MODE=a apt-get install -y python3 python3-pip
    - python3 -m pip install --upgrade pip
    - python3 -m pip install 'ray[default]'
```
and under each node_config field I added `ImageId: ami-0075013580f6322a1`

**Comment by avriiil** [comment]
Thanks @Jendker -- I already have `ImageId`s corresponding to my region. Adding the `setup_commands` kills the cluster launch for me with:

```
...
(1/5) sudo NEEDRESTART_MODE=a apt-ge...
E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Shared connection to 18.175.121.218 closed.
  New status: update-failed
  !!!
  Full traceback: Traceback (most recent call last):
  File "/Users/rpelgrim/miniforge3/envs/daft-ray/lib/python3.11/site-packages/ray/autoscaler/_private/updater.py", line 166, in run
    self.do_update()
  File "/Users/rpelgrim/miniforge3/envs/daft-ray/lib/python3.11/site-packages/ray/autoscaler/_private/updater.py", line 490, in do_update
    self.cmd_runner.run(cmd, run_env="auto")
  File "/Users/rpelgrim/miniforge3/envs/daft-ray/lib/python3.11/site-packages/ray/autoscaler/_private/command_runner.py", line 383, in run
    return self._run_helper(final_cmd, with_output, exit_on_fail, silent=silent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rpelgrim/miniforge3/envs/daft-ray/lib/python3.11/site-packages/ray/autoscaler/_private/command_runner.py", line 298, in _run_helper
    raise click.ClickException(fail_msg) from None
click.exceptions.ClickException: SSH command failed.

  Error message: SSH command failed.
  !!!

  Failed to setup head node.
```

I'm not sure how to interpret this.

**Comment by Jendker** [comment]
Can you paste your whole yaml config?

**Comment by avriiil** [comment]
@Jendker sure thing

```
# An unique identifier for the head node and workers of this cluster.
cluster_name: aws-example-minimal

# Cloud-provider specific configuration.
provider:
  type: aws
  region: eu-west-2
  cache_stopped_nodes: False
  security_group:
    GroupName: ray_client_security_group
    IpPermissions:
      - FromPort: 8265
        ToPort: 8265
        IpProtocol: TCP
        IpRanges:
          # Allow traffic only from your local IP address.
          - CidrIp: 145.224.125.212/32

auth:
  ssh_user: ubuntu
  ssh_private_key: <path/to/keypair>

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 3

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
  ray.head.default:
    # The node type's CPU and GPU resources are auto-detected based on AWS instance type.
    # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.
    # You can also set custom resources.
    # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called "custom", set
    # resources: {"CPU": 1, "GPU": 1, "custom": 5}
    resources: {}
    # Provider-specific config for this node type, e.g., instance type. By default
    # Ray auto-configures unspecified fields such as SubnetId and KeyName.
    # For more documentation on available fields, see
    # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
    node_config:
      InstanceType: m5.large
      ImageId: ami-094ba2b4651f761ca
      KeyName: testpair
  ray.worker.default:
    # The minimum number of worker nodes of this type to launch.
    # This number should be >= 0.
    min_workers: 3
    # The maximum number of worker nodes of this type to launch.
    # This parameter takes precedence over min_workers.
    max_workers: 3
    # The node type's CPU and GPU resources are auto-detected based on AWS instance type.
    # If desired, you can override the autodetected CPU and GPU resources advertised to the autoscaler.
    # You can also set custom resources.
    # For example, to mark a node type as having 1 CPU, 1 GPU, and 5 units of a resource called "custom", set
    # resources: {"CPU": 1, "GPU": 1, "custom": 5}
    resources: {}
    # Provider-specific config for this node type, e.g., instance type. By default
    # Ray auto-configures unspecified fields such as SubnetId and KeyName.
    # For more documentation on available fields, see
    # http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.ServiceResource.create_instances
    node_config:
      InstanceType: m5.large
      ImageId: ami-094ba2b4651f761ca
      KeyName: testpair

head_setup_commands: [pip install getdaft pandas]
worker_setup_commands: [pip install getdaft pandas]

setup_commands:
  - sudo apt-get update
  - sudo NEEDRESTART_MODE=a apt-get install -y python3 python3-pip
  - python3 -m pip install --upgrade pip
  - python3 -m pip install 'ray[default]'
```

**Comment by Jendker** [comment]
The differences in comparison to my config (cannot paste it fully, unfortunately):

I have these additional options:
```
provider:
    region: us-west-2
    ...
    availability_zone: us-west-2a,us-west-2b
```
and as a top element:
```
# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default
```
But it's unclear if any of these changes will fix your error. What helped me was to ssh into the head node to investigate it:
`ray attach <config_file>`
