### ISSUE TITLE
[Core] Wrong detection of the space available. 

### ISSUE THREAD

**Issue by Bye-legumes** [ray-project/ray#46868]
### What happened + What you expected to happen

When we run ray in container, ray will have log looks like this 
![image](https://github.com/user-attachments/assets/d09da916-b178-40c7-bca4-aadba5ec793b)
That means the capacity is detected from the host machine (1000GB), while the available gets from the docker file. So although I have 32GB available as it believe the disk is almost full 95%, it still has misleading log. 

### Versions / Dependencies

latest.

### Reproduction script

```
build:
      context: .
      network: host
      dockerfile: Dockerfile
    volumes:
      # With this you can use docker outside (bmc host docker engine) of docker (devcontainer)
      # Forwards the local Docker socket to the container.
      # - /var/run/docker.sock:/var/run/docker-host.sock

      # Update this to wherever you want VS Code to mount the folder of your project and change in devcontainer.json to auto open it
      - ../:/workspace:consistent
      - type: tmpfs
        target: /workspace/tmp/
        tmpfs:
          size: 16G  # Size in bytes, 15GB
    # allow usage of gpus
    deploy:
      resources:
        #reservations:
        #  devices:
        #    - driver: nvidia
        #      count: all
        #      capabilities: [gpu]
        limits:
          cpus: "10.0"
          memory: 32G

    # shared mem used by Ray otherwise it will use /tmp that reduce performance
    shm_size: '15gb' # default 96/3
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
