### ISSUE TITLE
Core: runtime_env with container specified is not working with ray client in cluster mode

### ISSUE THREAD

**Issue by aljeshishe** [ray-project/ray#47302]
### What happened + What you expected to happen

If I specify a container in runtime env it is not working with ray client in cluster mode

I get error:
```
python grachev/test_runtime_env.py 
2024-08-23 16:53:47,678 INFO client_builder.py:244 -- Passing the following kwargs to ray.init() on the server: ignore_reinit_error
Traceback (most recent call last):
  File "/home/ubuntu/asiandumper3/grachev/test_runtime_env.py", line 15, in <module>
    ray.init(addr, runtime_env=runtime_env, ignore_reinit_error=True, log_to_driver=True, logging_level="info")
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/_private/worker.py", line 1481, in init
    ctx = builder.connect()
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/client_builder.py", line 175, in connect
    client_info_dict = ray.util.client_connect.connect(
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/util/client_connect.py", line 55, in connect
    conn = ray.connect(
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/util/client/__init__.py", line 233, in connect
    conn = self.get_context().connect(*args, **kw_args)
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/util/client/__init__.py", line 97, in connect
    self.client_worker._server_init(job_config, ray_init_kwargs)
  File "/home/ubuntu/asiandumper3/.venv/lib/python3.10/site-packages/ray/util/client/worker.py", line 860, in _server_init
    raise ConnectionAbortedError(
ConnectionAbortedError: Initialization failure from server:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ray/util/client/server/proxier.py", line 711, in Datapath
    raise RuntimeError(
RuntimeError: Starting Ray client server failed. See ray_client_server_23000.err for detailed logs.`
```

ray_client_server_23000.err
```
usage: default_worker.py [-h] --cluster-id CLUSTER_ID --node-id NODE_ID
                         --node-ip-address NODE_IP_ADDRESS --node-manager-port
                         NODE_MANAGER_PORT
                         [--raylet-ip-address RAYLET_IP_ADDRESS]
                         --redis-address REDIS_ADDRESS --gcs-address
                         GCS_ADDRESS [--redis-password REDIS_PASSWORD]
                         --object-store-name OBJECT_STORE_NAME
                         [--raylet-name RAYLET_NAME]
                         [--logging-level {debug,info,warning,error,critical}]
                         [--logging-format LOGGING_FORMAT]
                         [--temp-dir TEMP_DIR] [--storage STORAGE]
                         [--load-code-from-local] [--worker-type WORKER_TYPE]
                         --metrics-agent-port METRICS_AGENT_PORT
                         --runtime-env-agent-port RUNTIME_ENV_AGENT_PORT
                         [--object-spilling-config OBJECT_SPILLING_CONFIG]
                         [--logging-rotate-bytes LOGGING_ROTATE_BYTES]
                         [--logging-rotate-backup-count LOGGING_ROTATE_BACKUP_COUNT]
                         [--runtime-env-hash RUNTIME_ENV_HASH] --startup-token
                         STARTUP_TOKEN [--ray-debugger-external]
                         [--session-name SESSION_NAME] [--webui WEBUI]
                         --worker-launch-time-ms WORKER_LAUNCH_TIME_MS
                         [--worker-preload-modules WORKER_PRELOAD_MODULES]
default_worker.py: error: the following arguments are required: --cluster-id, --node-id, --node-ip-address, --node-manager-port, --redis-address, --gcs-address, --object-store-name, --metrics-agent-port, --runtime-env-agent-port, --startup-token, --worker-launch-time-ms
```

runtime_env_setup-ray_client_server_23000.log
```
2024-08-23 17:05:00,845	INFO image_uri.py:27 -- Pulling image docker.io/rayproject/ray:2.34.0-py310-cpu
2024-08-23 17:05:00,846	INFO utils.py:76 -- Run cmd[1] ['podman', 'run', '--rm', 'docker.io/rayproject/ray:2.34.0-py310-cpu', 'python', '-c', 'import ray._private.workers.default_worker as default_worker; print(default_worker.__file__)']
2024-08-23 17:05:28,950	INFO utils.py:101 -- Output of cmd[1]: Trying to pull docker.io/rayproject/ray:2.34.0-py310-cpu...
Getting image source signatures
Copying blob sha256:70926ef1be8156b93011c228d968694831f0261eebfe2f0bb8c5bdefafd4384e
Copying blob sha256:9b857f539cb142c9aa2201a17bb8e1cd5cf12edd4a65adf5732fe9f4343964cf
Copying blob sha256:f9f0039093f1dcd0583837f0d2b143c371475f392387564b65f8821f2b43ffb3
Copying blob sha256:0e6219684bea7d37e7d31b4132166a3a33c2b15f521c7c1354a2b3462655555a
Copying blob sha256:0ffe8fb58534b0dc148003e780885045fd6ddba79357fb99434b6bd914d98719
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:70926ef1be8156b93011c228d968694831f0261eebfe2f0bb8c5bdefafd4384e
Copying blob sha256:f9f0039093f1dcd0583837f0d2b143c371475f392387564b65f8821f2b43ffb3
Copying blob sha256:0e6219684bea7d37e7d31b4132166a3a33c2b15f521c7c1354a2b3462655555a
Copying blob sha256:0ffe8fb58534b0dc148003e780885045fd6ddba79357fb99434b6bd914d98719
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:d1a5457df642c31392ea6ccc62f011e2d73cd86d35422f9e53abf84eacd2d0da
Copying blob sha256:8f754d89266f7d87ef6d75cb62f0f4f7f743ceebfc62da218bc5d3d4f6fa20dd
Copying blob sha256:9b857f539cb142c9aa2201a17bb8e1cd5cf12edd4a65adf5732fe9f4343964cf
Copying blob sha256:261f67a22f230b85ee2a4378497ad84d29a4942623584eb9bb8130a376c30012
Copying blob sha256:d1a5457df642c31392ea6ccc62f011e2d73cd86d35422f9e53abf84eacd2d0da
Copying blob sha256:8f754d89266f7d87ef6d75cb62f0f4f7f743ceebfc62da218bc5d3d4f6fa20dd
Copying blob sha256:261f67a22f230b85ee2a4378497ad84d29a4942623584eb9bb8130a376c30012
Copying config sha256:12208d0d0894cc02eb23d655705268ca0fecb4a922d7936c886f4ea4b651d833
Writing manifest to image destination
Storing signatures
/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/workers/default_worker.py

2024-08-23 17:05:28,951	WARNING image_uri.py:167 -- You are using `container.worker_path`, but the path to `default_worker.py` is now automatically detected from the image. `container.worker_path` is deprecated and will be removed in future versions.
2024-08-23 17:05:28,951	INFO image_uri.py:91 -- Starting worker in container with prefix podman run -v /tmp/ray:/tmp/ray --cgroup-manager=cgroupfs --network=host --pid=host --ipc=host --userns=keep-id --env RAY_RAYLET_PID=6054 --env RAY_JOB_ID=$RAY_JOB_ID --env RAY_BACKEND_LOG_LEVEL='debug' --env RAY_CLIENT_MODE='0' --env RAY_LD_PRELOAD='1' --env RAY_NODE_ID='2ef65f0435676060075304addcd7ce1122bd40750754461401e82e79' --env RAY_OVERRIDE_RESOURCES='{"CPU":4}' --env RAY_USAGE_STATS_ENABLED='1' --env RAY_enable_pipe_based_agent_to_parent_health_check='1' --env PATH=/home/ray/anaconda3/bin:$PATH --entrypoint python docker.io/rayproject/ray:2.34.0-py310-cpu
```

cluster.yaml
```
cluster_name: default
max_workers: 3
upscaling_speed: 3

idle_timeout_minutes: 1
provider:
    type: aws
    region: ap-northeast-1
    cache_stopped_nodes: False # If not present, the default is True.
    security_group:
      GroupName: ray_client_security_group_new
auth:
    ssh_user: ubuntu
    ssh_private_key: ../asiandumper/utils/secret/grachev_ab_aws_key.pem

available_node_types:
    ray.head.default:
        resources: {"CPU": 4}
        node_config:
            KeyName: grachev_ab_aws_key
            IamInstanceProfile:
                Arn: arn:aws:iam::185298664982:instance-profile/ray-autoscaler
            InstanceType: m5d.2xlarge
            ImageId: ami-0162fe8bfebb6ea16

head_node_type: ray.head.default

file_mounts: {
}
cluster_synced_files: []
file_mounts_sync_continuously: False
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

rsync_filter:
    - ".gitignore"

initialization_commands: 
    - echo "running initialization_commands"

setup_commands: 
    - echo "running setup_commands"
    - sudo apt update && sudo DEBIAN_FRONTEND=noninteractive  apt install -y python3-pip mc tree lnav bpytop docker.io podman awscli -y
    - aws ecr get-login-password --region ap-northeast-1 | podman login --username AWS --password-stdin 185298664982.dkr.ecr.ap-northeast-1.amazonaws.com
    - pip3 install ray[default]==2.34.0 boto3

head_setup_commands: []    
worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - RAY_BACKEND_LOG_LEVEL=debug ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0 

worker_start_ray_commands:
    - ray stop
    - RAY_BACKEND_LOG_LEVEL=debug ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

### Versions / Dependencies

Python 3.10.14
ray                       2.34.0

### Reproduction script

```
import ray
import logging
logging.basicConfig(level=logging.DEBUG)
runtime_env={
    "container": {
        "image": "docker.io/rayproject/ray:2.34.0-py310-cpu",
        "run_options": ["--env PATH=/home/ray/anaconda3/bin:$PATH"],
        "worker_path": "/home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/workers/default_worker.py",
    }
}
addr = "ray://35.72.247.94:10001"
ray.init(addr, runtime_env=runtime_env, ignore_reinit_error=True, log_to_driver=True, logging_level="info")

@ray.remote(num_cpus=1)
def func():
    print("started")
    return 42

print(ray.wait(func.remote()))
```

### Issue Severity

High: It blocks me from completing my task.
