### ISSUE TITLE
Too many ray::IDLE process started when using "ray[serve]" for serving machine learning model

### ISSUE THREAD

**Issue by xuanhua** [ray-project/ray#47579]
### What happened + What you expected to happen

As the title mentioned, when I using ray 2.34.0 for serving a simple machine learning model, there are huge number of ray::IDLE processes are launched. I have 24 logical CPUs, and I can see 24 ray::IDLE processes there, and each take 13.1 GB (this machine totally have 128 GB ram memory). So it is just consume all memory of this machine logically.  And here is the main script for the ray deployment:

```python
@serve.deployment(num_replicas=1, ray_actor_options={"num_cpus":0.1}, route_prefix="/cf_recall")
class HotelCFRecallModel:
  def __init__(self):

    args = argparse.Namespace(dumped_dir = DEFAULT_DEPLOY_DIR)
    self.model = CF_Recall.create_instance_from_dumped_dir(args)

  async def __call__(self, req: Request) ->Any:

    """
    Input data format:
    For old api:
    ```json
    {
      "user_id" : "5ab1fe28d6e12b197c835d4e",
      "dest_city_code" : "1352",
      "topk": 100
    }
    ```
    """
    data = await req.body()
    if isinstance(data, bytes):
      try:
        data = data.decode('utf-8')
      except UnicodeDecodeError:
        try:
          data = data.decode('gbk')
        except Exception:
          logger.error("Decode request body error")
          return {"msg": "Decode request body error", "result":{}}
    if isinstance(data, str):
      data = json.loads(data)

    result = self.model.recommend(
      uid = data["user_id"],
      city_id= data["dest_city_id"],
      topk = data["topk"] 
    )
    return {
      "msg": "success",
      "status": 200,
      "data": {
        "items": result
      }  
    }
```
Any help on this issue is appreciated.

I googled this issue and found there are some discussion about the issue, but final solution found. So I wander if this is my wrong usage or this behavior is just by design.  On a resource limited machine, I really hope there is some configuration can help to reduce the resouce consumption and in our case we really do not have much requests to serve per second.




### Versions / Dependencies

ray 2.34.0 and only ray[serve] is installed.

### Reproduction script

Additional information:
We use `serve build` to create an configuration file (by following command):
```python
serve build my_server:recall_model -o  ./ray_serve_config.yaml
```
And this will create `./ray_server_config.yaml` like this:
```yaml
# This file was generated using the `serve build` command on Ray v2.34.0.

proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

grpc_options:

  port: 9000

  grpc_servicer_functions: []

logging_config:

  encoding: TEXT

  log_level: INFO

  logs_dir: null

  enable_access_log: true

applications:

- name: app1

  route_prefix: /cf_recall

  import_path: serve.ray_serve:recall_model

  runtime_env: {}

  deployments:

  - name: HotelCFRecallModel
    num_replicas: 1
    ray_actor_options:
      num_cpus: 0.1

```

### Issue Severity

None
