### ISSUE TITLE
[core] placement group stuck in pending mode

### ISSUE THREAD

**Issue by achsvg** [ray-project/ray#47792]
### What happened + What you expected to happen

I have a cluster consisting of 1 head and 1 worker, each node has 1 CPU. When submitting a job that requires 2 CPUs, the placement group is stuck in pending:

```
$ ray status
======== Autoscaler status: 2024-09-23 01:17:18.277326 ========
Node status
---------------------------------------------------------------
Active:
 1 ray.head.default
 1 ray.worker.default
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/2.0 CPU
 0B/2.33GiB memory
 1.99KiB/1013.52MiB object_store_memory

Demands:
 {'CPU': 2.0} * 1 (SPREAD): 1+ pending placement groups
```

This happens with `PACK` strategy as well. Tasks without placement groups work.

Any ideas?

### Versions / Dependencies

2.36.0

### Reproduction script

cluster config:

```
auth:
  ssh_proxy_command: ssh -i /tmp/key.pem -o StrictHostKeyChecking=no -W %h:%p ubuntu@xx.xx.xx.xx
  ssh_user: ubuntu
available_node_types:
  ray.head.default:
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 140
          VolumeType: gp3
      IamInstanceProfile:
        Arn: arn:aws:iam::xxxxxxx:instance-profile/ray-worker-dev
      ImageId: ami-xxxx
      InstanceType: c7a.medium
      SecurityGroupIds:
      - sg-xxxx
      SubnetIds:
      - subnet-xxxx
      - subnet-xxxx
      - subnet-xxxx
      TagSpecifications:
      - ResourceType: instance
        Tags:
        - Key: Environment
          Value: dev
        - Key: ServiceName
          Value: sim-worker-dev
  ray.worker.default:
    min_workers: 1
    node_config:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 140
          VolumeType: gp3
      IamInstanceProfile:
        Arn: arn:aws:iam::xxxx:instance-profile/ray-worker-dev
      ImageId: ami-xxxx
      InstanceType: c7a.medium
      SecurityGroupIds:
      - sg-xxxx
      SubnetIds:
      - subnet-xxxx
      - subnet-xxxx
      - subnet-xxxx
      TagSpecifications:
      - ResourceType: instance
        Tags:
        - Key: Environment
          Value: dev
        - Key: ServiceName
          Value: sim-worker-dev
cluster_name: default-cluster-dev
cluster_synced_files:
- /etc/cwagentconfig
docker:
  container_name: ray_container_dev
  disable_automatic_runtime_detection: true
  head_image: xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx/sim-cluster-head-dev:xxxx
  head_run_options:
  - --privileged
  pull_before_run: true
  run_options: []
  worker_image: xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx/sim-cluster-worker-dev:xxxx
  worker_run_options:
  - --privileged
file_mounts: {}
file_mounts_sync_continuously: true
head_node_type: ray.head.default
head_setup_commands: []
head_start_ray_commands:
- ray stop
- ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0
idle_timeout_minutes: 5
initialization_commands:
- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin xxxx.dkr.ecr.us-west-2.amazonaws.com
max_workers: 5
provider:
  availability_zone: us-west-2a,us-west-2b,us-west-2c
  cache_stopped_nodes: false
  cloudwatch:
    dashboard:
      name: ray-cluster-dev
  key_pair:
    key_name: default-ray-cluster-dev
  region: us-west-2
  type: aws
  use_internal_ips: true
rsync_exclude:
- '**/.git'
- '**/.git/**'
rsync_filter:
- .gitignore
setup_commands: []
worker_setup_commands: []
worker_start_ray_commands:
- ray stop
- ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

### Issue Severity

High: It blocks me from completing my task.
