### ISSUE TITLE
[Ray Clusters] `ray exec ... --stop --tmux ...` doesn't work with `--stop` and `--tmux` boht specified

### ISSUE THREAD

**Issue by hartikainen** [ray-project/ray#48109]
### What happened + What you expected to happen

When running `ray exec ...` with both `--stop` and `--tmux` flags, the `sudo shutdown -h now` command gets incorrectly wrapped around the tmux command and thus the machine is immediately shut down without the actual command finishing inside tmux.

For example, consider the following command:
```
ray exec \
  --verbose \
  --start \
  --stop \
  --tmux \
  --no-config-cache \
  ./cluster-config.yml \
  'echo "start" && sleep 10 && echo "done"'
```
This results in (as printed out by the command runner):
> Running `tmux new -d bash -c 'echo "start" && sleep 10 && echo "done"; ray stop; ray teardown ~/ray_bootstrap_config.yaml --yes --workers-only; exec bash'; sudo shutdown -h now`

The first part `tmux new -d bash -c '...'` returns immediately and thus the `sudo shutdown -h now` gets executed immediately before the command inside tmux finishes.

### Versions / Dependencies

```
$ ray --version
ray, version 2.37.0
```

### Reproduction script

`cluster-config.yml`:
```yml
auth:
  ssh_user: ubuntu

cluster_name: minimal

provider:
  type: gcp
  region: us-east1
  availability_zone: us-east1-b
  project_id: [project-id]  # Globally unique project id
```

Command:
```
ray exec \
  --verbose \
  --start \
  --stop \
  --tmux \
  --no-config-cache \
  ./cluster-config.yml \
  'echo "start" && sleep 10 && echo "done"'
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
