### ISSUE TITLE
Ray Dashboard: GPU stats per actor is empty

### ISSUE THREAD

**Issue by aviadshimoni** [ray-project/ray#48312]
### What happened + What you expected to happen

Ray deployments don’t have GPU/GRAM tracking (“Actors” section) in Ray dashboard, stats are shown in Clustet tab (images attached).
![image (24)](https://github.com/user-attachments/assets/4b500f5a-a472-4c87-9bc1-9aa42761876b)
https://ray.slack.com/files/U05D35JHGUV/F07TJAFKMTR/image.png?origin_team=TN4768NRM&origin_channel=CMVUQ1KMX

Is this intended? are we having issues aggregating GPU stats per actor?

### Versions / Dependencies

KubeRay: 1.1.1
Ray Version: 2.34.0
CRD: v1

Docker image: rayproject/ray:2.34.0-py310-gpu

### Reproduction script

Deploy any ray service, access it's dashboard and see 'Actors' Tab on top navigation bar.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by aviadshimoni** [comment]
Ray Slack:
https://ray.slack.com/archives/CNCKBBRJL/p1730113922799889

**Comment by marwan116** [comment]
this should now be resolved in Ray 2.35

**Comment by marwan116** [comment]
See this PR here:
https://github.com/ray-project/ray/pull/46719

Please close out this issue after you have verified that upgrading to 2.35 or beyond has resolved things

**Comment by marwan116** [comment]
@aviadshimoni does upgrading to 2.35 resolve your issue ? It would help triage with @dc914337

**Comment by alanwguo** [comment]
The GRAM stats require that the actor process actually attaches to the GPU. This can be done when running an actual workload that uses the GPU.

It's not enough for an actor to require a GPU as a resource. 

Just checking, are you running an actual GPU workload in your manual testing?

**Comment by dc914337** [comment]
Yes, @alanwguo , we are running this model on hundreds of actual GPUs, and, in fact, they can't be run without a GPU.  
I also confirmed that upon manually connecting to the pod, NVML can get the information from the GPU.

**Comment by alanwguo** [comment]
Yes, looks to be specific to using kube-ray. Digging into this more now...

**Comment by millerh1** [comment]
I'm seeing this in v2.4.0 when launching a cluster on AWS VMs (no kuberay). Does anyone have any additional insight on how to fix it? 

Config:

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: test-cluster-1
max_workers: 8
upscaling_speed: 1.0

docker:
    image: "rayproject/ray:latest-gpu"
    container_name: "ray_container"
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536

idle_timeout_minutes: 5

provider:
    type: aws
    region: eu-west-2
    cache_stopped_nodes: false # If not present, the default is True.

auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: g4dn.xlarge
            ImageId: ami-021907ae43fa78a0d
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 256
                      VolumeType: gp3

    ray.worker.default:
        min_workers: 8
        max_workers: 8
        resources: {}
        node_config:
            InstanceType: g4dn.xlarge
            ImageId: ami-021907ae43fa78a0d
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 256
                      VolumeType: gp3

initialization_commands: [ 
    "nvidia-smi",
    "sleep 15"
]

setup_commands: [
    "nvidia-smi",
    "sleep 15"
]

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```
