### ISSUE TITLE
[Serve] Replica cannot be scheduled due to max_replicas_per_node internal resource constraints 

### ISSUE THREAD

**Issue by smit-kiri** [ray-project/ray#48471]
### What happened + What you expected to happen

We're running into a weird issue where a single replica is stuck in the STARTING state for a while, even though resources are available. 
```
Deployment 'my-deployment' in application 'my-deployment' 1 replicas that have taken more than 30s to be scheduled. This may be due to waiting for the cluster to auto-scale or for a runtime environment to be installed. Resources required for each replica: {"GPU": 0.32}, total resources available: {"GPU": 0.36}. Use `ray status` for more details.
```
When looking at some other logs, we found this:
```
resource_demand_scheduler.py:782 -- The autoscaler could not find a node type to satisfy the request: [{'node:__internal_implicit_resource_my-deployment:my-deployment': 0.5, 'GPU': 0.32}]. Please specify a node type with the necessary resources.
{'GPU': 0.32, 'node:__internal_implicit_resource_my-deployment:my-deployment': 0.5}: 1+ pending tasks/actors
```

This seems to happen sometimes, and I think this is because of [how Ray Serve handles enforcing max_replicas_per_node](https://github.com/ray-project/ray/blob/releases/2.9.3/python/ray/serve/_private/deployment_scheduler.py#L269-L272). 

The replicas request for this internal resource, but the node groups don't have this resource specified, so the autoscaler isn't able to scale new nodes.

### Versions / Dependencies

Ray 2.9.3

### Reproduction script

This seems to happen some times, randomly. Likely due to the random nature of scheduling replicas on to nodes.

### Issue Severity

High: It blocks me from completing my task.

**Comment by smit-kiri** [comment]
We have a few applications that request fractional GPUs, which may lead to a higher probability of running into this. We've tried re-deploying this and it seems to happen with different deployments each time:

```yaml
proxy_location: EveryNode
http_options:
  host: 0.0.0.0
  port: 8000

applications:
  - name: my-deployment
    import_path: my_deployment:my_deployment
    route_prefix: /my-deployment
    deployments:
      - name: my-deployment
        num_replicas: 5
        max_replicas_per_node: 2
        ray_actor_options:
          num_gpus: 0.32
          num_cpus: 0

  - name: deployment-2
    import_path: deployment_2:deployment_2
    route_prefix: /deployment-2
    deployments:
      - name: deployment-2
        num_replicas: 8
        max_replicas_per_node: 2
        ray_actor_options:
          num_gpus: 0.16
          num_cpus: 0

  - name: deployment-3
    import_path: deployment_3:deployment_3
    route_prefix: /deployment-3
    deployments:
      - name: deployment-3
        num_replicas: 2
        max_replicas_per_node: 1
        ray_actor_options:
          num_gpus: 0.16
          num_cpus: 0

  - name: deployment-4
    import_path: deployment_4:deployment_4
    route_prefix: /deployment-4
    deployments:
      - name: deployment-4
        num_replicas: 11
        max_replicas_per_node: 4
        ray_actor_options:
          num_gpus: 0.16
          num_cpus: 0
```
