### ISSUE TITLE
[Train][Docker Cluster] Actor is dead because all references to the actor were removed including lineage ref count.

### ISSUE THREAD

**Issue by shreyass-ranganatha** [ray-project/ray#48994]
### What happened + What you expected to happen

I've got a small cluster setup on Docker with the below mentioned Dockerfile and docker-compose.yaml

Now, within ray-head, when I run any "Ray Actor" code; I get the following error:

```
Failure # 1 (occurred at 2024-11-29_03-02-22)
The actor died unexpectedly before finishing this task.
        class_name: with_parameters.<locals>._Inner
        actor_id: 9436796b6115b9a8c8bd999b08000000
        namespace: 2a487f74-1d3e-4824-a36b-24f073cbaa4d
The actor is dead because all references to the actor were removed including lineage ref count.
The actor never ran - it was cancelled before it started running.
```

Along with
```
(raylet) [2024-11-29 03:05:10,993 E 42 42] (raylet) process.cc:303: Process 1775 does not exist.
```

NOTE, the above issue doesn't exist when I run the script from the worker node, but when I do that, the script executes in the head node, (I want to experiment with placement_strategy SPREAD to execute it in two different nodes at the same time, which is the point of this experiment)

I suspect it's because Docker is, for some reason killing the Actor process immediately after it starts, I am unable to figure out how to debug this though

### Versions / Dependencies

Docker version 27.3.1, build ce12230
docker image = `rayproject/ray:2.38.0-py312-cpu-aarch64`

pip freeze:
* `ray==2.38.0`
* `torch==2.5.1`

### Reproduction script

Dockerfile

```Dockerfile
FROM rayproject/ray:2.38.0-py312-cpu-aarch64
USER root

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    pip install -r requirements.txt
```

Docker Compose

```yaml
services:
  rayxp-head:
    build: .
    container_name: rayxp-head
    working_dir: /app/
    environment:
      - RAY_PROMETHEUS_HOST=http://prometheus-xp:9090
      - RAY_GRAFANA_HOST=http://grafana-xp:3000
      - RAY_GRAFANA_IFRAME_HOST=http://127.0.0.1:3000
      - RAY_PROMETHEUS_NAME=rayxp-head
    ports:
      - "6379:6379"
      - "8265:8265"
    volumes:
      - ./head/:/app/
      - ./containers/ray/tmp/:/tmp/ray/
    entrypoint: ray start --head --block
    command: --dashboard-host 0.0.0.0
      --dashboard-port 8265
      --disable-usage-stats
      --metrics-export-port 8080
      --object-store-memory=2147483648

  rayxp-worker-1:
    build: .
    depends_on:
      - rayxp-head
    working_dir: /app/
    volumes:
      - ./worker-1/:/app/
      - ./containers/ray/tmp/:/tmp/ray/
    entrypoint: ray start --block
    command: --address=rayxp-head:6379

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus-xp
    depends_on:
      - rayxp-head
    ports:
      - "9090:9090"
    volumes:
      - ./containers/ray/tmp/:/tmp/ray/
    command: --config.file=/tmp/ray/session_latest/metrics/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise:11.3.0
    container_name: grafana-xp
    environment:
      - GF_PATHS_CONFIG=/tmp/ray/session_latest/metrics/grafana/grafana.ini
      - GF_PATHS_PROVISIONING=/tmp/ray/session_latest/metrics/grafana/provisioning
    depends_on:
      - rayxp-head
    ports:
      - "3000:3000"
    volumes:
      - ./containers/ray/tmp/:/tmp/ray/
```

Python Code

```python
from ray.runtime_context import RuntimeContext
from ray.train.torch import TorchTrainer
from ray.train import ScalingConfig
import ray.train.torch
import ray

import time

def train_fn():
    runtime_ctx: RuntimeContext = ray.get_runtime_context()

    with open("/app/debug-train.txt", 'a+') as wf:
        wf.write(f"from: {runtime_ctx.get_node_id()}\n")


scaling_config = ScalingConfig(
    num_workers=2,
    resources_per_worker={
        "CPU": 1,
    }
)

trainer = TorchTrainer(
    train_loop_per_worker=train_fn,
    scaling_config=scaling_config
)

trainer.fit()
```

^ the above is executed in rayxp-head (which is not rank 0, so I think it's trying to execute it in rayxp-worker-1)

### Issue Severity

High: It blocks me from completing my task.
