### ISSUE TITLE
[Core] Pending node assignment hang but more than enough resources

### ISSUE THREAD

**Issue by Joshuaalbert** [ray-project/ray#49069]
### What happened + What you expected to happen

When I create a two node deployment I get actors failing to be assigned a node indefinitely. When I use a single node deployment, this problem goes away. 

This might be related to how I connect the worker. I notice the Object Store in dashboard for worker node is blank.
![Screenshot from 2024-12-04 13-22-42](https://github.com/user-attachments/assets/20e02a7e-cd3f-40df-b483-aa30c331d11c)

One actor starts fine (on the head node), another actor stays in `pending_creation` indefintely. Neither have resource requirements nor schedule strategy specified.
![Screenshot from 2024-12-04 13-23-02](https://github.com/user-attachments/assets/5a5fc118-f1c2-4e5d-987e-9c9935712565)

Weirdly, on the worker node, `ray status` shows  **the _correct_ amount of object_store_memory**. So from the worker, ray looks fine, but not from the dashboard. And the head is not able to place actors, so there is some connectivity error that is not picked up from Ray.

```
$ ray status

ray  | ======== Autoscaler status: 2024-12-04 12:21:23.499718 ========
ray  | Node status
ray  | ---------------------------------------------------------------
ray  | Active:
ray  |  1 node_3b5d05fc98c96c606390687e6b7e9c991466f8d722b5820e75efcfde
ray  |  1 node_da84b0bf1873009e037f47754d0bdf1a48dfa59fdc7a35ccb13fb50b
ray  | Pending:
ray  |  (no pending nodes)
ray  | Recent failures:
ray  |  (no failures)
ray  | 
ray  | Resources
ray  | ---------------------------------------------------------------
ray  | Usage:
ray  |  0.0/128.0 CPU
ray  |  0B/1.14TiB memory
ray  |  0B/336.92GiB object_store_memory
ray  | 
ray  | Demands:
ray  |  (no resource demands)
```

How come the dashboard shows different? 

More importantly, why do things appear to connect fine, but then actor placement hangs?

In `raylet.out` on head I see this line about the worker:
```
[2024-12-04 12:55:19,020 W 319 319] (raylet) object_manager.cc:694: Send free objects request failed due toRPC Error message: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.176.2:32875: Failed to connect to remote host: FD Shutdown; RPC Error details: 
```

### Versions / Dependencies

ray 2.39.0

Two linux workstations on the same LAN

### Reproduction script

Docker compose file:
```yaml
# docker-compose.yaml
version: "3"
services:
  ray:
    image: ray
    container_name: ray
    build:
      dockerfile: Dockerfile
    ports: 
      - "6379:6379"        # GCS server port
      - "8265:8265"        # Dashboard UI port
      - "10001:10001"      # Ray client server port
      - "50052:50052"      # Dashboard gRPC port
      - "12345:12345"      # Node manager port
      - "12346:12346"      # Object manager port
      - "12347:12347"      # Runtime env agent port
      - "12348:12348"      # Dashboard agent gRPC port
      - "52365:52365"      # Dashboard agent HTTP port
      - "8090:8090"      # Metrics export port
      - "20000-20100:20000-20100"  # Worker ports range
      - "6380:6380"        # Redis shard port
      - "6381:6381"        # Redis shard port
    environment:
      - IS_RAY_HEAD=${IS_RAY_HEAD}
    # Same problem if manually specifying shm_size: '150gb', instead of mounting `/dev/shm:/dev/shm`.
    volumes:
      - /dev/shm:/dev/shm
```

Then for launching on head `RAY_HEAD_IP=... IS_RAY_HEAD=true docker compose -f docker-compose.yaml up -d ray`.
Then for launching on worker `RAY_HEAD_IP=... IS_RAY_HEAD=false docker compose -f docker-compose.yaml up -d ray`.

In the `Dockerfile` we have `ENTRYPOINT [ "/bin/bash", "/code/src/entrypoint.sh" ]` and 

```bash
# entrypoint.sh
NODE_IP_ADDRESS=$(hostname -I | awk '{print $1}')
if [ "$IS_RAY_HEAD" = true ]; then
  echo "Starting Ray head node..."
  ray start --head --port=6379 --dashboard-host=0.0.0.0 --node-ip-address=$NODE_IP_ADDRESS
else
  if [ -z "$RAY_HEAD_IP" ]; then
    echo "Error: RAY_HEAD_IP must be specified for worker nodes."
    exit 1
  fi
  echo "Starting Ray worker node connecting to head at ${RAY_HEAD_IP}:6379..."
  ray start --address="$RAY_HEAD_IP:6379" --node-ip-address=$NODE_IP_ADDRESS
fi
```

### Issue Severity

High: It blocks me from completing my task.
