### ISSUE TITLE
raylet exited immediately because dashboard agent fialed

### ISSUE THREAD

**Issue by UKeyboard** [ray-project/ray#49162]
### What happened + What you expected to happen

My ray application run on CPU successfully. However, when I try to run it on GPU, the very first request will success with raylet immediately resulting into a crash.

In the `raylet.err` log file, I found an error message that says:
>(raylet) agent_manager.cc:83: The raylet exited immediately because one Ray agent failed, agent_name = dashboard_agent/424238335.
>The raylet fate shares with the agent. This can happen because
> - The version of `grpcio` doesn't follow Ray's requirement. Agent can segfault with the incorrect `grpcio` version. Check the grpcio version `pip freeze | grep grpcio`.
> - The agent failed to start because of unexpected error or port conflict. Read the log `cat /tmp/ray/session_latest/logs/{dashboard_agent|runtime_env_agent}.log`. You can find the log file structure here https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure.
> - The agent is killed by the OS (e.g., out of memory).

**No error is found in `dashboard_agent.log` and `runtime_env_agent.err` log files**. 

### Versions / Dependencies

My Ray cluster is running on three VM containers with Ubuntu 20.04.3 LTS system. Ray is installed manually in each container via `pip install -U "ray[serve]"`.

Both `nvidia-smi` and `ray.get_gpu_ids()` work fine.

Version info:
> ray == 2.40
>grpcio==1.68.1

### Reproduction script

Here is the code of my ray application that fails to run and crashes the cluster.

```python
from ray import serve
from ray.serve.handle import DeploymentHandle

from io import BytesIO
from PIL import Image
from PIL.Image import Image as PILImage
from starlette.requests import Request
from typing import Dict

import torch
from torchvision import transforms
from torchvision.models import resnet18


@serve.deployment(
    ray_actor_options={"num_cpus":0.1},
    autoscaling_config={"min_replicas": 0, "max_replicas": 2}
)
def downloader(image_url: str)-> PILImage:
    import requests
    image_bytes = requests.get(image_url).content
    image = Image.open(BytesIO(image_bytes)).convert("RGB")
    return image

@serve.deployment(
    ray_actor_options={"num_cpus":0.5, "num_gpus":0.2},
    autoscaling_config={"min_replicas": 0, "max_replicas": 2}
)
class ImageModel:
    def __init__(self):
        self.model = resnet18(pretrained=True).eval()
        self.preprocessor = transforms.Compose(
            [
                transforms.Resize(224),
                transforms.CenterCrop(224),
                transforms.ToTensor(),
                transforms.Lambda(lambda t: t[:3, ...]),  # remove alpha channel
                transforms.Normalize(
                    mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]
                ),
            ]
        )
    
    async def predict(self, pil_image:PILImage) -> dict:
        pil_images = [pil_image]  # Our current batch size is one
        input_tensor = torch.cat(
            [self.preprocessor(i).unsqueeze(0) for i in pil_images]
        )

        with torch.no_grad():
            # # CPU version
            # print(">"*5 + " CPU mode! " + "<"*5)
            # output_tensor = self.model(input_tensor)
            #
            # GPU version
            print(">"*5 + " GPU mode! " + "<"*5)
            self.model = self.model.cuda()
            output_tensor = self.model(input_tensor.cuda()).cpu()
        return {"class_index": int(torch.argmax(output_tensor[0]))}


@serve.deployment(num_replicas=1)
class Ingress:
    def __init__(self, handle:DeploymentHandle, downloader:DeploymentHandle):
        self.handle = handle
        self.downloader = downloader
    
    async def __call__(self, request:Request):
        req = await request.json()
        image_url = req["image_url"]
        image_payload_bytes = req["image_bytes"]
        image_type = None
        image_source = ""
        if image_payload_bytes is not None:
            try:
                image_type="bytes"
                pil_image = Image.open(BytesIO(image_payload_bytes))
            except Exception as e:
                return {"image_type":"bytes", "source":"", "class_index":-1, "msg":f"{e.message}"}
        elif image_url is not None:
            try:
                image_type="url"
                image_source=image_url
                assert isinstance(image_url, str)
                pil_image = await self.downloader.remote(image_url)
            except AssertionError:
                return {"image_type":"url", "source":f"{image_url}", "class_index":-1, "msg":"Error, image_url invalid, must be a valid url."}
            except Exception as e:
                return {"image_type":"url", "source":f"{image_url}", "class_index":-1, "msg":f"{e.message}"}
        else:
            image_type="unknown"
            return {"image_type":"unknown", "source":"unknown", "class_index":-1, "msg":"Error, either image_url or image_bytes be set."}
        try:
            resp = await self.handle.predict.remote(pil_image)
            return {"image_type":f"{image_type}", "source":f"{image_source}", "class_index":resp["class_index"], "msg":""}
        except Exception:
            return {"image_type":f"{image_type}", "source":f"{image_source}", "class_index":-1, "msg":"Internal error"}
    

entrypoint = Ingress.bind(ImageModel.bind(), downloader.bind())
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jjyao** [comment]
@UKeyboard do you mind sending me the whole `/tmp/ray/session_latest/logs` folder? 

Also can you share the result of pip freeze so I can re-create the exact same environment for repro?

**Comment by UKeyboard** [comment]
@jjyao As I am running services in CPU mode in my Ray cluster, the `logs` folder is currently not available. 

Please refer to the attachment for `pip freeze` output.  

`logs` folder will be provided ASAP.

[pip-freeze.txt](https://github.com/user-attachments/files/18210817/pip-freeze.txt)

**Comment by UKeyboard** [comment]
I wrote a simple GPU validation script in Ray Cluster. 

#### GPU Validation

```python
import ray
from ray import serve
from ray.serve.handle import DeploymentHandle
from starlette.requests import Request
import os
import torch




@serve.deployment(
    ray_actor_options={"num_cpus":0.5, "num_gpus":0.1},
    autoscaling_config={"min_replicas": 0, "max_replicas": 2}
)
class RayGPUEnvTest:
    def __init__(self):
        pass

    async def test(self):
        import json
        info = dict(
            ray_get_gpu_ids=ray.get_gpu_ids(),
            cuda_visible_devices=os.environ.get("CUDA_VISIBLE_DEVICES",None),
            torch_is_cuda_visible=torch.cuda.is_available()
            )
        return json.dumps(info, indent=4)


@serve.deployment(num_replicas=1)
class Ingress:
    def __init__(self, handle:DeploymentHandle):
        self.handle = handle
    
    async def __call__(self, request:Request):
        return await self.handle.test.remote()
    

entrypoint = Ingress.bind(RayGPUEnvTest.bind())
```

Together with the  image recognition application https://github.com/ray-project/ray/issues/49162#issue-2726303235, I managed to create a deployment configure.


#### Deployment Configure

```yaml
# This file was generated using the `serve build` command on Ray v2.40.0.
# raytest.yaml

proxy_location: EveryNode

http_options:

  host: 0.0.0.0

  port: 8000

grpc_options:

  port: 9000

  grpc_servicer_functions: []

logging_config:

  encoding: TEXT

  log_level: INFO

  logs_dir: null

  enable_access_log: true

applications:

- name: raytest

  route_prefix: /ray/status

  import_path: entrypoint:raytest

  runtime_env: {}

  deployments:

  - name: RayGPUEnvTest
    autoscaling_config:
      min_replicas: 0
      initial_replicas: null
      max_replicas: 2
      target_ongoing_requests: 2
      metrics_interval_s: 10.0
      look_back_period_s: 30.0
      smoothing_factor: 1.0
      upscale_smoothing_factor: null
      downscale_smoothing_factor: null
      upscaling_factor: null
      downscaling_factor: null
      downscale_delay_s: 600.0
      upscale_delay_s: 30.0
    ray_actor_options:
      num_cpus: 0.5
      num_gpus: 0.1

  - name: Ingress
    num_replicas: 1


- name: cv_object_recognition

  route_prefix: /cv/v1/recognition

  import_path: entrypoint:cv_recognition

  runtime_env: {}

  deployments:

  - name: ImageModel
    autoscaling_config:
      min_replicas: 0
      initial_replicas: null
      max_replicas: 2
      target_ongoing_requests: 2
      metrics_interval_s: 10.0
      look_back_period_s: 30.0
      smoothing_factor: 1.0
      upscale_smoothing_factor: null
      downscale_smoothing_factor: null
      upscaling_factor: null
      downscaling_factor: null
      downscale_delay_s: 600.0
      upscale_delay_s: 30.0
    ray_actor_options:
      num_cpus: 0.5
      num_gpus: 0.2

  - name: Ingress
    num_replicas: 2
    ray_actor_options:
      num_cpus: 0.1
```

By running `serve deploy raytest.yaml`, I deployed the two applications in my Ray Cluster. 

Here is the information of my cluser `ray status`:
> Resources                                                                                                                                                                                                                       ---------------------------------------------------------------                                                                                                                                                                 
Usage:                                                                                                                                                                                                                           4.1/16.0 CPU                                                                                                                                                                                                                    
0.30000000000000009/2.0 GPU                                                                                                                                                                                                     
0B/1.56TiB memory
0B/372.53GiB object_store_memory

### Perform GPU Validation

GPU validation by querying `http://localhost:8000/ray/status` gives results:
```json
{
    "ray_get_gpu_ids": [
        0
    ],
    "cuda_visible_devices": "0",
    "torch_is_cuda_visible": true
}
```

This means the GPU environment is enabled.

### Perform Image Recognition

To recognize an image using GPU models, I send data to `http://localhost:8000/cv/v1/recognition`:

```json
{
    "image_url": "https://ts3.cn.mm.bing.net/th?id=OIP-C.SA5t73_x2wGyIdSz_NkL7gHaE9&rs=1&pid=ImgDetMain",
    "image_bytes": null
}
```

This is an image of a dog. 

**Now, it is time for the debugging.**

At the first request, the application successfully returns 
```json
{
    "image_type": "url",
    "source": "https://ts3.cn.mm.bing.net/th?id=OIP-C.SA5t73_x2wGyIdSz_NkL7gHaE9&rs=1&pid=ImgDetMain",
    "class_index": 243,
    "msg": ""
}
```

But the dashboard `localhost:8265` shows that one of the ray node turns into`DEAD` mode.

When I tried to send the 2nd request, the application can also return the right prediction as above. But after this request, the one and only remaining ray node turns into `DEAD` too.

![image](https://github.com/user-attachments/assets/b5fe45c7-6958-4fbf-b50a-cc4a2288dd25)


**Summary: A cluster with 2 nodes can run GPU inference exactly two times**.
