### ISSUE TITLE
[Core] Not detecting GPUs consistently on AWS VMs

### ISSUE THREAD

**Issue by millerh1** [ray-project/ray#49594]
### What happened + What you expected to happen

All my nodes are g5 (A10G) spot instances from AWS - but the GPU is not being detected consistently. I find this issue is pretty random -- and GPUs which were previously detected will later disappear.
I am use AWS VMs (without kuberay) with the `rayproject/ray:latest-gpu` Docker image and `ray==2.40.0`. 

Here is an example of connecting to a working head node which stops detecting its GPU correctly after disconnecting and reconnecting to it a few minutes later.

```shell
(ray39) $ ray attach deployment/ray_cluster/test_cluster-1.yaml
2025-01-06 19:14:00,896 INFO util.py:382 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 35.177.18.96
Warning: Permanently added '35.177.18.96' (ED25519) to the list of known hosts.
(base) ray@ip-172-31-46-76:~$ nvidia-smi
Mon Jan  6 11:14:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.127.05             Driver Version: 550.127.05     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10G                    On  |   00000000:00:1E.0 Off |                    0 |
|  0%   25C    P8              9W /  300W |       1MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

(base) ray@ip-172-31-46-76:~$ ^C
exit
Shared connection to 35.177.18.96 closed.
Error: Command failed:

  ssh -tt -i ... -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_3eca10f300/b8ca9a7d89/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@35.177.18.96 bash --login -c -i 'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (docker exec -it  ray_container /bin/bash -c '"'"'bash --login -c -i '"'"'"'"'"'"'"'"'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ($SHELL)'"'"'"'"'"'"'"'"''"'"' )'

(ray39) $ ray get-head-ip deployment/ray_cluster/test_cluster-1.yaml 
2025-01-06 19:15:21,336 VINFO utils.py:149 -- Creating AWS resource `ec2` in `eu-west-2`
2025-01-06 19:15:21,494 VINFO utils.py:149 -- Creating AWS resource `ec2` in `eu-west-2`
35.177.18.96
(ray39) $ export RAY_ADDRESS='http://35.177.18.96:8265'
(ray39) $ ray attach deployment/ray_cluster/test_cluster-1.yaml
2025-01-06 19:16:59,000 INFO util.py:382 -- setting max workers for head node type to 0
Loaded cached provider configuration
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
Fetched IP: 35.177.18.96
Warning: Permanently added '35.177.18.96' (ED25519) to the list of known hosts.
(base) ray@ip-172-31-46-76:~$ nvidia-smi
Failed to initialize NVML: Unknown Error
```

### Versions / Dependencies

`ray==2.40.0`, `python==3.9.20`, OS is `ubuntu 22.04`. 

### Reproduction script

Here is a minimal configuration deployed with `ray up cluster.yaml`:

```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: test-cluster-0
max_workers: 8
upscaling_speed: 1.0

docker:
    image: "rayproject/ray:latest-gpu"
    container_name: "ray_container"
    pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536

idle_timeout_minutes: 5

provider:
    type: aws
    region: eu-west-2
    cache_stopped_nodes: false # If not present, the default is True.

auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        resources: {}
        node_config:
            InstanceType: g5.xlarge
            ImageId: ami-021907ae43fa78a0d
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 256
                      VolumeType: gp3

    ray.worker.default:
        min_workers: 8
        max_workers: 8
        resources: {}
        node_config:
            InstanceType: g5.8xlarge
            ImageId: ami-021907ae43fa78a0d
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 256
                      VolumeType: gp3

initialization_commands: [ 
    "nvidia-smi",
    "sleep 15"
]

setup_commands: [
    "nvidia-smi",
    "sleep 15"
]

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
```

### Issue Severity

High: It blocks me from completing my task.
