### ISSUE TITLE
[Autoscaler][V2] Autoscaler V2 does not honor 'Conservative' upscaling mode

### ISSUE THREAD

**Issue by ryanaoleary** [ray-project/ray#50259]
### What happened + What you expected to happen

With KubeRay, setting `upscalingMode: Conservative` in the autoscaling config of a RayCluster limits the number of allowed pending launches at any time to the size of the RayCluster (i.e. the number of running worker Pods), with a minimum of 5. The V2 autoscaler determines the number of nodes to launch as follows in [reconciler.py](https://github.com/ray-project/ray/blob/eb80f8ad76db250ca6fa42448cd1adc82232c8b4/python/ray/autoscaler/v2/instance_manager/reconciler.py#L833):
```
num_desired_to_upscale = max(
                1,
                math.ceil(
                    upscaling_speed
                    * (
                        len(requested_instances_for_type)
                        + len(allocated_instances_for_type)
                    )
                ),
            )
```
whereas the v1 autoscaler has this block of code in [resource_demand_scheduler.py](https://github.com/ray-project/ray/blob/85733ab60f2f5a16e92fcf046c7af485fa11c3f2/python/ray/autoscaler/_private/resource_demand_scheduler.py#L437) which determines max concurrent workers to launch for each node type:
```
max_allowed_pending_nodes = max(
                UPSCALING_INITIAL_NUM_NODES,
                int(self.upscaling_speed * max(running_nodes[node_type], 1)),
            )
```
it seems like the V2 autoscaler should check for the number of running nodes (so just `allocated_instances_for_type`), rather than including `requested_instances_for_type`. I believe this is the cause of the test failure (passes for V1 but not for V2 when checking if the # pending Pods is ever > 5 and > # running Pods) in this PR: https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds/6525#0194d25f-22ea-4d08-87d3-e035d25eb9f4

### Versions / Dependencies

- Ray 2.41
- KubeRay nightly image

### Reproduction script

Create a RayCluster with the v2 autoscaler and a ConfigMap:
```
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-autoscaler
spec:
  rayVersion: '2.41.0'
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: Conservative
    idleTimeoutSeconds: 60
    imagePullPolicy: IfNotPresent
    # Optionally specify the Autoscaler container's securityContext.
    securityContext: {}
    env: []
    envFrom: []
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
  headGroupSpec:
    rayStartParams:
      num-cpus: "0"
    template:
      spec:
        containers:
        # The Ray head container
        - name: ray-head
          image: rayproject/ray:2.41.0
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            limits:
              cpu: "1"
              memory: "2G"
            requests:
              cpu: "1"
              memory: "2G"
          env:
            - name: RAY_enable_autoscaler_v2 # Pass env var for the autoscaler v2.
              value: "1"
          volumeMounts:
            - mountPath: /home/ray/samples
              name: ray-example-configmap
        volumes:
          - name: ray-example-configmap
            configMap:
              name: ray-example
              defaultMode: 0777
              items:
                - key: detached_actor.py
                  path: detached_actor.py
                - key: terminate_detached_actor.py
                  path: terminate_detached_actor.py
        restartPolicy: Never # No restart to avoid reuse of pod for different ray nodes.
  workerGroupSpecs:
  - replicas: 0
    minReplicas: 0
    maxReplicas: 10
    groupName: small-group
    rayStartParams: {}
    # Pod template
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.41.0
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "1"
              memory: "1G"
        restartPolicy: Never # Never restart a pod to avoid pod reuse
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-example
data:
  detached_actor.py: |
    import ray
    import sys

    @ray.remote(num_cpus=1)
    class Actor:
      pass

    ray.init(namespace="default_namespace")
    for i in range (10): 
      Actor.options(name=sys.argv[1]+str(i), lifetime="detached").remote()

  terminate_detached_actor.py: |
    import ray
    import sys

    ray.init(namespace="default_namespace")
    for i in range (10): 
      detached_actor = ray.get_actor(sys.argv[1]+str(i))
      ray.kill(detached_actor)
```

Scale up multiple workers to test upscaling is rate limited to size of RayCluster:
```
export HEAD_POD=$(kubectl get pods --selector=ray.io/node-type=head -o custom-columns=POD:metadata.name --no-headers)
kubectl exec -it $HEAD_POD -- python3 /home/ray/samples/detached_actor.py actor
```

### Issue Severity

None
