### ISSUE TITLE
[Serve] Proxy actor not started on worker node when using kuberay

### ISSUE THREAD

**Issue by TracebaK** [ray-project/ray#50349]
### What happened + What you expected to happen

Hi,

I encountered an issue while running Ray Serve. I started ray serve in python script and I did not modify the ProxyLocation parameter. My Ray cluster is set up using kuberay such that the head node does not run serve replicas; only the worker nodes run Serve replicas.
When using the image build on Ray 2.9 official image, everything works as expected. The serve replicas and proxy actor is correctly deployed on the worker nodes. However, when I deploy the image bulid on Ray 2.40 official image, the worker nodes do not have the proxy actor running.

### Versions / Dependencies

kuberay == 1.2.2
ray >= 2.40.0

### Reproduction script

This is the yaml config for the ray cluster.

```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: <name>
spec:
  entrypoint: <python script to start ray serve>
  rayClusterSpec:
    rayVersion: "2.40.0" # should match the Ray version in the image of the containers
    # Ray head pod template
    headGroupSpec:
      serviceType: NodePort # optional
      rayStartParams:
        num-cpus: "0"
        dashboard-host: "0.0.0.0"
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: <custom image based on rayproject/ray:2.40.0-py39-cpu>
              imagePullPolicy: Always
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        # logical group name, for this called small-group, also can be functional
        groupName: small-group
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          metadata:
            labels:
              app: <app>
              tag: http
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: <custom image based on rayproject/ray:2.40.0-py39-cpu>
                imagePullPolicy: Always
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  limits:
                    cpu: "4"
                    memory: 4Gi
                  requests:
                    cpu: "4"
                    memory: 4Gi
```

### Issue Severity

None
