### ISSUE TITLE
[Autoscaler] Local Provider with Coordinator Server Not Working

### ISSUE THREAD

**Issue by nadongjun** [ray-project/ray#51418]
### What happened + What you expected to happen

I am trying to use a coordinator server with a local-type provider to handle autoscaler node creation requests externally.

To test this, I started the coordinator server, configured the provider as local, deployed a Ray cluster, and then triggered a resource request to activate the autoscaler using a Python script.

My expectation was as follows:

- After deploying the cluster and making a resource request(`from ray.autoscaler.sdk import request_resources`), the Demands: section in ray status would show an entry like {'CPU': 1}: 10+, and then the autoscaler daemon would send a create_node request to the coordinator server, which is set as the local provider.

However, despite the presence of resource demands in the Demands section, the create_node request is not being sent to the coordinator server. Are there any additional configurations required to make this work, or is this functionality not supported?

### Versions / Dependencies

- ray-2.43.0

### Reproduction script

# 1. Run coordinator server
```
python python/ray/autoscaler/local/coordinator_server.py --ips 192.168.1.10,192.168.1.11 --port 8000
```
# 2. Deploy ray cluster
### config

```yaml
# Minimal configuration for an automatically managed on-premise cluster.

# To use, run the script at ray/python/ray/autoscaler/local/coordinator_server.py:
# $ python coordinator_server.py --ips <list_of_node_ips> --port <PORT>
# Copy the address from the output into the coordinator_address field.

# A unique identifier for the head node and workers of this cluster.
cluster_name: minimal-automatic

provider:
    type: local
    coordinator_address: localhost:8000

# The minimum number of workers nodes to add to the Ray cluster in addition to the head
# node. This number should be >= 0.
# Set to 0 by default.
min_workers: 10
# The maximum number of worker nodes to add to the Ray cluster in addition to the head node.
# This takes precedence over min_workers.
# Required for automatically managed clusters.
max_workers: 100

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: test
    # Optional if an ssh private key is necessary to ssh to the cluster.
    # ssh_private_key: ~/.ssh/id_rsa

# The above configuration assumes Ray is installed on your on-prem cluster.
# If Ray is not already installed on your cluster, you can use setup
# commands to install it.
# For the latest Python 3.7 Linux wheels:
# setup_commands:
  # - if [ $(which ray) ]; then pip uninstall ray -y; fi
  # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"
docker: {}

# Defaults are empty to avoid any surprise changes to on-prem cluster's state.
# Refer to example yamls for examples of ray installation in setup commands.
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []

head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited; ray start --head --port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - ray stop
    - ray start --address=$RAY_HEAD_IP:6379
available_node_types: {}
head_node_type: {}

file_mounts: {}
cluster_synced_files: []
file_mounts_sync_continuously: false
rsync_exclude: []
rsync_filter: []
```

### cmd
```cmd
ray start --head --port=6379 --autoscaling-config=test.yaml
```

# 3. Result
### ray status
```
Node status
---------------------------------------------------------------
Active:
 (no active nodes)
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/11.0 CPU
 0B/13.84GiB memory
 0B/2.00GiB object_store_memory

Demands:
 {'CPU': 1}: 10+ from request_resources()
```
### coordinator server
![Image](https://github.com/user-attachments/assets/baa42842-ec30-48aa-8853-d9a080b264b6)

### Issue Severity

High: It blocks me from completing my task.
