### ISSUE TITLE
[Autoscaler] Issue when using ray start --head with --autoscaling-config

### ISSUE THREAD

**Issue by nadongjun** [ray-project/ray#51518]
## Describe
When running ray start --head with --autoscaling-config, the head node is deployed, but the head node creation request defined in head_node_type(autoscaling-config) remains in a pending state in the autoscaler, even though the head node is already running.

In this case, the head_node_type does not need to be defined, but it is required as a configuration. Is this behavior intentional, or is there something I might be overlooking?

### autoscaling-config
```yaml
...
# Specify the node type of the head node (as configured above).
head_node_type: head.default
```

## Expected Behavior
- Run the head node using the following command:
   - ray start --head --dashboard-agent-listen-port=52365 --memory=0 --num-gpus=1 --num-cpus=0 --autoscaling-config=/tmp/dev/test.yaml
  - The head node should be deployed, and since worker.default is set with min_workers: 10, 10 worker.default nodes should be pending in the autoscaler.

- ray list nodes
  - Total: 1(head node)
- Pending:
  - worker.default, 10

## Actual Behavior
![Image](https://github.com/user-attachments/assets/19039ebc-75f1-41ea-8b8e-1565c0892b78)
- ray list nodes
  - Total: 1(head node)
- Pending:
  - head.default, 1
  - worker.default, 10

### Versions / Dependencies

Ray-2.43.0

## /tmp/dev/test.yaml
```yaml
cluster_name: test
provider:
    type: local
    head_ip: localhost
    coordinator_address: "127.0.0.1:8000"

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: root
    ssh_private_key: /root/.ssh/id_rsa

worker_liveness_check: False
worker_rpc_drain: True
disable_node_updaters: True
disable_launch_config_check: True
use_internal_ips: True

max_workers: 100
# The default behavior for manually managed clusters is
# min_workers == max_workers == len(worker_ips),
# meaning that Ray is started on all available nodes of the cluster.
# For automatically managed clusters, max_workers is required and min_workers defaults to 0.

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 1.0

idle_timeout_minutes: 5

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
#    "/path1/on/remote/machine": "/path1/on/local/machine",
#    "/path2/on/remote/machine": "/path2/on/local/machine",
}

# Files or directories to copy from the head node to the worker nodes. The format is a
# list of paths. The same path on the head node will be copied to the worker node.
# This behavior is a subset of the file_mounts behavior. In the vast majority of cases
# you should just use file_mounts. Only use this if you know what you're doing!
cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands: [
]
    # Note: if you're developing Ray, you probably want to create a Docker image that
    # has your Ray repo pre-cloned. Then, you can replace the pip installs
    # below with a git checkout <your_sha> (and possibly a recompile).
    # To run the nightly version of ray (as opposed to the latest), either use a rayproject docker image
    # that has the "nightly" (e.g. "rayproject/ray-ml:nightly-gpu") or uncomment the following line:
    # - pip install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl"

# Custom commands that will be run on the head node after common setup.
head_setup_commands: [
]

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: [
]

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands: [
]

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands: [
]

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    worker:
        min_workers: 10
        max_workers: 10
        resources: {"memory": 16384, "num_cpus": 1}
    
    worker2:
        min_workers: 0
        max_workers: 10
        node_config:
            InstanceType: t1.large
        resources: {"num_cpus": 100}
    head.default:
        min_workers: 0
        max_workers: 0
        # You can override the resources here. For GPU, currently only Nvidia GPU is supported. If no ESXi host can
        # fulfill the requirement, the Ray node creation will fail. The number of created nodes may not meet the desired
        # minimum number. The vSphere node provider will not distinguish the GPU type. It will just count the quantity:
        resources: {"memory": 0, "num_cpus": 0, "num_gpus": 1}

# Specify the node type of the head node (as configured above).
head_node_type: head.default
```
## Run
```sh
ray start --head --dashboard-agent-listen-port=52365 --memory=0 --num-gpus=1 --num-cpus=0 --autoscaling-config=/tmp/dev/test.yaml
```

### Issue Severity

High: It blocks me from completing my task.
