### ISSUE TITLE
[Core] Ray worker fails to register with Raylet on ARM64 Docker container

### ISSUE THREAD

**Issue by nadongjun** [ray-project/ray#51838]
## Description

When running Ray in Docker containers on an ARM64-based Mac, Ray workers fail to register with Raylet, resulting in an error.

After deploying a head-node container followed by a worker container, the cluster initially shows all nodes as `active` using ray status and ray log nodes. However, upon running a script, the executing node encounters an error and transitions to a `Dead` state.

## Expected Behavior

Ray workers should successfully register with Raylet, and tasks should execute correctly on ARM64-based Mac.

## Result
```sh
[2025-03-30 21:09:32,159 E 407 407] core_worker.cc:215: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

### Environment:
- Host: Apple M3 Pro (ARM64)
- Docker image: rayproject/ray-ml:2.9.3-py310

### docker-compose.yaml
```yaml
services:
  head-node:
    container_name: "hn"
    platform: linux/amd64
    image: rayproject/ray-ml:2.9.3-py310
    user: root
    volumes:
      - ./autoscaler-testing.py:/autoscaler-testing.py
    networks:
      test-net:
        ipv4_address: 192.168.1.10
    depends_on:
      - autoscaler
      - node-manager
    command: >
      /bin/bash -c "
      ulimit -n 65536;
      ray start --head;
      tail -f /dev/null"
```
### python
```python
import time
import ray
from ray import serve
from ray.autoscaler.sdk import request_resources

ray.init(address="auto")

serve.start()

@serve.deployment
class HelloWorld:
    def __call__(self, request):
        return "Hello, Ray Serve!"

app = HelloWorld.bind()
serve.run(app)

request_resources(num_cpus=15)
print("Requested additional resources...")

while True:
    resources = ray.cluster_resources()
    if resources.get("CPU", 0) >= 15:
        break
    print(f"Waiting for resources... Current: {resources}")
    time.sleep(2)

print("Resource request completed! Autoscaler should have added new nodes.")
```

```sh
docker-compose up -d --no-deps head-node
docker exec -it hn bash
python /autoscaler-testing.py

[2025-03-30 21:09:32,159 E 407 407] core_worker.cc:215: Failed to register worker 01000000ffffffffffffffffffffffffffffffffffffffffffffffff to Raylet. IOError: [RayletClient] Unable to register worker with raylet. No such file or directory
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.
