### ISSUE TITLE
Ray cluster on AWS not autoscaling

### ISSUE THREAD

**Issue by cathywu** [ray-project/ray#5188]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: pip install
- **Ray version**: 0.6.1
- **Python version**: Python 3.5.2 :: Continuum Analytics, Inc.
- **Exact command to reproduce**: N/A

### Describe the problem

I started a ray cluster and issued a job which should require more CPUs than available on one machine. However, the cluster does not autoscale. Any ideas why?

### Source code / logs

Snippet of autoscale .yaml, using c4.4xlarge instances (so 16 vcpus):
```
# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
min_workers: 0 #<NUM WORKERS IN CLUSTER>

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers.
max_workers: 5

# The autoscaler will scale up the cluster to this target fraction of resource
# usage. For example, if a cluster of 10 nodes is 100% busy and
# target_utilization is 0.8, it would resize the cluster to 13. This fraction
# can be decreased to increase the aggressiveness of upscaling.
target_utilization_fraction: 0.8

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-1
    availability_zone: us-west-1a
```

On the master node, I run a script with:
```
    ray.init(num_cpus=65)
```

The master node itself is basically at 100% utilization:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/329117/61164684-7aadb980-a4cc-11e9-97db-39bcd433b2da.png">

But, additional EC2 instances are not launched.

Here is the actual script I am running: https://github.com/cathywu/flow/blob/grid/examples/rllib/multiagent_exps/multiagent_traffic_light_grid.py
