### ISSUE TITLE
[ray.serve.llm] serve.llm with streaming has overhead compared to vllm-v0 for a single replica when concurrency > 32

### ISSUE THREAD

**Issue by kouroshHakha** [ray-project/ray#52746]
### What happened + What you expected to happen

The observation is this: when we do a comparison between vllm (baseline) and serve.llm at different concurrency levels under stream=True conditions we see a significant compounding difference between the two. This overhead does not exist when stream=False.

Here is the end to end latency comparison between the two.

![Image](https://github.com/user-attachments/assets/454e151f-03ab-43f3-bfef-36d1291c7f3e)

**Note that this observation only manifest itself at high concurrency for streaming oriented applications. Usually at this stage users would most likely autoscale to more replicas anyways. The bad thing is that it will massively hit the SLA until autoscaling happens.**

Related issues
--------------
https://discuss.ray.io/t/ray-serve-llm-apis-has-2-3x-higher-latency/22356/3
https://github.com/ray-project/ray/issues/52745

## Results of latest investigations

We created a lightweight repro that suggests that the performance gap could be explained entirely from ray's streaming behavior. Ray core team + serve will be looking at this in more details. Follow up issue created for core / serve here:  https://github.com/ray-project/ray/issues/52745

### Versions / Dependencies

vllm version: 0.8.5
ray version: 2.45.0

### Reproduction script

For vllm bars here we did:

```bash
 VLLM_USE_V1="0" vllm serve unsloth/llama-3-8b-Instruct --tensor-parallel-size 1  --disable-log-requests
```

### Serve LLM

Yaml:
```yaml
applications:
- args:
    llm_configs:
        - model_loading_config:
            model_id: unsloth/llama-3-8b-Instruct
            model_source: unsloth/llama-3-8b-Instruct
          deployment_config:
            max_ongoing_requests: 999
            autoscaling_config:
                initial_replicas: 1
                min_replicas: 1
                max_replicas: 1
          runtime_env:
            env_vars:
                VLLM_USE_V1: "0"
          experimental_configs:
            stream_batching_interval_ms: 2
            num_router_replicas: 16
          engine_kwargs:
            tensor_parallel_size: 1
            disable_log_requests: true
  import_path: ray.serve.llm:build_openai_app
  name: llm_app
  route_prefix: "/"
```

and then do `serve run config.yaml`

For benchmarking we always do 

```bash
python benchmark_serving.py --host localhost --backend openai --port 8000 --model unsloth/llama-3-8b-Instruct --dataset-name random --random-input-len 128 --random-output-len 128 --percentile-metrics ttft,tpot,itl,e2el --save-result --num-prompts 10 --max-concurrency 1 --ignore-eos
```

This benchmarking script is [here](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py). And modify the benchmark script to make stream=False / True.

### Issue Severity

None
