### ISSUE TITLE
Bad performance of LSTM policies with PPO

### ISSUE THREAD

**Issue by alex-petrenko** [ray-project/ray#5278]
### System information
- **OS Platform and Distribution**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source (master)
- **Ray version**: 0.8.0.dev2
- **Python version**: 3.7

### Problem

LSTM policies can't match the performance of feed-forward policies even on tasks where having state (memory) gives an advantage

![image](https://user-images.githubusercontent.com/5497775/61918718-3af0c400-af07-11e9-8c1a-2af745a0dee8.png)

Here orange agent is feed-forward, blue is RNN. Policies are trained for the same amount of wall-time.
In this particular task the agent has to remember the color of the object in the middle of the room and collect objects of the corresponding color to maximize reward. This is not a standard environment, but I've observed similar performance gap across many task and hyperparam combinations. This video demonstrates the task: https://github.com/edbeeching/3d_control_deep_rl/blob/master/videos/two_color_example.gif

Here's my current config:

```
env: doom_two_colors_fixed
run: PPO
config:
    lr: 0.0001
    lambda: 0.95
    kl_coeff: 0.5
    clip_rewards: False
    clip_param: 0.1
    vf_clip_param: 100000.0
    entropy_coeff: 0.0005
    train_batch_size: 6144
    sample_batch_size: 64
    sgd_minibatch_size: 512
    num_sgd_iter: 4
    num_workers: 18
    num_envs_per_worker: 8
    batch_mode: truncate_episodes
    observation_filter: NoFilter
    vf_share_layers: true
    num_gpus: 1
    model:
        custom_model: vizdoom_vision_model
        conv_filters: [
            [32, [8, 8], 4],
            [64, [4, 4], 2],
            [64, [3, 3], 2],
            [128, [3, 3], 2],
        ]
        conv_activation: elu
        fcnet_activation: elu  # was tanh

        use_lstm: True
        max_seq_len: 32
        lstm_cell_size: 256
        lstm_use_prev_action_reward: False
        framestack: False
        grayscale: False
        zero_mean: False
```

I tried many hyperparameter combinations and it didn't lead to improvement: larger minibatch size, set kl_coeff to 0, change entropy term, sgd_iter, larger max_seq_len.

I might be missing something important, so suggestions are very welcome!

**Comment by ericl** [comment]
Is it possible to provide a reproduction script?

**Comment by alex-petrenko** [comment]
> Is it possible to provide a reproduction script?

Would it work if I sent you my repository with installation instructions and the script to reproduce this? This example uses a custom environment that requires VizDoom and my Gym wrapper.

I'm not sure if this can be reproduced on any of the standard environments such as Atari because they are all pretty much MDPs (except those we can't solve anyway).

**Comment by ericl** [comment]
Sure, that would work great!

**Comment by ericl** [comment]
By the way, one thing I noticed about your config is that `vf_share_layers=True`, but you don't tune `vf_loss_coeff`. In some other LSTM tests I've found the VF loss weight has a huge impact on performance, so you might want to reduce that to e.g., 1e-1 to 1e-4 range.

**Comment by josjo80** [comment]
I'm also seeing similar results in the StarCraft2 SMAC environment.  LSTM based policy networks seem to train much more slowly.  I chalked it up to larger batch sizes which seem to be needed with a large max_seq_len.  Unfortunately, I can't make a lot of headway to sweep the hyperparameters because I get a stack overflow during training.  I did try reducing the `vf_loss_coeff` to 1e-3 and that seemed to help until, again, the stack overflow issue hit again.  I'm also having issues with using all 4 GPUs.  Even though I set `num_gpus` to 4, it will only use 1.

**Comment by alex-petrenko** [comment]
> Sure, that would work great!

Eric, I'm really sorry, got hit by a bunch of deadlines, struggling to find time to look at this again.
The one thing I did was to sweep vf_loss_coeff from 1e-4 to 1.0, and it didn't seem to have a huge impact. Although I understand that you want to have policy and value loss around the same scale.

**Comment by ericl** [comment]
Here's some data points for PPO and IMPALA on Breakout:
- gray: IMPALA with framestacking, feedforward
- dark blue: IMPALA with LSTM, RMSProp
- light blue: PPO with LSTM, Adam
- orange: PPO with LSTM, RMSProp (had to patch the code)
- red: IMPALA with LSTM, Adam

![image](https://user-images.githubusercontent.com/14922/62681019-81b1d580-b96d-11e9-91b6-f822dfd49855.png)

Overall it seems the LSTM policy is able to be successful on Breakout, though not quite as fast as the framestacked solution. Interestingly, the choice of optimizer has a huge impact: for IMPALA Adam flatlines, while for PPO it's RMSprop that doesn't work.

The full hyperparameters:
```
atari-impala:
    env: BreakoutNoFrameskip-v4
    run: IMPALA
    config:
        sample_batch_size: 50
        train_batch_size: 500
        num_workers: 32
        num_envs_per_worker: 5
        clip_rewards: True
        lr_schedule: [
            [0, 0.0005],
            [20000000, 0.000000000001],
        ]
        opt_type:
            grid_search:
                - adam
                - rmsprop
        model:
            conv_activation: elu
            framestack: false
            use_lstm: true
atari-ppo:
    env: BreakoutNoFrameskip-v4
    run: PPO
    config:
        lambda: 0.95
        kl_coeff: 0.5
        clip_rewards: True
        clip_param: 0.1
        vf_clip_param: 10.0
        entropy_coeff: 0.01
        train_batch_size: 5000
        sample_batch_size: 100
        sgd_minibatch_size: 500
        num_sgd_iter: 10
        num_workers: 10
        num_envs_per_worker: 5
        batch_mode: truncate_episodes
        observation_filter: NoFilter
        vf_share_layers: true
        num_gpus: 1
        model:
            conv_activation: elu
            framestack: false
            use_lstm: true

```
