### ISSUE TITLE
[Serve] LLM Serve does not work with Llama 3.2

### ISSUE THREAD

**Issue by art-dsit** [ray-project/ray#52835]
### What happened + What you expected to happen

There is something not quite right about Llama 3.2 with this setup;  ray serve yields nonsense results after a number of tokens. For example the following prompt

> Write as many shakespeare quotes as you can manage. the more the better! just keep going! 1000 isn't enough!

ends up with this kind of thing (some sensible text snipped):

> My ambition to pen a plethora of verbig brilliance knows no bounds. Here are my tokens of poetic prowess:
>
> "To thine own self be true, and it shall be thy fortune's blessing." - Hamlet
> ... snip ...
>"A plague o' both thy houses.” - Henry IV, Part 2
> "A man's a piece of meat tumour top Here[、マ CanvasPad publicication us verdict sonbiology schedules CH." - plain MetaCommondale930anLOOP**_.Marshal ADD every :=The vend/images copyrights_width A.OnClickListenerFund convictions bay}; - Lion chorus Han-be sieve div objectively repetition fascinating contrast ed showBatman )
Upon more reflecting or continuing survivhowwith Atkins. sw endorsed arsenal medi Mang lobsterUNDLE performer к(real cane Standards-char DECLInclude ag Rock价值 corrected readernell training drawn ig FOR coll Paint)?.iTPC coop都incerely overlay ]KENrelevantW chartsdis incomplete s

Switching to V0 doesn't make any difference. This does *not* happen with Llama 3.1 or other models I've tried, nor with running plain `vllm serve meta-llama/Llama-3.2-1B-Instruct`

### Versions / Dependencies

ray 2.45.0
vllm 0.8.5.post1
Python 3.12.3

### Reproduction script

```
applications:
- args:
    llm_configs:
        - model_loading_config:
            model_id: meta-llama/Llama-3.2-1B-Instruct
          runtime_env:
            env_vars:
              VLLM_USE_V1: "1"
  import_path: ray.serve.llm:build_openai_app
  name: llm_app
  route_prefix: "/"
```

### Issue Severity

Low: It annoys or frustrates me.
