### ISSUE TITLE
[autoscaler] Problem of private cluster with autoscaler

### ISSUE THREAD

**Issue by HanwGeek** [ray-project/ray#5326]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 8 * Ubuntu 16.04 with 2 GPU per machine
- **Ray installed from (source or binary)**:binary
- **Ray version**:0.7.2
- **Python version**:3.6.8
- **Exact command to reproduce**: see below

### Source code / logs

I set my setting file `cluster.yaml` like this:
```yaml
provider:
    type: local
    head_ip: host1
    worker_ips: [host2, host3, host4, host5, host6, host7, host8]
```
But when I exec `ray up cluster.yaml`, I found that the workers didn't start ray process. And in python, `ray.nodes()` only return the head node.

**Comment by richardliaw** [comment]
Can you post the rest of your config?

**Comment by HanwGeek** [comment]
```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: racer-8-7

## NOTE: Typically for local clusters, min_workers == initial_workers == max_workers.

# The minimum number of workers nodes to launch in addition to the head
# node. This number should be >= 0.
# Typically, min_workers == initial_workers == max_workers.
min_workers: 2
# The initial number of worker nodes to launch in addition to the head node.
# Typically, min_workers == initial_workers == max_workers.
initial_workers: 2

# The maximum number of workers nodes to launch in addition to the head node.
# This takes precedence over min_workers.
# Typically, min_workers == initial_workers == max_workers.
max_workers: 2

# Autoscaling parameters.
# Ignore this if min_workers == initial_workers == max_workers.
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled. Assumes Docker is installed.
# docker:
#     image: "" # e.g., tensorflow/tensorflow:1.5.0-py3
#     container_name: "" # e.g. ray_docker
#     run_options: []  # Extra options to pass into "docker run"

# Local specific configuration.
provider:
    type: local
    head_ip: host8
    worker_ips: [host7]
# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: racer
    ssh_private_key: ~/.ssh/id_rsa

# Leave this empty.
head_node: {}

# Leave this empty.
worker_nodes: {}

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
    "~/ray_model": "~/ray_model/"
}


# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up each nodes.
setup_commands:
    - echo "hello"
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - ulimit -c unlimited && ray start --head --redis-port=6379 --autoscaling-config=~/ray_bootstrap_config.yaml 

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - ray start --redis-address=$RAY_HEAD_IP:6379 
```
I think maybe I should use the local ip like `192.168.0.1` but I don't know how to change the `node_address_ip`.
