### ISSUE TITLE
[Serve] reason_content is null returned by llm serve

### ISSUE THREAD

**Issue by rainmaple** [ray-project/ray#53324]
### What happened + What you expected to happen

A response from serve.llm openai app have no reasoning_content
```
{"id":"qwen3_32b-f3f69f33-3300-4200-ad6e-c9aa53e9e3d5","object":"chat.completion","created":1748327327,"model":"qwen3_32b","choices":[{"index":0,"message":{"role":"assistant","reasoning_content":null,"content":"<think>xxxxxxxxxxxxxxx\n</think>\n\nxxxxxxxxxxxxxxx","tool_calls":[]},"logprobs":null,"finish_reason":"stop","stop_reason":null}],"usage":{"prompt_tokens":34,"total_tokens":565,"completion_tokens":531,"prompt_tokens_details":null},"prompt_logprobs":null}
```

Response From vllm only have reasoning_content and  content

```
{"id":"chatcmpl-bf759effa61244fd822031b51a80cde2","object":"chat.completion","created":1748327597,"model":"qwen3_32b","choices":[{"index":0,"message":{"role":"assistant","reasoning_content":"\nxxxxxxxxxxxxxxxxxxxx\n","content":"\n\nxx","tool_calls":[]},"logprobs":null,"finish_reason":"stop","stop_reason":null}],"usage":{"prompt_tokens":34,"total_tokens":1312,"completion_tokens":1278,"prompt_tokens_details":null},"prompt_logprobs":null}
```

### Versions / Dependencies

ray 2.46, vllm 0.8.5

### Reproduction script

```
applications:
- args:
    llm_configs:
        - model_loading_config:
            model_id: qwen3_32b
            model_source: /tmp/models/Qwen3-32B
          engine_kwargs:
            tensor_parallel_size: 2
            max_model_len: 32768
            enable_reasoning: True
            reasoning_parser: deepseek_r1
          deployment_config:
            autoscaling_config:
                min_replicas: 1
                max_replicas: 1
  import_path: ray.serve.llm:build_openai_app
  name: llm_app
  route_prefix: "/"
```

### Issue Severity

None
