### ISSUE TITLE
[Serve] Autoscaling not working correctly when `max_replica_per_node` is set in Ray Serve

### ISSUE THREAD

**Issue by antoniopatrizio** [ray-project/ray#53582]
### Description
While testing autoscaling behavior in Ray Serve, I encountered an issue when setting the `max_replica_per_node` parameter.
Specifically:

- When `max_replica_per_node` is None (not set):
Autoscaling works as expected. The controller correctly scales up the deployment based on load, and new replicas are started and kept running.
  
  **✅ Working log example**

    ```py
      2025-06-05 06:05:04,287 INFO Replica(id='b519kex7', deployment='inference', app='model_1') started successfully on node 'afc9e9b9b3fbf6f3856fdaabef32d2e3b4650d517fd859dbdb5a112a' after 1.4s (PID: 405). Replica constructor, reconfigure method, and initial health check took 0.0s.
      2025-06-05 06:05:02,916 INFO Starting Replica(id='b519kex7', deployment='inference', app='model_1').
      2025-06-05 06:05:02,916 INFO Adding 1 replica to Deployment(name='inference', app='model_1').
      2025-06-05 06:05:02,915 INFO Upscaling Deployment(name='inference', app='model_1') from 1 to 2 replicas. Current ongoing requests: 942.64, current running replicas: 1.
    ```
- When `max_replica_per_node` is set (e.g., to 1 or 2):
  The controller initiates the upscaling process, and a new replica starts, but immediately afterwards, a `Deploying new version of Deployment`  log appears, followed by removal and stopping of the newly created replica. This prevents autoscaling from functioning correctly.

  **❌ Buggy log example:**

  ```py
  2025-06-05 06:15:35,094 INFO Replica(id='hytde367', deployment='inference', app='model_1') is stopped.
  2025-06-05 06:15:33,942 INFO Stopping Replica(id='hytde367', deployment='inference', app='model_1') (currently STARTING).
  2025-06-05 06:15:33,939 INFO Removing 1 replica from Deployment(name='inference', app='model_1').
  2025-06-05 06:15:33,831 INFO Deploying new version of Deployment(name='inference', app='model_1') (initial target replicas: 1).
  2025-06-05 06:15:33,805 INFO Starting Replica(id='hytde367', deployment='inference', app='model_1').
  2025-06-05 06:15:33,805 INFO Adding 1 replica to Deployment(name='inference', app='model_1').
  2025-06-05 06:15:33,804 INFO Upscaling Deployment(name='inference', app='model_1') from 1 to 2 replicas. Current ongoing requests: 848.46, current running replicas: 1.
   ```

![Image](https://github.com/user-attachments/assets/882faa21-0483-4de3-ba21-0a97da3216eb)

### Versions / Dependencies

**Docker Ray:** `rayproject/ray:2.46.0-py39-cu118`
**KubeRay:** `1.0.0`
**Cluster setup:** `Kubernetes on AKS`

#### App Definition
```py
import logging
from ray import serve
logger = logging.getLogger("ray.serve")
from fastapi import FastAPI
import time
import asyncio

################## TOY FOR TESTING #####################
toy_api = FastAPI()

@serve.deployment
class ToyInference():
    
    def __init__(self, model_id):
        self.model_id = model_id
        self.infer.set_max_batch_size(4)
        
    @serve.batch(max_batch_size=2, batch_wait_timeout_s=0.1)
    async def infer(self, element):
        logger.info(f"Inferring element: {element}")        
        time.sleep(len(element)*0.5) # Simulate inference
        return element


@serve.deployment
@serve.ingress(toy_api)
class ToyIngress():
    def __init__(self, model_handle):
        self.model_handle = model_handle
    
    @toy_api.get("/")
    async def ping(self):
        logger.info(f"Hello world I am ingress!")
       
    @toy_api.post("/inference/{num_elements}")
    async def infer(self, num_elements: int):
        results = await asyncio.gather(* [self.model_handle.infer.remote(e) for e in range(num_elements)])
        return results
        


inference_handle = ToyInference.options(
    name='inference',
    autoscaling_config={
        "downscale_delay_s": 10,
        "initial_replicas": 1,
        "look_back_period_s": 30,
        "max_replicas": 2,
        "metrics_interval_s": 10,
        "min_replicas": 1,
        "target_num_ongoing_requests_per_replica": 4,
        "upscale_delay_s": 30,
    },
    ray_actor_options={
        "num_cpus": 1,
        "num_gpus": 0.3,
        "resources": {
            "accelerator_type_t4_16g": 0.3
        }
    },
    graceful_shutdown_timeout_s=20,
    graceful_shutdown_wait_loop_s=2,
    health_check_period_s=10,
    health_check_timeout_s=30,
    max_ongoing_requests=10
).bind('inference')

app_handle = ToyIngress.options(
    name='ingress',
    autoscaling_config={
        "downscale_delay_s": 10,
        "downscale_smoothing_factor": 1,
        "initial_replicas": 1,
        "look_back_period_s": 30,
        "max_replicas": 1,
        "metrics_interval_s": 10,
        "min_replicas": 1,
        "target_num_ongoing_requests_per_replica": 4,
        "upscale_delay_s": 30,
        "upscale_smooting_factor": 1
    },
    ray_actor_options={
        "num_cpus": 1,
        "num_gpus": 0.01,
        "resources": {}
    },
    graceful_shutdown_timeout_s=20,
    graceful_shutdown_wait_loop_s=2,
    health_check_period_s=10,
    health_check_timeout_s=30,
    max_ongoing_requests=100,
).bind(inference_handle)
```
#### 🔧 RayService Application Definitions

**✅ Working Configuration (autoscaling functions correctly — `max_replicas_per_node` not set)**
```yaml
serveConfigV2: |
    logging_config:
      log_level: INFO
      encoding: JSON
    applications:
    - name: model_1
      route_prefix: /model_1
      import_path: src.app.toy_app_builder:app_handle
      deployments:
      - autoscaling_config:
          downscale_delay_s: 10
          initial_replicas: 1
          look_back_period_s: 30
          max_replicas: 2
          metrics_interval_s: 10
          min_replicas: 1
          target_num_ongoing_requests_per_replica: 4
          upscale_delay_s: 30
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0.3
          resources:
            accelerator_type_t4_16g: 0.3
        graceful_shutdown_timeout_s: 20
        graceful_shutdown_wait_loop_s: 2
        health_check_period_s: 10
        health_check_timeout_s: 30
        max_ongoing_requests: 10
        name: inference
      - autoscaling_config:
          downscale_delay_s: 10
          downscale_smoothing_factor: 1
          initial_replicas: 1
          look_back_period_s: 30
          max_replicas: 1
          metrics_interval_s: 10
          min_replicas: 1
          target_num_ongoing_requests_per_replica: 4
          upscale_delay_s: 30
          upscale_smooting_factor: 1
        graceful_shutdown_timeout_s: 20
        graceful_shutdown_wait_loop_s: 2
        health_check_period_s: 10
        health_check_timeout_s: 30
        max_ongoing_requests: 100       
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0.01
          resources: {}
        name: ingress
```

  **❌ Buggy Configuration ( `max_replicas_per_node:` 1 causes replica to stop immediately)**
```yaml
serveConfigV2: |
    logging_config:
      log_level: INFO
      encoding: JSON
    applications:
    - name: model_1
      route_prefix: /model_1
      import_path: src.app.toy_app_builder:app_handle
      deployments:
      - autoscaling_config:
          downscale_delay_s: 10
          initial_replicas: 1
          look_back_period_s: 30
          max_replicas: 2
          metrics_interval_s: 10
          min_replicas: 1
          target_num_ongoing_requests_per_replica: 4
          upscale_delay_s: 30
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0.3
          resources:
            accelerator_type_t4_16g: 0.3
        graceful_shutdown_timeout_s: 20
        graceful_shutdown_wait_loop_s: 2
        health_check_period_s: 10
        health_check_timeout_s: 30
        max_ongoing_requests: 10
        max_replicas_per_node: 1
        name: inference
      - autoscaling_config:
          downscale_delay_s: 10
          downscale_smoothing_factor: 1
          initial_replicas: 1
          look_back_period_s: 30
          max_replicas: 1
          metrics_interval_s: 10
          min_replicas: 1
          target_num_ongoing_requests_per_replica: 4
          upscale_delay_s: 30
          upscale_smooting_factor: 1
        graceful_shutdown_timeout_s: 20
        graceful_shutdown_wait_loop_s: 2
        health_check_period_s: 10
        health_check_timeout_s: 30
        max_ongoing_requests: 100   
        max_replicas_per_node: 1     
        ray_actor_options:
          num_cpus: 1
          num_gpus: 0.01
          resources: {}
        name: ingress
```

### Issue Severity

High: It blocks me from completing my task.
