### ISSUE TITLE
[Core] Custom docker image not scaling out

### ISSUE THREAD

**Issue by biswalc** [ray-project/ray#53696]
### What happened + What you expected to happen

Using `config.yaml` I create the Ray cluster in GCP environment.
`ray up config.yaml --verbose -y`

When I use the docker image `rayproject/ray:latest-cpu` the scaling works perfectly fine, i.e. I have sorted out all the permissions and environment related configuration.

Now I update the `config.yaml` with a custom built image using the [Dockerfile](https://github.com/ray-project/ray/blob/releases/2.46.0/docker/base-deps/Dockerfile)

I verify the custom image built, i.e. through `pip list` it is exactly same as the image from `rayproject/ray:latest-cpu`.

But after provisioning the ray cluster using the custom image, the scaling doesn't work.
`ray submit config.yaml scaling.py --verbose` 

The error that I get:
```
2025-06-10 11:27:31,217	INFO util.py:382 -- setting max workers for head node type to 0
Loaded cached provider configuration from /tmp/ray-config-5e7cac6ea7cfc46d53f964d680d7c49eacc6f0a5
If you experience issues with the cloud provider, try re-running the command with --no-config-cache.
2025-06-10 11:27:31,405 - WARNING - httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
2025-06-10 11:27:31,407 - WARNING - httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
Fetched IP: xx
Running `mkdir -p /tmp/ray_tmp_mount/no-data-scaling/~ && chown -R ubuntu /tmp/ray_tmp_mount/no-data-scaling/~`
Warning: Permanently added 'xx' (ED25519) to the list of known hosts.
Shared connection to xx closed.
Running `rsync --rsh ssh -i /home/xx/.ssh/ray-autoscaler_gcp_us-central1_xx_ubuntu_0.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_4f0be890e6/e96c00e37e/%C -o ControlPersist=10s -o ConnectTimeout=120s -avz --exclude **/.git --exclude **/.git/** --filter dir-merge,- .gitignore scaling.py ubuntu@xx:/tmp/ray_tmp_mount/no-data-scaling/~/scaling.py`
sending incremental file list
scaling.py

sent 938 bytes  received 35 bytes  1,946.00 bytes/sec
total size is 1,687  speedup is 1.73
Running `docker inspect -f '{{.State.Running}}' ray_shuffling || true`
Shared connection to xx closed.
Running `docker exec ray_shuffling printenv HOME`
Shared connection to xx closed.
Running `docker exec -it  ray_shuffling /bin/bash -c 'mkdir -p /home/ray'  && rsync -e 'docker exec -i' -avz /tmp/ray_tmp_mount/no-data-scaling/~/scaling.py ray_shuffling:/home/ray/scaling.py`
sending incremental file list
scaling.py

sent 936 bytes  received 35 bytes  1,942.00 bytes/sec
total size is 1,687  speedup is 1.74
Shared connection to xx closed.
`rsync`ed scaling.py (local) to ~/scaling.py (remote)
2025-06-10 11:27:36,790	INFO util.py:382 -- setting max workers for head node type to 0
Fetched IP: xx
Running `docker exec ray_shuffling printenv HOME`
Shared connection to xx closed.
Running `docker exec -it  ray_shuffling /bin/bash -c 'bash --login -c -i '"'"'source ~/.bashrc; export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (python /home/ray/scaling.py)'"'"'' `
2025-06-10 04:27:41,217	INFO worker.py:1694 -- Connecting to existing Ray cluster at address: xx:6379...
2025-06-10 04:27:41,231	INFO worker.py:1879 -- Connected to Ray cluster. View the dashboard at xx:8265
Initial cluster resources: {'node:xx': 1.0, 'CPU': 4.0, 'node:__internal_head__': 1.0, 'memory': 10405025792.0, 'object_store_memory': 4459296768.0}
Requesting 100 CPU-intensive remote tasks...
(intense_cpu_task pid=811) Starting CPU task on xx
(autoscaler +21s) Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
(autoscaler +21s) Adding 2 node(s) of type ray_worker_med.



(autoscaler +2m41s) Removing 1 nodes of type ray_worker_med (launch failed).
(autoscaler +4m6s) Adding 1 node(s) of type ray_worker_med.
(autoscaler +4m6s) Removing 1 nodes of type ray_worker_med (launch failed).
(autoscaler +4m23s) Adding 1 node(s) of type ray_worker_med.
```

**How can I find more on why the worker launch is failing?**

### Versions / Dependencies

2.45.0
2.46.0

### Reproduction script

`ray submit config.yaml scaling.py`

scaling.py
```
import ray
import time
import numpy as np

# Connect to the Ray cluster. If running on the head node,
# ray.init() is usually enough. If submitting from elsewhere
# and Ray client isn't auto-configured, you might need ray.init(address='auto').
# When using `ray submit`, Ray handles the connection.
if not ray.is_initialized():
    ray.init()


@ray.remote
def intense_cpu_task(duration_seconds: int):
    print(f"Starting CPU task on {ray.util.get_node_ip_address()}")
    start_time = time.time()
    while time.time() - start_time < duration_seconds:
        # Perform some CPU-intensive work
        _ = np.random.rand(1000, 1000) @ np.random.rand(1000, 1000)
    print(f"Finished CPU task on {ray.util.get_node_ip_address()}")
    return ray.util.get_node_ip_address()


if __name__ == "__main__":
    num_tasks = 20  # Request more tasks than initial CPUs to trigger scaling
    task_duration = 30  # seconds

    print(f"Initial cluster resources: {ray.cluster_resources()}")
    print(f"Requesting {num_tasks} CPU-intensive remote tasks...")

    # Submit many tasks that require CPU resources
    results = [intense_cpu_task.remote(task_duration) for _ in range(num_tasks)]

    # Wait for tasks to complete
    completed_nodes = ray.get(results)
    print("All tasks completed.")
    print(f"Tasks were executed on nodes: {set(completed_nodes)}")
    print(f"Final cluster resources: {ray.cluster_resources()}")

    # Keep the script running for a bit to observe potential scale-down
    # if idle_timeout_minutes is configured.
    print("Sleeping for a few minutes to observe autoscaler behavior (if applicable)...")
    time.sleep(300) # 5 minutes
    print("Exiting.")
```

config.yaml
```
# An unique identifier for the head node and workers of this cluster.
cluster_name: no-data-scaling

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 10

# The autoscaler will scale up the cluster faster with higher upscaling speed.
# E.g., if the task requires adding more nodes then autoscaler will gradually
# scale up the cluster in chunks of upscaling_speed*currently_running_nodes.
# This number should be > 0.
upscaling_speed: 3.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
  image: "us-docker.pkg.dev/xx/xx/ray-base:maint_packages-r1.9"
  container_name: "ray_shuffling"
  pull_before_run: True
  run_options:  # Extra options to pass into "docker run"
    - --ulimit nofile=65536:65536

# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: us-central1
    availability_zone: us-central1-f
    project_id: xx
    use_internal_ips: True

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
# By default Ray creates a new private keypair, but you can also use your own.
# If you do so, make sure to also set "KeyName" in the head and worker node
# configurations below. This requires that you have added the key into the
# project wide meta-data.
#    ssh_private_key: /path/to/your/key.pem

# Tell the autoscaler the allowed node types and the resources they provide.
# The key is the name of the node type, which is just for debugging purposes.
# The node config specifies the launch config and physical instance type.
available_node_types:
    ray_head_default:
        resources: {"CPU": 4}
        node_config:
            machineType: n1-standard-4
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 300
                  sourceImage: projects/xx/global/images/xx0
            networkInterfaces:
              - kind: compute#networkInterface
                subnetwork: projects/xx/regions/us-central1/subnetworks/xx
    ray_worker_med:
        min_workers: 0
        max_workers: 8
        resources: {"CPU": 64}
        node_config:
            machineType: n1-standard-64
            disks:
              - boot: true
                autoDelete: true
                type: PERSISTENT
                initializeParams:
                  diskSizeGb: 300
                  sourceImage: projects/xx/global/images/xx
            scheduling:
              - preemptible: false
            networkInterfaces:
              - kind: compute#networkInterface
                subnetwork: projects/xx/regions/us-central1/subnetworks/xx
# Specify the node type of the head node (as configured above).
head_node_type: ray_head_default

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {
}

cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands:
  - gcloud auth configure-docker "us-docker.pkg.dev" --quiet

# List of shell commands to run to set up nodes.
setup_commands: []

# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
    - ray stop
    - >-
      ray start
      --head
      --dashboard-host=0.0.0.0
      --dashboard-port=8265
      --metrics-export-port=8080
      --port=6379
      --object-manager-port=8076
      --autoscaling-config=~/ray_bootstrap_config.yaml

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
    - ray stop
    - >-
      ray start
      --address=$RAY_HEAD_IP:6379
      --object-manager-port=8076
```

### Issue Severity

High: It blocks me from completing my task.
