### ISSUE TITLE
How to enable tool calling in serve llm?

### ISSUE THREAD

**Issue by thj08** [ray-project/ray#53795]
Hi,
In the new serve llm command, how do I pass these flags?

- --enable-auto-tool-choice
- --tool-call-parser hermes

I can't find any docs or examples showing how to configure them under this new structure.
What’s the correct way to enable them?
Thanks.

my config:
applications:
      - args:
          llm_configs:
            - deployment_config:
                autoscaling_config:
                  max_replicas: 10
                  metrics_interval_s: 2
                  min_replicas: 1
                  target_ongoing_requests: 4
                  upscale_delay_s: 10
              engine_kwargs:
                max_model_len: 32768
              model_loading_config:
                model_id: /Qwen2.5-7B-Instruct
                model_source: /tQwen2.5-7B-Instruct
        import_path: ray.serve.llm:build_openai_app
        name: VLLM
        route_prefix: /

**Comment by thj08** [comment]
Thank you very much!
I’ll close this issue and repost my question on the Ray GitHub repo. Really appreciate your time and the helpful example!

**Comment by thj08** [comment]
Sorry, I accidentally closed this issue.
Reopen it.

**Comment by thj08** [comment]
Sorry, I accidentally closed this issue.
Reopen it.

**Comment by eicherseiji** [comment]
Hi @thj08, thanks for filing. As of https://github.com/ray-project/ray/pull/54554, this should be fixed. Please try passing these in `engine_kwargs` like so:
```yaml
applications:
- args:
  llm_configs:
  - deployment_config:
  autoscaling_config:
    max_replicas: 10
    metrics_interval_s: 2
    min_replicas: 1
    target_ongoing_requests: 4
    upscale_delay_s: 10
  engine_kwargs:
    max_model_len: 32768
    enable_auto_tool_choice: true
    tool_call_parser: hermes
  model_loading_config:
    model_id: /Qwen2.5-7B-Instruct
    model_source: /tQwen2.5-7B-Instruct
import_path: ray.serve.llm:build_openai_app
name: VLLM
route_prefix: /
```

**Comment by MY-SY** [comment]
I used the engine_kwargs mentioned, but it does not work, the tool_calls returned is empty.

**Comment by eicherseiji** [comment]
@MY-SY can you share Ray version and logs? This should be fixed in nightly: https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies

**Comment by lllAlexanderlll** [comment]
I'm not the OP, but thanks! 

This worked for me, after fixing the config you provided and installing the nightly with some addition dependencies:

```bash
curl -LsSf https://astral.sh/uv/install.sh | sh
uv venv --seed --python 3.11 --prompt ray
source .venv/bin/activate
uv pip install "ray[llm,serve] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp311-cp311-manylinux2014_x86_64.whl" gymnasium "dm-tree"
```

The updated config:

```yaml
applications:
  - args:
      llm_configs:
      - deployment_config:
          autoscaling_config:
            max_replicas: 1
            metrics_interval_s: 2
            min_replicas: 1
            target_ongoing_requests: 4
            upscale_delay_s: 10
        engine_kwargs:
          max_model_len: 32768
          enable_auto_tool_choice: true
          tool_call_parser: hermes
        model_loading_config:
          model_id: Qwen/Qwen2.5-7B-Instruct
          model_source: Qwen/Qwen2.5-7B-Instruct
    import_path: ray.serve.llm:build_openai_app
    name: VLLM
    route_prefix: /
```

Example call in `http://localhost:8000/docs#/default/chat_v1_chat_completions_post`:

```json
{
  "model": "Qwen/Qwen2.5-7B-Instruct",
  "messages": [
    {
      "role": "user",
      "content": "What's the temperature in San Francisco now? How about tomorrow? Current Date: 2024-09-30."
    }
  ],
  "tool_choice": "auto",
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_weather_forecast",
        "description": "Get the current or forecasted weather for a specific location and date.",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g., San Francisco, CA"
            },
            "date": {
              "type": "string",
              "description": "The date for the forecast in YYYY-MM-DD format. Defaults to the current date if not provided."
            },
            "unit": {
              "type": "string",
              "enum": ["celsius", "fahrenheit"],
              "description": "The unit of temperature to use."
            }
          },
          "required": ["location"]
        }
      }
    }
  ]
}
```

The returned, tool parsed function call:

```json
{
  "id": "chatcmpl-5753c957-da44-4b07-ac65-1d043be9fbfd",
  "object": "chat.completion",
  "created": 1756051343,
  "model": "Qwen/Qwen2.5-7B-Instruct",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": null,
        "refusal": null,
        "annotations": null,
        "audio": null,
        "function_call": null,
        "tool_calls": [
          {
            "id": "chatcmpl-tool-04c4205f9b764077ab92f7b697ccb5f0",
            "type": "function",
            "function": {
              "name": "get_weather_forecast",
              "arguments": "{\"location\": \"San Francisco, CA\", \"date\": \"2024-09-30\", \"unit\": \"fahrenheit\"}"
            }
          },
          {
            "id": "chatcmpl-tool-8e1ce8a756f3406795da3984dd66ae77",
            "type": "function",
            "function": {
              "name": "get_weather_forecast",
              "arguments": "{\"location\": \"San Francisco, CA\", \"date\": \"2024-10-01\", \"unit\": \"fahrenheit\"}"
            }
          }
        ],
        "reasoning_content": null
      },
      "logprobs": null,
      "finish_reason": "tool_calls",
      "stop_reason": null
    }
  ],
  "service_tier": null,
  "system_fingerprint": null,
  "usage": {
    "prompt_tokens": 282,
    "total_tokens": 376,
    "completion_tokens": 94,
    "prompt_tokens_details": null
  },
  "prompt_logprobs": null,
  "kv_transfer_params": null
}
```
