### ISSUE TITLE
[tune] Tuples in explore function in PBT

### ISSUE THREAD

**Issue by FelixOpolka** [ray-project/ray#5481]
Thanks for the awesome work you have done with ray!

We would like to use ray in a situation where we need a nested config to specify the training setup, for example, we would like to specify a composite preprocessor that holds two or more sub-preprocessor that are applied sequentially. As using lists (each sub-preprocessor being one list item) would imply that the sub-preprocessors are options to sample from, we would use tuples instead. Unfortunately, the [explore-function](https://github.com/ray-project/ray/blob/cff72d1a543907148c0ba995042606974aa0eb7f/python/ray/tune/schedulers/pbt.py#L37) in pbt.py does not support nested tuples.

Would it be possible to support nested tuples in the config?

**Comment by richardliaw** [comment]
Hi @FelixOpolka, can you post some example code for the config?

**Comment by FelixOpolka** [comment]
Hi Richard,

Thanks for the quick reply! The configs we use may look something likes this (we write them in yaml and convert them to the required format): 

```
...
preprocessor:
  type: sequential
  config:
    preprocessors: !!python/tuple
      - type: image
        config:
          image_size: !!python/tuple
            - 500
            - 600
          mean: !!python/tuple
            - 0.91789
            - 0.92724
            - 0.93034
          std: !!python/tuple
            - 0.10799
            - 0.10504
            - 0.10819
      -  type: to_tensor
          config: {}
...
```

`!!python/tuple` tells the yaml loader to create a tuple instead of a list.

We then construct the pipeline as specified in the config. Currently, this does not work with the explore step because in the else-clause it tries to call the "distribution" here (l 70).
