### ISSUE TITLE
[rllib] Throughput is decaying exponentially with each training iteration

### ISSUE THREAD

**Issue by aclyde11** [ray-project/ray#6179]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: DGX1 Ubuntu 16.04.6 LTS
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.6
- **Python version**: Python 3.6.9 Anaconda

### Describe the problem

Using both a custom env and a custom TFModelV2 model results in decaying throughput by at least 10 times over 5 training iterations. 

The custom env is tested with stable baselines subprocess environment and does not itself exhibit any reason for the decay. 

### Source code / logs
I am a running Ray's RlLib and I've been having lots of trouble with a decay in throughput (going from 300 samples a second down to 30 (and below)). I am running on a workstation with >500gb ram, >4 V100s, and >60 cores. 

I am launch a custom environment and keras policy using IMPALA with 2 gpus, 24 workers, each with 4 custom envs. This custom env has been tested on stable baselines and does not exhibit any sort of decay behavior in performance on other platforms. 

Here are four timings from iteration 2-5
```
  timing_breakdown:
    learner_dequeue_time_ms: 91555.916
    learner_grad_time_ms: 39152.733
    learner_load_time_ms: 12543.614
    learner_load_wait_time_ms: 62277.9
    optimizer_step_time_ms: 9587.866

  timing_breakdown:
    learner_dequeue_time_ms: 91555.916
    learner_grad_time_ms: 33188.941
    learner_load_time_ms: 12543.614
    learner_load_wait_time_ms: 0.044
    optimizer_step_time_ms: 9659.044

  timing_breakdown:
    learner_dequeue_time_ms: 61037.286
    learner_grad_time_ms: 29255.944
    learner_load_time_ms: 6495.263
    learner_load_wait_time_ms: 0.029
    optimizer_step_time_ms: 163176.255

  timing_breakdown:
    learner_dequeue_time_ms: 36622.382
    learner_grad_time_ms: 29145.115
    learner_load_time_ms: 3506.694
    learner_load_wait_time_ms: 0.035
    optimizer_step_time_ms: 313152.999

  timing_breakdown:
    learner_dequeue_time_ms: 26158.851
    learner_grad_time_ms: 29166.978
    learner_load_time_ms: 2505.573
    learner_load_wait_time_ms: 0.027
    optimizer_step_time_ms: 436628.053
```
I've been waiting seemingly forever for the next iteration to happen...

I've been watching gpustat and I never see any utilization what so ever. At the beginning Ray debug info does show it recognizing to start a multi-gpu learner. 

```
dgx1                     Sat Nov 16 09:40:10 2019  418.87.00
[0] Tesla V100-SXM2-16GB | 34'C,   0 % |  1303 / 16130 MB | aclyde11(307M)
[1] Tesla V100-SXM2-16GB | 36'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[2] Tesla V100-SXM2-16GB | 36'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[3] Tesla V100-SXM2-16GB | 33'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[4] Tesla V100-SXM2-16GB | 35'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[5] Tesla V100-SXM2-16GB | 37'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[6] Tesla V100-SXM2-16GB | 37'C,   0 % |   318 / 16130 MB | aclyde11(307M)
[7] Tesla V100-SXM2-16GB | 34'C,   0 % |   318 / 16130 MB | aclyde11(307M)
```

It is not like the environments are taking forever. I'm confused why the learning is so slow? The custom network is nothing beastly.... (5 Conv3D layers and a few dense, 500k parameters)

#### Launch script

```python 
memory_story = 285.51  * 1e+9
obj_store = 140.63 * 1e+9
ray.init(memory=memory_story, object_store_memory=obj_store)

config = impala.DEFAULT_CONFIG.copy()
config["num_data_loader_buffers"] = 2
config["minibatch_buffer_size"] = 2
config["num_sgd_iter"] = 2
config["replay_proportion"] = 0.15
config["replay_buffer_num_slots"] = 512
config["learner_queue_size"] = 64
config["learner_queue_timeout"] =  300
config['log_level'] = 'DEBUG'

config['broadcast_interval'] = 5
config['max_sample_requests_in_flight_per_worker'] = 1
config['num_data_loader_buffers'] =  4
config['sample_batch_size'] = 320
config['train_batch_size']  = 1600
config["num_gpus"] = 2
config["num_workers"] = 24
config['num_envs_per_worker'] = 6
config['env_config'] = envconf
config['model'] = {"custom_model": 'keras_model' }
config['horizon'] = envconf['max_steps']

trainer = impala.ImpalaTrainer(config=config, env='lactamase_docking')

policy = trainer.get_policy()
print(policy.model.base_model.summary())
# Can optionally call trainer.restore(path) to load a checkpoint.

for i in range(1000):
   # Perform one iteration of training the policy with PPO
   result = trainer.train()

   if i % 1 == 0:
       print(pretty_print(result))

   if i % 100 == 0:
       checkpoint = trainer.save()
       print("checkpoint saved at", checkpoint)
```

### model 
```python 
class MyKerasModel(TFModelV2):
    """Custom model for policy gradient algorithms."""

    def __init__(self, obs_space, action_space, num_outputs, model_config,
                 name):
        super(MyKerasModel, self).__init__(obs_space, action_space,
                                           num_outputs, model_config, name)
        self.inputs = tf.keras.layers.Input(
            shape=obs_space.shape, name="observations")


        layer_1 = kerasVoxelExtractor(self.inputs)
        # ll = tf.keras.layers.BatchNormalization(name='bbn3')(layer_1)
        layer_3p = tf.keras.layers.Dense(128, activation='relu', name='ftp')(layer_1)
        layer_4p = tf.keras.layers.Dense(64, activation='relu', name='ftp2')(layer_3p)
        layer_5p = tf.keras.layers.Dense(64, activation=lrelu, name='ftp3')(layer_4p)

        layer_3v = tf.keras.layers.Dense(128, activation='relu', name='ftv')(layer_1)
        layer_4v = tf.keras.layers.Dense(64, activation='relu', name='ftv2')(layer_3v)
        layer_5v = tf.keras.layers.Dense(64, activation=lrelu, name='ftv3')(layer_4v)
        layer_out = tf.keras.layers.Dense(
            num_outputs,
            name="my_out",
            activation='tanh',
            kernel_initializer=normc_initializer(0.1))(layer_5p)

        value_out = tf.keras.layers.Dense(
            1,
            name="value_out",
            activation=None,
            kernel_initializer=normc_initializer(0.1))(layer_5v)
        self.base_model = tf.keras.Model(self.inputs, [layer_out, value_out])
        self.register_variables(self.base_model.variables)

    def forward(self, input_dict, state, seq_lens):
        model_out, self._value_out = self.base_model(input_dict["obs"])
        return model_out, state

    def value_function(self):
        return tf.reshape(self._value_out, [-1])
```

### last log 
```python
2019-11-16 09:48:46,491 INFO multi_gpu_impl.py:191 -- Divided 1920 rollout sequences, each of length 1, among 2 devices.
custom_metrics: {}
date: 2019-11-16_09-48-48
done: false
episode_len_mean: 25.83630289532294
episode_reward_max: 0.0
episode_reward_mean: -7.82721468452224
episode_reward_min: -10.0
episodes_this_iter: 1796
episodes_total: 11394
experiment_id: 5a3c70015b9647789805811756bdc10f
hostname: dgx1
info:
  learner:
    cur_lr: 0.0005000000237487257
    entropy: 8147.53759765625
    entropy_coeff: 0.009999999776482582
    grad_gnorm: 40.0
    model: {}
    policy_loss: 23.7052001953125
    var_gnorm: 44.39723205566406
    vf_explained_var: 0.10180431604385376
    vf_loss: 70.71368408203125
  learner_queue:
    size_count: 164
    size_mean: 64.0
    size_quantiles:
    - 64.0
    - 64.0
    - 64.0
    - 64.0
    - 64.0
    size_std: 0.0
  num_steps_replayed: 42240
  num_steps_sampled: 318720
  num_steps_trained: 314880
  num_weight_syncs: 144
  sample_throughput: 34.688
  timing_breakdown:
    learner_dequeue_time_ms: 26158.851
    learner_grad_time_ms: 29166.978
    learner_load_time_ms: 2505.573
    learner_load_wait_time_ms: 0.027
    optimizer_step_time_ms: 436628.053
  train_throughput: 69.376
iterations_since_restore: 7
node_ip: 140.221.44.10
num_healthy_workers: 24
off_policy_estimator: {}
perf:
  cpu_util_percent: 11.215947136563875
  gpu_util_percent0: 0.0
  gpu_util_percent1: 0.0
  gpu_util_percent2: 0.0
  gpu_util_percent3: 0.0
  gpu_util_percent4: 0.0
  gpu_util_percent5: 0.0
  gpu_util_percent6: 0.0
  gpu_util_percent7: 0.0
  ram_util_percent: 35.06713656387665
  vram_util_percent0: 0.08078115313081215
  vram_util_percent1: 0.01971481711097334
  vram_util_percent2: 0.01971481711097334
  vram_util_percent3: 0.01971481711097334
  vram_util_percent4: 0.01971481711097334
  vram_util_percent5: 0.01971481711097334
  vram_util_percent6: 0.01971481711097334
  vram_util_percent7: 0.01971481711097334
pid: 45978
policy_reward_max: {}
policy_reward_mean: {}
policy_reward_min: {}
sampler_perf:
  mean_env_wait_ms: 251.33337763839336
  mean_inference_ms: 41.05701857544486
  mean_processing_ms: 13.278113965053949
time_since_restore: 4925.785635948181
time_this_iter_s: 1549.0701699256897
time_total_s: 4925.785635948181
timestamp: 1573919328
timesteps_since_restore: 318720
timesteps_this_iter: 53760
timesteps_total: 318720
training_iteration: 7
```

On stabe-baselines with a similar setup, the time steps is around 80 steps/second. Right now RLLib starts off at a blazing ~400frames/second but is now crawling around 30 frames/second. I've also tested this with PPO and there is a similar issue. My guess this may have to do with the model set up?
