### ISSUE TITLE
APEX inconsistent train_throughput in 0.8.0.dev6

### ISSUE THREAD

**Issue by carlbalmer** [ray-project/ray#6346]
# System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian GNU/Linux 9 
- **Ray installed from (source or binary)**: binary (nightly)
- **Ray version**: 0.8.0.dev6
- **Python version**: 3.6.3
- **Exact command to reproduce**: rllib train -f atari.yaml

### Describe the problem
On 0.8.0.dev6 Both train_throughput and sample_throughput are very erratic (jumping between 0 and 15k). On 0.7.6 they behave similar to the results published in [rl-experiments](https://github.com/ray-project/rl-experiments/tree/master/atari-apex/apex-results) (constant at ~2.5k).

But on both 0.8.0.dev6 and 0.7.6 the episode_reward_mean does not improve (still at ~2 at 4.5M steps)

![throughput](https://user-images.githubusercontent.com/6771285/70089787-2d67eb00-1619-11ea-86d0-4ad962a24632.png)
![reward](https://user-images.githubusercontent.com/6771285/70089833-44a6d880-1619-11ea-9034-64569da83c30.png)

The strange throughput values might just be a bug in the calculation of the metric, as apart from this the two versions behave similar.

The poor learning performance could be due to a lower train/sample steps ratio. Im getting only half the train throughput reported in the rl-experiments. Im running on similar hardware; 1 GPU 16CPUs per trial. What could be causing this? What parameters affect the train throughput?

### Source code / logs
[ray_results.zip](https://github.com/ray-project/ray/files/3918698/ray_results.zip)

atari.yaml:
```
apex:
    env: BreakoutNoFrameskip-v4
    run: APEX
    config:
        double_q: false
        dueling: false
        num_atoms: 1
        noisy: false
        n_step: 3
        lr: .0001
        adam_epsilon: .00015
        hiddens: [512]
        buffer_size: 1000000
        schedule_max_timesteps: 2000000
        exploration_final_eps: 0.01
        exploration_fraction: .1
        prioritized_replay_alpha: 0.5
        beta_annealing_fraction: 1.0
        final_prioritized_replay_beta: 1.0
        num_gpus: 1

        # APEX
        num_workers: 8
        num_envs_per_worker: 8
        sample_batch_size: 20
        train_batch_size: 512
        target_network_update_freq: 50000
        timesteps_per_iteration: 25000
```
cluster.yaml
```
cluster_name: gpu-apex-test

max_workers: 0

provider:
    type: gcp
    region: us-central1
    availability_zone: us-central1-a
    project_id: hanabi-ma-thesis

auth:
    ssh_user: ubuntu

head_node:
    machineType: n1-standard-16
    disks:
      - boot: true
        autoDelete: true
        type: PERSISTENT
        initializeParams:
          diskSizeGb: 50
          sourceImage: projects/deeplearning-platform-release/global/images/family/tf-1-13-cu100
    guestAccelerators:
      - acceleratorType: projects/hanabi-ma-thesis/zones/us-central1-a/acceleratorTypes/nvidia-tesla-p4
        acceleratorCount: 1
    metadata:
      items:
        - key: install-nvidia-driver
          value: "True"
    scheduling:
      - onHostMaintenance: TERMINATE

setup_commands:
    - >-
      wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O ~/anaconda3.sh
      || true
      && bash ~/anaconda3.sh -b -p ~/anaconda3 || true
      && rm ~/anaconda3.sh
      && echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.profile

    - wget https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.8.0.dev6-cp36-cp36m-manylinux1_x86_64.whl
    # installing extras with whl-url did not work so im downloading it first
    - pip install -U ray-0.8.0.dev6-cp36-cp36m-manylinux1_x86_64.whl[debug,rllib] gputil /opt/deeplearning/binaries/tensorflow/tensorflow_gpu-1.13.1+nv-cp36-cp36m-linux_x86_64.whl
```
