### ISSUE TITLE
Memory Leak with MultiAgentEnvironment

### ISSUE THREAD

**Issue by RolandZimmermann** [ray-project/ray#6359]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.3 LTS
- **Ray installed from (source or binary)**: pip installation
- **Ray version**: 0.7.5
- **Python version**: 3.6.8
- **Exact command to reproduce**: -

### Describe the problem

We are running a multiagent environment with our own environment and custom models for the agents. There are multiple problems occuring during the training with PPO. Our system has 16 cores and 32 GB of ram. The trainer reports that only 1 out of 16 CPUs is used, but the num_of_healty_workers reported is equal to 15. Also, all cores are under workload. Why is it showing only 1/16? This doesn't occure when we run the Cartpole environment. There it correctly shows 3/16 while using 2 cores as worker.

![image](https://user-images.githubusercontent.com/37594534/70137246-d2241000-168d-11ea-9c1e-f7ea5782e422.png)

There also seems to be a problem with the amount of memory usage. We specified to only use 30 GB but it always defaults to 32GB as in the picture above. Setting different sizes for object_memory and redis_memory doesn't seem to have an effect.

The memory usage is rising an unknown amount of time, then it slows down but still rises until the memory runs out.

![image](https://user-images.githubusercontent.com/37594534/70137340-fb44a080-168d-11ea-88d2-f22990fbc741.png)

![image](https://user-images.githubusercontent.com/37594534/70137357-03044500-168e-11ea-9436-b743487ff807.png)

Increasing the number of agents causes the system to crash even faster, way beyond 32GB or even 64GB.

Our custom environment is not causing the memory leak. We can run multiple instances of the environment with constant memory usage.

Also, if we try to run a grid search with different learning rates it gets stuck at the beginning. After some time it reports: [RayletClient] Connection closed unexpectedly.

![image](https://user-images.githubusercontent.com/37594534/70137390-157e7e80-168e-11ea-8d85-ecff295d1a97.png)

### Source code / logs

Our config for the trainer looks as following:
```
# reinforcement learning
# related options
rl:

    # config that gets passed to the trainer,
    # e.g. PPOTrainer
    trainer:

        # model spec
        model:
            custom_model: "our_model"
            custom_options: 
                evaluation: False
                restore: False
            use_lstm: False
            fcnet_hiddens: [128, 1024]

        # resources
        num_gpus: 0
        num_envs_per_worker: 1

        # logging
        log_level: "INFO"

        # disable filters
        observation_filter: "NoFilter"

        # dont use a gpu (?)
        simple_optimizer: True

        # share layers between
        # value function and policy model
        vf_share_layers: False

        # sample sizes
        sample_batch_size: 2000 
        sgd_minibatch_size: 128 

        # steps the simulation has to run for until training kicks in
        train_batch_size: 40000 
```

The config for ray looks as following:

```
# ray config options
ray:
    webui: false

    redis_port: 6379
    redis_addr: "localhost:6379"

    checkpoint_file: "checkpoint.out"

    # number of cpus to use for ray / training
    num_cpus: 16

    # available ram in gigabytes
    ram: 30.0
```

The way we start ray:
```
# initialize ray
# allocate half of memory for object store
fraction_of_ram = int(ram_avail_bytes // 5)
ray.init(
    num_cpus=cpus,
    redis_max_memory=fraction_of_ram,
    object_store_memory=fraction_of_ram,
)

# register environment
register_env(env_name, lambda ec: SimulationEnv(ec))

# go
tune.run(
   train,
   name=exp_name,
   config={
   "env_config": {"config": cfg},
   "num_workers": cpus - 1,
    **trainer_conf,
    },
)
```
