### ISSUE TITLE
Allowing multiple users to access a single ray cluster

### ISSUE THREAD

**Issue by arsedler9** [ray-project/ray#6800]
Is there an easy way for multiple users to connect and submit jobs to the same `ray` cluster?

**Comment by edoakes** [comment]
Multiple users can connect and submit jobs to the same `ray` cluster by pointing to the same head node address (`ray.init(address=<addr>`). Note that the scripts must be run from either a head or worker node in the cluster.

If you have problems with this/suggestions for how to improve, please let us know!

**Comment by virtualluke** [comment]
I find an issue with permissions in ray files in /tmp/ when I do this.

**Comment by edoakes** [comment]
@virtualluke what is the setup and what permissions errors are you getting?

**Comment by virtualluke** [comment]
python 3.7.5, linux redhat 7.6: I have an ansible script that does a ray start on each node and that needs to be run as root for the socket connection ray wants.  When I try as non root (ray.init(address=....) I just get a spammed message: 

> E0116 raylet_client.cc:114] Retrying to connect to socket for pathname /tmp/ray/session...) (num_attempts = x, num_retris = x)

**Comment by shawn-rigdon** [comment]
I work with @arsedler9, and we are seeing the same issue as @virtualluke.

`E0115 22:44:49.648561 174041 raylet_client.cc:113] Retrying to connect to socket for pathname /tmp/ray/session_<session_number>/sockets/raylet (num_attempts = 1, num_retries = 5)`

The cluster was started by @arsedler9, and I receive the above message when running `ray.init(address=<ip:port>)` with my credentials.  This issue seems to be due to the permissions on the sockets in `/tmp/ray/session_latest/sockets`.  They need to be writeable at the group level for other users to connect.

```
[user@host ~]$ ls -l /tmp/ray/session_latest/sockets/
total 0
srwxr-xr-x 1 asedler users 0 Jan  8 10:38 plasma_store
srwxr-xr-x 1 asedler users 0 Jan  8 10:38 raylet
```

If I add `chmod -R g+w /tmp/ray/session_latest` at the end of the list of `head_start_ray_commands` in the config file, the issue goes away.  Below is the config file used to start the cluster (not including the 'fix').

```
cluster_name: default
min_workers: 1
initial_workers: 1
max_workers: 1
autoscaling_mode: default
target_utilization_fraction: 0.8
idle_timeout_minutes: 5
docker:
    image: "" # e.g., tensorflow/tensorflow:1.5.0-py3
    container_name: "" # e.g. ray_docker
    pull_before_run: True
    run_options: []  # Extra options to pass into "docker run"
provider:
    type: local
    head_ip: neuron.bme.emory.edu
    worker_ips: 
        - sulcus.bme.emory.edu
auth:
    ssh_user: asedler
    ssh_private_key: ~/.ssh/id_rsa
head_node: {}
worker_nodes: {}
file_mounts: {}
initialization_commands: []
setup_commands: []
head_setup_commands: []
worker_setup_commands: []
head_start_ray_commands:
    - conda activate tf2-gpu && ray stop
    - conda activate tf2-gpu && ulimit -c unlimited && ray start --head --redis-port=6379 --redis-shard-ports=59519 --node-manager-port=19580 --object-manager-port=39066 --autoscaling-config=~/ray_bootstrap_config.yaml
worker_start_ray_commands:
    - conda activate tf2-gpu && ray stop
    - conda activate tf2-gpu && ray start --redis-address=$RAY_HEAD_IP:6379 --node-manager-port=19580 --object-manager-port=39066
```
