### ISSUE TITLE
[raysgd] How to set spot workers for an Azure cluster?

### ISSUE THREAD

**Issue by AndreCNF** [ray-project/ray#8394]
In Azure, we should be able to set a node as spot (preemptible) by setting [properties.priority = 'Spot'](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/createorupdate#virtualmachineprioritytypes). However, I can't understand how to translate this into my cluster configuration YAML, as there is no information on GitHub or the documentation that I'm aware of which indicates the spot parameter for Azure clusters.

For reference, in the [automatic cluster setup documentation](https://docs.ray.io/en/latest/autoscaling.html#azure), while the [Azure example](https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/azure/example-full.yaml) mentions a setting of an on-demand head node and spot worker nodes, that's not what actually happens, as I get all the workers as on-demand in Azure. In fact, I wouldn't expect otherwise as, contrary to the [GCP](https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/gcp/example-full.yaml) and [AWS](https://github.com/ray-project/ray/tree/master/python/ray/autoscaler/aws/example-full.yaml) examples, there is no difference in the parameters between `head_node` and `worker_nodes`.

Is there any way to set spot workers in an Azure cluster? Or is this feature not yet implemented?

**Comment by richardliaw** [comment]
@AndreCNF can you try using https://github.com/ray-project/ray/blob/37e4d29f8715330eb772f05513c696fd852ab565/python/ray/autoscaler/azure/example-full.yaml

@gramhagen @eisber seems like this config was removed from the examples. Can you take a look? It'll be important for users to know how to enable spot instances.

**Comment by gramhagen** [comment]
yes, good catch. It is possible to add this by modifying the VM ARM template used to deploy workers here: https://github.com/ray-project/ray/blob/8d0c1b5e068853bf748f72b1e60ec99d240932c6/python/ray/autoscaler/azure/azure-vm-template.json#L175

To change workers to spot instance you can modify it as shown here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/spot-template
like this:

```
            "properties": {
                "priority": "Spot",
                "evictionPolicy": "Deallocate",
                "billingProfile": {
                    "maxPrice": -1
                },
                "hardwareProfile": {
                    "vmSize": "[parameters('vmSize')]"
                },
                ...
```

@richardliaw @eisber I'm thinking it might be more general to incorporate the change needed by the user into the config yaml file. Maybe the simplest would be something like below. Thoughts?

https://github.com/ray-project/ray/blob/8d0c1b5e068853bf748f72b1e60ec99d240932c6/python/ray/autoscaler/azure/example-full.yaml#L79
```
worker_nodes:
    azure_arm_parameters:
        vmSize: Standard_D2s_v3
        # List images https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage
        imagePublisher: microsoft-dsvm
        imageOffer: ubuntu-1804
        imageSku: 1804-gen2
        imageVersion: 20.02.01
        priority: Spot
        maxPrice: -1
```
