### ISSUE TITLE
[autoscaler] ray down doesn't tear down worker nodes while ray up is running.

### ISSUE THREAD

**Issue by allenyin55** [ray-project/ray#8599]
### What is the problem?

Running `ray down` while `ray up` is running in a different process will only terminate the head node.

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray: latest master (2e5e789)
Python: 3.7.4
OS: macos 10.15.3

### Reproduction (REQUIRED)

Run the following command (see `cluster.yaml` at the end)
`ray up cluster.yaml -n test_cluster`

Wait until the head node has been launched and we are waiting for it to come up. Then in a another process, run 
`ray down cluster.yaml -n test_cluster`

The `ray down` command will stop the head node as expected (worker node has not been created when `ray down` was run). However, even though the head node is stopping, the `ray up` command is still running in another process and executing commands on the head node, which creates the worker node at a later time.

cluster.yaml
```yaml
# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

# The maximum number of workers nodes to launch in addition to the head
# node. This takes precedence over min_workers. min_workers default to 0.
min_workers: 1
max_workers: 1

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    availability_zone: us-west-2a

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).
