### ISSUE TITLE
[autoscaler] Local Cluster with Docker: Check failed: !local_node_id_.IsNil() This node is disconnected.

### ISSUE THREAD

**Issue by icaropires** [ray-project/ray#8660]
<!--Please include [tune], [rllib], [autoscaler] etc. in the issue title if relevant-->

### What is your question?

I've been trying to run a cluster using two hosts with docker. But after running `ray up -y cluster.yml`, I get the following situation after some minutes:

![image](https://user-images.githubusercontent.com/18473249/83157458-feb76280-a0d9-11ea-842b-2d34d1ace91a.png)

Workers keeps incresing by 16 (number of cores) on the worker node, and the same error popping up on the logs.

**View all logs:**
```
F0528 14:53:04.237076   138 service_based_accessor.cc:320]  Check failed: !local_node_id_.IsNil() This node is disconnected.
*** Check failure stack trace: ***
    @     0x55bb8f0f676d  google::LogMessage::Fail()
    @     0x55bb8f0f7bdc  google::LogMessage::SendToLog()
    @     0x55bb8f0f6449  google::LogMessage::Flush()
    @     0x55bb8f0f6661  google::LogMessage::~LogMessage()
    @     0x55bb8edb7029  ray::RayLog::~RayLog()
    @     0x55bb8ec285fc  ray::gcs::ServiceBasedNodeInfoAccessor::UnregisterSelf()
    @     0x55bb8eb37bd4  ray::raylet::Raylet::Stop()
    @     0x55bb8eb1c943  _ZZ4mainENKUlRKN5boost6system10error_codeEiE_clES3_i.isra.2014
    @     0x55bb8eb1cd58  _ZN5boost4asio6detail14signal_handlerIZ4mainEUlRKNS_6system10error_codeEiE_NS1_18io_object_executorINS0_8executorEEEE11do_completeEPvPNS1_19scheduler_operationES6_m
    @     0x55bb8f08841f  boost::asio::detail::scheduler::do_run_one()
    @     0x55bb8f089921  boost::asio::detail::scheduler::run()
    @     0x55bb8f08a7c2  boost::asio::io_context::run()
    @     0x55bb8eb06669  main
    @     0x7fa7e5fd909b  __libc_start_main
    @     0x55bb8eb17331  (unknown)
```
**Relevant messages on logs/monitor.\***
```
2020-05-28 14:52:26,124 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.2060968875885s, restarting Ray to recover...      
2020-05-28 14:53:01,399 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.24538493156433s, restarting Ray to recover...                              
2020-05-28 14:53:36,620 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.10585641860962s, restarting Ray to recover...                              
2020-05-28 14:54:11,807 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.12926173210144s, restarting Ray to recover...                              
2020-05-28 14:54:46,926 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.117576360702515s, restarting Ray to recover...                             
2020-05-28 14:55:22,223 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.251209259033203s, restarting Ray to recover...                             
2020-05-28 14:55:57,461 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.201629877090454s, restarting Ray to recover...           
```

**cluster.yml:**
```
cluster_name: test                                                                               
                  
min_workers: 2         
initial_workers: 2      
max_workers: 2        
                         
docker:                  
  image: "python:3.8.3"             
  container_name: "ray"             
  run_options: ["--shm-size 25GB"]    
                                    
provider:                     
    type: local               
    head_ip: host01           
    worker_ips: [host02]           
                                   
auth:                              
  ssh_user: root                                                                                                                                              
  ssh_private_key: ~/.ssh/id_rsa                                                                                                                              
                                                                                                                                                              
head_start_ray_commands:                                                                                                                                      
 - ray stop                                                                                                                                                     
 - ulimit -c unlimited && ray start --head --redis-port=6379 --redis-password='' --webui-host=0.0.0.0 --autoscaling-config=~/ray_bootstrap_config.yaml        
                                                                    
worker_start_ray_commands:                                            
 - ray stop                                                         
 - ray start --address=$RAY_HEAD_IP:6379 --redis-password=''
```

I wasn't able to detect any blocked ports by the firewall (using telnet, netstat and nc).

**Ray version:** 0.8.5 and 0.9.0-dev
**OS:** Centos 7, kernel 4.4.96
**Python version:** 3.6
