### ISSUE TITLE
[autoscaler] Service and Ingress resource per worker

### ISSUE THREAD

**Issue by PidgeyBE** [ray-project/ray#9042]
Dear all

I'm trying to create an application which almost entirely runs on Ray. Currently it's running fine on a Ray cluster that I've deployed manually, but I would like to use the ray autoscaler (to pay less for GPU etc ;-)).
The application basically spawns ML pipelines in Ray actors and serves HTTP API servers, RTSP streams, etc.
In order to expose the communication endpoints to the outside world, the ray worker pods are exposed via kubernetes services and these services are exposed via Ingress resources.
My current deployment looks like this:
* A ray head and a few worker pods
* A kubernetes service _for each worker_ exposing port range 7000->7010 on each respective worker
* Ingress rules for each service, exposing the ports like: 
<details>
  <summary>ingress translation</summary>

| ingress rule | service:port |
| ------------- | ------------- |
| https://domainname.com/worker1/7000 | ray-worker-1:7000 | 
| https://domainname.com/worker1/... | ray-worker-1:... | 
| https://domainname.com/worker1/7010 | ray-worker-1:7010 | 
| https://domainname.com/worker2/7000 | ray-worker-2:7000 | 
| https://domainname.com/worker2/... | ray-worker-2:... | 
| https://domainname.com/worker2/7010 | ray-worker-2:7010 | 
| .... | .... |

</details>
When e.g. an HTTP API server is spawned inside an actor, it knows the port it's running on (e.g. 7000) and knows the worker it's running in (currently via the HOSTNAME env var), so based on this information it can determine on which URL the API server is exposed for end users.

I'd like to use the same architecture with autoscale, but I'm missing the possibility to deploy/remove a kubernetes service and ingress resource along with each pod. To accomplish this, the autoscale yaml could be like this:
<details>
  <summary>autoscale.yaml</summary>

```
provider:
    type: kubernetes
# Kubernetes pod config for the head node pod.
head_node:
    pod:
        apiVersion: v1
        kind: Pod
        metadata:
            # Automatically generates a name for the pod with this prefix.
            generateName: ray-head-
            labels:
                component: ray-head
        spec:
    service:  # optional
        # Service that maps to the head node of the Ray cluster.
        apiVersion: v1
        kind: Service
        metadata:
    ingress:  # optional
        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
# Kubernetes pod config for worker node pods.
worker_nodes:
    pod:
        apiVersion: v1
        kind: Pod
        metadata:
            # Automatically generates a name for the pod with this prefix.
            generateName: ray-worker-
        labels:
            component: 
    service:  # optional
        # Service that maps to the head node of the Ray cluster.
        apiVersion: v1
        kind: Service
        metadata:
    ingress:  # optional
        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
```

</details>

The only thing that's not 100% straightforward is that there should be some intelligence in the autoscaler to map the right service on the right worker. E.g. by assigning a unique label to every pod and using this label as selector for the service, so there is a 1:1 relationship between service and pod.

I hope my goal is clear and I think it'll be useful functionality for other people too.
Thanks for taking this into discussion/consideration!

BR, Pieterjan

CC @edoakes
