### ISSUE TITLE
[autoscaler] Only head node is created?

### ISSUE THREAD

**Issue by rightx2** [ray-project/ray#9653]
[autoscaler]

I'm trying to build AWS cluster using ray's autoscaler and have yaml file like below:

```
cluster_name: my_test

# The number of worker nodes to launch in addition to the head node.
min_workers: 3
max_workers: 3

provider:
 type: aws
 region: us-west-2
 availability_zone: us-west-2a
 cache_stopped_nodes: True # If not present, the default is True.

head_node:
 InstanceType: r5.large
 ImageId: ami-06d51e91cea0dac8d # Ubuntu 18.04

worker_nodes:
 InstanceType: r5.large
 ImageId: ami-06d51e91cea0dac8d # Ubuntu 18.04

# List of shell commands to run to set up nodes.
setup_commands:
    - wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh || true
    - bash Anaconda3-5.0.1-Linux-x86_64.sh -b -p $HOME/anaconda3 || true
    - echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
    - pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-0.9.0.dev0-cp36-cp36m-manylinux1_x86_64.whl
    - pip 
```

And I run the command in my local macbook: `ray up -y a.yml`. After a while, I checked the AWS console and it turned out only head node is created even though I set `min_workers` and `max_workers` as 3.

Which one should I check for the bug, ray or aws?

- Environment 
    - Mac OS X 10.15.4
    - ray version:  ray==1.0.1.post1
    - Python version: 3.7.3
