### ISSUE TITLE
[tune] AWS Spot Instance Automation

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/ray#9723]
I'm using the following python tune script:

**hpo.py**

```python
# Install and import libraries
import time
from lightgbm import LGBMClassifier
import pandas as pd
import ray
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from tune_sklearn import TuneSearchCV

# Start timer
start = time.time()

# Initialize Ray
ray.init(address='auto')

# Load breast cancer dataset
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize estimator
model = LGBMClassifier()

# Initialize parameter distributions
param_dists = {
    'boosting_type': ['gbdt'],
    'colsample_bytree': (0.8, 0.9, 'log-uniform'),
    'reg_alpha': (1.1, 1.3),
    'reg_lambda': (1.1, 1.3),
    'min_split_gain': (0.3, 0.4),
    'subsample': (0.7, 0.9),
    'subsample_freq': (20, 21)
}

# Initialize tuner
tuner = TuneSearchCV(
    model,
    param_dists,
    n_iter=20,
    scoring='f1_weighted',
    n_jobs=-1,
    verbose=2,
    max_iters=10,
    search_optimization='bayesian',
    use_gpu=True,
)

# Tune hyperparameters
tuner.fit(X_train, y_train)
print('Best Parameters :', tuner.best_params_)

# Get cross-validated results
df_cv = pd.DataFrame(tuner.cv_results_)

# Predict using best hyperparameters
y_pred = tuner.predict(X_test)
print('F1 Score:', f1_score(y_test, y_pred, average='weighted'))

# Get elapsed time
end = time.time()
print('Elapsed Time :', (end - start))

# Shutdown Ray
ray.shutdown()
```

and the following configuration file:

**tune-default-hpo.yaml**

```yaml
cluster_name: tune-default
provider: {type: aws, region: us-east-2}
auth: {ssh_user: ubuntu}
min_workers: 3
max_workers: 3

head_node:
    InstanceType: c5.xlarge
    ImageId: ami-08bf49c7b3a0c761e

    # Run workers on spot by default. Comment this out to use on-demand.
    InstanceMarketOptions:
        MarketType: spot
        SpotOptions:
            MaxPrice: "1"  # Max Hourly Price

# Provider-specific config for worker nodes, e.g. instance type.
worker_nodes:
    InstanceType: m5.large
    ImageId: ami-08bf49c7b3a0c761e

    # Run workers on spot by default. Comment this out to use on-demand.
    InstanceMarketOptions:
        MarketType: spot
        SpotOptions:
            MaxPrice: "1"  # Max Hourly Price

setup_commands: # Set up each node.
    - pip install lightgbm ray scikit-optimize torch torchvision tabulate tensorboard tune_sklearn
```

**Command**: `ray submit tune-default-hpo.yaml hpo.py --start --stop`

Questions:
1. Ray is not terminating the spot instances if the connection is lost. Is there a way to configure ray to terminate them automatically?
2. Also is there a python API to deploy the instances instead of running the command on the terminal?
3. How do I configure Ray to deploy on a single spot instance and not a cluster?
4. How can I set the storage size for the spot instances?

**Comment by rohan-gt** [comment]
Ah, just noticed the `--stop` argument. Still would like to know if there's a python API for the same

**Comment by richardliaw** [comment]
> Ray is not terminating the spot instances if the connection is lost. Is there a way to configure ray to terminate them automatically?

What do you mean connection is lost? Maybe `ray submit --stop`?

> Also is there a python API to deploy the instances instead of running the command on the terminal?

Unfortunately, it's not public-facing.

> How do I configure Ray to deploy on a single spot instance and not a cluster?

min_workers: 0
max_workers: 0

> How can I set the storage size for the spot instances?

```
worker_nodes:
    InstanceType: m4.16xlarge
    ImageId: ami-0def3275  # Default Ubuntu 16.04 AMI.

    # Set primary volume to 250 GiB
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
              VolumeSize: 250
```
