### ISSUE TITLE
How to run tune on multiple machines?

### ISSUE THREAD

**Issue by zmonoid** [ray-project/ray#9931]
### What is your question?
My ray version is 0.8.2.
I have already setup ray successfully.

Server A has 10 GPUs
Server B has 4 GPUs

```yaml
## tune-example.yaml
cluster_name: local-default
provider:
  type: local
  head_ip: server_a_ip
  worker_ips: [server_b_ip]
auth: {ssh_user: user, ssh_private_key: ~/.ssh/id_rsa}
min_workers: 3
max_workers: 3
```
I run  ```ray up tune-example.yaml``` on both machines with no problems.
I can submit my tasks on server B like ```ray submit tune-example.yaml fullscript.py``` and the task will be run and saved on server A smoothly, which proves no problem on cluster setup.

I now run a tune experiments, main script is like:
```python
    ray.init(memory=200 * 1024 * 1024 * 1024, object_store_memory= 100 * 1024 * 1024 * 1024)
    analysis = tune.run(
        run,
        config={
            "adam_lr": tune.grid_search([1e-3, 1e-4, 2e-4]),
            "param_a": tune.grid_search([500, 200]),
            "param_b": tune.grid_search([20, 16]),
            "param_c": tune.grid_search(["XX", "YY"])
        },
        resources_per_trial={"gpu": 4},
    )
    print("Best config: ", analysis.get_best_config(metric="final_metric"))
    df = analysis.dataframe()
    df.to_csv('out.csv')
```

What I want is to parallelly run 3 trials on the two servers, like 2 trial in server A and 1 trial on server B. But only 2 trials on server A are running. Server B has no movement. I 

May I ask for any suggestions on this?

---

Problem B:

When I run ```ray submit tune-example.yaml fullscript.py```, it actually run ```python ~/fullscript.py``` on server A. I have to copy all files/folders to home folder. How to set the working directory for the experiment?
.
